force-app/main/default/objects/Pool__c/Pool__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Pool ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pool__c/fields/Placepool_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Placepool_Accounts__c</fullName>
    <description>This field is used to show count of Products present in Pool</description>
    <label>Placepool Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pool__c/fields/Placepool_Facevalue__c.field-meta.xml
<CustomField>
    <fullName>Placepool_Facevalue__c</fullName>
    <description>Placepool Facevalue
This field is used to show total current balance of product</description>
    <label>Placepool Facevalue</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Total Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pool_Name__c.field-meta.xml
<CustomField>
    <fullName>Pool_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated by Bulk Pool Excel Processing</description>
    <inlineHelpText>Pool Name</inlineHelpText>
    <label>Pool Name</label>
    <referenceTo>Pool__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PoolSummaryBatchClass.cls
global class PoolSummaryBatchClass implements Database.Batchable<Pool__c>,Database.AllowsCallouts{
	
    List<Pool__c> listPool = new List<Pool__c>();
    List<Pool__c> PoolRec = new List<Pool__c>();
    List<String> setPool = new List<String>();
     public List<Pool__c> start(Database.BatchableContext BC) {
		listPool = [Select id,name from Pool__c]; 
         system.debug('listPool test::' +listPool);
         
        return listPool;
    }
    public void execute(Database.BatchableContext BC,List<Pool__c> listPool) {
       system.debug('listPool::'+listPool);
       system.debug('block run');
        for(Pool__c poolList : listPool){
             setPool.add(poolList.id);
         }
       
        Map<String, AggregateResult> productSumTotal = new Map<String, AggregateResult>();
        
        for(AggregateResult aggr : [SELECT Pool_Name__c, Count(Pool_Name__r.Name) poolCnt, sum(Current_Balance__c) totalBalance
                                    FROM Product__c 
                                    WHERE 
                                    Pool_Name__c IN :setPool
                                   GROUP BY Pool_Name__c]){
            system.debug('aggr check::'+aggr);
            
            Pool__c pool=new Pool__c();
            pool.Id=(id)aggr.get('Pool_Name__c'); 
            pool.Placepool_Accounts__c = (decimal)aggr.get('poolCnt');
            pool.Placepool_Facevalue__c = (decimal)aggr.get('totalBalance');
            PoolRec.add(pool);        
        }
        PoolTriggerHandler.runPoolTrigger = false;       
        update PoolRec;
        PoolTriggerHandler.runPoolTrigger = true;       
        
    }
     public void finish(Database.BatchableContext BC){
        
     }

}