force-app/main/default/objects/Agency_Portal_Fields_Mapping__c/Agency_Portal_Fields_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Agency Portal Fields Mapping to sync records</description>
    <label>Agency Portal Fields Mapping</label>
</CustomObject>

force-app/main/default/objects/Agency_Portal_Fields_Mapping__c/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <description>Field API</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Field API</inlineHelpText>
    <label>Field API</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Fields_Mapping__c/fields/Field_JSON_Tag__c.field-meta.xml
<CustomField>
    <fullName>Field_JSON_Tag__c</fullName>
    <description>Field JSON Tag</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Field JSON Tag</inlineHelpText>
    <label>Field JSON Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Fields_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Object Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Object Name</inlineHelpText>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Error__c/API_Error__c.object-meta.xml
<CustomObject>
    <label>API Error</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/Judgment__c.object-meta.xml
<CustomObject>
    <description>To store the data for Judgement data</description>
    <label>Judgment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/fields/Garnishment_Renewal_Date_Formula__c.field-meta.xml
<CustomField>
    <fullName>Garnishment_Renewal_Date_Formula__c</fullName>
    <description>Calculate the garnishment renewal date based on the garnishment date.</description>
    <formula>IF(ISNULL(Garnishment_Renewal_Date__c),CASE(Judgment_Province__c,
&apos;British Columbia&apos;,ADDMONTHS(Garnishment_Date__c, 24),
&apos;Alberta&apos;,ADDMONTHS(Garnishment_Date__c, 120),
&apos;Saskatchewan&apos;,ADDMONTHS(Garnishment_Date__c, 120),
&apos;Manitoba&apos;,ADDMONTHS(Garnishment_Date__c, 72),
&apos;New Brunswick&apos;,ADDMONTHS(Garnishment_Date__c, 180),
&apos;Nova Scotia&apos;,ADDMONTHS(Garnishment_Date__c, 60),
&apos;Newfoundland and Labrador&apos;,ADDMONTHS(Garnishment_Date__c, 120),
&apos;Prince Edward Island&apos;,ADDMONTHS(Garnishment_Date__c, 120),
&apos;Ontario&apos;,ADDMONTHS(Garnishment_Date__c, 72),
&apos;Quebec&apos;,ADDMONTHS(Garnishment_Date__c, 120),
&apos;Yukon&apos;,ADDMONTHS(Garnishment_Date__c, 24),
&apos;Northwest Territories&apos;,ADDMONTHS(Garnishment_Date__c, 24),
&apos;Nunavut&apos;,ADDMONTHS(Garnishment_Date__c, 24),
null),Garnishment_Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculate the garnishment renewal date based on the garnishment date.</inlineHelpText>
    <label>Garnishment Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Judgment__c/fields/Writ_Renewal_Date_Formula__c.field-meta.xml
<CustomField>
    <fullName>Writ_Renewal_Date_Formula__c</fullName>
    <description>Writ Renewal Date calculated</description>
    <formula>IF(ISNULL(Writ_Renewal_Date__c),CASE(Judgment_Province__c,
&apos;British Columbia&apos;,ADDMONTHS(Date_Writ_Issued__c, 24),
&apos;Alberta&apos;,ADDMONTHS(Date_Writ_Issued__c, 120),
&apos;Saskatchewan&apos;,ADDMONTHS(Date_Writ_Issued__c, 120),
&apos;Manitoba&apos;,ADDMONTHS(Date_Writ_Issued__c, 72),
&apos;New Brunswick&apos;,ADDMONTHS(Date_Writ_Issued__c, 180),
&apos;Nova Scotia&apos;,ADDMONTHS(Date_Writ_Issued__c, 60),
&apos;Newfoundland and Labrador&apos;,ADDMONTHS(Date_Writ_Issued__c, 120),
&apos;Prince Edward Island&apos;,ADDMONTHS(Date_Writ_Issued__c, 120),
&apos;Ontario&apos;,ADDMONTHS(Date_Writ_Issued__c, 72),
&apos;Quebec&apos;,ADDMONTHS(Date_Writ_Issued__c, 120),
&apos;Yukon&apos;,ADDMONTHS(Date_Writ_Issued__c, 24),
&apos;Northwest Territories&apos;,ADDMONTHS(Date_Writ_Issued__c, 24),
&apos;Nunavut&apos;,ADDMONTHS(Date_Writ_Issued__c, 24),
null),Writ_Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Writ Renewal Date calculated</inlineHelpText>
    <label>Writ Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Judgment__c/recordTypes/Judgment.recordType-meta.xml
<RecordType>
    <fullName>Judgment</fullName>
    <active>true</active>
    <label>Judgment</label>
</RecordType>

force-app/main/default/classes/PortalJudgmentProcessingAPI.cls
/**************************************************************************************************
*
*  Class:   
*  @description : This is a webservice class(provide) to create/update Judgment Record from 
*            Salesforce to Portal DB
*  @author : A5E Consulting
*  @date : 17/01/2022

*************************************************************************************************/
public class PortalJudgmentProcessingAPI {
    
    public static API_Call_Details__c apiCallDetails = API_Call_Details__c.getInstance('Agency Portal API');
    static List<Agency_Portal_Fields_Mapping__c> fieldMapping = Agency_Portal_Fields_Mapping__c.getall().values();
    public static List<API_Error__c> listAPIErrors = new List<API_Error__c>();
    public static map<String, Agency_Portal_Fields_Mapping__c> mapAgencyField = Agency_Portal_Fields_Mapping__c.getAll();
    public static map<String, object> mapAgencyJudgFieldData = new map<String, object>();

    @future (callout=true)
    public static void processJudgment(ID judgmentId){ 
                            
        String Query = 'SELECT ID,Name,Writ_Renewal_Date_Formula__c,Garnishment_Renewal_Date_Formula__c, ';
        for(Agency_Portal_Fields_Mapping__c fieldMappingInstance : fieldMapping){
            if(fieldMappingInstance.Object_Name__c == 'Judgment'){
                Query += fieldMappingInstance.Field_API__c + ', ';
            }
            
        }
        Query = Query.removeEnd(', ');
        Query+= ' FROM Judgment__c WHERE ID=: judgmentId';
        list<Judgment__c> listJudgment= Database.query(Query);
                                    
        String JudgmentJSONRequest;
        Judgment__c judgmentInstance;
        if(!listJudgment.isEmpty()){
            //Create JSON request for customer update
            judgmentInstance = listJudgment[0];
            for(Agency_Portal_Fields_Mapping__c agencyFieldData : mapAgencyField.values()){
                if(agencyFieldData.Object_Name__c == 'Judgment'){
                    mapAgencyJudgFieldData.put(agencyFieldData.Field_JSON_Tag__c, judgmentInstance.get(agencyFieldData.Field_API__c)); 
                }
            }
            mapAgencyJudgFieldData.put('Writ_Renewal_Date', judgmentInstance.get('Writ_Renewal_Date_Formula__c'));
            mapAgencyJudgFieldData.put('Garnishment_Renewal_Date', judgmentInstance.get('Garnishment_Renewal_Date_Formula__c'));
            JudgmentJSONRequest = JSON.serialize(mapAgencyJudgFieldData);
            
        }
        List<string> JudgmentJSONRequestList = new List<string>();
        JudgmentJSONRequestList.add(JudgmentJSONRequest);
        List<Judgment__c> judList = new List<Judgment__c>();
        judList.add(judgmentInstance);
        
        AzureUtility.apiCallToPortal('Agency Portal API',JudgmentJSONRequestList, 'SFJudgement',judList, 'Judgment');
        
    }
    
}