force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/recordTypes/Remittance.recordType-meta.xml
<RecordType>
    <fullName>Remittance</fullName>
    <active>true</active>
    <description>Remittance Insolvency Payments</description>
    <label>Remittance</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Email_to_Case_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Email_to_Case_Reference_Number__c</fullName>
    <description>Email to Case Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email to Case Reference Number</inlineHelpText>
    <label>Email to Case Reference Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RemittanceInlineController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a controller class to display Remittance Documents
 *  @author : A5E Consulting
 *  @date : 09/10/2018
 *  
 *************************************************************************************************/
public class RemittanceInlineController{
	
	public List<RemAttachWrap> remAttachWrapList{get;set;}
	
	//Constructor
    public RemittanceInlineController(ApexPages.StandardController controller) {
    	
    	String insolvencyPaymentId = ApexPages.currentPage().getParameters().get('Id');
    	
    	remAttachWrapList = new List<RemAttachWrap>();
    	
    	Insolvency_Payment__c insolvencyPayment = [Select Id, Name, Remittance__c 
    														from Insolvency_Payment__c
    														where  Id =: insolvencyPaymentId];
    														
       
    	Id remittanceId = insolvencyPayment.Remittance__c;
    	
    	if(remittanceId != null){
    		
    		Remittance__c paymentRemittance = [Select Id, Email_to_Case_Reference_Number__c 
    													 from Remittance__c
    													 where Id =: remittanceId];
    													 
    		String caseRefId = paymentRemittance.Email_to_Case_Reference_Number__c;
    		
    		if(!String.isBlank(caseRefId)){
    			List<Attachment> remAttachList = [SELECT Id, Name, Description, CreatedDate, LastModifiedDate, parentId 
														FROM Attachment 
														WHERE ParentId in (select id from EMailMessage where relatedToid =: caseRefId) 
														ORDER BY CreatedDate DESC];
    												
	    		if(remAttachList.size() > 0 ){
	    			for(Attachment remAttach : remAttachList){
	    				remAttachWrapList.add(new RemAttachWrap(remAttach));
	    			}
	    		}
    			
    		}
    		
    		
    		/*
    		
    		List<Attachment> remAttachList = [SELECT Id, Name, Description, CreatedDate, LastModifiedDate, parentId FROM Attachment 
    												WHERE ParentId =: remittanceId];
    												
    		if(remAttachList.size() > 0 ){
    			for(Attachment remAttach : remAttachList){
    				remAttachWrapList.add(new RemAttachWrap(remAttach));
    			}
    		}
    		*/
    	}
    }
    
    //Attachment Wrapper
    public class RemAttachWrap{
    	
        public Attachment attach{get;set;}
        
        public RemAttachWrap(Attachment attach){
            this.attach = attach;
            
        }
    }
}