force-app/main/default/objects/Insolvency_Error__c/Insolvency_Error__c.object-meta.xml
<CustomObject>
    <description>An object to store error/exception related to Insolvency flow</description>
    <label>Insolvency Error</label>
    <nameField>
        <displayFormat>IErr-{0000}</displayFormat>
        <label>Insolvency Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Error__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error / Exception Details</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Error / Exception Details</inlineHelpText>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Unallocated payment record</description>
    <inlineHelpText>Lookup field to Unallocated payment record</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Email_to_Case_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Email_to_Case_Reference_Number__c</fullName>
    <description>Email to Case Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email to Case Reference Number</inlineHelpText>
    <label>Email to Case Reference Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/DividendsDelete.cls
/**
 * @description       : Dividend delation with the related payments and Assignment records.
 * @author            : nagendra.yanadigalla@canaccede.com
 * @last modified on  : 2024-11-18
 * @last modified by  : nagendra.yanadigalla@canaccede.com
 **/

public class DividendsDelete {
    public static boolean displayPopup;
    
    Public DividendsDelete(ApexPages.StandardController controller) {
    }
    public static void deleteDividend(){
        string dividendId = ApexPages.currentPage().getParameters().get('id');
        
        Remittance__c dividend = new Remittance__c();
        
        try{  
            dividend = [SELECT Id, Email_to_Case_Reference_Number__c 
                        FROM Remittance__c 
                        WHERE Id = :dividendId];
        }catch(Exception e) {
            System.debug('List has no rows for assignment to SObject' + e.getMessage());
        } 
        
        List<SObject> recordsToDelete = new List<SObject>(); 
        // If there is an Assignment record, delete it
        if (String.isNotBlank(dividend.Email_to_Case_Reference_Number__c)) {
            
            List <Case> assignment = [SELECT Id 
                                      FROM case 
                                      WHERE ID = :dividend.Email_to_Case_Reference_Number__c LIMIT 1];
            
            if (!assignment.isEmpty()) {
                recordsToDelete.addAll(assignment);
            }
        }
        
        //related Insolvency Payment records
        List<Insolvency_Payment__c> insolvencyPayments = [SELECT Id 
                                                          FROM Insolvency_Payment__c 
                                                          WHERE Remittance__c = :dividendId];
        
        if (!insolvencyPayments.isEmpty()) {
            recordsToDelete.addAll(insolvencyPayments);
        }
        
        // related Unallocated_Payment__c records
        List<Unallocated_Payment__c> unallocatedPayments = [SELECT Id 
                                                            FROM Unallocated_Payment__c
                                                            WHERE Remittance__c = :dividendId];
        
        if (!unallocatedPayments.isEmpty()) {
            recordsToDelete.addAll(unallocatedPayments);
        }
        // Add the Dividend record to the delete list
        recordsToDelete.add(dividend);
        // Delete all the records in one DML operation
        try{ 
            if(Test.isRunningTest() && dividendId == '111111111111111'){
                DmlException dmlEx = new DmlException('TEST_EXCEPTION_MESSAGE');
                throw new DmlException(dmlEx);
            }
           
            if (!recordsToDelete.isEmpty()){
                delete recordsToDelete;
            }
        }catch (DmlException de) {
            System.debug('Exception during Dividend deletion ' + de.getMessage());
            Insolvency_Error__c error = new Insolvency_Error__c(Error__c = de.getMessage());
            insert error;
        } 
        displayPopup = true;
    }
    
    public static PageReference closePopup() {
        return new ApexPages.Action('{!List}').invoke();
    }
    
}