force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_EmailMessage_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_EmailMessage_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run EmailMessage Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Account_Number_Without_Space__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Without_Space__c</fullName>
    <description>This field has been created to store account number with out spaces. Actual account number may have space but this is removed in this field using workflow.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number Without Space</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Reason_for_No_PoC_Required_Dropdown__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_No_PoC_Required_Dropdown__c</fullName>
    <description>Reason for No PoC Required</description>
    <inlineHelpText>Reason for No PoC Required</inlineHelpText>
    <label>Reason for No PoC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Open Accounts</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unable to Locate Account</fullName>
            </value>
            <value>
                <fullName>Account Sold</fullName>
            </value>
            <value>
                <fullName>Proposal: Secured file</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SDA Account</fullName>
            </value>
            <value>
                <fullName>Scotia Private Label Account</fullName>
            </value>            
            <value>
                <fullName>BNS Account</fullName>
            </value>
            <value>
                <fullName>Not SDA Account</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
            <value>
                <fullName>Repo’d – Seize or Sue</fullName>
            </value>
            <value>
                <fullName>Unable to Locate</fullName>
            </value>
            <value>
                <fullName>Below Threshold</fullName>
            </value>
            <value>
                <fullName>Settled/PIF</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>DOB mismatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Type_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Service__c</fullName>
    <description>Type of Service</description>
    <inlineHelpText>Type of Service</inlineHelpText>
    <label>Type of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Only</fullName>
            </value>
            <value>
                <fullName>Service and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Name__c/Portfolio_Name__c.object-meta.xml
<CustomObject>
    <label>Portfolio Name</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Name__c/fields/Account_Purchasing_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Purchasing_Entity_ID__c</fullName>
    <description>Account Purchasing Entity ID (numeric)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account Purchasing Entity ID(numeric)</inlineHelpText>
    <label>Account Purchasing Entity ID</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEmailMessageTriggerHandler.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a trigger handler class for EmailMessage object 
 *  @author : A5E Consulting
 *  @date : 24/04/2019
 
 *************************************************************************************************/
  @isTest(SeeAllData=false)
  public class TestEmailMessageTriggerHandler {
    @isTest
    static void testData(){
        
        //Custom setting
        Application_Config_Settings__c config = Application_Config_Settings__c.getOrgDefaults();
        config.Run_Insolvency_Account_Trigger__c = true;
        config.Run_Insolvency_Status_Validations__c = true;
        config.Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm';
        config.Bank_Eligible_for_Duplicate_Check__c = 'SPL';
        config.Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN';
        config.Run_Insolvency_Trigger__c = false;
        config.Run_Insolvency_Account_Duplicate_Check__c = true;
        config.Run_EmailMessage_Trigger__c = true;
        insert config; 
        
        List<ID> listID = new List<ID>();
        Map<ID,EmailMessage> oldmap=new Map<ID,EmailMessage>();
        
        //Portfolio reocrd creation
        
       Portfolio_Name__c pn=new Portfolio_Name__c();
       pn.name='Test_Portfolio';
       pn.Account_Purchasing_Entity_ID__c = 'text';
       insert pn;    
           
        //Insolvency record creation     
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insert insolv1;
        
        //Insolvency-Account record creation
        list<RecordType> recordTypeList = new list<RecordType>([SELECT Id,Name FROM RecordType WHERE SobjectType='Insolvency_Account__c']);
        
        Insolvency_Account__c insolAcct = new Insolvency_Account__c();
        insolAcct.RecordTypeId = recordTypeList[1].Id;
        insolAcct.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insolAcct.Client_Identifier__c = 'Scotia Bank';
        insolAcct.Insolvency__c = insolv1.Id;
        insolAcct.Account_Number_Without_Space__c = 'Test-001';
        insolAcct.name = 'test11';
        insolAcct.Insolvency_Type__c='Division 1 Proposal';
        insolAcct.Claim_Type__c='Unsecured';
        insolAcct.Type_of_Service__c ='Service and Sale';
        insolAcct.Investment_Group__c='OTHER';
        insolAcct.Portfolio_Name_Lookup__c=pn.id;
        insolAcct.Portfolio_Group_Name__c='CAL004';
        insert insolAcct;
        
        // Case record creation
       List<Case> listCase = new List<Case>();
        Case c1 = new Case();
        c1.subject='email';
        c1.status='completed';
        c1.Insolvency_Account__c=insolAcct.id;
        c1.New_Email_on_Case__c = true;
        listCase.add(c1);
        
        Case c2 = new Case();
        c2.subject='email';
        c2.status='completed';
        c2.Insolvency_Account__c=insolAcct.id;
        c2.New_Email_on_Case__c = true;
        c2.Is_Email_to_Case__c = true;
        listCase.add(c2);
        insert listcase;
        
        
        List<EmailMessage> listEmailMessage = new List<EmailMessage>();
        EmailMessage email1 = new EmailMessage();
        email1.Subject='Test1';
        email1.RelatedToId=c1.Id;
        listEmailMessage.add(email1);
        
        EmailMessage email2 = new EmailMessage();
        email2.Subject='Test1';
        email2.RelatedToId=c2.Id;
        listEmailMessage.add(email2);
        insert listEmailMessage;

        Attachment attach = new Attachment(Name = 'Test', ContentType = 'text/xml', ParentId = email2.Id, Body = Blob.valueOf('Test'));
        insert attach;
        
        listID.add(email1.Id);
        listID.add(email2.Id);
        
        email1.subject='UpdateTest1';
        email2.subject='UpdateTest2';
        update listEmailMessage;
        
        
        
        List<Case> listCases = [select id, subject, status, New_Email_on_Case__c from Case where id in :listID];
        
        oldmap.put(email1.Id, email1);
        oldmap.put(email2.Id, email2);
        
        //delete listEmailMessage;
        
        EmailMessageTriggerHandler.handleBeforeDelete(listEmailMessage);
        EmailMessageTriggerHandler.handleAfterUpdate(listEmailMessage, oldmap);
        EmailMessageTriggerHandler.handleAfterInsert(listEmailMessage);
        EmailMessageTriggerHandler.handleBeforeInsert(listEmailMessage);

    }

    }