force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Record_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Run_Record_Ownership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Record Ownership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Canadian_Tire_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Canadian_Tire_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canadian Tire Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CanadianTireRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Chase_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Chase_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chase Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ChaseRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Fairstone_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Fairstone_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fairstone Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FairstoneRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Flexiti_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Flexiti_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flexiti Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FlexitiRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Goeasy_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Goeasy_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Easyfinancial Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GoeasyRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Owner__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Owner__c</fullName>
    <description>Insolvency Owner</description>
    <formula>CASE(
$Profile.Name,
&apos;SDA Community User&apos;, ( SDA_Record_Owner__r.FirstName + &apos; &apos; + SDA_Record_Owner__r.LastName),
&apos;SDA Community User Readonly&apos;, (SDA_Record_Owner__r.FirstName + &apos; &apos; + SDA_Record_Owner__r.LastName),
&apos;SDA Login Community User&apos;, (SDA_Record_Owner__r.FirstName + &apos; &apos; + SDA_Record_Owner__r.LastName),
&apos;SDA Login Community User Readonly&apos;, (SDA_Record_Owner__r.FirstName + &apos; &apos; + SDA_Record_Owner__r.LastName),
&apos;SPL Community User&apos;, (Chase_Record_Owner__r.FirstName + &apos; &apos; + Chase_Record_Owner__r.LastName),
&apos;SPL Community User Readonly&apos;, (Chase_Record_Owner__r.FirstName + &apos; &apos; + Chase_Record_Owner__r.LastName),
&apos;SPL Login Community User&apos;, (Chase_Record_Owner__r.FirstName + &apos; &apos; + Chase_Record_Owner__r.LastName),
&apos;SPL Login Community User Readonly&apos;, (Chase_Record_Owner__r.FirstName + &apos; &apos; + Chase_Record_Owner__r.LastName),
&apos;Scotia Bank Community User&apos;, (Scotia_Record_Owner__r.FirstName + &apos; &apos; + Scotia_Record_Owner__r.LastName) ,
&apos;Scotia Bank Community User Readonly&apos;, (Scotia_Record_Owner__r.FirstName + &apos; &apos; + Scotia_Record_Owner__r.LastName),
&apos;Scotia Bank Login Community User&apos;, (Scotia_Record_Owner__r.FirstName + &apos; &apos; + Scotia_Record_Owner__r.LastName),
&apos;Scotia Bank Login Community User Readonly&apos;, (Scotia_Record_Owner__r.FirstName + &apos; &apos; + Scotia_Record_Owner__r.LastName),
&apos;Fairstone Community User&apos;, (Fairstone_Record_Owner__r.FirstName + &apos; &apos; + Fairstone_Record_Owner__r.LastName),
&apos;Fairstone Community User Readonly&apos;, (Fairstone_Record_Owner__r.FirstName + &apos; &apos; + Fairstone_Record_Owner__r.LastName),
&apos;Goeasy Community User&apos;, (Goeasy_Record_Owner__r.FirstName + &apos; &apos; + Goeasy_Record_Owner__r.LastName),
&apos;Goeasy Community User Readonly&apos;, (Goeasy_Record_Owner__r.FirstName + &apos; &apos; + Goeasy_Record_Owner__r.LastName),
&apos;Canadian Tire Community User&apos;, (Canadian_Tire_Record_Owner__r.FirstName + &apos; &apos; + Canadian_Tire_Record_Owner__r.LastName),
(Owner:User.FirstName + &apos; &apos; + Owner:User.LastName))</formula>
    <inlineHelpText>Insolvency Owner</inlineHelpText>
    <label>Insolvency Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Owner_Id__c</fullName>
    <formula>CASE( 
$Profile.Name, 
&apos;SDA Community User&apos;, (SDA_Record_Owner__c) , 
&apos;SDA Community User Readonly&apos;, (SDA_Record_Owner__c), 
&apos;SDA Login Community User&apos;, (SDA_Record_Owner__c), 
&apos;SDA Login Community User Readonly&apos;, (SDA_Record_Owner__c), 
&apos;SPL Community User&apos;, (Chase_Record_Owner__c) , 
&apos;SPL Community User Readonly&apos;, (Chase_Record_Owner__c), 
&apos;SPL Login Community User&apos;, (Chase_Record_Owner__c), 
&apos;SPL Login Community User Readonly&apos;, (Chase_Record_Owner__c), 
&apos;Scotia Bank Community User&apos;, (Scotia_Record_Owner__c) , 
&apos;Scotia Bank Community User Readonly&apos;, (Scotia_Record_Owner__c), 
&apos;Scotia Bank Login Community User&apos;, (Scotia_Record_Owner__c), 
&apos;Scotia Bank Login Community User Readonly&apos;, (Scotia_Record_Owner__c),
&apos;Fairstone Community User&apos;, (Fairstone_Record_Owner__c), 
(Owner:User.Id))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insolvency Owner Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Money_Mart_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Money_Mart_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Money Mart Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MoneyMartRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Scotia_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Scotia_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scotia Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ScotiaRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/SDA_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDA_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDA Record Owner</description>
    <inlineHelpText>SDA Record Owner</inlineHelpText>
    <label>SDA Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SDARecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsolvencyOwnerShipController.cls
/**************************************************************************************************
 *
 *  Class:   InsolvencyOwnerShipController
 *
 *  @description : Implemented Insolvency, and related Insolvency Accounts Owner Id with either scotia/chase bank user
 *  @author : A5E Consulting
 *  @date : 16/04/2018
 
 *************************************************************************************************/
public class InsolvencyOwnerShipController{

    public Insolvency__c insolv {set;get;}
    Application_Config_Settings__c config = Application_Config_Settings__c.getOrgDefaults();
    
    // Check varialble for community users
    @TestVisible
    public Boolean isScotiaBankCommunityUser {set;get;}
    
    @TestVisible
    public Boolean isChaseBankCommunityUser {set;get;}
    
    @TestVisible
    public Boolean isSDABankCommunityUser {set;get;}
    
    @TestVisible
    public Boolean isFairstoneBankCommunityUser {set;get;}

    @TestVisible
    public Boolean isGoeasyBankCommunityUser {set;get;}

    @TestVisible
    public Boolean isCanadianTireCommunityUser {set;get;}
    
    @TestVisible
    public Boolean isMoneyMartCommunityUser {set;get;}
    
    @TestVisible
    public Boolean isFlexitiCommunityUser {set;get;}
    
    public InsolvencyOwnerShipController(ApexPages.StandardController controller) {
    	
    	//Initialize the values
        isScotiaBankCommunityUser = InsolvencyUtil.isScotiaBankCommunityUser(UserInfo.getProfileId());
        isChaseBankCommunityUser = InsolvencyUtil.isChaseBankCommunityUser(UserInfo.getProfileId());
    	isSDABankCommunityUser = InsolvencyUtil.isSDABankCommunityUser(UserInfo.getProfileId());
        isFairstoneBankCommunityUser = InsolvencyUtil.isFairstoneBankCommunityUser(UserInfo.getProfileId());
        isGoeasyBankCommunityUser = InsolvencyUtil.isGoeasyBankCommunityUser(Userinfo.getProfileId());
        isCanadianTireCommunityUser = InsolvencyUtil.isCanadianTireCommunityUser(Userinfo.getProfileId());
        isMoneyMartCommunityUser = InsolvencyUtil.isMoneyMartCommunityUser(Userinfo.getProfileId());
        isFlexitiCommunityUser = InsolvencyUtil.isFlexitiCommunityUser(Userinfo.getProfileId());
        //Eligible Insolvency Account Record Type Name 
        String eligibleInsAcctRecordType = InsolvencyUtil.getInsAccntRecordTypeProfile(Userinfo.getProfileId());
 
        // Run only if record ownership functionality is Enabled at custom settings level
        if(config.Run_Record_Ownership__c){
            insolv = [SELECT Scotia_Record_Owner__c,
                             Chase_Record_Owner__c, 
                             SDA_Record_Owner__c,
                             Insolvency_Owner__c,
                      		 Fairstone_Record_Owner__c,
                             Goeasy_Record_Owner__c,
                             Canadian_Tire_Record_Owner__c,
                      		 Money_Mart_Record_Owner__c,
                      		 Flexiti_Record_Owner__c,
                             OwnerId, Owner.Name, Insolvency_Owner_Id__c,
                             (SELECT OwnerId 
                                    FROM Insolvency_Accounts__r 
                                    where RecordType.name =: eligibleInsAcctRecordType
                             ) 
                             FROM Insolvency__c 
                             WHERE Id =: ((Insolvency__c)controller.getRecord()).Id];
        }
        
    }
    
    // Default method called to check and assign ownership of an Insolvency & Insolvency Account
    public void checkInsolvencyAccountOwnerShip(){
        // Run only if record ownership functionality is Enabled at custom settings level
        if(config.Run_Record_Ownership__c){
            if(isScotiaBankCommunityUser){
                if(insolv.Scotia_Record_Owner__c == null){
                    insolv.Scotia_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }else if(isChaseBankCommunityUser){
                if(insolv.Chase_Record_Owner__c == null){
                    insolv.Chase_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            
            else if(isSDABankCommunityUser){
                if(insolv.SDA_Record_Owner__c == null){
                    insolv.SDA_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            
            else if(isFairstoneBankCommunityUser){
                if(insolv.Fairstone_Record_Owner__c == null){
                    insolv.Fairstone_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            else if(isGoeasyBankCommunityUser){
                if(insolv.Goeasy_Record_Owner__c == null){
                    insolv.Goeasy_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            else if(isCanadianTireCommunityUser){
                if(insolv.Canadian_Tire_Record_Owner__c == null){
                    insolv.Canadian_Tire_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            else if(isMoneyMartCommunityUser){
                if(insolv.Money_Mart_Record_Owner__c == null){
                    insolv.Money_Mart_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
            else if(isFlexitiCommunityUser){
                if(insolv.Flexiti_Record_Owner__c == null){
                    insolv.Flexiti_Record_Owner__c = UserInfo.getUserId();
                    InsolvencyUtil.updateOwnerShip(insolv);
                }
            }
        }
    }
}