force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Display_Duplicate_Accounts_List_View__c.field-meta.xml
<CustomField>
    <fullName>Display_Duplicate_Accounts_List_View__c</fullName>
    <label>Display Duplicate Accounts List View</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Date__c</fullName>
    <description>The effective date of the insolvency filing as noted in the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The effective date of the insolvency filing as noted in the creditor’s package</inlineHelpText>
    <label>Insolvency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Account_Number_Without_Space__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Without_Space__c</fullName>
    <description>This field has been created to store account number with out spaces. Actual account number may have space but this is removed in this field using workflow.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number Without Space</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The debtor estate number as noted on the creditor’s package</inlineHelpText>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPOCDocController.cls
/**************************************************************************************************
 *
 *  Class:   TestPOCDocController
 *
 *  @description : This class contains unit tests for generating and saving poc pdf document
 *  @author : A5E Consulting
 *  @date : 10/08/2017
 * 
 *************************************************************************************************/

@isTest
public class TestPOCDocController{
    //Create all necessary Object records in this method
     @testSetup 
     static void testData() {
         //Custom setting record creation
        Application_Config_Settings__c config = Application_Config_Settings__c.getOrgDefaults();
        config.Run_Insolvency_Account_Trigger__c = true;
        config.Run_Insolvency_Status_Validations__c = true;
        config.Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm';
        config.Display_Duplicate_Accounts_List_View__c=10;
        config.Bank_Eligible_for_Duplicate_Check__c = 'SPL';
        config.Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN';
        config.Run_Insolvency_Trigger__c = false;
        config.Run_Insolvency_Account_Duplicate_Check__c = true;
        insert config; 
         
         PoC_Package_Settings__c poc = new PoC_Package_Settings__c(Name = 'Scotia Bank');
         insert poc;
         
         //Insolvency insertion
        Insolvency__c insolv = new Insolvency__c();
        insolv.name = 'Dup-1';
        
        //insolv.Insolvency_Date__c=Date.newInstance(2020,04, 11);
        insolv.Insolvency_Date__c = Date.Today().addMonths(-1);
        
        insolv.Insolvency_Type__c='Bankruptcy';
        insolv.Debtor_2_Estate_Number__c='1234';
        insert insolv;
         
        //Insolvency Account insertion
        Id devRecordTypeId = Schema.SObjectType.Insolvency_Account__c.getRecordTypeInfosByName().get('Scotia Bank Insolvency Account').getRecordTypeId();
        Insolvency_Account__c insolAcct = new Insolvency_Account__c();
        insolAcct.name = 'TestDup -1';
        insolAcct.Account_Number_Without_Space__c = 'TestDup-1';
        insolAcct.Insolvency_Status__c = 'New';
        insolAcct.Insolvency__c = insolv.id;
        insolAcct.Account_Type__c = 'Line of Credit';
        insolAcct.Borrower_Primary__c = 'Kajal';
        insolAcct.Type_of_Service__c = 'Service Only';
        insolAcct.Claim_Amount__c = 1200.00;
        insolAcct.Claim_Type__c = 'Secured';
        insolAcct.Excluded_from_Purchase__c=False;
        insolAcct.Excluded_Account_Comments__c='TestData';
        insolAcct.Is_Duplicate_Resolved__c=False;
        insolAcct.Insolvency_Type__c='Bankruptcy';
        insolAcct.Insolvency_Date__c=Date.newInstance(2020,04, 11);
        insolAcct.Product_Code__c='MOR';
        insolAcct.Debtor__c='test';
        insolAcct.PoC_Created_Date__c=DateTime.newInstance(2020, 01, 08);
        insolAcct.Asset_Status__c ='Purchased';
        insolAcct.Insolvency__c = insolv.id;
        insolAcct.Account_Type__c = '';
        insolAcct.Borrower_Primary__c = '';    
        insolAcct.Type_of_Service__c = '';
        insolAcct.Claim_Type__c = '';
        insolAcct.Reasons_for_Duplicate_Account_Number__c='Test';
        insolAcct.Client_Identifier__c = 'Scotia Bank';
        insolAcct.Portfolio_Group_Name__c='CAL005';
        insolAcct.recordTypeId = devRecordTypeId;
        insert insolAcct;
     }
     
     // Unit test for saving poc pdf document as attachment of insolvancy account
		static testMethod void savePOCDocTest(){
          Insolvency_Account__c insolAcct = [SELECT Id FROM Insolvency_Account__c LIMIT 1];
          ApexPages.currentPage().getParameters().put('Id', insolAcct.Id);
          
          POCDocController obj = new POCDocController();
          obj.language = 'en_US';
          obj.savePOCDoc();
          
          try{
             throw new DMLException('My DML EXCEPTION'); 
          }catch(Exception ex){
              obj.handleException(ex);
          }
          //obj.goToInsolvancyAccount();
     }
    
    static testMethod void testChangeLangugae(){
		  Insolvency_Account__c insolAcct = [SELECT Id FROM Insolvency_Account__c LIMIT 1];
          ApexPages.currentPage().getParameters().put('Id', insolAcct.Id);
          
          POCDocController obj = new POCDocController();
          obj.language = 'en_US';
          obj.pageName = 'Canaccede';
          obj.changeLanguage();
        
          obj.language = 'fr';
          obj.pageName = 'Canaccede';
          obj.changeLanguage();
        
          obj.language = 'en_US';
          obj.pageName = 'Scotia';
          obj.changeLanguage();
        
          obj.language = 'fr';
          obj.pageName = 'Scotia';
          obj.changeLanguage();
          
          try{
             throw new DMLException('My DML EXCEPTION'); 
          }catch(Exception ex){
              obj.handleException(ex);
          }
          //obj.goToInsolvancyAccount();
    }
}