force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Attachment_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Attachment_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Run Attachment Trigger</description>
    <inlineHelpText>Run Attachment Trigger</inlineHelpText>
    <label>Run Attachment Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Before_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Before_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To run or not to run Product Before Trigger</description>
    <inlineHelpText>To run or not to run Product Before Trigger</inlineHelpText>
    <label>Run Product Before Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestAlertEmailOnTriggerOFF.cls
/**************************************************************************************************
*
*  Class:   
*  @description : This testclass will test validation of is the trigger is off from custom settings
*  @author : A5E Consulting
*  @date : 04th March 2024
*  task  :  6159
*************************************************************************************************/
@isTest
public class TestAlertEmailOnTriggerOFF {

    @isTest
    static void testBatchExecution() {
        // Create test data for Application_Config_Settings__c
        Application_Config_Settings__c config = new Application_Config_Settings__c ();
        config.name = 'Test name';
        config.Run_Insolvency_Account_Trigger__c = false;
        config.Run_Insolvency_Trigger__c = false;
        
        insert config;
        System.debug('creted record id'+config);
      

        // Create test data for Loan_ReEngineering__c
            Loan_ReEngineering__c loanReengineeringRecords = new Loan_ReEngineering__c ();
            loanReengineeringRecords.name = 'test name';
            loanReengineeringRecords.Run_Attachment_Trigger__c = false;
            loanReengineeringRecords.Run_Product_Before_Trigger__c = false;
            
            insert loanReengineeringRecords;
            System.debug('creted record id'+loanReengineeringRecords);

        Test.startTest();
        AlertEmailOnTriggerOFF batchInstance = new AlertEmailOnTriggerOFF();
        Database.executeBatch(batchInstance);
        Test.stopTest();

    }
}