force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Product_Coll_Sub_Status_Validation__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Coll_Sub_Status_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>not to allow status change directly to Legal status. Legal status will only be changed automatically after Judgment record is added</description>
    <label>Run Product Coll Sub Status Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Judgment__c/Judgment__c.object-meta.xml
<CustomObject>
    <description>To store the data for Judgement data</description>
    <label>Judgment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/fields/Legal_Agency__c.field-meta.xml
<CustomField>
    <fullName>Legal_Agency__c</fullName>
    <description>placement name of who is responsible for this legal action</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Agency</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/CCS_Agency__c.field-meta.xml
<CustomField>
    <fullName>CCS_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CCS Account attcahed to CCS ofiice</description>
    <label>CCS Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (CCS Agency)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>Sub Status</description>
    <inlineHelpText>Sub Status</inlineHelpText>
    <label>Placement Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Accepted by agency</fullName>
            </value>
            <value>
                <fullName>Initial Letter Sent</fullName>
            </value>
            <value>
                <fullName>Follow-Up Letter Sent</fullName>
            </value>
            <value>
                <fullName>Return To Sender</fullName>
            </value>
            <value>
                <fullName>Added To Dialer</fullName>
            </value>
            <value>
                <fullName>Message Left</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
            </value>
            <value>
                <fullName>Email Contact Established</fullName>
            </value>
            <value>
                <fullName>Possible Payer</fullName>
            </value>
            <value>
                <fullName>Settlement Pending</fullName>
            </value>
            <value>
                <fullName>Refusal</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Debtor Claims Paid - Awaiting Proof</fullName>
            </value>
            <value>
                <fullName>Proof of Payment Submitted to Client</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Client Request</fullName>
            </value>
            <value>
                <fullName>Checking for Assets - Possible Legal</fullName>
            </value>
            <value>
                <fullName>Claim Issued</fullName>
            </value>
            <value>
                <fullName>Claim Served</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement</fullName>
            </value>
            <value>
                <fullName>Defended Action</fullName>
            </value>
            <value>
                <fullName>Media Requested - Awaiting</fullName>
            </value>
            <value>
                <fullName>Counterclaim</fullName>
            </value>
            <value>
                <fullName>Abandonned Claim</fullName>
            </value>
            <value>
                <fullName>Recommended for Legal Action</fullName>
            </value>
            <value>
                <fullName>Approved for Legal Action</fullName>
            </value>
            <value>
                <fullName>Reviewing for Legal action</fullName>
            </value>
            <value>
                <fullName>Demand Letter Sent</fullName>
            </value>
            <value>
                <fullName>Legal Action Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCustomerAccountJudgmentCntrl.cls
/**************************************************************************************************
 *
 *  Class:   TestCustomerAccountJudgmentCntrl
 *
 *  @description : This class contains unit tests for custom look up results
 *  @author : A5E Consulting
 *  @date : 01/08/2019
 * 
 *************************************************************************************************/

@isTest
public class TestCustomerAccountJudgmentCntrl{
    @testSetup
    static void testData(){
        Application_Config_Settings__c config = new Application_Config_Settings__c(Run_Product_Coll_Sub_Status_Validation__c = true);
        insert config;
         
        Account acc = TestRecordsFactory.createBusinessAccount('TestAccount');
		acc.RecordTypeID = TestRecordsFactory.getObjectRecordType('Account', 'CCS_Agency');
        insert acc;
        
        Judgment__c judg = new Judgment__c();
        judg.Legal_Agency__c = '29';
        insert judg;
        
        Product__c prod = TestRecordsFactory.createProduct('1111');
        prod.CCS_Agency__c = acc.Id;
        prod.Status__c = 'New Allocation - New Allocation';
        prod.Sub_Status__c = 'Ready';
        prod.Product_Status__c = 'Test';
        insert prod;
        
    }
    
   //Test linkRecords
    static testMethod void fetchAccountJudgments(){
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        CustomerAccountJudgmentCntrl.fetchAccountJudgments(accId);
    }
}