force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/CCS_Final_Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>CCS_Final_Deposit_Slip__c</fullName>
    <description>To Determine Final deposit slip is generated for particular day</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To Determine Final deposit slip is generated for particular day</inlineHelpText>
    <label>CCS Final Deposit Slip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Do_Not_Run_Payment_Validation__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Run_Payment_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not to run validation rule for Payment record update</description>
    <inlineHelpText>Not to run validation rule for Payment record update</inlineHelpText>
    <label>Do Not Run Payment Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Final_Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Final_Deposit_Slip__c</fullName>
    <description>Final Deposit Slip for the day</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Deposit Slip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/Deposit_Slip__c.object-meta.xml
<CustomObject>
    <description>View the deposit slips for today generated in previous step/tab - &quot;Generate Deposit Slip&quot;</description>
    <label>Deposit Slip</label>
    <nameField>
        <displayFormat>DS-{000}</displayFormat>
        <label>Deposit Slip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Slips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Amount__c</fullName>
    <label>CIML - 156 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Cheque__c</fullName>
    <label>CIML - 156 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/recordTypes/Insolvency_Deposit_Slip.recordType-meta.xml
<RecordType>
    <fullName>Insolvency_Deposit_Slip</fullName>
    <active>true</active>
    <description>Deposit Slip for Insolvency</description>
    <label>Insolvency Deposit Slip</label>
</RecordType>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Unallocated payment record</description>
    <inlineHelpText>Lookup field to Unallocated payment record</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <description>Payment Amount</description>
    <inlineHelpText>Payment Amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Deposit_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Name__c</fullName>
    <description>Name of custom setting</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of custom setting</inlineHelpText>
    <label>Deposit Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Do_Not_Process__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to not include dividend when generating deposit slip</description>
    <label>Do Not Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/recordTypes/Insolvency_Dividend.recordType-meta.xml
<RecordType>
    <fullName>Insolvency_Dividend</fullName>
    <active>true</active>
    <description>Dividends for Insolvency strip lists</description>
    <label>Insolvency Dividend</label>
</RecordType>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the generated Deposit Slip</description>
    <inlineHelpText>Link to the generated Deposit Slip</inlineHelpText>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/GenerateDepositSlipRecordsController.cls
public class GenerateDepositSlipRecordsController {
    
    public String type { get; set; }
    public Boolean depositSlipAvailable{get;set;}
    public Boolean showFinalDepositSlipButton{get;set;}
    public static List<Insolvency_Payment__c> insolvVardePayments{get;set;}
    public static List<Unallocated_Payment__c> unAllocPayList{get;set;}
    public static List<String> relatedVardeRemittanceIDs = new List<String>();
    public static List<Insolvency_payment__c> listCIHIAccounts{get; set;}
    public static List<Insolvency_payment__c> listVardeCDAccounts{get; set;}
    public static List<Insolvency_payment__c> listFortressAccounts{get; set;}
    public static List<Insolvency_payment__c> listEquitableAccounts{get; set;}
    public static List<Insolvency_payment__c> listVardeAccounts{get; set;}
    List<Insolvency_Payment__c> insolvPayToUpdate = new List<Insolvency_Payment__c>();
    Map<Id, Double> accountInsolvencyPaymentMap = new Map<Id, Double>();
    Application_Config_Settings__c appConfigFinal;//=Application_Config_Settings__c.getOrgDefaults();
    Map<String, Deposit_Accounts__c> depositAccountMap = Deposit_Accounts__c.getAll();
    public Deposit_Accounts__c depositAcc {set;get;}
    public String action = 'createPdfAttachment';
    
    public GenerateDepositSlipRecordsController(){
        appConfigFinal = [SELECT Final_Deposit_Slip__c, CCS_Final_Deposit_Slip__c, Do_Not_Run_Payment_Validation__c FROM Application_Config_Settings__c FOR UPDATE];//update for lock issue
        
        insolvVardePayments = new List<Insolvency_Payment__c>();
        unAllocPayList = new List<Unallocated_Payment__c>();
        insolvPayToUpdate = new List<Insolvency_Payment__c>();
        //Application_Config_Settings__c appConfigFinal = Application_Config_Settings__c.getOrgDefaults();
        showFinalDepositSlipButton = false;
        if(appConfigFinal.Final_Deposit_Slip__c == system.today()){
            showFinalDepositSlipButton = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is locked for the day'));
            return;
        }
        if(checkJobCompletion()){
            showFinalDepositSlipButton = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is in progress. Notification will be sent over Email.'));
            return;
        }
        List<Deposit_Slip__c> depositSlip = [SELECT Id, Name FROM Deposit_Slip__c WHERE CreatedDate = TODAY AND recordType.developerName = 'Insolvency_Deposit_Slip'];
        
        if(depositSlip.isEmpty()){
            depositSlipAvailable = false;
        }else{
            depositSlipAvailable = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Deposit Slip already created today : <a href="'+System.Url.getSalesforceBaseURL().toExternalForm() +'/'+depositSlip[0].Id+'" target="_blank">'+depositSlip[0].Name+'</a>'));
            
        }
        
    }
    @RemoteAction
    public static Boolean checkJobCompletion(){
        List<AsyncApexJob> listofAsyncJob = [select id,ApexClass.Name,Status, ExtendedStatus, MethodName, CreatedDate from AsyncApexJob where ApexClass.name = 'GenerateDepositSlipQueueable' and createddate = today and status = 'Queued'];
        return !listofAsyncJob.isEmpty();
    }
    public void generateDepositSlip(){
        
        DateTime LastDepositSlipCreatedDate = LastDepositSlipCreatedDate();
        List<AggregateResult> listAggregateResults = [select count(id) total, sum(Cheque_Amount__c) amount, Deposit_Account_Name__c
                                              from remittance__C 
                                              where lastmodifiedDate >= :LastDepositSlipCreatedDate
                                              AND Status__c = 'Processed'
                                              AND recordType.Developername = 'Insolvency_Dividend' AND Do_Not_Process__c = false
                                              group by Deposit_Account_Name__c ];
        
        if(listAggregateResults.size() == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No records available for Deposit Slip'));
            return;
        }
        //Delete today's old deposit slip
        List<Deposit_slip__c> listDepositSlip = [select id from Deposit_slip__c where createdDate = today AND recordType.developerName = 'Insolvency_Deposit_Slip'];
        DepositSlipTriggerHandler.runDepsoitSlipTrigger = False;
        database.delete(listDepositSlip, false);
        DepositSlipTriggerHandler.runDepsoitSlipTrigger = True;
        
        //Generate new deposit slip
        Deposit_Slip__c deposit = new Deposit_Slip__c();
        deposit.recordTypeId = [select id from RecordType where SobjectType = 'Deposit_Slip__C' and name like '%Insolvency%'].id;
        insert deposit;
        Boolean isError = false;
        
        Boolean flagCCL = false;
        Boolean flagETC = false;
        deposit.CIML_156_Total_Cheque__c = 0;
        deposit.CIML_156_Total_Amount__c = 0.0;
        
        if(listAggregateResults.size() > 0){
            System.enqueueJob(new GenerateDepositSlipQueueable(listAggregateResults, deposit, LastDepositSlipCreatedDate, appConfigFinal, action));
        }
        if(checkJobCompletion()){
            showFinalDepositSlipButton = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is in progress. Notification will be sent over Email.'));
            return;
        }
    }
    
    // Create attachment
    public static void createAttachment(Blob body, String depositSlipType, Id depositId){
        Attachment attach = new Attachment(); 
        DateTime d = Date.Today() ;
        String dateStr =  d.formatGMT('yyyy-MM-dd') ;
        attach.Body = body;
        attach.Name = depositSlipType+' - '+dateStr + '.pdf';
        attach.IsPrivate = false;
        attach.Description = '';
        attach.ParentId = depositId;
        insert attach;
    }
    
    //change Id's to String of list
    public static List<String> idToStringConvert(List<String> listOfID){
        List<String> listString = new List<String>();
        for(String idString : listOfID){
            listString.add('\'' + idString + '\'');
        }
        
        return listString;
    }
    
    public static DateTime lastDepositSlipCreatedDate(){
        List<Deposit_Slip__c> lastDepositSlip = [SELECT Id, Name, createdDate FROM Deposit_Slip__c WHERE CreatedDate <> TODAY AND recordType.developerName = 'Insolvency_Deposit_Slip' ORDER BY createdDate DESC];
        if(lastDepositSlip.size() > 0){
            return lastDepositSlip[0].createdDate;
        }else{
            system.debug(system.TODAY());
            return system.TODAY();
        }
    }
    
    public static String strCreatedDate(DateTime createdDateToCovert){
        //2019-01-02T11:15:42.000+0000
        String strDate = '' + createdDateToCovert;
        strDate = strDate.replace(' ', 'T');
        strDate += '.000+0000';
        
        return strDate;
    }
    public void finalDepositSlip(){
        
        List<Deposit_Slip__c> todayDepositSlip = [SELECT Id, Name, createdDate FROM Deposit_Slip__c WHERE CreatedDate = TODAY AND recordType.developerName = 'Insolvency_Deposit_Slip' ORDER BY createdDate DESC];
        System.debug('TodayDepositSlip---'+todayDepositSlip);
        if(todayDepositSlip.size()>0){
            showFinalDepositSlipButton = true;
            appConfigFinal.Final_Deposit_Slip__c = system.TODAY();
            update appConfigFinal;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is locked for the day'));
        }
        
    }
}