force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_EmailMessage_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_EmailMessage_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run EmailMessage Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/EFT_Files__c.object-meta.xml
<CustomObject>
    <label>EFT Files</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>EFT Files  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Files__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>EFT Files</relationshipLabel>
    <relationshipName>EFT_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/EFT_Processing_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>EFT Processing Config</label>
</CustomObject>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Insolvency_EFT_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_EFT_RecordTypeID__c</fullName>
    <description>record type ID for Insolvency EFT record</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Insolvency EFT RecordTypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Insolvency_Payment_Record_TypeID__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Payment_Record_TypeID__c</fullName>
    <description>Record type id of Insolvency Payment for EFT</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record type id of Insolvency Payment for EFT</inlineHelpText>
    <label>Insolvency Payment Record TypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Insolvency__r.Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Insolvency__r.Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to EFT Record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Portfolio_Name__c/Portfolio_Name__c.object-meta.xml
<CustomObject>
    <label>Portfolio Name</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Name__c/fields/Account_Purchasing_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Purchasing_Entity_ID__c</fullName>
    <description>Account Purchasing Entity ID (numeric)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account Purchasing Entity ID(numeric)</inlineHelpText>
    <label>Account Purchasing Entity ID</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to EFT record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/TestInsolvencyEFTProcessing.cls
@isTest
public class TestInsolvencyEFTProcessing {
    @testSetup
    public static void testSetup(){
        EFT_Processing_Config__c  config = new EFT_Processing_Config__c();
        config.Insolvency_EFT_RecordTypeID__c = Schema.SObjectType.EFT_Files__c.getRecordTypeInfosByName().get('Insolvency EFT').getRecordTypeId();
        config.Insolvency_Payment_Record_TypeID__c   = Schema.SObjectType.Insolvency_Payment__c.getRecordTypeInfosByName().get('Insolvency Payment').getRecordTypeId();
        insert config;
        
        Application_Config_Settings__c config1 =  new Application_Config_Settings__c();
        config1.Run_EmailMessage_Trigger__c = false;
        config1.Run_Insolvency_Account_Trigger__c = true;
        insert config1;
        Account Truscomp=new Account();
        Id Recrdid =[SELECT Id FROM RecordType WHERE SobjectType='Account' and name like 'Trustee Company'].id;
        Truscomp.RecordTypeId=Recrdid;
        Truscomp.name='Test';
        insert Truscomp;
        
        // Trustee Office Record
        Account Trusoff=new Account();
        Id Recordid =[SELECT Id FROM RecordType WHERE SobjectType='Account' and name like 'Trustee Office'].id;
        Trusoff.RecordTypeId=Recordid;
        Trusoff.name='Testrecord';
        Trusoff.Trustee_ID__c=Truscomp.id;
        Trusoff.Is_Active__c=True;
        Trusoff.Follow_up_Email__c='Test@test.com';
        insert Trusoff;
        
        //Insolvency Record
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Trustee__c=Trusoff.id;
        insert insolv1;
        
        Portfolio_Name__c portfolioName = new Portfolio_Name__c();
        portfolioName.name = 'AFSCARDS';
        portfolioName.Account_Purchasing_Entity_ID__c = 'test';
        insert portfolioName;
        
        list<RecordType> recordTypeList = new list<RecordType>([SELECT Id,Name FROM RecordType WHERE SobjectType='Insolvency_Account__c' and name like '%SPL%']);
        
        //Insolvency Account records
        Insolvency_Account__c insolvencyAccount = new Insolvency_Account__c();
        insolvencyAccount.RecordTypeId = recordTypeList[0].Id;
        insolvencyAccount.Name = '4537049889659';
        insolvencyAccount.Insolvency_Status__c = 'No PoC Required';
        insolvencyAccount.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insolvencyAccount.Claim_Type__c = 'Unsecured';
        insolvencyAccount.Insolvency__c = insolv1.Id;
        insolvencyAccount.Account_Number_Without_Space__c = '4537049889659';
        insolvencyAccount.Portfolio_Group_Name__c = 'CCL001';
        insolvencyAccount.Investment_Group__c = 'AFFIRM';
        insolvencyAccount.Portfolio_Name_Lookup__c = portfolioName.id;
        insert insolvencyAccount;
    }
    public static testMethod void TestPaymentUpload(){
        Application_Config_Settings__c config = new Application_Config_Settings__c();
        config.Run_EmailMessage_Trigger__c = false;
        //insert config;
        
        String testOutputJSON = '';
        InsolvencyPaymentUploadController controller = new InsolvencyPaymentUploadController();
        //upload error
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'error';
        controller.importDatatoApex();
        
        //account no null
        testOutputJSON = '[{'+
            '"AccountNumber":null,'+
            '"ClientID":254801.0,'+
            '"ClientName":"LEBLANC, JUSTIN ",'+
            '"PaymentSource":3,'+
            '"PaymentType":1000,'+
            '"NetPayment":390.0,'+
            '"FairSharePayment":110.0,'+
            '"GrossPayment":500.0'+
        '}]';
        controller = new InsolvencyPaymentUploadController();
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        
        //net payment null
        testOutputJSON = '[{'+
            '"AccountNumber":"4537049889659",'+
            '"ClientID":254801.0,'+
            '"ClientName":"LEBLANC, JUSTIN ",'+
            '"PaymentSource":3,'+
            '"PaymentType":1000,'+
            '"NetPayment":null,'+
            '"FairSharePayment":110.0,'+
            '"GrossPayment":500.0'+
        '}]';
        controller = new InsolvencyPaymentUploadController();
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        
        //success
        testOutputJSON = '[{'+
            '"AccountNumber":"4537049889659",'+
            '"ClientID":254801.0,'+
            '"ClientName":"LEBLANC, JUSTIN ",'+
            '"PaymentSource":3,'+
            '"PaymentType":1000,'+
            '"NetPayment":390.0,'+
            '"FairSharePayment":110.0,'+
            '"GrossPayment":500.0'+
        '},'+
        '{'+
            '"AccountNumber":"4537049851733",'+
            '"ClientID":257269.0,'+
            '"ClientName":"URINTSOV, OLGA ",'+
            '"PaymentSource":3,'+
            '"PaymentType":1000,'+
            '"NetPayment":50.7,'+
            '"FairSharePayment":14.3,'+
            '"GrossPayment":65.0'+
        '}]';
        controller = new InsolvencyPaymentUploadController();
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        
        EFT_Files__c eftInstance = new EFT_Files__c();
        insert eftInstance;
        system.debug('eftInstance: '+eftInstance);
        Test.setCurrentPageReference(new PageReference('InsolvencyPaymentUpload')); 
        System.currentPageReference().getParameters().put('id', eftInstance.Id);
        controller = new InsolvencyPaymentUploadController();
        controller.showAllocatedProductPayments();
        controller.ShowUnallocatedProductPayments();   
    }
    
    public static testMethod void testProcessBatch(){
        
        List<EFTUtil.paymentRecordsWrapper> listPaymentRecordWrapper = new List<EFTUtil.paymentRecordsWrapper>();
        EFTUtil.paymentRecordsWrapper wrapper = new EFTUtil.paymentRecordsWrapper();
        wrapper.accountNumber = '4537049889659';
        wrapper.chequeNumber = 'TestFile';
        wrapper.paymentSource = '3';
        wrapper.paymentType = '1000';
        wrapper.netPayment = '65.0';
        wrapper.postingDate = string.valueOf(system.today());
        listPaymentRecordWrapper.add(wrapper);
        
        EFT_Files__c eft = new EFT_Files__c();
        eft.Posting_Date__c = system.today();
        insert eft;
        
        ProcessInsolvencyEFTBatch batch1 = new ProcessInsolvencyEFTBatch(listPaymentRecordWrapper, eft);
        database.executeBatch(batch1);        
    }
    
    public static testMethod void testInsertInsolvencyPaymentBatch(){
        Insolvency_Account__c insolvencyAccount = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0];
        EFT_Files__c eft = new EFT_Files__c();
        insert eft;
        blob blob1;
        Attachment allocatedPayment = new Attachment();
        allocatedPayment.parentid = eft.id;
        allocatedPayment.name = 'Allocated Payments.csv';
        String attachBody = 'AccountNumber,accountID,netPayment,postingDate,shortURL,paymentSource,paymentType,chequeNumber';
        attachBody += '\n';
        attachBody += '4537049889659,'+insolvencyAccount.Id+',35.60,'+String.valueOf(system.today())+',null,null,null,TestCCSFileUpload';
        allocatedPayment.Body = Blob.valueOf(attachBody);
        insert allocatedPayment;
        
        InsertInsolvencyPaymentsBatch batch1 = new InsertInsolvencyPaymentsBatch(eft);
        database.executeBatch(batch1);
    }
    
    public static testMethod void testDisplayAllocatedInsolvencyPayments(){
        EFT_Files__c eftInstance = new EFT_Files__c();
        insert eftInstance;
        
        Insolvency_Payment__c paymentInstance1 = new Insolvency_Payment__c  ();
        paymentInstance1.Insolvency_Account__c = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0].ID;
        paymentInstance1.Payment_Posting_Date__c = system.today();
        paymentInstance1.Payment_Amount__c = 321.98;
        paymentInstance1.Cheque_Payment_Reference_Number__c  = 'Test File Uploaded123456';
        paymentInstance1.EFT_Files__c = eftInstance.Id;
        insert paymentInstance1;
        
        DisplayAllocatedInsolvencyController controller;
        Test.setCurrentPageReference(new PageReference('DisplayAllocatedInsolvencyPayments')); 
        System.currentPageReference().getParameters().put('id', eftInstance.Id);
        controller = new DisplayAllocatedInsolvencyController();
        controller.Save();
    }
    
    public static testMethod void testDisplayUnallocatedInsolvencyPayments(){
        Insolvency_Account__c insoAccount = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0];
        EFT_Files__c eft = new EFT_Files__c();
        eft.Allocated_Payments_Amount__c = 0;
        insert eft;
        blob blob1;
        Attachment unallocatedPayment = new Attachment();
        unallocatedPayment.parentid = eft.id;
        unallocatedPayment.name = 'Un-allocated Payments.csv';
        String attachBody = 'AccountNumber,NetPayment,postingDate,shortURL,paymentSource,paymentType,ChequeNumber';
        attachBody += '\n';
        attachBody += '4537049209659,'+'61.0,'+String.valueOf(system.today())+',www.google.com,,3,1000,TestInsolvencyFileUpload';
        attachBody += '4537049889659,'+'61.0,'+String.valueOf(system.today())+',www.google.com,3,1000,TestInsolvencyFileUpload';
        unallocatedPayment.Body = Blob.valueOf(attachBody);
        insert unallocatedPayment;
        
        Test.setCurrentPageReference(new PageReference('DisplayInsolvencyUnallocatedPayments')); 
        System.currentPageReference().getParameters().put('id', eft.Id);
        DisplayInsolUnAllocatedPaymentController controller = new DisplayInsolUnAllocatedPaymentController();
        controller.paymentRecordListInner[0].prodLookup.Insolvency_Account__c = insoAccount.Id;
        controller.Save();
        controller.Cancel();
        
        InsertUnallocatedPaymentsBatch batch2 = new InsertUnallocatedPaymentsBatch(controller.listUnallocatedPayment, eft, 'Insolvency');
        database.executeBatch(batch2);
    }
    
    public static testMethod void testDisplayUnAllocatedProcessedInsoPayments(){
        EFT_Files__c eftInstance = new EFT_Files__c();
        insert eftInstance;
        
        Unallocated_Payment__c paymentInstance1 = new Unallocated_Payment__c();
        paymentInstance1.Payment_Posting_Date__c = system.today();
        paymentInstance1.Unallocated_Amount__c = 321.98;
        paymentInstance1.Cheque_Number__c = 'Test File Uploaded123456';
        paymentInstance1.EFT_Files__c = eftInstance.Id;
        insert paymentInstance1;
        
        DisplayUnallocatedProcessedController controller;
        Test.setCurrentPageReference(new PageReference('DisplayUnallocatedProcessed')); 
        System.currentPageReference().getParameters().put('id', eftInstance.Id);
        System.currentPageReference().getParameters().put('rt', 'Insolvency');
        controller = new DisplayUnallocatedProcessedController();
        controller.redirectPaymentUpload();
    }
}