force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Creditor_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Creditor_Account_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Creditor Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Remittance_Validation__c.field-meta.xml
<CustomField>
    <fullName>Run_Remittance_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To run remittance validation rule</description>
    <inlineHelpText>To run remittance validation rule</inlineHelpText>
    <label>Run Remittance Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/Creditor_Account__c.object-meta.xml
<CustomObject>
    <description>Creditor Account records captured from Credit pack</description>
    <label>Creditor Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditor Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Creditor_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insolvency</description>
    <inlineHelpText>Insolvency</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Creditor Accounts</relationshipLabel>
    <relationshipName>Creditor_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Name_on_Clearing_Account__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_on_Clearing_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Name on Clearing Account</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Transit_Number__c.field-meta.xml
<CustomField>
    <fullName>Transit_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transit Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/TestCreditorAccountTriggerHandler.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of CreditorAccountTriggerHandler
 *  @author : A5E Consulting
 *  @date : 05/21/2024
 * 
 *************************************************************************************************/
 
 @isTest
 public class TestCreditorAccountTriggerHandler{
     
     @testSetup
     static void testData(){
           //Application config creation
         Application_Config_Settings__c config = new Application_Config_Settings__c(
             Run_Remittance_Validation__c = false,
             Run_Creditor_Account_Trigger__c = true,
             Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN',
             Run_Insolvency_Trigger__c = false,
             Run_Insolvency_Account_Duplicate_Check__c = true,
             Run_Insolvency_Account_Trigger__c = false,
             Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm',
             Run_Insolvency_Status_Validations__c = true,
             Bank_Eligible_for_Duplicate_Check__c = 'SPL',
             Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm'
         );
         insert config;
     }
     
     static testMethod void afterInsertTest(){
        Account Truscomp = new Account();
        Id Recrdid = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND name LIKE 'Trustee Company'].id;
        Truscomp.RecordTypeId = Recrdid;
        Truscomp.name = 'Test';
        insert Truscomp;

        Deposit_Accounts__c depositeAcc = new Deposit_Accounts__c();
        depositeAcc.Name = 'CCL';
        depositeAcc.Account_Number__c = '1993-130';
        depositeAcc.Bank_Name__c = 'Canaccede Credit LP Blocked';
        depositeAcc.Entity_Name__c = 'Canaccede Credit LP';
        depositeAcc.Account_Name_on_Clearing_Account__c = 'CCLP - 130';
        depositeAcc.Transit_Number__c = '03482';
        insert depositeAcc;

        // Trustee Office Record
        Account Trusoff = new Account();
        Id Recordid = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND name LIKE 'Trustee Office'].id;
        Trusoff.RecordTypeId = Recordid;
        Trusoff.name = 'Testrecord';
        Trusoff.Trustee_ID__c = Truscomp.id;
        Trusoff.Is_Active__c = true;
        Trusoff.Follow_up_Email__c = 'Test@test.com';
        insert Trusoff;

        //Insolvency Record
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '00-000001';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Trustee__c = Trusoff.id;
        insert insolv1;

        Creditor_Account__c creditorAccount=new Creditor_Account__c();
        creditorAccount.Name='test123';
        creditorAccount.Insolvency__c=insolv1.ID;
        creditorAccount.External_Correlation_ID__c='';
        insert creditorAccount;
        list<Creditor_Account__c> creditorAccountRecords=new list<Creditor_Account__c>();
        creditorAccountRecords.add(creditorAccount);
         CreditorAccountTriggerHandler.handleAfterInsert(creditorAccountRecords);         
     }    
 
 }