force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_EmailMessage_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_EmailMessage_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run EmailMessage Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Name_on_Clearing_Account__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_on_Clearing_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Name on Clearing Account</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Transit_Number__c.field-meta.xml
<CustomField>
    <fullName>Transit_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transit Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/EFT_Files__c.object-meta.xml
<CustomObject>
    <label>EFT Files</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>EFT Files  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Files__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>EFT Files</relationshipLabel>
    <relationshipName>EFT_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/EFT_Processing_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>EFT Processing Config</label>
</CustomObject>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Insolvency_EFT_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_EFT_RecordTypeID__c</fullName>
    <description>record type ID for Insolvency EFT record</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Insolvency EFT RecordTypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Insolvency_Payment_Record_TypeID__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Payment_Record_TypeID__c</fullName>
    <description>Record type id of Insolvency Payment for EFT</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record type id of Insolvency Payment for EFT</inlineHelpText>
    <label>Insolvency Payment Record TypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <formula>CASE(TEXT(Client_Identifier__c), &apos;Goeasy&apos;, &apos;Easyfinancial&apos;, TEXT(Client_Identifier__c))</formula>
    <inlineHelpText>Bank Name</inlineHelpText>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Insolvency__r.Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Insolvency__r.Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The Insolvency Account’s account number this payment belongs to</description>
    <formula>Insolvency_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Insolvency Account’s account number this payment belongs to</inlineHelpText>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <formula>Insolvency_Account__r.Bank_Name__c</formula>
    <inlineHelpText>Bank Name</inlineHelpText>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to EFT Record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/recordTypes/Remittance.recordType-meta.xml
<RecordType>
    <fullName>Remittance</fullName>
    <active>true</active>
    <description>Remittance Insolvency Payments</description>
    <label>Remittance</label>
</RecordType>

force-app/main/default/objects/Portfolio_Name__c/Portfolio_Name__c.object-meta.xml
<CustomObject>
    <label>Portfolio Name</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Name__c/fields/Account_Purchasing_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Purchasing_Entity_ID__c</fullName>
    <description>Account Purchasing Entity ID (numeric)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account Purchasing Entity ID(numeric)</inlineHelpText>
    <label>Account Purchasing Entity ID</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <description>Entity Name of Bank account to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Entity Name of Bank account to which Dividend has been moved</inlineHelpText>
    <label>Entity Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInsolvencyStriplistParsing.cls
@isTest
public class TestInsolvencyStriplistParsing {
    @testSetup
    public static void testSetup(){
        EFT_Processing_Config__c  config = new EFT_Processing_Config__c();
        config.Insolvency_EFT_RecordTypeID__c = Schema.SObjectType.EFT_Files__c.getRecordTypeInfosByName().get('Insolvency EFT').getRecordTypeId();
        config.Insolvency_Payment_Record_TypeID__c   = Schema.SObjectType.Insolvency_Payment__c.getRecordTypeInfosByName().get('Insolvency Payment').getRecordTypeId();
        insert config;
        
        Application_Config_Settings__c config1 =  new Application_Config_Settings__c();
        config1.Run_EmailMessage_Trigger__c = false;
        config1.Run_Insolvency_Account_Trigger__c = true;
        insert config1;
        Account Truscomp=new Account();
        Id Recrdid =[SELECT Id FROM RecordType WHERE SobjectType='Account' and name like 'Trustee Company'].id;
        Truscomp.RecordTypeId=Recrdid;
        Truscomp.name='Test';
        insert Truscomp;
        
        
        Deposit_Accounts__c depositeAcc = new Deposit_Accounts__c();
        depositeAcc.Name = 'CCL';
        depositeAcc.Account_Number__c = '1993-130';
        depositeAcc.Bank_Name__c = 'Canaccede Credit LP Blocked';
        depositeAcc.Entity_Name__c = 'Canaccede Credit LP';
        depositeAcc.Account_Name_on_Clearing_Account__c = 'CCLP - 130';
        depositeAcc.Transit_Number__c    = '03482';
        insert depositeAcc;
        
        // Trustee Office Record
        Account Trusoff=new Account();
        Id Recordid =[SELECT Id FROM RecordType WHERE SobjectType='Account' and name like 'Trustee Office'].id;
        Trusoff.RecordTypeId=Recordid;
        Trusoff.name='Testrecord';
        Trusoff.Trustee_ID__c=Truscomp.id;
        Trusoff.Is_Active__c=True;
        Trusoff.Follow_up_Email__c='Test@test.com';
        insert Trusoff;
        
        //Insolvency Record
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Trustee__c=Trusoff.id;
        insert insolv1;
        
        Portfolio_Name__c portfolioName = new Portfolio_Name__c();
        portfolioName.name = 'AFSCARDS';
        portfolioName.Account_Purchasing_Entity_ID__c = 'test';
        insert portfolioName;
        
        list<RecordType> recordTypeList = new list<RecordType>([SELECT Id,Name FROM RecordType WHERE SobjectType='Insolvency_Account__c' and name like '%SPL%']);
        
        //Insolvency Account records
        Insolvency_Account__c insolvencyAccount = new Insolvency_Account__c();
        insolvencyAccount.RecordTypeId = recordTypeList[0].Id;
        insolvencyAccount.Name = '4537049889659';
        insolvencyAccount.Insolvency_Status__c = 'No PoC Required';
        insolvencyAccount.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insolvencyAccount.Claim_Type__c = 'Unsecured';
        insolvencyAccount.Insolvency__c = insolv1.Id;
        insolvencyAccount.Account_Number_Without_Space__c = '4537049889659';
        insolvencyAccount.Portfolio_Group_Name__c = 'CCL001';
        //insolvencyAccount.Investment_Group__c = 'AFFIRM';
        //insolvencyAccount.Portfolio_Name_Lookup__c = portfolioName.id;
        insolvencyAccount.Debtor_1_Estate_Number__c = '00-000001';
        
        insert insolvencyAccount;
    }
    public static testMethod void TestPaymentUpload(){
        Application_Config_Settings__c config = new Application_Config_Settings__c();
        config.Run_EmailMessage_Trigger__c = false;
        //insert config;
        
        String testOutputJSON = '';
        Remittance__c remittanceInstance = new Remittance__c ();
        remittanceInstance.Cheque_Amount__c = 390;
        insert remittanceInstance;
        ApexPages.StandardController sc = new ApexPages.StandardController(remittanceInstance);
        StriplistInsolPaymentUploadController controller = new StriplistInsolPaymentUploadController(sc);
        //upload error
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'error';
        controller.importDatatoApex();
        
        //account no null
        testOutputJSON = '[{'+
            '"AccountNumber":null,'+
            '"ClientID":254801.0,'+
            '"ClientName":"LEBLANC, JUSTIN ",'+
            '"EstateNumber":00-000001,'+
            '"Amount":390.0,'+
        '}]';
        controller = new StriplistInsolPaymentUploadController(sc);
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        
        //net payment null
        testOutputJSON = '[{'+
            '"AccountNumber":"4537049889659",'+
            '"ClientID":254801.0,'+
            '"DebtorName":"LEBLANC JUSTIN ",'+
            '"EstateNumber":00-000001,'+
            '"Amount":null,'+
        '}]';
        controller = new StriplistInsolPaymentUploadController(sc);
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        
        remittanceInstance.Cheque_Amount__c = 313.53;
        update remittanceInstance;
        //success
        testOutputJSON = '['+
          '{'+
            '"EstateNumber": "00-000001",'+
            '"DebtorName": "WHALEN, BERNARD",'+
            '"Amount": 245.94,'+
            '"AccountNumber": "4537049889659"'+
          '},'+
          '{'+
            '"EstateNumber": "51-2397556",'+
            '"DebtorName": "WHEATLEY, KEVIN Michael",'+
            '"Amount": 67.59,'+
            '"AccountNumber": "438930122025"'+
          '}'+
        ']';
        controller = new StriplistInsolPaymentUploadController(sc);
        controller.outputJSON = testOutputJSON; 
        controller.fileUploadStatus = 'success';
        controller.importDatatoApex();
        controller.backToDividend();
        
        Test.setCurrentPageReference(new PageReference('InsolvencyPaymentUpload')); 
        System.currentPageReference().getParameters().put('id', remittanceInstance.Id);
        controller = new StriplistInsolPaymentUploadController(sc);
        controller.showAllocatedProductPayments();
        controller.ShowUnallocatedProductPayments();   
    }
    
    public static testMethod void testProcessBatch(){
        Remittance__c remittance = new Remittance__c();
        insert remittance;
        List<StriplistUtil.paymentRecordsWrapper> listPaymentRecordWrapper = new List<StriplistUtil.paymentRecordsWrapper>();
        StriplistUtil.paymentRecordsWrapper wrapper = new StriplistUtil.paymentRecordsWrapper();
        wrapper.accountNumber = '4537049889659';
        wrapper.debtorName = 'TestFile';
        wrapper.estateNumber = '00-000001';
        wrapper.amount = '65.0';
        listPaymentRecordWrapper.add(wrapper);
        wrapper = new StriplistUtil.paymentRecordsWrapper();
        wrapper.accountNumber = '111';
        wrapper.debtorName = 'TestFile';
        wrapper.estateNumber = '00-000001';
        wrapper.amount = '65.0';
        listPaymentRecordWrapper.add(wrapper);
        
        ProcessInsolvencyStriplistBatch batch1 = new ProcessInsolvencyStriplistBatch(listPaymentRecordWrapper, remittance);
        database.executeBatch(batch1);        
    }
    
    public static testMethod void testInsertInsolvencyPaymentBatch(){
        Insolvency_Account__c insolvencyAccount = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0];
        Remittance__c remittance = new Remittance__c();
        insert remittance;
        blob blob1;
        Attachment allocatedPayment = new Attachment();
        allocatedPayment.parentid = remittance.id;
        allocatedPayment.name = 'Allocated Payments.csv';
        String attachBody = 'AccountNumber,accountID,debtorName,estateNumber,amount';
        attachBody += '\n';
        attachBody += '4537049889659,'+insolvencyAccount.Id+',TestName,00-000001,100';
        allocatedPayment.Body = Blob.valueOf(attachBody);
        insert allocatedPayment;
        
        InsertInsolvencyPaymentsStriplistBatch batch1 = new InsertInsolvencyPaymentsStriplistBatch(remittance);
        database.executeBatch(batch1);
    }
    
    public static testMethod void testDisplayAllocatedInsolvencyPayments(){
        Remittance__c remittanceInstance = new Remittance__c();
        insert remittanceInstance;
        
        Insolvency_Payment__c paymentInstance1 = new Insolvency_Payment__c  ();
        paymentInstance1.Insolvency_Account__c = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0].ID;
        paymentInstance1.Payment_Posting_Date__c = system.today();
        paymentInstance1.Payment_Amount__c = 321.98;
        paymentInstance1.Cheque_Payment_Reference_Number__c  = 'Test File Uploaded123456';
        paymentInstance1.Remittance__c = remittanceInstance.Id;
        insert paymentInstance1;
        
        DisplayStriplistInsolAllocatedController controller;
        Test.setCurrentPageReference(new PageReference('DisplayStriplistInsolAllocatedPayments')); 
        System.currentPageReference().getParameters().put('id', remittanceInstance.Id);
        controller = new DisplayStriplistInsolAllocatedController();
        controller.Save();
        controller.Redirect();
    }
    
    public static testMethod void testDisplayUnallocatedInsolvencyPayments(){
        Insolvency_Account__c insoAccount = [SELECT ID FROM Insolvency_Account__c LIMIT 1][0];
        Remittance__c remittanceInstance = new Remittance__c();
        remittanceInstance.Allocated_Payments_Amount__c = 130;
        insert remittanceInstance;
        blob blob1;
        Attachment unallocatedPayment = new Attachment();
        unallocatedPayment.parentid = remittanceInstance.id;
        unallocatedPayment.name = 'Un-allocated Payments.csv';
        String attachBody = 'AccountNumber,accountID,debtorName,estateNumber,amount';
        attachBody += '\n';
        attachBody += '4537049889659,'+insoAccount.Id+',TestName,00-000001,100';
        unallocatedPayment.Body = Blob.valueOf(attachBody);
        insert unallocatedPayment;
        
        Test.setCurrentPageReference(new PageReference('DisplayStriplistUnallocatedPayments')); 
        System.currentPageReference().getParameters().put('id', remittanceInstance.Id);
        DisplayStriplistInsolUnallocController controller = new DisplayStriplistInsolUnallocController();
        controller.paymentRecordListInner[0].insolvencyAccInstance.Insolvency_Account__c = insoAccount.Id;
        controller.Save();
        controller.Cancel();
        
        InsertUnallocatedPaymentsStriplistBatch batch2 = new InsertUnallocatedPaymentsStriplistBatch(controller.listUnallocatedPayment, remittanceInstance, 'Insolvency');
        database.executeBatch(batch2);
    }
    
    public static testMethod void testFileUploadErrors(){
        Remittance__c remittanceInstance = new Remittance__c ();
        remittanceInstance.Cheque_Amount__c = 390;
        remittanceInstance.File_Processing_Status__c = 'Completed';
        remittanceInstance.Status__c = 'Processed';
        insert remittanceInstance;
        Test.setCurrentPageReference(new PageReference('StriplistInsolvencyPaymentUpload')); 
        System.currentPageReference().getParameters().put('id', remittanceInstance.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(remittanceInstance);
        StriplistInsolPaymentUploadController controller = new StriplistInsolPaymentUploadController(sc);
        remittanceInstance.Status__c = 'Payment Reversed';
        update remittanceInstance;
        controller = new StriplistInsolPaymentUploadController(sc);
        //upload error        
    }
}