force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Doc_Parser_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Doc_Parser_API_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Doc Parser API Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Domain Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Target_URL_for_DataFetch__c.field-meta.xml
<CustomField>
    <fullName>Target_URL_for_DataFetch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target URL for DataFetch</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Target_URL_for_Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Target_URL_for_Insolvency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target URL for Insolvency</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/EmailToCase.recordType-meta.xml
<RecordType>
    <fullName>EmailToCase</fullName>
    <active>true</active>
    <businessProcess>Email to Case Process</businessProcess>
    <description>Record type for Email to Case functionality</description>
    <label>EmailToCase</label>
</RecordType>

force-app/main/default/objects/Domain_Name_Parser__c/Domain_Name_Parser__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>English Domain Name Parser</label>
</CustomObject>

force-app/main/default/objects/French_Domain_Name_Parser__c/French_Domain_Name_Parser__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>French Domain Name Parser</label>
</CustomObject>

force-app/main/default/objects/French_Domain_Name_Parser__c/fields/Parser_Name__c.field-meta.xml
<CustomField>
    <fullName>Parser_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parser Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <description>To store document ID from DocParser</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To store document ID from DocParser</inlineHelpText>
    <label>Document ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Remote_ID__c.field-meta.xml
<CustomField>
    <fullName>Remote_ID__c</fullName>
    <description>Remote Id is Salesforce ID for related Case</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Remote Id is Salesforce ID for related Case</inlineHelpText>
    <label>Remote ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/TestInsolvencyAccountCreationFuture.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of InsolvencyAccountCreationFuture
 *  @author : A5E Consulting
 *  @date : 07/20/2018
 * 
 *************************************************************************************************/
@IsTest
public class TestInsolvencyAccountCreationFuture{
    
    @IsTest
    static void testDataCreation() {

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        User userRec = new User(Alias = 'standt', Email='sfuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@testorg.com',
            ManagerId = UserInfo.getUserId());  
        insert userRec;
        
        RecordType emailToCaseRecordType = [select Id from RecordType where SObjectType = 'Case' and DeveloperName = 'EmailToCase'];
        
        System.Test.startTest();

        //Application config creation
        Application_Config_Settings__c appConfig = new Application_Config_Settings__c();
        appConfig.Doc_Parser_API_Key__c = '7146d1c4f964579e9faa36c112b2035e3d965a03';
        //appConfig.Target_URL_for_Insolvency__c = 'https://api.docparser.com/v1/document/upload'; //'https://api.docparser.com/v1/document/upload
        appConfig.Target_URL_for_DataFetch__c = 'https://api.docparser.com/v1/document/upload/';
        insert appConfig;

        //English domain name record creation
        Domain_Name_Parser__c domainNameParserObj = new Domain_Name_Parser__c();
        domainNameParserObj.Name = 'a5econsulting.net';
        domainNameParserObj.Domain_Name__c = 'a5econsulting.net'; //'a5econsulting.net'
        domainNameParserObj.Parser_Name__c = 'tkvojqfbfkrm'; //'tkvojqfbfkrm'
        insert domainNameParserObj;

        //French domain name creation
        French_Domain_Name_Parser__c frenchDomainObj = new French_Domain_Name_Parser__c();
        frenchDomainObj.Name = 'a5econsulting.net';
        frenchDomainObj.Domain_Name__c = 'a5econsulting.net'; //a5econsulting.net
        frenchDomainObj.Parser_Name__c = 'cikdcfvgvhqa'; //cikdcfvgvhqa
        insert frenchDomainObj;

        //Case record creation
        Case caseObj = new Case();
        caseObj.SuppliedEmail = 'abc@a5econsulting.net';
        caseObj.Assigned_To__c = userRec.Id;
        caseObj.Status = 'In Progress';
        caseObj.Document_ID__c = '27367623767';
        caseObj.Creditor_s_Pack_Language__c = 'English';
        caseObj.RecordTypeId = emailToCaseRecordType.Id;
        insert caseObj;
        
        EmailMessage emailMsg =  new EmailMessage();
        emailMsg.relatedToid = caseObj.Id;
        emailMsg.TextBody = 'Test Email';
        emailMsg.FromAddress = 'abc@gmail.com';
        emailMsg.ToAddress = 'xyz@gmail.com';
        insert emailMsg;
        
        //Attachment record creation
        Attachment att = new Attachment();
        att.parentId = caseObj.Id;
        att.Body = Blob.valueOf('Test Attach');
        att.Name= 'Test';
        insert att; 
        
        //Document_ID__c
        //Insolvency creation
        Insolvency__c insolvencyRec = new Insolvency__c();
        insolvencyRec.Name = 'INSOL-90809';
        insolvencyRec.Insolvency_Type__c = 'Consumer Proposal';
        insolvencyRec.Insolvency_Status__c = 'For Owner Review';
        insolvencyRec.Document_ID__c = '27367623767';
        insolvencyRec.remote_ID__C = caseObj.id;
        insert insolvencyRec;
        
        // This causes a fake response to be generated
        Test.setMock(HttpCalloutMock.class, new DocParserMockResponseGenerator());
        
        // Call the method that invokes a callout
        InsolvencyAccountCreationFuture.SendPDFtoParser(caseObj.id);
        
        caseObj.Status = 'In Progress';
        caseObj.Document_ID__c = '27367623767';
        caseObj.Creditor_s_Pack_Language__c = 'French';
        update caseObj;
        
        // This causes a fake response to be generated
        Test.setMock(HttpCalloutMock.class, new DocParserMockResponseGenerator());
        
        System.Test.stopTest();

    }
}