force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Attachment_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Attachment_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Run Attachment Trigger</description>
    <inlineHelpText>Run Attachment Trigger</inlineHelpText>
    <label>Run Attachment Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Remittance_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Remittance_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Remittance Trigger</description>
    <inlineHelpText>Run Remittance Trigger</inlineHelpText>
    <label>Run Remittance Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Remittance_Validation__c.field-meta.xml
<CustomField>
    <fullName>Run_Remittance_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To run remittance validation rule</description>
    <inlineHelpText>To run remittance validation rule</inlineHelpText>
    <label>Run Remittance Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAttachmentTriggerHandler.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class contains unit tests for validating behavior of AttachmentTriggerHandler
*  @author : A5E Consulting
*  @date : 10/14/2016
* 
*************************************************************************************************/
@isTest
private class TestAttachmentTriggerHandler {
    
    static {
        System.Test.startTest();
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.Run_Product_Validation_Trigger__c = true;
        loanSettings.Run_Product_Trigger__c = true;
        //loanSettings.Run_Attachment_Trigger__c = true;
        insert loanSettings;        
        Application_Config_Settings__c config = new Application_Config_Settings__c(
            Run_Remittance_Validation__c = false,
            Run_Remittance_Trigger__c = true,
            Run_Attachment_Trigger__c = true,
            Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN',
            Run_Insolvency_Trigger__c = false,
            Run_Insolvency_Account_Duplicate_Check__c = true,
            Run_Insolvency_Account_Trigger__c = false,
            Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm',
            Run_Insolvency_Status_Validations__c = true,
            Bank_Eligible_for_Duplicate_Check__c = 'SPL',
            Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm'
        );
        insert config;  
    }
    
    static testMethod void attachmentTest(){
        
        //Run As CSR User
        User csrUser = TestRecordsFactory.getCSRUser();
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.Payment_Setup_Status__c = 'Automated';
        prod.Funding_Status__c = 'Pending';
        prod.Funding_Type__c = 'Automated';
        prod.Disbursement_Amount__c = 2000.00;
        insert prod;
        
        //Delete Attachment
        Attachment attchDelete = new Attachment();
        attchDelete.body = Blob.valueof('Test Body Delete');
        attchDelete.name = 'AttchDelete.pdf';
        attchDelete.parentId = prod.Id;
        insert attchDelete;
        List<Attachment> deleteList = new List<Attachment>();
        deleteList.add(attchDelete);
        System.runAs(csrUser) {
            AttachmentTriggerHandler.handleBeforeDelete(deleteList);
        }
        
        //Edit Attachment
        Attachment attchEdit = new Attachment();
        attchEdit.body = Blob.valueof('Test Body Edit');
        attchEdit.name = 'AttchEdit.pdf';
        attchEdit.parentId = prod.Id;
        insert attchEdit;
        List<Attachment> editList = new List<Attachment>();
        editList.add(attchEdit);        
        System.runAs(csrUser) {
            AttachmentTriggerHandler.handleBeforeEdit(editList);
        }
        
        delete attchDelete;
        //After Attachment is Deleted 
        if(attchDelete==Null){
            List<Attachment> attachm = new list<Attachment>();
            List<Task> activities = new List<Task>();
            for(Attachment attach : attachm){
                Task activity = new Task();
                activity.Subject = 'Deleted-'+attach.Name;
                activity.WhatId = attach.ParentId;
                activity.Status = 'Completed';
                activities.add(activity);
            }
            if(activities.size() > 0){
                insert activities;
            }
            
            System.runAs(csrUser) {
                AttachmentTriggerHandler.handleAfterDelete(attachm);
            }
        }
    }    
    
    static testMethod void attachmentCoomunityUser(){
        
        Insolvency_Account__c inAcc = new Insolvency_Account__c(Name='werty');
        insert inAcc;
        
        //Delete Attachment
        Attachment attchDelete = new Attachment();
        attchDelete.body = Blob.valueof('Test Body Delete');
        attchDelete.name = 'AttchDelete.pdf';
        attchDelete.parentId = inAcc.Id;
        insert attchDelete;
        List<Attachment> deleteList = new List<Attachment>();
        deleteList.add(attchDelete);
        AttachmentTriggerHandler.handleBeforeDelete(deleteList);
        
        //After Attachment is Deleted 
        
        List<Attachment> attachm = new list<Attachment>();
        List<Task> activities = new List<Task>();
        for(Attachment attach : attachm){
            Task activity = new Task();
            activity.Subject = 'Deleted-'+attach.Name;
            activity.WhatId = attach.ParentId;
            activity.Status = 'Completed';
            activities.add(activity);
        }
        if(activities.size() > 0){
            insert activities;
        }
        AttachmentTriggerHandler.handleAfterDelete(deleteList);
        System.Test.stopTest();        
    }
}