force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Do_Not_Run_Payment_Validation__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Run_Payment_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not to run validation rule for Payment record update</description>
    <inlineHelpText>Not to run validation rule for Payment record update</inlineHelpText>
    <label>Do Not Run Payment Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/Deposit_Slip__c.object-meta.xml
<CustomObject>
    <description>View the deposit slips for today generated in previous step/tab - &quot;Generate Deposit Slip&quot;</description>
    <label>Deposit Slip</label>
    <nameField>
        <displayFormat>DS-{000}</displayFormat>
        <label>Deposit Slip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Slips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/fields/A1LP_394_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>A1LP_394_Total_Amount__c</fullName>
    <label>FIM - 810 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/A1LP_394_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>A1LP_394_Total_Cheque__c</fullName>
    <label>FIM - 810 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/ACQ_618_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACQ_618_Total_Amount__c</fullName>
    <label>ACQ - 618 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/ACQ_618_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>ACQ_618_Total_Cheque__c</fullName>
    <label>ACQ - 618 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/AFSI_631_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>AFSI_631_Total_Amount__c</fullName>
    <label>AFSI - 631 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/AFSI_631_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>AFSI_631_Total_Cheque__c</fullName>
    <label>AFSI - 631 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CAL_767_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CAL_767_Total_Amount__c</fullName>
    <label>CAL - 767 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CAL_767_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CAL_767_Total_Cheque__c</fullName>
    <label>CAL - 767 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CCLP_130_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CCLP_130_Total_Amount__c</fullName>
    <label>CCLP - 130 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CCLP_130_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CCLP_130_Total_Cheque__c</fullName>
    <label>CCLP - 130 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CFL_602_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CFL_602_Total_Amount__c</fullName>
    <description>Total amount on the CFL - 602 cheques</description>
    <inlineHelpText>Total amount on the CFL - 602 cheques</inlineHelpText>
    <label>CFL - 602 Total Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CFL_602_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CFL_602_Total_Cheque__c</fullName>
    <description>Total number of cheques for CFL - 602</description>
    <inlineHelpText>Total number of cheques for CFL - 602</inlineHelpText>
    <label>CFL - 602 Total # Cheque</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIHI_877_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CIHI_877_Total_Amount__c</fullName>
    <label>CIHI - 877 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIHI_877_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CIHI_877_Total_Cheque__c</fullName>
    <label>CIHI - 877 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Amount__c</fullName>
    <label>CIML - 156 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Cheque__c</fullName>
    <label>CIML - 156 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/recordTypes/Insolvency_Deposit_Slip.recordType-meta.xml
<RecordType>
    <fullName>Insolvency_Deposit_Slip</fullName>
    <active>true</active>
    <description>Deposit Slip for Insolvency</description>
    <label>Insolvency Deposit Slip</label>
</RecordType>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Unallocated payment record</description>
    <inlineHelpText>Lookup field to Unallocated payment record</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Deposit_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Name__c</fullName>
    <description>Name of custom setting</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of custom setting</inlineHelpText>
    <label>Deposit Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Do_Not_Process__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to not include dividend when generating deposit slip</description>
    <label>Do Not Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <description>Entity Name of Bank account to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Entity Name of Bank account to which Dividend has been moved</inlineHelpText>
    <label>Entity Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Trustee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trustee Company lookup</description>
    <inlineHelpText>Trustee Company lookup</inlineHelpText>
    <label>Trustee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>012f10000015HcqAAE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Remittance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/recordTypes/Insolvency_Dividend.recordType-meta.xml
<RecordType>
    <fullName>Insolvency_Dividend</fullName>
    <active>true</active>
    <description>Dividends for Insolvency strip lists</description>
    <label>Insolvency Dividend</label>
</RecordType>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To know whether this is unallocated amount is allocated to some Insolvency Account or not</description>
    <label>Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the generated Deposit Slip</description>
    <inlineHelpText>Link to the generated Deposit Slip</inlineHelpText>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if unallocated payment has been remitted back to bank</description>
    <inlineHelpText>To track if unallocated payment has been remitted back to bank</inlineHelpText>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Is_Payments_Reversed__c.field-meta.xml
<CustomField>
    <fullName>Is_Payments_Reversed__c</fullName>
    <label>Payment Reversed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Unauthorised</fullName>
            </value>
            <value>
                <fullName>Stale Dated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateDepositSlipQueueable.cls
/**
* @description       : Queueable class to generate Deposit Slips
* @author            : pradeepk@a5econsulting.net
* @group             :
* @last modified on  : 01-27-2025
* @last modified by  : pradeepk@a5econsulting.net
**/
public with sharing class GenerateDepositSlipQueueable implements Queueable, Database.AllowsCallouts{
    public DateTime LastDepositSlipCreatedDate;
    public List<AggregateResult> listOfAggregateResult;
    public AggregateResult aggregateResult;
    public Map<String, Deposit_Accounts__c> depositAccountMap = Deposit_Accounts__c.getAll();
    public Deposit_Slip__c deposit;
    public Application_Config_Settings__c appConfigFinal;
    public String action = 'Update';
    public Boolean flagCCL = false;
    public Boolean flagETC = false;
    
    public GenerateDepositSlipQueueable(List<AggregateResult> listOfAggregateResult, 
                                        Deposit_Slip__c deposit, 
                                        DateTime LastDepositSlipCreatedDate,
                                        Application_Config_Settings__c appConfigFinal,
                                        String action){
                                            this.action = action;
                                            this.listOfAggregateResult = listOfAggregateResult;
                                            this.deposit = deposit;
                                            this.LastDepositSlipCreatedDate = LastDepositSlipCreatedDate;
                                            this.appConfigFinal = appConfigFinal;
                                            if(listOfAggregateResult.size() > 0){
                                                this.aggregateResult = listOfAggregateResult[0];
                                            }                                            
                                        }
    public GenerateDepositSlipQueueable(List<AggregateResult> listOfAggregateResult,
                                        Deposit_Slip__c deposit, 
                                        DateTime LastDepositSlipCreatedDate,
                                        Application_Config_Settings__c appConfigFinal,
                                        String action, Boolean flagCCL, Boolean flagETC
                                        ){
        									this.action = action;
                                            this.flagCCL = flagCCL;
                                            this.flagETC = flagETC;
        									this.listOfAggregateResult = listOfAggregateResult;
                                            this.deposit = deposit;
                                            this.LastDepositSlipCreatedDate = LastDepositSlipCreatedDate;
                                            this.appConfigFinal = appConfigFinal;
                                            if(listOfAggregateResult.size() > 0){
                                                this.aggregateResult = listOfAggregateResult[0];
                                            }
                                        }
    /**
    * @description : Execute method
    * @author pradeepk@a5econsulting.net | 01-27-2025
    * @param context
    **/
    public void execute(QueueableContext context) { 
        if(aggregateResult != null){            
            String depoAccName = (String)aggregateResult.get('Deposit_Account_Name__c');
            System.debug('depoAccName:: '+depoAccName);
            if(null == depoAccName){
                action = 'skipNcontinue';
            }
            if(flagCCL == false && (depoAccName == 'CCL' || depoAccName == 'CLP')){
                flagCCL = true;
                action = 'createPdfAttachment';
            }else if(flagCCL == true && (depoAccName == 'CCL' || depoAccName == 'CLP')){
                action = 'skipNcontinue';
            }        
            if(flagETC == false && (depoAccName == 'ETC' || depoAccName == 'AFF')){
                flagETC = true;
                action = 'createPdfAttachment';
            }else if(flagETC == true && (depoAccName == 'ETC' || depoAccName == 'AFF')){
                action = 'skipNcontinue';
            }
            if(depoAccName != 'CCL' &&
              depoAccName != 'CLP' &&
              depoAccName != 'ETC' &&
              depoAccName != 'AFF' &&
              null != depoAccName){
                action = 'createPdfAttachment';
            }
        }
        
        switch on action{
            when 'updatePayments'{
                updatePayments();
            }
            when 'createPdfAttachment'{
                createPdfAttachment();
            }
            when 'skipNcontinue'{
                skipNcontinue();
            }
        }
    }
    public void sendNotification(){
        /* Sending of email */
        List<Deposit_Slip__c> depositSlipRecord = [select id, name from Deposit_Slip__c where createdDate = Today AND recordType.developerName = 'Insolvency_Deposit_Slip' order by createdDate];
        if(depositSlipRecord.size() > 0){
           	String emailId = UserInfo.getUserEmail();
            if(!String.isBlank(emailId)){
               	List<String> toAddressList = new List<String>{emailId};
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.toAddresses = toAddressList;
                message.htmlBody = 'Deposit Slip generated successfully : <a href="' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + depositSlipRecord[0].Id + '" target="_blank">' + depositSlipRecord[0].Name + '</a>';
                message.subject = 'Generate Deposit Slip';
                Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            }             
        }        
    }
    public void skipNcontinue(){
        if(listOfAggregateResult.size() > 0){
           	listOfAggregateResult.remove(0);
            if (!Test.isRunningTest()) {
                if(listOfAggregateResult.size() > 0){
                    System.enqueueJob(new GenerateDepositSlipQueueable(listOfAggregateResult, deposit, LastDepositSlipCreatedDate, appConfigFinal, 'createPdfAttachment', flagCCL, flagETC));
                }else{
                    System.enqueueJob(new GenerateDepositSlipQueueable(listOfAggregateResult, deposit, LastDepositSlipCreatedDate, appConfigFinal, 'updatePayments', flagCCL, flagETC));
                } 
            }
        }        
    }
    public void updatePayments(){
        List<Insolvency_payment__C> listPayment = [select id, name, remittance__r.Deposit_Account_Name__c
                                                   from Insolvency_payment__C
                                                   where remittance__r.lastmodifiedDate >= :LastDepositSlipCreatedDate
                                                   AND remittance__r.Status__c = 'Processed'
                                                   AND Remittance__r.Do_Not_Process__c = false
                                                   AND remittance__r.recordtype.Developername = 'Insolvency_Dividend'
                                                   AND Is_Payment_Remitted__c = False];
        
        List<Unallocated_payment__C> listUnallocPay = [select id, name, remittance__r.Deposit_Account_Name__c
                                                       from Unallocated_payment__C
                                                       where remittance__r.lastmodifiedDate >= :LastDepositSlipCreatedDate
                                                       AND remittance__r.Status__c = 'Processed'
                                                       AND remittance__r.recordtype.Developername = 'Insolvency_Dividend'
                                                       AND allocated__c = false
                                                       AND Remittance__r.Do_Not_Process__c = false
                                                       AND Is_Payment_Remitted__c = false
                                                       AND Is_Payments_Reversed__c = null];
        
        for(Insolvency_payment__C insolPay : listPayment){
            insolpay.Deposit_Slip__c = deposit.Id;
        }
        //Application_Config_Settings__c appConfig = Application_Config_Settings__c.getOrgDefaults();
        appConfigFinal.Do_Not_Run_Payment_Validation__c = true;
        update appConfigFinal;
        Set<Insolvency_Payment__c> setPaymentRecords = new Set<Insolvency_Payment__c>(listPayment );
        List<Insolvency_Payment__c> listPaymentRecordsToUpdate = new List<Insolvency_Payment__c>(setPaymentRecords);
        update listPaymentRecordsToUpdate;
        appConfigFinal.Do_Not_Run_Payment_Validation__c = false;
        update appConfigFinal;
        
        //Update Unallocated Payments
        for(Unallocated_payment__C insolPay : listUnallocPay){
            insolpay.Deposit_Slip__c = deposit.Id;
        }
        update listUnallocPay;
        
        update deposit;
        
        //Send Email Notification to the user notifying the completion of deposit slip generation
        sendNotification();
    }
    
    public void createPdfAttachment(){
        try {
            String depoAccName = (String)aggregateResult.get('Deposit_Account_Name__c');
            
            PageReference depositSlip = new PageReference('/apex/GenerateSlip');
            depositSlip.getParameters().put('type', depoAccName);            
            blob pdfBody;
            if(Test.isRunningTest()) {
                pdfBody = Blob.valueOf('test');
            }else{
                pdfBody = depositSlip.getContent();
            }
            
            GenerateDepositSlipRecordsController.createAttachment(pdfBody, (depositAccountMap.get(depoAccName )).Entity_Name__c, deposit.Id);
            
            if(depoAccName == 'CIML'){
                PageReference depositSlipCanaccede = new PageReference('/apex/GenerateSlip');
                depositSlipCanaccede.getParameters().put('type', 'Canaccede_Account_Perticulars');
                
                blob pdfBodyCanaccede;
                if(Test.isRunningTest()) {
                    pdfBodyCanaccede = Blob.valueOf('test');
                }else{
                    pdfBodyCanaccede = depositSlipCanaccede.getContent();
                }
                
                GenerateDepositSlipRecordsController.createAttachment(pdfBodyCanaccede, 'Canaccede Suspense Account', deposit.Id);
                
            }
            if(depoAccName == 'AFSI'){
                PageReference depositSlipAffirm = new PageReference('/apex/GenerateSlip');
                depositSlipAffirm.getParameters().put('type', 'Affirm_Account_Perticulars');
                
                blob pdfBodyAffirm;
                if(Test.isRunningTest()) {
                    pdfBodyAffirm = Blob.valueOf('test');
                }else{
                    pdfBodyAffirm = depositSlipAffirm.getContent();
                }
                GenerateDepositSlipRecordsController.createAttachment(pdfBodyAffirm, 'Fidem Suspense Account', deposit.Id);
                
            }
            
            if(depoAccName == 'AAL'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'ETC' || depoAccName == 'AFF'){
                deposit.A1LP_394_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.A1LP_394_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'AFL'){
                deposit.ACQ_618_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.ACQ_618_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'CAL'){
                deposit.CAL_767_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CAL_767_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'CIH'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'CCL' || depoAccName == 'CLP'){
                deposit.CCLP_130_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CCLP_130_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'CIA'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'CFL'){
                deposit.CFL_602_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.CFL_602_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else if(depoAccName == 'AFSI'){
                deposit.AFSI_631_Total_Cheque__c = (Integer)aggregateResult.get('total');
                deposit.AFSI_631_Total_Amount__c = (Decimal)aggregateResult.get('amount');
            }else {
                deposit.CIML_156_Total_Cheque__c += (Integer)aggregateResult.get('total');
                deposit.CIML_156_Total_Amount__c += (Decimal)aggregateResult.get('amount');
            }
            listOfAggregateResult.remove(0);
            if (!Test.isRunningTest()) {
                if(listOfAggregateResult.size() > 0){
                    System.enqueueJob(new GenerateDepositSlipQueueable(listOfAggregateResult, deposit, LastDepositSlipCreatedDate, appConfigFinal, 'createPdfAttachment', flagCCL, flagETC));
                }else{
                    System.enqueueJob(new GenerateDepositSlipQueueable(listOfAggregateResult, deposit, LastDepositSlipCreatedDate, appConfigFinal, 'updatePayments', flagCCL, flagETC));
                }
            }
        }catch(Exception ex){
            System.debug('Exception occured: '+ex.getMessage());
        }
    }
}