force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size__c</fullName>
    <description>Maximum Email Attachments Size</description>
    <inlineHelpText>Maximum Email Attachments Size</inlineHelpText>
    <label>Maximum Email Attachments Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size_Text__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size_Text__c</fullName>
    <description>Maximum Email Attachments Size Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Maximum Email Attachments Size Text</inlineHelpText>
    <label>Maximum Email Attachments Size Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Received_Date__c</fullName>
    <description>The date that the creditor’s package was received.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the creditor’s package was received.</inlineHelpText>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Received_Date__c</fullName>
    <description>The date that the creditor’s package was received.</description>
    <formula>Insolvency__r.Insolvency_Received_Date__c</formula>
    <inlineHelpText>The date that the creditor’s package was received.</inlineHelpText>
    <label>Insolvency Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Insolvency__r.Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Account_Statement_Not_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Account_Statement_Not_Allowed__c</fullName>
    <description>Account statement should be visible only to some particular trustee</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account statement should be visible only to some particular trustee</inlineHelpText>
    <label>Account Statement Not Allowed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_French_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_French_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG French Office Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Fax_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Fax Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name_2__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Phone Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Notice_to_Trustee_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Notice_to_Trustee_Template_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notice to Trustee Template Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestServicerNoticeToTrusteeController.cls
/**************************************************************************************************
 *  Class:   TestServicerNoticeToTrusteeController
 *  @description : This class contains unit tests for sending Notice To Servicer
 *  @author : A5E Consulting
 *  @date : 31/05/2018
 * 
 *************************************************************************************************/
@isTest
public class TestServicerNoticeToTrusteeController {
    
    @testSetup 
    static void testData() {
         Application_Config_Settings__c config = new Application_Config_Settings__c(Run_Insolvency_Status_Validations__c = True,
                                                                                      Maximum_Email_Attachments_Size__c = 18874368,
                                                                                      Maximum_Email_Attachments_Size_Text__c = 'You can send attachments only upto 18 MB',
                                                                                     Run_Insolvency_Account_Trigger__c = true,
                                                                                     Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm',
        																			 Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm',
        																			 Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm',
        																			 Bank_Eligible_for_Duplicate_Check__c = 'SPL',
        																		     Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN',
        																	         Run_Insolvency_Trigger__c = false,
        																			 Run_Insolvency_Account_Duplicate_Check__c = True);
         insert config;
        
        User u = [SELECT Id FROM User WHERE Id !=: UserInfo.getUserId() AND Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
        //Email Template Insertion 
        System.runAs(u){
            EmailTemplate NoTTemplate = new EmailTemplate(Name = 'Notice to Trustee Template',TemplateType  = 'custom', DeveloperName='Notice_to_Trustee_Template', HtmlValue = '{!TODAY()}', Body = '{!TODAY()}',Subject = 'Servicer Notice to Trustee', FolderId = UserInfo.getUserId());      
        	insert NoTTemplate;
             
         	PoC_Package_Settings__c poc = new PoC_Package_Settings__c(Name = 'Scotia Bank', 
                                                                         Client_Company_Name__c = 'Canaccede International ltd.', 
                                                                         CFG_Office_Phone_Number__c = '800-800-800', 
                                                                         CFG_Office_Name__c = 'The Scotia Bank',
                                                                         CFG_Office_Email_Address__c = 'test@canaccede.com',
                                                                         CFG_Office_Fax_Number__c = '111-111-111',
                                                                         CFG_Office_Name_2__c = 'temp',
                                                                         Notice_to_Trustee_Template_Id__c = NoTTemplate.Id,
                                                                      	 CFG_French_Office_Name__c = 'Canaccede International Management Ltd.',
                                                                         Account_Statement_Not_Allowed__c  = '00X17000000RbO1EAK');                                                                    
        	insert poc;
            
            PoC_Package_Settings__c poc1 = new PoC_Package_Settings__c(Name = 'Scotia Bank', 
                                                                         Client_Company_Name__c = 'Canaccede International ltd.', 
                                                                         CFG_Office_Phone_Number__c = '800-800-800', 
                                                                         CFG_Office_Name__c = 'CFG Canada Funding, LLC',
                                                                         CFG_Office_Email_Address__c = 'test@canaccede.com',
                                                                         CFG_Office_Fax_Number__c = '111-111-111',
                                                                         CFG_Office_Name_2__c = 'temp',
                                                                         Notice_to_Trustee_Template_Id__c = NoTTemplate.Id,
                                                                       	 CFG_French_Office_Name__c = 'Canaccede International Management Ltd.',
                                                                         Account_Statement_Not_Allowed__c  = '00X17000000RbO1EAK');                                                                    
        	insert poc1;
        }
        //Cusomer record Insertion
        Account parentAcc = new Account(Name = 'my acc', Communication_Preference__c = 'Email', 
                                        Business_Email__c = 'test@sample.com', BillingStreet = 'test', 
                                        BillingState = 'test', BillingPostalcode = 'test',
                                       BillingCity = 'test',Is_Active__c=True);
        insert parentAcc;
        //Insolvency record Insertion
        Insolvency__c insolv = new Insolvency__c();
        insolv.name = 'insolv';
        insolv.Insolvency_Type__c = 'Bankruptcy	';
        insolv.Insolvency_Received_Date__c = system.today();
        insolv.Insolvency_Status__c = 'Active';
        insolv.Insolvency_Date__c = system.today();
        insolv.Debtor_1_Court_Number__c = 'test';
        insolv.Court_Division_Number__c = 'test';
        insolv.Court_District_Name__c = 'Mission';
        insolv.Court_Province__c = 'Newfoundland and Labrador';
        insolv.Debtor_2_First_Name__c = 'Gari';
        insolv.Debtor_2_Last_Name__c = 'Steves';
        insolv.Debtor_2_Date_of_Birth__c = system.today();
        insolv.Debtor_2_Gender__c = 'Male';
        insolv.Debtor_2_Mailing_Street__c = '45 A street 12';
        insolv.Debtor_2_Mailing_City__c = 'test city';
        insolv.Debtor_2_Mailing_State_Province__c = 'Newfoundland and Labrador';
        insolv.Debtor_2_Mailing_Postal_Code__c = 'N8U 7Y7';
        insolv.Trustee__c = parentAcc.Id;
        insert insolv;
        //Insolvency Account record Insertion 
        Insolvency_Account__c insolcAcc = new Insolvency_Account__c(Claim_Type__c = 'Unsecured', 
                                                                 Proof_of_Claim_Required__c = false, 
                                                                 Client_Identifier__c='Scotia Bank',
                                                                 Insolvency__c = insolv.Id,
                                                                 Name='Test- 001',
                                                                 Insolvency_Status_Last_Changed__c = System.Today(),
                                                                 Servicer_Notice_to_Trustee_Sent_Date__c = System.Today(),
                                                                 Insolvency_Status__c = 'For Owner Review',
                                                                 Account_Number_Without_Space__c='Test-001');
                                                                   
        insert insolcAcc;
        Insolvency_Account__c insolcAcc1 = new Insolvency_Account__c(Claim_Type__c = 'Unsecured', 
                                                                 Proof_of_Claim_Required__c = false, 
                                                                 Client_Identifier__c='Goeasy',
                                                                 Insolvency__c = insolv.Id,
                                                                 Name='Test- 001',
                                                                 Insolvency_Status_Last_Changed__c = System.Today(),
                                                                 Servicer_Notice_to_Trustee_Sent_Date__c = System.Today(),
                                                                 Insolvency_Status__c = 'For Owner Review',
                                                                 Account_Number_Without_Space__c='Test-001');
                                                                   
        insert insolcAcc1;
        //Attachment insertion on related Insolvency account
        Attachment attch = new Attachment(name='Sample Document', body=Blob.valueOf('test Body'), parentId=insolcAcc.id);
        insert attch;
 
    }
    
    static testMethod void saveDocTest(){
      Insolvency_Account__c insolAcc = [SELECT Id, Trustee_Company__c FROM Insolvency_Account__c LIMIT 1];
      Attachment attchObj = [select Name, description from attachment limit 1];
      ApexPages.currentPage().getParameters().put('Id', insolAcc.Id);
      PageReference pRef = Page.ServicerNoticeToTrustee;
      pRef.getParameters().put('id', insolAcc.Id);
      Test.setCurrentPage(pRef);
        
      ServicerNoticeToTrusteeController obj = new ServicerNoticeToTrusteeController();
       //calling class methods
       obj.toEmail = 'test@cfg.com;';
       obj.poulateRecord();
       obj.attachmentRemoved();
       obj.attachmentSelected = [SELECT Id FROM Attachment LIMIT 1].Id;
       obj.attachmentSelected();
       obj.attachmentSelected = [SELECT Id FROM Attachment LIMIT 1].Id;
       obj.sendEmail();
       obj.isAnyException = false;
        
    }
    
}