force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/CCS_Final_Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>CCS_Final_Deposit_Slip__c</fullName>
    <description>To Determine Final deposit slip is generated for particular day</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To Determine Final deposit slip is generated for particular day</inlineHelpText>
    <label>CCS Final Deposit Slip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Do_Not_Run_Payment_Validation__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Run_Payment_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not to run validation rule for Payment record update</description>
    <inlineHelpText>Not to run validation rule for Payment record update</inlineHelpText>
    <label>Do Not Run Payment Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/Deposit_Slip__c.object-meta.xml
<CustomObject>
    <description>View the deposit slips for today generated in previous step/tab - &quot;Generate Deposit Slip&quot;</description>
    <label>Deposit Slip</label>
    <nameField>
        <displayFormat>DS-{000}</displayFormat>
        <label>Deposit Slip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Slips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/fields/A1LP_394_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>A1LP_394_Total_Amount__c</fullName>
    <label>FIM - 810 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/A1LP_394_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>A1LP_394_Total_Cheque__c</fullName>
    <label>FIM - 810 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/ACQ_618_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACQ_618_Total_Amount__c</fullName>
    <label>ACQ - 618 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/ACQ_618_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>ACQ_618_Total_Cheque__c</fullName>
    <label>ACQ - 618 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/AFSI_631_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>AFSI_631_Total_Amount__c</fullName>
    <label>AFSI - 631 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/AFSI_631_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>AFSI_631_Total_Cheque__c</fullName>
    <label>AFSI - 631 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CAL_767_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CAL_767_Total_Amount__c</fullName>
    <label>CAL - 767 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CAL_767_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CAL_767_Total_Cheque__c</fullName>
    <label>CAL - 767 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CCLP_130_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CCLP_130_Total_Amount__c</fullName>
    <label>CCLP - 130 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CCLP_130_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CCLP_130_Total_Cheque__c</fullName>
    <label>CCLP - 130 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CFL_602_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CFL_602_Total_Amount__c</fullName>
    <description>Total amount on the CFL - 602 cheques</description>
    <inlineHelpText>Total amount on the CFL - 602 cheques</inlineHelpText>
    <label>CFL - 602 Total Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CFL_602_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CFL_602_Total_Cheque__c</fullName>
    <description>Total number of cheques for CFL - 602</description>
    <inlineHelpText>Total number of cheques for CFL - 602</inlineHelpText>
    <label>CFL - 602 Total # Cheque</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIHI_877_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CIHI_877_Total_Amount__c</fullName>
    <label>CIHI - 877 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIHI_877_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CIHI_877_Total_Cheque__c</fullName>
    <label>CIHI - 877 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Amount__c</fullName>
    <label>CIML - 156 Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/fields/CIML_156_Total_Cheque__c.field-meta.xml
<CustomField>
    <fullName>CIML_156_Total_Cheque__c</fullName>
    <label>CIML - 156 Total # Cheque</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/recordTypes/CCS_Deposit_Slip.recordType-meta.xml
<RecordType>
    <fullName>CCS_Deposit_Slip</fullName>
    <active>true</active>
    <description>Deposit slip for CCS</description>
    <label>CCS Deposit Slip</label>
</RecordType>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Dividend__c.field-meta.xml
<CustomField>
    <fullName>Dividend__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dividend</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Payment Remitted</description>
    <inlineHelpText>Is Payment Remitted</inlineHelpText>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to unallocated payment reocord</description>
    <inlineHelpText>Link to unallocated payment reocord</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <description>Payment Amount</description>
    <inlineHelpText>Payment Amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Deposit_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Name__c</fullName>
    <description>Name of custom setting</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of custom setting</inlineHelpText>
    <label>Deposit Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Do_Not_Process__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to not include dividend when generating deposit slip</description>
    <label>Do Not Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <description>Entity Name of Bank account to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Entity Name of Bank account to which Dividend has been moved</inlineHelpText>
    <label>Entity Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Trustee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trustee Company lookup</description>
    <inlineHelpText>Trustee Company lookup</inlineHelpText>
    <label>Trustee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>012f10000015HcqAAE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Remittance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/recordTypes/CCS_Dividend.recordType-meta.xml
<RecordType>
    <fullName>CCS_Dividend</fullName>
    <active>true</active>
    <description>Dividends for CCS strip lists</description>
    <label>CCS Dividend</label>
</RecordType>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To know whether this is unallocated amount is allocated to some Insolvency Account or not</description>
    <label>Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the generated Deposit Slip</description>
    <inlineHelpText>Link to the generated Deposit Slip</inlineHelpText>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if unallocated payment has been remitted back to bank</description>
    <inlineHelpText>To track if unallocated payment has been remitted back to bank</inlineHelpText>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

force-app/main/default/classes/GenerateDepositSlipProductController.cls
public class GenerateDepositSlipProductController {
    
    public String type { get; set; }
    public Boolean depositSlipAvailable{get;set;}
    public Boolean showFinalDepositSlipButton{get;set;}
    public static List<Product_Payments__C> insolvVardePayments{get;set;}
    public static List<Unallocated_Payment__c> unAllocPayList{get;set;}
    public static List<String> relatedVardeRemittanceIDs = new List<String>();
    public static List<Product_Payments__C> listCIHIAccounts{get; set;}
    public static List<Product_Payments__C> listVardeCDAccounts{get; set;}
    public static List<Product_Payments__C> listFortressAccounts{get; set;}
    public static List<Product_Payments__C> listEquitableAccounts{get; set;}
    public static List<Product_Payments__C> listVardeAccounts{get; set;}
    List<Product_Payments__C> insolvPayToUpdate = new List<Product_Payments__C>();
    Map<Id, Double> accountInsolvencyPaymentMap = new Map<Id, Double>();
    Application_Config_Settings__c appConfigFinal;//==Application_Config_Settings__c.getOrgDefaults();
    Map<String, Deposit_Accounts__c> depositAccountMap = Deposit_Accounts__c.getAll();
    public Deposit_Accounts__c depositAcc {set;get;}
    
    public GenerateDepositSlipProductController(){
        
        appConfigFinal = [SELECT CCS_Final_Deposit_Slip__c, Do_Not_Run_Payment_Validation__c FROM Application_Config_Settings__c FOR UPDATE];//update for lock issue
        
        insolvVardePayments = new List<Product_Payments__C>();
        unAllocPayList = new List<Unallocated_Payment__c>();
        insolvPayToUpdate = new List<Product_Payments__C>();
        //Application_Config_Settings__c appConfigFinal = Application_Config_Settings__c.getOrgDefaults();
        showFinalDepositSlipButton = false;
        if(appConfigFinal.CCS_Final_Deposit_Slip__c == system.today()){
            showFinalDepositSlipButton = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is locked for the day'));
            return;
        }
        
        List<Deposit_Slip__c> depositSlip = [SELECT Id, Name FROM Deposit_Slip__c WHERE LastModifiedDate = TODAY AND recordType.developerName = 'CCS_Deposit_Slip'];
        
        if(depositSlip.isEmpty()){
            depositSlipAvailable = false;
        }else{
            depositSlipAvailable = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Deposit Slip already created today : <a href="'+System.Url.getSalesforceBaseURL().toExternalForm() +'/'+depositSlip[0].Id+'" target="_blank">'+depositSlip[0].Name+'</a>'));
            
        }
        
    }
    
    public void generateDepositSlip(){
        
        DateTime LastDepositSlipCreatedDate = LastDepositSlipCreatedDate();
        List<AggregateResult> listAggregateResults = [select count(id) total, sum(Cheque_Amount__c) amount, Deposit_Account_Name__c
                                              from remittance__C 
                                              where lastmodifiedDate >= :LastDepositSlipCreatedDate
                                              AND Status__c = 'Processed'
                                              AND recordType.developerName = 'CCS_Dividend'
                                              AND Do_Not_Process__c = false
                                              group by Deposit_Account_Name__c ];
        
        if(listAggregateResults.size() == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No records available for Deposit Slip'));
            return;
        }
        //Delete today's old deposit slip
        List<Deposit_slip__c> listDepositSlip = [select id from Deposit_slip__c where createdDate = today AND recordType.developerName = 'CCS_Deposit_Slip'];
        DepositSlipTriggerHandler.runDepsoitSlipTrigger = False;
        database.delete(listDepositSlip, false);
        DepositSlipTriggerHandler.runDepsoitSlipTrigger = True;
        
        //Generate new deposit slip
        Deposit_Slip__c deposit = new Deposit_Slip__c();
        deposit.recordTypeId = [select id from RecordType where SobjectType = 'Deposit_Slip__C' and name like '%CCS%'].id;
        insert deposit;
        Boolean isError = false;
        
        Boolean flagCCL = false;
        Boolean flagETC = false;
        deposit.CIML_156_Total_Cheque__c = 0;
        deposit.CIML_156_Total_Amount__c = 0.0;
        
        system.debug('Results : ' + listAggregateResults );
        for(AggregateResult listAggr : listAggregateResults ){
            
            system.debug('listAggr : ' + listAggr);
            String depoAccName = (String)listAggr.get('Deposit_Account_Name__c');
            
            if(null == depoAccName){
                //depoAccName = 'CIML';
                continue;
            }
            if(flagCCL == false && (depoAccName == 'CCL' || depoAccName == 'CLP')){
                flagCCL = true;
            }else if(flagCCL == true && (depoAccName == 'CCL' || depoAccName == 'CLP')){
                continue;
            }
            
            if(flagETC == false && (depoAccName == 'ETC' || depoAccName == 'AFF')){
                flagETC = true;
            }else if(flagETC == true && (depoAccName == 'ETC' || depoAccName == 'AFF')){
                continue;
            }
            
            PageReference depositSlip = new PageReference('/apex/GenerateProductSlip');
            depositSlip.getParameters().put('type', depoAccName);
            
            blob pdfBody;
            if(Test.isRunningTest()) {
                pdfBody = Blob.valueOf('test');
            }else{
                pdfBody = depositSlip.getContent();
            }
            
            createAttachment(pdfBody, (depositAccountMap.get(depoAccName )).Entity_Name__c, deposit.Id);
            
            if((String)listAggr.get('Deposit_Account_Name__c') == 'CIML'){
                PageReference depositSlipCanaccede = new PageReference('/apex/GenerateProductSlip');
                depositSlipCanaccede.getParameters().put('type', 'Canaccede_Account_Perticulars');
                
                blob pdfBodyCanaccede;
                if(Test.isRunningTest()) {
                    pdfBodyCanaccede = Blob.valueOf('test');
                }else{
                    pdfBodyCanaccede = depositSlipCanaccede.getContent();
                }
                
                createAttachment(pdfBodyCanaccede, 'Canaccede Suspense Account', deposit.Id);
            
            }
            if((String)listAggr.get('Deposit_Account_Name__c') == 'AFSI'){
                PageReference depositSlipAffirm = new PageReference('/apex/GenerateProductSlip');
                depositSlipAffirm.getParameters().put('type', 'Affirm_Account_Perticulars');
                
                blob pdfBodyAffirm;
                if(Test.isRunningTest()) {
                    pdfBodyAffirm = Blob.valueOf('test');
                }else{
                    pdfBodyAffirm = depositSlipAffirm.getContent();
                }
                
                createAttachment(pdfBodyAffirm, 'Fidem Suspense Account', deposit.Id);
                
            }
            
            if(depoAccName == 'AAL'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'ETC' || depoAccName == 'AFF'){
                deposit.A1LP_394_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.A1LP_394_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'AFL'){
                deposit.ACQ_618_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.ACQ_618_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'CAL'){
                deposit.CAL_767_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CAL_767_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'CIH'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'CCL' || depoAccName == 'CLP'){
                deposit.CCLP_130_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CCLP_130_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'CIA'){
                deposit.CIHI_877_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CIHI_877_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'CFL'){
                deposit.CFL_602_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.CFL_602_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else if(depoAccName == 'AFSI'){
                deposit.AFSI_631_Total_Cheque__c = (Integer)listAggr.get('total');
                deposit.AFSI_631_Total_Amount__c = (Decimal)listAggr.get('amount');
            }else {
                deposit.CIML_156_Total_Cheque__c += (Integer)listAggr.get('total');
                deposit.CIML_156_Total_Amount__c += (Decimal)listAggr.get('amount');
            }
            
        }
        
        List<Product_Payments__C> listPayment = [select id, name, Dividend__r.Deposit_Account_Name__c
                                              from Product_Payments__C
                                              where Dividend__r.lastmodifiedDate >= :LastDepositSlipCreatedDate
                                              AND Dividend__r.Status__c = 'Processed'
                                              AND dividend__r.recordType.developerName = 'CCS_Dividend'
                                              AND Dividend__r.Do_Not_Process__c = false
                                              AND Is_Payment_Remitted__c = False];
                                              
        List<Unallocated_payment__C> listUnallocPay = [select id, name, remittance__r.Deposit_Account_Name__c
                                              from Unallocated_payment__C
                                              where remittance__r.lastmodifiedDate >= :LastDepositSlipCreatedDate
                                              AND remittance__r.Status__c = 'Processed'
                                              AND allocated__c = false
                                              AND remittance__r.recordType.developerName = 'CCS_Dividend'
                                              AND remittance__r.Do_Not_Process__c = false
                                              AND Is_Payment_Remitted__c = false
                                              ANd Is_Payments_Reversed__c = null];
        
        for(Product_Payments__C insolPay : listPayment){
            insolpay.Deposit_Slip__c = deposit.Id;
        }
        //Application_Config_Settings__c appConfig = Application_Config_Settings__c.getOrgDefaults();
        appConfigFinal.Do_Not_Run_Payment_Validation__c = true;
        update appConfigFinal;
        Set<Product_Payments__C> setPaymentRecords = new Set<Product_Payments__C>(listPayment );
        List<Product_Payments__C> listPaymentRecordsToUpdate = new List<Product_Payments__C>(setPaymentRecords);
        update listPaymentRecordsToUpdate;
        appConfigFinal.Do_Not_Run_Payment_Validation__c = false;
        update appConfigFinal;
        
        //Update Unallocated Payments
        for(Unallocated_payment__C insolPay : listUnallocPay){
            insolpay.Deposit_Slip__c = deposit.Id;
        }
        update listUnallocPay;
        
        update deposit;
        
        List<Deposit_Slip__c> depositSlipRecord = [select id, name from Deposit_Slip__c where createdDate = Today AND recordType.developerName = 'CCS_Deposit_Slip' order by createdDate];
        depositSlipAvailable = true;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Deposit Slip generated successfully : <a href="'+System.Url.getSalesforceBaseURL().toExternalForm() +'/'+depositSlipRecord[0].id+'" target="_blank">'+depositSlipRecord[0].Name+'</a>'));
        
    }
    
    // Create attachment
    public void createAttachment(Blob body, String depositSlipType, Id depositId){
        Attachment attach = new Attachment(); 
        DateTime d = Date.Today() ;
        String dateStr =  d.formatGMT('yyyy-MM-dd') ;
        attach.Body = body;
        attach.Name = depositSlipType+' - '+dateStr + '.pdf';
        attach.IsPrivate = false;
        attach.Description = '';
        attach.ParentId = depositId;
        insert attach;
    }
    
    //change Id's to String of list
    public static List<String> idToStringConvert(List<String> listOfID){
        List<String> listString = new List<String>();
        for(String idString : listOfID){
            listString.add('\'' + idString + '\'');
        }
        
        return listString;
    }
    
    public static DateTime lastDepositSlipCreatedDate(){
        List<Deposit_Slip__c> lastDepositSlip = [SELECT Id, Name, createdDate FROM Deposit_Slip__c WHERE CreatedDate <> TODAY AND recordType.developerName = 'CCS_Deposit_Slip' ORDER BY createdDate DESC];
        if(lastDepositSlip.size() > 0){
            return lastDepositSlip[0].createdDate;
        }else{
            system.debug(system.TODAY());
            return system.TODAY();
        }
    }
    
    public static String strCreatedDate(DateTime createdDateToCovert){
        //2019-01-02T11:15:42.000+0000
        String strDate = '' + createdDateToCovert;
        strDate = strDate.replace(' ', 'T');
        strDate += '.000+0000';
        
        return strDate;
    }
    public void finalDepositSlip(){
        
        List<Deposit_Slip__c> todayDepositSlip = [SELECT Id, Name, createdDate FROM Deposit_Slip__c WHERE CreatedDate = TODAY AND recordType.developerName = 'CCS_Deposit_Slip' ORDER BY createdDate DESC];
        System.debug('TodayDepositSlip---'+todayDepositSlip);
        if(todayDepositSlip.size()>0){
            showFinalDepositSlipButton = true;
            appConfigFinal.CCS_Final_Deposit_Slip__c = system.TODAY();
            update appConfigFinal;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Deposit slip is locked for the day'));
        }
        
    }
}