force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size__c</fullName>
    <description>Maximum Email Attachments Size</description>
    <inlineHelpText>Maximum Email Attachments Size</inlineHelpText>
    <label>Maximum Email Attachments Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size_Text__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size_Text__c</fullName>
    <description>Maximum Email Attachments Size Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Maximum Email Attachments Size Text</inlineHelpText>
    <label>Maximum Email Attachments Size Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Do_Not_Run_Status_Validation__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Run_Status_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To avoid running Insolvency account status validation</description>
    <inlineHelpText>To avoid running Insolvency account status validation</inlineHelpText>
    <label>Do Not Run Status Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Insolvency__r.Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Servicer_Notice_to_Trustee_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Servicer_Notice_to_Trustee_Sent_Date__c</fullName>
    <description>The date that the servicer notice was sent to trustee</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the servicer notice was sent to trustee</inlineHelpText>
    <label>Servicer Notice to Trustee Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Trustee_Company__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Company__c</fullName>
    <description>The company name of the debtor&apos;s insolvency trustee</description>
    <formula>Insolvency__r.Trustee_Company_Name_Formula__c</formula>
    <inlineHelpText>The company name of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Trustee_Office__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Office__c</fullName>
    <description>The company office name of the debtor&apos;s insolvency trustee</description>
    <formula>Insolvency__r.Trustee_Name_Formula__c</formula>
    <inlineHelpText>The company office name of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/Insolvency_Error__c.object-meta.xml
<CustomObject>
    <description>An object to store error/exception related to Insolvency flow</description>
    <label>Insolvency Error</label>
    <nameField>
        <displayFormat>IErr-{0000}</displayFormat>
        <label>Insolvency Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Error__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action that caused the error/exception</description>
    <inlineHelpText>Action that caused the error/exception</inlineHelpText>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PoC Generation</fullName>
            </value>
            <value>
                <fullName>Email Trustee</fullName>
            </value>
            <value>
                <fullName>Trustee Assignment</fullName>
            </value>
            <value>
                <fullName>Document Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error / Exception Details</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Error / Exception Details</inlineHelpText>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Insolvency record</description>
    <inlineHelpText>Related Insolvency record</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Errors</relationshipLabel>
    <relationshipName>Insolvency_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Insolvency Account record</description>
    <inlineHelpText>Related Insolvency Account record</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Errors</relationshipLabel>
    <relationshipName>Insolvency_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_City__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Fax_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Fax Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name_2__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Phone Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Notice_to_Trustee_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Notice_to_Trustee_Template_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notice to Trustee Template Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Trustee_Email_Org_Wide_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Email_Org_Wide_Address_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trustee Email Org Wide Address Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServicerNoticeToTrusteeController.cls
/**************************************************************************************************
 *
 *  Class:   ServicerNoticeToTrusteeController
 *
 *  @description : Implemented functionality to send LoR Notice letter, and save LoR Notice as attachment on Insolvency Account
 *  @author : A5E Consulting
 *  @date : 08/05/2018
 
 *************************************************************************************************/
public class ServicerNoticeToTrusteeController{
    public Insolvency_Account__c insolvAcc {set;get;}
     
    // Variable that are used to store emails, email subject, body and exceptions
    public String toEmail{set;get;}
    public String subject {set;get;}
    public String emailBody {set;get;}
    public String attachmentBody {set;get;}
    PoC_Package_Settings__c pocPackage;
    public Boolean  isAnyException{set;get;}
    public Boolean isActive {set;get;}
    public List<InsolvAttachments> insolvAttachList{set;get;}
    
    //Show validation message when total attachments size is exceeded
    public Application_Config_Settings__c config; // = Application_Config_Settings__c.getOrgDefaults();
    public Boolean attachSizeException{set;get;}
    public String attachSizeExceptionMessage{set;get;}
    
    // Stores all attachments that are selected by user
    public Set<Id> mySelectedAtt = new Set<Id>();
    public Id attachmentSelected{set;get;}
    
    // Controller loads Insolvency Account record data
    public ServicerNoticeToTrusteeController(){
    
        config = [SELECT Maximum_Email_Attachments_Size_Text__c, Maximum_Email_Attachments_Size__c,
                    Run_Insolvency_Status_Validations__c FROM Application_Config_Settings__c FOR UPDATE];//update for lock issue
        poulateRecord();
        insolvAttachList= new List<InsolvAttachments>();
        Datetime now = Datetime.now();
        Integer offset = UserInfo.getTimezone().getOffset(now);
        
        //Atachment Size limit check
        attachSizeException = false;
        
        //TrusteeOffice Active Check
        isActive = true;
        
        attachSizeExceptionMessage = config.Maximum_Email_Attachments_Size_Text__c;
        
        // Read all attachments related to insolvacny account
        for (Attachment attchmt : [select Name,  
                            Description,
                            BodyLength,
                            createdDate 
                            from Attachment where ParentId =: insolvAcc.Id 
                            order by lastmodifieddate desc
                      ]){
                        
            InsolvAttachments temp = new InsolvAttachments();
            temp.attId = attchmt.Id;
            temp.selected =false;
            temp.fileName=attchmt.Name;
            temp.fileDesc=attchmt.Description;
            temp.fileCreatedDate = attchmt.createdDate.addSeconds(offset/1000);
            temp.displaySize = InsolvencyUtil.fileSizeToString((attchmt.BodyLength));
           
            insolvAttachList.add(temp);
        }
        
        //checking if Trustee Office is Active
        if(insolvAcc.Is_Active__c == False){ 
           system.debug('Trustee is not Active so Email cannot be sent');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Trustee Office is not Active so email cannot be sent')); 
            isActive=false;
        }
        
     }
     //Load intital values
     public void poulateRecord(){
         insolvAcc = [SELECT Id,
                            Trustee_Company__c,
                            Insolvency__r.Name,Is_Active__c,
                            Insolvency__r.Trustee__r.BillingStreet,
                            Insolvency__r.Trustee__r.BillingState,
                            Insolvency__r.Trustee__r.BillingPostalcode,
                            Insolvency__r.Trustee__r.BillingCity,
                            Insolvency__r.Trustee__r.Communication_Preference__c,
                            Insolvency__r.Trustee__r.Business_Email__c,
                            Insolvency__r.Trustee__r.Fax,
                            Servicer_Notice_to_Trustee_Sent_Date__c,
                            Client_Identifier__c, Trustee_Office__c
                    FROM Insolvency_Account__c 
                    WHERE Id =: ApexPages.currentPage().getParameters().get('Id')];
        
        // Check communication preference and use them to send email
        if(insolvAcc.Insolvency__r.Trustee__r.Communication_Preference__c == 'Fax'){
            toEmail =  InsolvencyUtil.formatFaxAsEmail(insolvAcc.Insolvency__r.Trustee__r.Fax);                        
        }
        else{
            toEmail =  insolvAcc.Insolvency__r.Trustee__r.Business_Email__c;
        }
        
        // Fetch PoC custom settings which will have critical information about the bank
        pocPackage = (PoC_Package_Settings__c)PoC_Package_Settings__c.getValues(insolvAcc.Client_Identifier__c);
        Date dateToday = System.Today();
        
        // Convert DateTime to Date format ex: May 01, 2018
        //String formattedDate = DateTime.newInstance(dt.year(),dt.month(),dt.day()).format('MMM dd, YYYY');
        String formattedDate = DateTime.newInstance(dateToday.year(),dateToday.month(),dateToday.day()).formatGMT('MMM dd, YYYY');
        
        // Merge fields used in email template
        Map<String, String> emailMergeFields  = new Map<String, String>{
                                                    '{!TODAY()}' => formattedDate,
                                                    '{!insolvAcc.Trustee_Company__c}' => (insolvAcc.Trustee_Company__c != null ? insolvAcc.Trustee_Company__c.toUppercase() : ''),
                                                    '{!Insolvency_Account__c.Insolvency__r.Trustee__r.BillingStreet}' => (insolvAcc.Insolvency__r.Trustee__r.BillingStreet != null ? insolvAcc.Insolvency__r.Trustee__r.BillingStreet : ''),
                                                    '{!Insolvency_Account__c.Insolvency__r.Trustee__r.BillingState}' => (insolvAcc.Insolvency__r.Trustee__r.BillingState != null ? insolvAcc.Insolvency__r.Trustee__r.BillingState : ''),
                                                    '{!Insolvency_Account__c.Insolvency__r.Trustee__r.BillingPostalcode}' => (insolvAcc.Insolvency__r.Trustee__r.BillingPostalcode != null ? insolvAcc.Insolvency__r.Trustee__r.BillingPostalcode : ''),
                                                    '{!Insolvency_Account__c.Insolvency__r.Trustee__r.BillingCity}' => (insolvAcc.Insolvency__r.Trustee__r.BillingCity != null ? insolvAcc.Insolvency__r.Trustee__r.BillingCity : ''),
                                                    '{!pocPackage.Client_Company_Name__c}' => pocPackage.Client_Company_Name__c.toUppercase(),
                                                    '{!pocPackage.Client_Company_Name}' => pocPackage.Client_Company_Name__c,
                                                    '{!pocPackage.CFG_Office_Name__c}' => pocPackage.CFG_Office_Name__c.toUppercase(),
                                                    '{!pocPackage.CFG_Office_Name}' => pocPackage.CFG_Office_Name__c,             
                                                    '{!pocPackage.CFG_Office_Address_1__c}' => pocPackage.CFG_Office_Address_1__c,
                                                    '{!pocPackage.CFG_Office_City__c}' => pocPackage.CFG_Office_City__c,
                                                    '{!pocPackage.CFG_Office_Province__c}' => pocPackage.CFG_Office_Province__c,
                                                    '{!pocPackage.CFG_Office_Postal_Code__c}' => pocPackage.CFG_Office_Postal_Code__c,
                                                    '{!pocPackage.CFG_Office_Name}' => pocPackage.CFG_Office_Name__c,
                                                    '{!pocPackage.CFG_Office_Phone_Number__c}' => pocPackage.CFG_Office_Phone_Number__c.replace('-','.'),
                                                    '{!pocPackage.CFG_Office_Fax_Number__c}' => pocPackage.CFG_Office_Fax_Number__c.replace('-','.'),
                                                    '{!pocPackage.CFG_Office_Email_Address__c}' => pocPackage.CFG_Office_Email_Address__c,
                                                    '{!pocPackage.CFG_Office_Name_2__c}' => pocPackage.CFG_Office_Name_2__c
                                                    };
        
        // Fetch LoRNotice1 email template
        for(EmailTemplate emt :  [SELECT Id, Name, HtmlValue, Body,Subject FROM EmailTemplate WHERE Id =: pocPackage.Notice_to_Trustee_Template_Id__c]){
            if(emt.Id == pocPackage.Notice_to_Trustee_Template_Id__c){
                subject = emt.subject;
                subject = subject.replace('{!insolv.EstateNumber}', insolvAcc.Insolvency__r.Name);
                emailBody = emt.HtmlValue;
                emailBody = emailBody.replace('{!Insolvency_Account__c.Trustee_Company__c}', (insolvAcc.Trustee_Company__c+ ''));
                emailBody = emailBody.replace('{!Insolvency_Account__c.Trustee_Office__c}', (insolvAcc.Trustee_Office__c+ ''));
                emailBody = emailBody.replace('{!Trustee_street}', (insolvAcc.Insolvency__r.Trustee__r.BillingStreet != null? insolvAcc.Insolvency__r.Trustee__r.BillingStreet : ''));
               // attachmentBody = emt.HtmlValue;
            }
        }
        
        // replace merge fields in email template with actual values in Insolvency Account
        for(String str : emailMergeFields.keySet()){
            emailBody = emailBody.replace(str, (emailMergeFields.get(str)+''));
            //attachmentBody = attachmentBody.replace(str, emailMergeFields.get(str));
        }
     }
     

     
     //Method is used to send email to trustee, and creates Activity under Insolvency account
     public PageReference sendEmail(){  
        
        //Atachment Size limit check    
        attachSizeException = false;
        
        Decimal totalFilesize = 0;
        Decimal maxAttachSize = config.Maximum_Email_Attachments_Size__c;
        system.debug('maxAttachSize ='+maxAttachSize );
        for(Attachment selectedAtt: [SELECT Name, Body, BodyLength FROM Attachment WHERE Id IN : mySelectedAtt]){
          totalFilesize = totalFilesize + selectedAtt.BodyLength;
        }
        system.debug('totalFilesize ='+totalFilesize );
        if(totalFilesize > maxAttachSize){
            attachSizeException = true;
             return null;
        } 
        else{
            attachSizeException = false;
        }
           
        //Sending Email to trustee,and creates activity   
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        if(toEmail.endsWith(';')){
        toEmail = toEmail.subString(0, toEmail.length()-1);
        }
        List<String> toEmails = new List<String>(toEmail.split(';'));
        mail.setToAddresses(toEmails);
        mail.setOrgWideEmailAddressId(pocPackage.Trustee_Email_Org_Wide_Address_Id__c);
        mail.setSubject(subject);
        mail.setHTMLBody(emailBody );
        mail.setSaveAsActivity(true);
        mail.setWhatId(insolvAcc.Id);
        
        DateTime d = Date.Today() ;
        String dateStr =  d.formatGMT('yyyy-MM-dd') ;
        String attachmentName = 'Servicer Notice.pdf';
        
       /* // Attach pdf to email message with same content as per LoR Notice Letter 1 template
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
        efa.setFileName(attachmentName);
        efa.setBody(Blob.toPDF(attachmentBody));
        fileAttachments.add(efa);
      */  
        // Attach files to email
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        
            for(Attachment attObj : [SELECT Name, Body FROM Attachment WHERE Id IN : mySelectedAtt]){
                    
                    Messaging.Emailfileattachment att = new Messaging.Emailfileattachment();
                    att.setFileName(attObj.Name);
                    att.setBody(attObj.Body);
                    fileAttachments.add(att);
                
            }
        mail.setFileAttachments(fileAttachments);        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        /*
        //Don't run validation rules
        //Application_Config_Settings__c config = [SELECT Run_Insolvency_Status_Validations__c FROM Application_Config_Settings__c ];
        
        // Read and store actuall value about running validation rule
        Boolean storeCustomsettingValue = config.Run_Insolvency_Status_Validations__c;
        config.Run_Insolvency_Status_Validations__c = false;
        update config;
        */
        
        try{  
            // Update LoR notice sent date
            insolvAcc.Servicer_Notice_to_Trustee_Sent_Date__c = System.Today();
            insolvAcc.Do_Not_Run_Status_Validation__c = True;
            update insolvAcc;
            
            //InsolvencyUtil.saveAttachment(insolvAcc.Id, attachmentBody, attachmentName, 'Servicer Notice');
            /*
            config.Run_Insolvency_Status_Validations__c = storeCustomsettingValue;
            update config;
            */
            
            // Revert back custom setting value with previous value
            InsolvencyAccountTriggerHandler.runInsolvencyAccountTrigger = true;
            
        }catch(Exception ex){
            
            /*
            config.Run_Insolvency_Status_Validations__c = storeCustomsettingValue;
            update config;            
            */
            InsolvencyAccountTriggerHandler.runInsolvencyAccountTrigger = true;
           
            isAnyException = true;
            Insolvency_Error__c inslErr = new Insolvency_Error__c();
            inslErr.Insolvency_Account__c = insolvAcc.Id;
            inslErr.Action__c = 'Email Trustee';
            inslErr.Error__c = 'Exception: ' + ex.getTypeName();
            inslErr.Error__c += '\nMessage: ' + ex.getMessage();
            inslErr.Error__c += '\nStack trace:\n' + ex.getStackTraceString();
            
            try{
                insert inslErr;
            }
            catch(Exception inslErrEx){
                system.debug('inslErr Message :'+inslErrEx.getMEssage());
            }
        }
        
        // Create Attachment against activity history on Insolvency Account
        Task emailTask = [select id from Task where whatID =: insolvAcc.id ORDER BY CreatedDate DESC limit 1];
        EmailMessage emailmsg = [select Id, parentId from EmailMessage where activityId = : emailTask.Id];
      
        list<Attachment> emailMsgAttachments = new list<Attachment>();
        for(Attachment emailMsgAtt : [SELECT Name, Body, ParentId, Description FROM Attachment WHERE Id IN : mySelectedAtt]){
            Attachment emailAttachment = new Attachment();
            emailAttachment.body = emailMsgAtt.body;
            emailAttachment.Name = emailMsgAtt.Name;
            emailAttachment.Description = emailMsgAtt.Description;
            emailAttachment.ParentId = emailmsg.id; 
            emailAttachment.isPrivate = false; 
            emailMsgAttachments.add(emailAttachment);
        }         
        if(emailMsgAttachments.size()>0){
            insert emailMsgAttachments;
        }
       
       return null; 
     }
     
     /*********************************************************
    * Method description: Handles to store list of attachments selected by user
    * Parameters : none
    * return type: void
    **********************************************************/
    public void attachmentSelected(){
        if(attachmentSelected != null){
            mySelectedAtt.add(attachmentSelected );
            attachmentSelected = null;
        }
    }
    
    /*********************************************************
    * Method description: Handles to remove attachments un selected by user
    * Parameters : none
    * return type: void
    **********************************************************/
    public void attachmentRemoved(){
        if(attachmentSelected != null){
            mySelectedAtt.remove(attachmentSelected );
            attachmentSelected = null;
        }
    }
       // Wrapper class used to frame attachments with checkboxes 
    public class InsolvAttachments{
        public Boolean selected{set;get;}
        public Id attId{set;get;}
        public String filename{set;get;}
        public String fileDesc{set;get;}
        public DateTime fileCreatedDate {set;get;}
        public String displaySize {set;get;}
    }
}