force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Court_District_Name__c.field-meta.xml
<CustomField>
    <fullName>Court_District_Name__c</fullName>
    <description>The name of the court district as found in the creditor&apos;s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the court district as found in the creditor&apos;s package</inlineHelpText>
    <label>Court District</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Court_Division_Number__c.field-meta.xml
<CustomField>
    <fullName>Court_Division_Number__c</fullName>
    <description>The court division number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The court division number as noted on the creditor’s package</inlineHelpText>
    <label>Court Division Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Court_Province_Name__c.field-meta.xml
<CustomField>
    <fullName>Court_Province_Name__c</fullName>
    <description>The province of the court as found in the creditor&apos;s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The province of the court as found in the creditor&apos;s package</inlineHelpText>
    <label>Court Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Court_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Court_Number__c</fullName>
    <description>The court number for the primary debtor as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The court number for the primary debtor as noted on the creditor’s package.</inlineHelpText>
    <label>Court Number</label>
    <length>110</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Date_of_Birth__c</fullName>
    <description>Date of Birth of the primary filer</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Date of Birth of the primary filer</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Employer_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Employer_Postal_Code__c</fullName>
    <description>The address postal code of the primary debtor&apos;s employer.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The address postal code of the primary debtor&apos;s employer.</inlineHelpText>
    <label>Employer Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Gender__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Gender__c</fullName>
    <description>The primary debtor&apos;s gender.</description>
    <inlineHelpText>The primary debtor&apos;s gender.</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_City__c</fullName>
    <description>The primary debtor&apos;s address city.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address city.</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_State_Province__c</fullName>
    <description>The primary debtor&apos;s address province.</description>
    <inlineHelpText>The primary debtor&apos;s address province.</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Street__c</fullName>
    <description>The primary debtor&apos;s address street name and number.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address street name and number.</inlineHelpText>
    <label>Street Name &amp; Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Mailing_State_Province__c</fullName>
    <description>The secondary debtor&apos;s address province.</description>
    <inlineHelpText>The secondary debtor&apos;s address province.</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Expected_Discharge_Month__c.field-meta.xml
<CustomField>
    <fullName>Expected_Discharge_Month__c</fullName>
    <description>Expected Discharge Months</description>
    <inlineHelpText>Expected Discharge Months</inlineHelpText>
    <label>Expected Discharge Months</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Date__c</fullName>
    <description>The effective date of the insolvency filing as noted in the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The effective date of the insolvency filing as noted in the creditor’s package</inlineHelpText>
    <label>Insolvency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Received_Date__c</fullName>
    <description>The date that the creditor’s package was received.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the creditor’s package was received.</inlineHelpText>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status_Last_Changed__c</fullName>
    <description>The date and time of the most recent insolvency status change.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date and time of the most recent insolvency status change.</inlineHelpText>
    <label>Insolvency Status Last Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestInsolvencyTrigger.cls
@isTest
public class TestInsolvencyTrigger {
@testSetup static void testData(){
        
}
@isTest static void TestInsolvency(){  
Application_Config_Settings__c config = new Application_Config_Settings__c();
        config.Run_Insolvency_Trigger__c = true;
        insert config; 
InsolvencyTriggerHandler.runInsolvencyTrigger=True; 
Insolvency__c insolv=new Insolvency__c();
insolv.Name='1000000';
insolv.Insolvency_Type__c='Bankruptcy';
insolv.Insolvency_Received_Date__c=system.today();
insolv.Insolvency_Date__c=system.today();
insolv.Debtor_1_Mailing_State_Province__c='Ontario';
insolv.Debtor_2_Mailing_State_Province__c='Ontario';
insolv.Debtor_2_Estate_Number__c='10000000';
insolv.Insolvency_Status__c='Staging';
insolv.Debtor_1_Court_Number__c='1023';
insolv.Court_Division_Number__c='1234';
insolv.Court_District_Name__c='sample';
insolv.Court_Province_Name__c='sample';
insolv.Debtor_1_First_Name__c='sam';
insolv.Debtor_1_Last_Name__c='samp';
insolv.Debtor_1_Mailing_Street__c='sample address';
insolv.Debtor_1_Mailing_City__c='city sample';
insolv.Debtor_1_Employer_Postal_Code__c='L7S1X3';
insolv.Debtor_1_Date_of_Birth__c=system.today();
insolv.Debtor_1_Gender__c='male';
insolv.Insolvency_Status_Last_Changed__c=System.now();
insolv.Expected_Discharge_Month__c='24';
insolv.Insolvency_Date__c=system.today();
insert insolv;
insolv.Name='1000001';
insolv.Debtor_2_Estate_Number__c='1000002';
update insolv;
}
   
}