force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Record_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Run_Record_Ownership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Record Ownership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Canadian_Tire_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Canadian_Tire_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canadian Tire Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CanadianTireRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Chase_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Chase_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chase Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ChaseRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Fairstone_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Fairstone_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fairstone Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FairstoneRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Flexiti_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Flexiti_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flexiti Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FlexitiRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Goeasy_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Goeasy_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Easyfinancial Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GoeasyRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Money_Mart_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Money_Mart_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Money Mart Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MoneyMartRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Scotia_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Scotia_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scotia Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ScotiaRecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/SDA_Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDA_Record_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDA Record Owner</description>
    <inlineHelpText>SDA Record Owner</inlineHelpText>
    <label>SDA Record Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SDARecordOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsolvencyAccountEditController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a controller class for Insolvency Account edit
 *  @author : A5E Consulting
 *  @date : 01/20/2018
 
 *************************************************************************************************/
 
public class InsolvencyAccountEditController {
  
    public String insolvencyAccntId{get;set;}
    public Insolvency_Account__c insolvncyAccnt{get;set;}
    Application_Config_Settings__c config = Application_Config_Settings__c.getOrgDefaults();
    //public Insolvency__c insolvncy{get;set;}
  
    public InsolvencyAccountEditController(ApexPages.StandardController controller){
        //Insolvency Account ID
        insolvencyAccntId = ApexPages.currentPage().getParameters().get('id');  
          
        //Insolvency Account record
        insolvncyAccnt = [SELECT Id, Name, 
                            Client_Identifier__c, 
                            Insolvency__c,
                            OwnerId 
                            FROM Insolvency_Account__c WHERE Id =: insolvencyAccntId limit 1];
    }
  
    //Redirect to Edit PAge
    public PageReference redirPage(){
    
        // Run only if record ownership functionality is Enabled at custom settings level
        if(config.Run_Record_Ownership__c){
            User owner = [SELECT ProfileId FROM User WHERE ID =: insolvncyAccnt.OwnerId];
            //Eligible Insolvency Account Record Type Name 
            String eligibleInsAcctRecordType = InsolvencyUtil.getInsAccntRecordTypeProfile(Userinfo.getProfileId());
             
             if(!InsolvencyUtil.isScotiaBankCommunityUser(owner.profileId) &&
                !InsolvencyUtil.isChaseBankCommunityUser(owner.profileId) && 
                !InsolvencyUtil.isSDABankCommunityUser(owner.profileId)){
                
                Insolvency__c insolv = [SELECT Scotia_Record_Owner__c, 
                                                Chase_Record_Owner__c, 
                                                SDA_Record_Owner__c,
                                        		Fairstone_Record_Owner__c,
                                                Goeasy_Record_Owner__c,
                                                Canadian_Tire_Record_Owner__c,
                                        		Money_Mart_Record_Owner__c,
                                        		Flexiti_Record_Owner__c,
                                                (SELECT OwnerId 
                                                    FROM Insolvency_Accounts__r 
                                                    where RecordType.name =: eligibleInsAcctRecordType
                                                 ) 
                                                FROM Insolvency__c WHERE Id =: insolvncyAccnt.Insolvency__c];
                                                
                if(InsolvencyUtil.isScotiaBankCommunityUser(Userinfo.getProfileId())){
                    if(insolv.Scotia_Record_Owner__c == null){
                        insolv.Scotia_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }
                else if(InsolvencyUtil.isChaseBankCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Chase_Record_Owner__c == null){
                        insolv.Chase_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }
                
                else if(InsolvencyUtil.isSDABankCommunityUser(UserInfo.getProfileId())){
                    if(insolv.SDA_Record_Owner__c == null){
                        insolv.SDA_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }
                 
                else if(InsolvencyUtil.isFairstoneBankCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Fairstone_Record_Owner__c == null){
                        insolv.Fairstone_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }

                else if(InsolvencyUtil.isGoeasyBankCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Goeasy_Record_Owner__c == null){
                        insolv.Goeasy_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }

                else if(InsolvencyUtil.isCanadianTireCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Canadian_Tire_Record_Owner__c == null){
                        insolv.Canadian_Tire_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }
                else if(InsolvencyUtil.isMoneyMartCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Money_Mart_Record_Owner__c == null){
                        insolv.Money_Mart_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }
                else if(InsolvencyUtil.isFlexitiCommunityUser(UserInfo.getProfileId())){
                    if(insolv.Flexiti_Record_Owner__c == null){
                        insolv.Flexiti_Record_Owner__c = UserInfo.getUserId();
                        InsolvencyUtil.updateOwnerShip(insolv);
                    }
                }    
            }
        }
        
        return redirectEditPage();
    }
    
    private PageReference redirectEditPage(){
        try {
            String redirectUrl = '/' +Insolvency_Account__c.SObjectType.getDescribe().getKeyPrefix() + '/e';
            PageReference redirectPg = new PageReference(redirectUrl);
                
            Map<String, String> paramMap = redirectPg.getParameters();
            paramMap.putAll(ApexPages.currentPage().getParameters()); 
            paramMap.put('nooverride', '1');                       
            redirectPg.setRedirect(true);
            return redirectPg;            
        }
        catch(Exception exp){  
            return null;
        }
    }
}