force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size__c</fullName>
    <description>Maximum Email Attachments Size</description>
    <inlineHelpText>Maximum Email Attachments Size</inlineHelpText>
    <label>Maximum Email Attachments Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Maximum_Email_Attachments_Size_Text__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Email_Attachments_Size_Text__c</fullName>
    <description>Maximum Email Attachments Size Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Maximum Email Attachments Size Text</inlineHelpText>
    <label>Maximum Email Attachments Size Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status_Last_Changed__c</fullName>
    <description>The date and time of the most recent insolvency status change.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date and time of the most recent insolvency status change.</inlineHelpText>
    <label>Insolvency Status Last Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Date_LOR_received_for_Secured__c.field-meta.xml
<CustomField>
    <fullName>Date_LOR_received_for_Secured__c</fullName>
    <description>The date that the Letter of Release was received for the account&apos;s security.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the Letter of Release was received for the account&apos;s security.</inlineHelpText>
    <label>Date LoR Received For Secured</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status_Last_Changed__c</fullName>
    <description>The date and time of the most recent insolvency status change.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date and time of the most recent insolvency status change.</inlineHelpText>
    <label>Processing Status Last Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Proof_of_Claim_Required__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Claim_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <description>An indicator whether a Proof of Claim is required to be provided to the Trustee.</description>
    <inlineHelpText>An indicator whether a Proof of Claim is required to be provided to the Trustee.</inlineHelpText>
    <label>Proof of Claim Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_City__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Phone Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Withdrawal_PoC_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Withdrawal_PoC_Template_Id__c</fullName>
    <description>Id of Withdrawal PoC Email Template, used to sent Withdrawal PoC request on Insolvency Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Withdrawal PoC Template Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Withdrawal_PoC_Template_ID_French__c.field-meta.xml
<CustomField>
    <fullName>Withdrawal_PoC_Template_ID_French__c</fullName>
    <description>Withdrawal PoC Template ID French</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Withdrawal PoC Template ID French</inlineHelpText>
    <label>Withdrawal PoC Template ID French</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestWithdrawalPoCController.cls
/**************************************************************************************************
 *  Class:   TestWithdrawalPoCController
 *  @description : This class contains unit tests for sending Withdrawal PoC request
 *  @author : A5E Consulting
 *  @date : 06/06/2017
 * 
 *************************************************************************************************/

@isTest
public class TestWithdrawalPoCController{
    //Create all necessary Object records in this method
     @testSetup 
     static void testData() {
         //Custom setting Insertion
         Application_Config_Settings__c config = new Application_Config_Settings__c(Run_Insolvency_Status_Validations__c = True,
                                                                                      Maximum_Email_Attachments_Size__c = 18874368,
                                                                                      Maximum_Email_Attachments_Size_Text__c = 'You can send attachments only upto 18 MB',
                                                                                     Run_Insolvency_Account_Trigger__c = true,
                                                                                     Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm',
        																			 Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm',
        																			 Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm',
        																			 Bank_Eligible_for_Duplicate_Check__c = 'SPL',
        																		     Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN',
        																	         Run_Insolvency_Trigger__c = false,
        																			 Run_Insolvency_Account_Duplicate_Check__c = True);
         insert config;
         
         User u = [SELECT Id FROM User WHERE Id !=: UserInfo.getUserId() AND Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
         
         System.runAs(u){
             EmailTemplate withdrawalTemplate = new EmailTemplate(Name = 'LoR Template',TemplateType  = 'custom', DeveloperName='LoR_Template', HtmlValue = '{!TODAY()}', Body = '{!TODAY()}',Subject = 'Letter Of Release', FolderId = UserInfo.getUserId());
             insert withdrawalTemplate;
              //Custom setting Insertion
             PoC_Package_Settings__c poc = new PoC_Package_Settings__c(Name = 'Scotia Bank', 
                                                                         Client_Company_Name__c = 'Canaccede International ltd.', 
                                                                         CFG_Office_Phone_Number__c = '800-800-800', 
                                                                         CFG_Office_Name__c = 'The Scotia Bank',
                                                                         CFG_Office_Email_Address__c = 'test@canaccede.com',
                                                                         Withdrawal_PoC_Template_Id__c = withdrawalTemplate.Id,
                                                                         CFG_Office_Address_1__c = 'Country',
                                                                         CFG_Office_City__c = 'city',
                                                                         CFG_Office_Province__c='province',
                                                                         CFG_Office_Postal_Code__c = '12345',
                                                                      	 Withdrawal_PoC_Template_ID_French__c = withdrawalTemplate.Id);
             insert poc;
         }
         
          //Account Record Insertion
         Account parentAcc = new Account(Name = 'my acc', Communication_Preference__c = 'Fax', Business_Email__c = 'test@sample.com', Fax = 'test@test.com');
         insert parentAcc;
         
         //Insolvency Record Insertion
         Insolvency__c insolv = new Insolvency__c(Trustee__c = parentAcc.Id, Name = 'Test');
         insert insolv;
         
         //Insolvency  Account Record Insertion
         Insolvency_Account__c insolvAcc = new Insolvency_Account__c(Claim_Type__c = 'Unsecured', 
                                                                 Proof_of_Claim_Required__c = false, 
                                                                 Client_Identifier__c='Scotia Bank',
                                                                 Name='Test- 001',
                                                                 Insolvency__c = insolv.Id,
                                                                 Insolvency_Status_Last_Changed__c = System.Today(),
                                                                 Date_LOR_received_for_Secured__c = System.Today(),
                                                                 Insolvency_Status__c = 'For Owner Review',
                                                                 Account_Number_Without_Space__c='Test- 001');
         insert insolvAcc;
         
         //Attachment insertion on related Insolvency account
         Attachment att = new Attachment(Name = 'myAtt', parentId = insolvAcc.Id, Body = Blob.valueOf('my text'));
         insert att;
     }
     
     // Unit test for saving poc pdf document as attachment of insolvancy account
     static testMethod void sendWithdrawalTest(){
          Insolvency_Account__c insolcAcc = [SELECT Id FROM Insolvency_Account__c LIMIT 1];
          ApexPages.currentPage().getParameters().put('Id', insolcAcc.Id);
          
          WithdrawalPoCController obj = new WithdrawalPoCController();
          obj.toEmail = 'test@cfg.com;';
          obj.attachmentSelected = [SELECT Id FROM Attachment LIMIT 1].Id;
          obj.attachmentSelected();
          obj.sendEmail();
          obj.attachmentSelected = [SELECT Id FROM Attachment LIMIT 1].Id;
          obj.attachmentRemoved();
          obj.isAnyException = false;
     }

}