force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Remittance_Validation__c.field-meta.xml
<CustomField>
    <fullName>Run_Remittance_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To run remittance validation rule</description>
    <inlineHelpText>To run remittance validation rule</inlineHelpText>
    <label>Run Remittance Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deposit_Accounts__c/fields/Transit_Number__c.field-meta.xml
<CustomField>
    <fullName>Transit_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transit Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Portfolio_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Group_Name__c</fullName>
    <description>Portfolio Group Name</description>
    <inlineHelpText>Portfolio Group Name</inlineHelpText>
    <label>Portfolio Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAL001</fullName>
            </value>
            <value>
                <fullName>AAL002</fullName>
            </value>
            <value>
                <fullName>AFF001</fullName>
            </value>
            <value>
                <fullName>AFF002</fullName>
            </value>
            <value>
                <fullName>AFF003</fullName>
            </value>
            <value>
                <fullName>AFF004</fullName>
            </value>
            <value>
                <fullName>AFL001</fullName>
            </value>
            <value>
                <fullName>AFSCCO107</fullName>
            </value>
            <value>
                <fullName>autocapita</fullName>
            </value>
            <value>
                <fullName>BNSCCO3</fullName>
            </value>
            <value>
                <fullName>BNSDFFAU34</fullName>
            </value>
            <value>
                <fullName>BNS PERU</fullName>
            </value>
            <value>
                <fullName>CAL001</fullName>
            </value>
            <value>
                <fullName>CAL002</fullName>
            </value>
            <value>
                <fullName>CAL003</fullName>
            </value>
            <value>
                <fullName>CAL004</fullName>
            </value>
            <value>
                <fullName>CAL005</fullName>
            </value>
            <value>
                <fullName>CAL006</fullName>
            </value>
            <value>
                <fullName>CAL007</fullName>
            </value>
            <value>
                <fullName>CAL008</fullName>
            </value>
            <value>
                <fullName>CAL009</fullName>
            </value>
            <value>
                <fullName>CAL010</fullName>
            </value>
            <value>
                <fullName>CAL011</fullName>
            </value>
            <value>
                <fullName>CAL012</fullName>
            </value>
            <value>
                <fullName>CAL013</fullName>
            </value>
            <value>
                <fullName>CAL014</fullName>
            </value>
            <value>
                <fullName>CAL015</fullName>
            </value>
            <value>
                <fullName>CAL016</fullName>
            </value>
            <value>
                <fullName>CAL017</fullName>
            </value>
            <value>
                <fullName>CAL018</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The Insolvency Account’s account number this payment belongs to</description>
    <formula>Insolvency_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Insolvency Account’s account number this payment belongs to</inlineHelpText>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Deposit_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Deposit Account Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Insolvency Account.</description>
    <inlineHelpText>The amount to be applied to the Insolvency Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Unallocated payment record</description>
    <inlineHelpText>Lookup field to Unallocated payment record</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Allocated_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Amount__c</fullName>
    <label>Allocated Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Allocated_Payments_Count__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Count__c</fullName>
    <label>Allocated Payments Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Bank Account Number to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Account Number to which Dividend has been moved</inlineHelpText>
    <label>Bank Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Deposit_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Name__c</fullName>
    <description>Name of custom setting</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of custom setting</inlineHelpText>
    <label>Deposit Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <description>Entity Name of Bank account to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Entity Name of Bank account to which Dividend has been moved</inlineHelpText>
    <label>Entity Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>Transit_Code__c</fullName>
    <description>Transit Code of Bank account to which Dividend has been moved</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Transit Code of Bank account to which Dividend has been moved</inlineHelpText>
    <label>Transit Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Store Insolvency Account number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/StriplistUtil.cls
/**************************************************************************************************
 *
 *  Class:
 *
 *  @description : This class will be the utility methods and wrapper classes for the Striplist payment processing
 *  @author : A5E Consulting
 *  @date : 14-10-2020
 *
 *************************************************************************************************/
public class StriplistUtil {
    //Wrapper class for insolvency payment records
    public class paymentRecordsWrapper {
        public String accountNumber { get; set; }
        public String accountID { get; set; }
        public String debtorName { get; set; }
        public String estateNumber { get; set; }
        public String amount { get; set; }
        public Remittance__c insolvencyAccInstance { get; set; }
    }

    public boolean readSuccess { get; set; }
    public List<String> listFieldNames { get; set; }
    paymentRecordsWrapper payWrapRecord;

    String fieldValue;
    Integer fieldNumber;
    Map<String, Integer> fieldNumberMap = new Map<String, Integer>();

    public List<paymentRecordsWrapper> deSerializeJSON(String dataAsString) {
        List<paymentRecordsWrapper> listPaymentRecordWrapper = (List<paymentRecordsWrapper>) JSON.deserialize(dataAsString, List<paymentRecordsWrapper>.class);
        return listPaymentRecordWrapper;
    }
    public List<List<paymentRecordsWrapper>> readFromFile(String dataAsString) {
        List<List<paymentRecordsWrapper>> listWrapper = new List<List<paymentRecordsWrapper>>();
        listFieldNames = new List<String>();
        readSuccess = false;

        try {
            listWrapper = readCSVFile(DataAsString);
            return listWrapper;
        } catch (exception e) {
            readSuccess = false;
            system.debug('exception in reading file: ' + e);
        }
        return null;
    }

    public List<List<paymentRecordsWrapper>> readCSVFile(String dataAsString) {
        List<List<paymentRecordsWrapper>> listWrapper = new List<List<paymentRecordsWrapper>>();
        List<paymentRecordsWrapper> listWrapperTemp = new List<paymentRecordsWrapper>();
        String[] DataLines = new List<String>{};
        listFieldNames = new List<String>();
        DataLines = dataAsString.split('\n');
        string[] csvFieldNames = DataLines[0].split(',');
        for (Integer i = 0; i < csvFieldNames.size(); i++) {
            fieldNumberMap.put(csvFieldNames[i], i);
            listFieldNames.add(csvFieldNames[i].trim());
        }
        for (Integer i = 1; i < DataLines.size(); i++) {
            payWrapRecord = new paymentRecordsWrapper();
            string[] csvRecordData = DataLines[i].split(',(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)');
            for (String fieldName : csvFieldNames) {
                fieldNumber = fieldNumberMap.get(fieldName);
                fieldValue = csvRecordData[fieldNumber];
                assignToWrapper(payWrapRecord, fieldValue, fieldName);
            }
            if (listWrapperTemp.size() < 40) {
                payWrapRecord.insolvencyAccInstance = new Remittance__c();
                listWrapperTemp.add(payWrapRecord);
            } else {
                payWrapRecord.insolvencyAccInstance = new Remittance__c();
                listWrapperTemp.add(payWrapRecord);
                listWrapper.add(listWrapperTemp);
                listWrapperTemp = new List<paymentRecordsWrapper>();
            }
        }
        if (listWrapperTemp.size() > 0) {
            listWrapper.add(listWrapperTemp);
        }
        if (listWrapper.size() > 0) {
            readSuccess = true;
        }

        return listWrapper;
    }

    public paymentRecordsWrapper assignToWrapper(paymentRecordsWrapper prdWrp, String fieldValue, String fieldName) {
        if (fieldName.trim() == 'accountNumber') {
            prdWrp.accountNumber = fieldValue.remove('\\n').deleteWhitespace();
        }
        if (fieldName.trim() == 'accountID') {
            prdWrp.accountID = fieldValue.trim();
        }
        if (fieldName.trim() == 'amount') {
            prdWrp.amount = fieldValue.trim();
        }
        if (fieldName.trim() == 'estateNumber') {
            prdWrp.estateNumber = fieldValue.deleteWhitespace();
        }
        if (fieldName.trim() == 'debtorName') {
            prdWrp.debtorName = fieldValue.trim().remove('"');
        }
        return prdWrp;
    }

    public void assignBankInformation(String remitID) {
        Map<String, Deposit_Accounts__c> depositAccountMap = Deposit_Accounts__c.getAll();
        Double allocatedPaymentAmount = 0;
        List<Remittance__c> remitList = [
            SELECT id, name, status__C, Bank_Account_Number__c, Allocated_Payments_Amount__c
            FROM remittance__C
            WHERE id = :remitID
        ];
        Remittance__c remit = new Remittance__c();

        if (null == remitList || remitList.size() < 1) {
            return;
        } else {
            remit = remitList[0];
        }

        Set<String> setPortfolioGroupName = new Set<String>();

        List<Insolvency_Payment__c> listPaymentstoUpdate = [
            SELECT Id, Deposit_Account_Type__c, Insolvency_Account__r.Portfolio_Group_Name__c, Payment_Amount__c
            FROM Insolvency_Payment__c
            WHERE remittance__c = :remit.id
        ];

        for (Insolvency_Payment__c insPay : listPaymentstoUpdate) {
            allocatedPaymentAmount += insPay.Payment_Amount__c;
            if (String.isNotBlank(insPay.Insolvency_Account__r.Portfolio_Group_Name__c)) {
                String PortfolioGroupName = (insPay.Insolvency_Account__r.Portfolio_Group_Name__c).subString(0, 3);
                if (PortfolioGroupName == 'CIA' || PortfolioGroupName == 'AAL') {
                    PortfolioGroupName = 'CIH';
                }
                setPortfolioGroupName.add(PortfolioGroupName);
            } else {
                setPortfolioGroupName.add('');
            }
        }

        List<Unallocated_Payment__c> listUnallocatedPayments = [SELECT id, name FROM Unallocated_payment__c WHERE remittance__c = :remitID];
        Deposit_Accounts__c depositAcc = new Deposit_Accounts__c();

        if (listUnallocatedPayments.size() > 0 && setPortfolioGroupName.size() == 0) {
            depositAcc = depositAccountMap.get('CIML');
        } else if (listUnallocatedPayments.size() > 0 && setPortfolioGroupName.size() > 0) {
            if (setPortfolioGroupName.contains('')) {
                depositAcc = depositAccountMap.get('CIML');
            } else if (setPortfolioGroupName.contains('CIH')) {
                if (
                    setPortfolioGroupName.contains('CCL') ||
                    setPortfolioGroupName.contains('CLP') ||
                    setPortfolioGroupName.contains('CIA') ||
                    setPortfolioGroupName.contains('CAL') ||
                    setPortfolioGroupName.contains('CFL')
                ) {
                    depositAcc = depositAccountMap.get('CIML');
                } else if (
                    setPortfolioGroupName.contains('ETC') ||
                    setPortfolioGroupName.contains('AFF') ||
                    setPortfolioGroupName.contains('AAL') ||
                    setPortfolioGroupName.contains('AFL')
                ) {
                    depositAcc = depositAccountMap.get('AFSI');
                } else {
                    depositAcc = depositAccountMap.get('CIML');
                }
            } else if (
                setPortfolioGroupName.contains('CCL') ||
                setPortfolioGroupName.contains('CLP') ||
                setPortfolioGroupName.contains('CIA') ||
                setPortfolioGroupName.contains('CAL') ||
                setPortfolioGroupName.contains('CFL')
            ) {
                depositAcc = depositAccountMap.get('CIML');
            } else if (
                setPortfolioGroupName.contains('ETC') ||
                setPortfolioGroupName.contains('AFF') ||
                setPortfolioGroupName.contains('AAL') ||
                setPortfolioGroupName.contains('AFL')
            ) {
                depositAcc = depositAccountMap.get('AFSI');
            } else {
                depositAcc = depositAccountMap.get('CIML');
            }
        } else if (listUnallocatedPayments.size() == 0 && setPortfolioGroupName.size() > 0) {
            if (setPortfolioGroupName.contains('')) {
                depositAcc = depositAccountMap.get('CIML');
            } else if (setPortfolioGroupName.size() > 2) {
                if (setPortfolioGroupName.contains('CIH')) {
                    if (
                        setPortfolioGroupName.contains('CCL') ||
                        setPortfolioGroupName.contains('CLP') ||
                        setPortfolioGroupName.contains('CIA') ||
                        setPortfolioGroupName.contains('CAL') ||
                        setPortfolioGroupName.contains('CFL')
                    ) {
                        depositAcc = depositAccountMap.get('CIML');
                    } else if (
                        setPortfolioGroupName.contains('ETC') ||
                        setPortfolioGroupName.contains('AFF') ||
                        setPortfolioGroupName.contains('AAL') ||
                        setPortfolioGroupName.contains('AFL')
                    ) {
                        depositAcc = depositAccountMap.get('AFSI');
                    } else {
                        depositAcc = depositAccountMap.get('CIML');
                    }
                } else if (
                    setPortfolioGroupName.contains('CCL') ||
                    setPortfolioGroupName.contains('CLP') ||
                    setPortfolioGroupName.contains('CIA') ||
                    setPortfolioGroupName.contains('CAL') ||
                    setPortfolioGroupName.contains('CFL')
                ) {
                    depositAcc = depositAccountMap.get('CIML');
                } else if (
                    setPortfolioGroupName.contains('ETC') ||
                    setPortfolioGroupName.contains('AFF') ||
                    setPortfolioGroupName.contains('AAL') ||
                    setPortfolioGroupName.contains('AFL')
                ) {
                    depositAcc = depositAccountMap.get('AFSI');
                } else {
                    depositAcc = depositAccountMap.get('CIML');
                }
            } else if (setPortfolioGroupName.size() == 2) {
                if (setPortfolioGroupName.contains('CCL') && setPortfolioGroupName.contains('CLP')) {
                    depositAcc = depositAccountMap.get('CCL');
                } else if (setPortfolioGroupName.contains('ETC') && setPortfolioGroupName.contains('AFF')) {
                    depositAcc = depositAccountMap.get('ETC');
                } else if (setPortfolioGroupName.contains('CIH')) {
                    if (
                        setPortfolioGroupName.contains('CCL') ||
                        setPortfolioGroupName.contains('CLP') ||
                        setPortfolioGroupName.contains('CIA') ||
                        setPortfolioGroupName.contains('CAL') ||
                        setPortfolioGroupName.contains('CFL')
                    ) {
                        depositAcc = depositAccountMap.get('CIML');
                    } else if (
                        setPortfolioGroupName.contains('ETC') ||
                        setPortfolioGroupName.contains('AFF') ||
                        setPortfolioGroupName.contains('AAL') ||
                        setPortfolioGroupName.contains('AFL')
                    ) {
                        depositAcc = depositAccountMap.get('AFSI');
                    } else {
                        depositAcc = depositAccountMap.get('CIML');
                    }
                } else if (
                    setPortfolioGroupName.contains('CCL') ||
                    setPortfolioGroupName.contains('CLP') ||
                    setPortfolioGroupName.contains('CIA') ||
                    setPortfolioGroupName.contains('CAL') ||
                    setPortfolioGroupName.contains('CFL')
                ) {
                    depositAcc = depositAccountMap.get('CIML');
                } else if (
                    setPortfolioGroupName.contains('ETC') ||
                    setPortfolioGroupName.contains('AFF') ||
                    setPortfolioGroupName.contains('AAL') ||
                    setPortfolioGroupName.contains('AFL')
                ) {
                    depositAcc = depositAccountMap.get('AFSI');
                } else {
                    depositAcc = depositAccountMap.get('CIML');
                }
            } else if (setPortfolioGroupName.size() == 1) {
                if (setPortfolioGroupName.contains('CCL')) {
                    depositAcc = depositAccountMap.get('CCL');
                } else if (setPortfolioGroupName.contains('CLP')) {
                    depositAcc = depositAccountMap.get('CCL');
                } else if (setPortfolioGroupName.contains('CIA')) {
                    depositAcc = depositAccountMap.get('CIH');
                } else if (setPortfolioGroupName.contains('AFF')) {
                    depositAcc = depositAccountMap.get('ETC');
                } else if (setPortfolioGroupName.contains('AFL')) {
                    depositAcc = depositAccountMap.get('AFL');
                } else if (setPortfolioGroupName.contains('ETC')) {
                    depositAcc = depositAccountMap.get('ETC');
                } else if (setPortfolioGroupName.contains('CIH')) {
                    depositAcc = depositAccountMap.get('CIH');
                } else if (setPortfolioGroupName.contains('CAL')) {
                    depositAcc = depositAccountMap.get('CAL');
                } else if (setPortfolioGroupName.contains('AAL')) {
                    depositAcc = depositAccountMap.get('CIH');
                } else if (setPortfolioGroupName.contains('CFL')) {
                    depositAcc = depositAccountMap.get('CFL');
                } else {
                    depositAcc = depositAccountMap.get('CIML');
                }
            } else {
                depositAcc = depositAccountMap.get('CIML');
            }
        }

        remit.Bank_Account_Number__c = depositAcc.Account_Number__c;
        remit.Transit_Code__c = depositAcc.Transit_Number__c;
        remit.Entity_Name__c = depositAcc.Entity_Name__c;
        remit.Deposit_Account_Name__c = depositAcc.Name;
        remit.Allocated_Payments_Count__c = listPaymentstoUpdate.size();
        if (allocatedPaymentAmount != 0) {
            remit.Allocated_Payments_Amount__c = allocatedPaymentAmount;
        }

        Application_Config_Settings__c acs = Application_Config_Settings__c.getOrgDefaults();

        acs.Run_Remittance_Validation__c = false;
        update acs;

        update remit;

        acs.Run_Remittance_Validation__c = true;
        update acs;

        if (remit.Deposit_Account_Name__c <> 'CIML' && remit.Deposit_Account_Name__c <> 'AFSI') {
            for (Insolvency_Payment__c insolPay : listPaymentstoUpdate) {
                insolPay.Deposit_Account_Type__c = remit.Deposit_Account_Name__c;
            }
        } else {
            for (Insolvency_Payment__c insolPay : listPaymentstoUpdate) {
                Deposit_Accounts__c depositAccRecord = new Deposit_Accounts__c();
                if (null != insolPay.Insolvency_Account__r.Portfolio_Group_Name__c) {
                    depositAccRecord = depositAccountMap.get((insolPay.Insolvency_Account__r.Portfolio_Group_Name__c).subString(0, 3));
                }
                if (null == insolPay.Insolvency_Account__r.Portfolio_Group_Name__c || null == depositAccRecord) {
                    depositAccRecord = depositAccountMap.get('CIML');
                }
                insolPay.Deposit_Account_Type__c = depositAccRecord.Name;
            }
        }
        update listPaymentstoUpdate;
    }
}