force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Record_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Run_Record_Ownership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Record Ownership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Is_Record_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Record_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Record Locked</description>
    <inlineHelpText>Is Record Locked</inlineHelpText>
    <label>Is Record Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInsolvencyOwnerShipController.cls
/**************************************************************************************************
 *
 *  Class:   TestInsolvencyOwnerShipController
 *
 *  @description : This class contains unit tests for generating and saving poc pdf document
 *  @author : A5E Consulting
 *  @date : 10/08/2017
 * 
 *************************************************************************************************/

@isTest
public class TestInsolvencyOwnerShipController{
    //Create all necessary Object records in this method
    @testSetup 
    static void testData() {
         Application_Config_Settings__c config = new  Application_Config_Settings__c(Run_Insolvency_Status_Validations__c = false, Run_Record_Ownership__c = true);
         insert config;
         
         Insolvency_Account__c insolvAacc = new Insolvency_Account__c();
         insert insolvAacc ;
         
         // insert insolvency record
         Insolvency__c insolv = new Insolvency__c(name = 'test-insolOwner', Is_Record_Locked__c = true);
         insert insolv;      
    }
     
    // Unit test for saving poc pdf document as attachment of insolvancy account
    static testMethod void testRecorOwneship(){
        Insolvency__c insolv = [SELECT Id FROM Insolvency__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('Id', insolv.Id);  
        InsolvencyOwnerShipController obj = new InsolvencyOwnerShipController(new ApexPages.StandardController(insolv));
        
        obj.isScotiaBankCommunityUser = true;
        obj.checkInsolvencyAccountOwnerShip();
        
        obj.isScotiaBankCommunityUser = false;
        obj.isChaseBankCommunityUser = true;
        obj.checkInsolvencyAccountOwnerShip();
        
        obj.isChaseBankCommunityUser = false;
        obj.isSDABankCommunityUser = true;
        obj.checkInsolvencyAccountOwnerShip();
        
        obj.isSDABankCommunityUser = false;
        obj.isChaseBankCommunityUser = true;
        obj.checkInsolvencyAccountOwnerShip();
     }
}