force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/CCS_Final_Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>CCS_Final_Deposit_Slip__c</fullName>
    <description>To Determine Final deposit slip is generated for particular day</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To Determine Final deposit slip is generated for particular day</inlineHelpText>
    <label>CCS Final Deposit Slip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Final_Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Final_Deposit_Slip__c</fullName>
    <description>Final Deposit Slip for the day</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Deposit Slip</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deposit_Slip__c/Deposit_Slip__c.object-meta.xml
<CustomObject>
    <description>View the deposit slips for today generated in previous step/tab - &quot;Generate Deposit Slip&quot;</description>
    <label>Deposit Slip</label>
    <nameField>
        <displayFormat>DS-{000}</displayFormat>
        <label>Deposit Slip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Slips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/recordTypes/CCS_Deposit_Slip.recordType-meta.xml
<RecordType>
    <fullName>CCS_Deposit_Slip</fullName>
    <active>true</active>
    <description>Deposit slip for CCS</description>
    <label>CCS Deposit Slip</label>
</RecordType>

force-app/main/default/objects/Deposit_Slip__c/recordTypes/Insolvency_Deposit_Slip.recordType-meta.xml
<RecordType>
    <fullName>Insolvency_Deposit_Slip</fullName>
    <active>true</active>
    <description>Deposit Slip for Insolvency</description>
    <label>Insolvency Deposit Slip</label>
</RecordType>

force-app/main/default/classes/DepositSlipAutoLock.cls
public class DepositSlipAutoLock {
    // Production Issue - Converted variables to list
    public static List<Deposit_Slip__c> ccsdepositSlip = new List<Deposit_Slip__c>();
    public static List<Deposit_Slip__c> InsolvdepositSlip = new List<Deposit_Slip__c>();
    public static Application_Config_Settings__c appConfigFinal = Application_Config_Settings__c.getOrgDefaults();

    public static void DepositSlipLock() {
        appConfigFinal = [SELECT CCS_Final_Deposit_Slip__c, Final_Deposit_Slip__c FROM Application_Config_Settings__c FOR UPDATE]; //CCS and Inolsvency Final Depsoti slip dates
        ccsdepositSlip = [
            SELECT Id, Name
            FROM Deposit_Slip__c
            WHERE CreatedDate = TODAY AND recordType.developerName = 'CCS_Deposit_Slip'
            ORDER BY createdDate DESC
            LIMIT 1
        ]; // Today's CCS Deposit Slips
        InsolvdepositSlip = [
            SELECT Id, Name
            FROM Deposit_Slip__c
            WHERE CreatedDate = TODAY AND recordType.developerName = 'Insolvency_Deposit_Slip'
            ORDER BY createdDate DESC
            LIMIT 1
        ]; // Today's Insolvency Deposit Slips
        //Logic to CCS Deposit Auto Lock
        // Production Issue - Added List empty check
        if (!ccsdepositSlip.isEmpty() && appConfigFinal.CCS_Final_Deposit_Slip__c != system.today()) {
            appConfigFinal.CCS_Final_Deposit_Slip__c = system.today();
            update appConfigFinal;
        }

        //Logic to Insolvency Deposit Auto Lock
        // Production Issue - Added List empty check
        if (!InsolvdepositSlip.isEmpty() && appConfigFinal.Final_Deposit_Slip__c != system.today()) {
            appConfigFinal.Final_Deposit_Slip__c = system.today();
            update appConfigFinal;
        }
    }
}