force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Display_Duplicate_Accounts_List_View__c.field-meta.xml
<CustomField>
    <fullName>Display_Duplicate_Accounts_List_View__c</fullName>
    <label>Display Duplicate Accounts List View</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestInsolvencyAcctStatusValidation.cls
/**************************************************************************************************
*
*  Class:    
*
*  @description : This is a Test class for InsolvencyAcctStatusValidationController
*  @author : A5E Consulting
*  @date : 10/04/2019

*************************************************************************************************/
@isTest
public class TestInsolvencyAcctStatusValidation {
    @TestSetup
    static void makeData(){
        Application_Config_Settings__c config = new Application_Config_Settings__c();
        config.Run_Insolvency_Account_Trigger__c = true;
        config.Run_Insolvency_Status_Validations__c = true;
        config.Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
        config.Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm';
        config.Display_Duplicate_Accounts_List_View__c = 10;
        config.Bank_Eligible_for_Duplicate_Check__c = 'SPL';
        config.Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN';
        config.Run_Insolvency_Trigger__c = false;
        config.Run_Insolvency_Account_Duplicate_Check__c = true;
        insert config;
    }
    static testMethod void internalStatusValidation() {
        InsolvencyAccountTriggerHandler.runInsolvencyAccountTrigger = false;
        List<Insolvency__c> insolvList = new List<Insolvency__c>();
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Insolvency_Type__c = 'Bankruptcy';
        insert insolv1;
        list<RecordType> recordTypeList = new List<RecordType>(
            [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Insolvency_Account__c' AND Name LIKE '%SDA%']
        );
        Insolvency_Account__c insacc = new Insolvency_Account__c();
        insacc.RecordTypeId = recordTypeList[0].Id;
        insacc.Name = 'Test-001';
        insacc.Insolvency_Status__c = 'No PoC Required';
        insacc.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insacc.Claim_Type__c = 'Unsecured';
        insacc.Insolvency__c = insolv1.Id;
        insacc.Account_Number_Without_Space__c = 'Test-001';
        insert insacc;

        InsolvencyAcctStatusValidationController validCont = new InsolvencyAcctStatusValidationController();

        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, null, 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'NULL', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'New', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'PoC Package Generated');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review Completed', 'No PoC Required');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Wait / Hold', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Package Generated', 'Claim Filed');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Refused', 'Sent to collections');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Refused', 'Pending Assignment to Collection Agency');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Annulled', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Withdraw PoC', 'Claim Withdrawn');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Claim Filed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review completed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review completed', 'Claim Filed');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Details Provided', 'No PoC Required');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Package Generated', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Claim Filed', 'For Owner Review');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Details Provided', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Annulled', 'Annulled - Filed New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Refused', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'Account Recall Requested');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Account Recall Requested', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Account Recall Requested', 'For Owner Review');
    }

    static testMethod void externalStatusValidation() {
        InsolvencyAccountTriggerHandler.runInsolvencyAccountTrigger = false;
        List<Insolvency__c> insolvList = new List<Insolvency__c>();
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Scotia Bank';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Insolvency_Type__c = 'Bankruptcy';
        insert insolv1;
        list<RecordType> recordTypeList = new List<RecordType>(
            [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Insolvency_Account__c' AND Name LIKE '%SDA%']
        );
        Insolvency_Account__c insacc = new Insolvency_Account__c();
        insacc.RecordTypeId = recordTypeList[0].Id;
        insacc.Name = 'Test-001';
        insacc.Insolvency_Status__c = 'No PoC Required';
        insacc.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insacc.Claim_Type__c = 'Unsecured';
        insacc.Insolvency__c = insolv1.Id;
        insacc.Account_Number_Without_Space__c = 'Test-001';
        insert insacc;

        InsolvencyAcctStatusValidationController validCont = new InsolvencyAcctStatusValidationController();

        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'New');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'Trustee Followup');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'BOT Review Completed');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Review Completed', 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Wait / Hold', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Package Generated', 'Claim Filed');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Withdraw PoC', 'Claim Withdrawn');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Claim Filed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Review completed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Review completed', 'Claim Filed');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'For Owner Review', 'New');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'No PoC Required', 'New');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'No PoC Required', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Details Provided', 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Package Generated', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Claim Filed', 'For Owner Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'No PoC Required', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Details Provided', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Trustee Followup', 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'For Owner Review', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, null, 'Wait / Hold');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'For Owner Review', 'Wait / Hold');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Review', 'BOT Mismatch');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Mismatch', 'BOT Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Review completed', 'Wait / Hold');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'For Owner Review', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Trustee Followup', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'For Owner Review', 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Wait / Hold', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Details Provided', 'Wait / Hold');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Wait / Hold', 'No PoC Required');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'No PoC Required', 'Wait / Hold');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'PoC Details Provided', 'For Owner Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'No PoC Required', 'For Owner Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Wait / Hold', 'For Owner Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'Wait / Hold', 'Withdraw PoC');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Mismatch', 'BOT Review');
        InsolvencyAcctStatusValidationController.externalValidationRule(insacc, 'BOT Mismatch', 'BOT Review completed');
    }

    static testMethod void internalStatusValidationforFidem() {
        InsolvencyAccountTriggerHandler.runInsolvencyAccountTrigger = false;
        List<Insolvency__c> insolvList = new List<Insolvency__c>();
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insolv1.Client_Identifiers__c = 'Fidem';
        insolv1.Sent_For_Owner_Review_Date__c = System.today();
        insolv1.Insolvency_Type__c = 'Bankruptcy';
        insert insolv1;
        list<RecordType> recordTypeList = new List<RecordType>(
            [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Insolvency_Account__c' AND Name LIKE '%Fidem%']
        );
        Insolvency_Account__c insacc = new Insolvency_Account__c();
        insacc.RecordTypeId = recordTypeList[0].Id;
        insacc.Name = 'Test-001';
        insacc.Client_Identifier__c = 'Fidem';
        insacc.Insolvency_Status__c = 'No PoC Required';
        insacc.Reason_for_No_PoC_Required_Dropdown__c = 'Duplicate';
        insacc.Claim_Type__c = 'Unsecured';
        insacc.Insolvency__c = insolv1.Id;
        insacc.Account_Number_Without_Space__c = 'Test-001';
        insacc.Asset_Status__c = 'Purchased';
        insert insacc;

        InsolvencyAcctStatusValidationController validCont = new InsolvencyAcctStatusValidationController();

        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, null, 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'NULL', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'New', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'PoC Package Generated');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review Completed', 'No PoC Required');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Wait / Hold', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Package Generated', 'Claim Filed');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Refused', 'Sent to collections');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Annulled', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Withdraw PoC', 'Claim Withdrawn');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Claim Filed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review completed', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'BOT Review completed', 'Claim Filed');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Details Provided', 'No PoC Required');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Package Generated', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Claim Filed', 'For Owner Review');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'No PoC Required', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Details Provided', 'Trustee Followup');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Annulled', 'Annulled - Filed New');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Refused', 'Debtor Paying Direct');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'For Owner Review', 'Account Recall Requested');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'PoC Details Provided', 'Account Recall Requested');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Account Recall Requested', 'PoC Details Provided');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Account Recall Requested', 'For Owner Review');
        InsolvencyAcctStatusValidationController.internalValidationRule(insacc, 'Account Recall Requested', 'Annulled');
    }
}