force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Trustee_Email_Default_Content__c.field-meta.xml
<CustomField>
    <fullName>CFG_Trustee_Email_Default_Content__c</fullName>
    <description>Contains the (HTML optional) default content to be pre-populated when the Email Trustee page is opened from an Insolvency Account record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Contains the (HTML optional) default content to be pre-populated when the Email Trustee page is opened from an Insolvency Account record.</inlineHelpText>
    <label>CFG Trustee Email Default Content</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Trustee_Email_Default_Subject__c.field-meta.xml
<CustomField>
    <fullName>CFG_Trustee_Email_Default_Subject__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Trustee Email Default Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestInsolvencyDragNDropController.cls
/**************************************************************************************************
 *
 *  Class:   TestInsolvencyDragNDropController
 *
 *  @description : This class contains unit tests for InsolvencyAccntDragNDropController regarding insolvancy drag and drop of an attachments
 *  @author : A5E Consulting
 *  @date : 30-Dec-2017
 * 
 *************************************************************************************************/
@isTest(seeAllData=false)
public class TestInsolvencyDragNDropController{
    
     // Create all necessary test data
     @testSetup 
     static void testData() {
         // create poc custom settings
         PoC_Package_Settings__c poc = new PoC_Package_Settings__c(Name = 'Scotia Bank', CFG_Trustee_Email_Default_content__c = 'test', CFG_Trustee_Email_Default_Subject__c ='test');
         insert poc;
         
         // insert insolvency record
         Insolvency__c insolv = new Insolvency__c(Name='test');
         insert insolv; 
         
         // insert attachments for insolvance
         Attachment att = new Attachment(Name = 'testAtt', Body = Blob.valueOf('Test'), parentId = insolv.Id);
         insert att;
                                                     
         Application_Config_Settings__c appConfig = new Application_Config_Settings__c(Run_Insolvency_Status_Validations__c = true);
         insert appConfig;
     }
     
     // Testing update attachments
     static testMethod void sendEmailTest(){
          Insolvency__c insolv = [SELECT Id FROM Insolvency__c LIMIT 1];
          // call the constructor
          InsolvencyDragNDropController controller = new InsolvencyDragNDropController(new ApexPages.StandardController(insolv));
          InsolvencyDragNDropController.getDocumentOptions();
          InsolvencyDragNDropController.getfileDocumentOptions();
          InsolvencyDragNDropController.getRecordInfo(insolv.Id);
          controller.updateAtList();
          controller.description = 'Account';
          Double db = controller.offset;
          controller.selectedAttId = [SELECT Id FROM Attachment LIMIT 1].Id;
          controller.deleteAttachment();
     }
}