force-app/main/default/objects/Case/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <label>Assign To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CFG</fullName>
                <default>true</default>
                <label>CFG</label>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Fairstone</fullName>
            </value>
            <value>
                <fullName>Goeasy</fullName>
                <label>Easyfinancial</label>
            </value>
            <value>
                <fullName>Canadian Tire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Form_Types__c.field-meta.xml
<CustomField>
    <fullName>Form_Types__c</fullName>
    <description>To differentiate between emails(Assignments)</description>
    <inlineHelpText>To differentiate between emails(Assignments)</inlineHelpText>
    <label>Form Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Balance Updates</fullName>
            </value>
            <value>
                <fullName>Bulk Response</fullName>
            </value>
            <value>
                <fullName>Chq Stub</fullName>
            </value>
            <value>
                <fullName>Creditor Package</fullName>
            </value>
            <value>
                <fullName>Deficiency / Rejected POC</fullName>
            </value>
            <value>
                <fullName>DMP</fullName>
            </value>
            <value>
                <fullName>Drop Notification</fullName>
            </value>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Form 149 – Notice to Prove Claim</fullName>
            </value>
            <value>
                <fullName>Form 15 – Deemed Discharge of Trustee</fullName>
            </value>
            <value>
                <fullName>Form 16 – Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Form 33 – Notice of Intention</fullName>
            </value>
            <value>
                <fullName>Form 40.1 - Notice of Hearing</fullName>
            </value>
            <value>
                <fullName>Form 49 – Amendment</fullName>
            </value>
            <value>
                <fullName>Form 50 - Meeting Of Creditors</fullName>
            </value>
            <value>
                <fullName>Form 52 – Notice of Status</fullName>
            </value>
            <value>
                <fullName>Form 56 – Notice of annulment</fullName>
            </value>
            <value>
                <fullName>Form 69 – Impending Automatic Discharge</fullName>
            </value>
            <value>
                <fullName>Form 71 – Notice of First Meeting</fullName>
            </value>
            <value>
                <fullName>Form 76 – Notice of Proof of Security</fullName>
            </value>
            <value>
                <fullName>Form 77 – Notice of Disallowance</fullName>
            </value>
            <value>
                <fullName>Form 80 – Notice of Intended opposition to discharge.</fullName>
            </value>
            <value>
                <fullName>Form 81 &amp; 82– Application for Discharge</fullName>
            </value>
            <value>
                <fullName>Form 92 – Notice of Proposal</fullName>
            </value>
            <value>
                <fullName>Form 93 &amp; 96 – Revival</fullName>
            </value>
            <value>
                <fullName>French Document</fullName>
            </value>
            <value>
                <fullName>Inspector File</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>LendCare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Insolvency_Assignment_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Assignment_Type__c</fullName>
    <description>Insolvency Assignment Type</description>
    <inlineHelpText>Insolvency Assignment Type</inlineHelpText>
    <label>Insolvency Assignment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Assign_To__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Validation</fullName>
            </value>
            <value>
                <fullName>Amend Claim</fullName>
            </value>
            <value>
                <fullName>Business Insolvency</fullName>
            </value>
            <value>
                <fullName>Chq Stub</fullName>
            </value>
            <value>
                <fullName>Distressed Sale</fullName>
            </value>
            <value>
                <fullName>Letter of Release Request</fullName>
            </value>
            <value>
                <fullName>More Information Required</fullName>
            </value>
            <value>
                <fullName>Needs Documentation</fullName>
            </value>
            <value>
                <fullName>Notice of Disallowance</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Refund Request</fullName>
            </value>
            <value>
                <fullName>Secured Communications</fullName>
            </value>
            <value>
                <fullName>Vehicle Pickup Request</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>OSB Request</fullName>
            </value>
            <value>
                <fullName>Fax Confirmation Report</fullName>
            </value>
            <value>
                <fullName>Balance Updates</fullName>
            </value>
            <value>
                <fullName>DMP</fullName>
            </value>
            <value>
                <fullName>Drop Notification</fullName>
            </value>
            <value>
                <fullName>PIF request</fullName>
            </value>
            <value>
                <fullName>Payout Request</fullName>
            </value>
            <value>
                <fullName>Settlement Offer</fullName>
            </value>
            <value>
                <fullName>Forward Request</fullName>
                <isActive>false</isActive>
                <label>Forward Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <formula>CASE(TEXT(Client_Identifier__c), &apos;Goeasy&apos;, &apos;Easyfinancial&apos;, TEXT(Client_Identifier__c))</formula>
    <inlineHelpText>Bank Name</inlineHelpText>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Name__c</fullName>
    <description>Populate Debtor name In Overview section</description>
    <formula>Debtor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Debtor name</inlineHelpText>
    <label>Debtor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Store Insolvency Account number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To know whether this is unallocated amount is allocated to some Insolvency Account or not</description>
    <label>Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link to to assignment</description>
    <inlineHelpText>To link to to assignment</inlineHelpText>
    <label>Assignment</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name from Insolvency Account</description>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>MBNA</fullName>
            </value>
            <value>
                <fullName>TD Bank</fullName>
            </value>
            <value>
                <fullName>Tangerine</fullName>
            </value>
            <value>
                <fullName>Auto Capital</fullName>
            </value>
            <value>
                <fullName>Progressa</fullName>
            </value>
            <value>
                <fullName>Lendcare</fullName>
            </value>
            <value>
                <fullName>Fairstone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated Customer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Debtor_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Debtor / Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Estate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remittance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remittance Cheque Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Reviewed_status__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_status__c</fullName>
    <label>Reviewed status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold to Canaccede</fullName>
            </value>
            <value>
                <fullName>Need to be remitted</fullName>
            </value>
            <value>
                <fullName>Unable To Locate Account - More Information Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Store unallocated amount for Remittance</description>
    <label>Unallocated Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/AddAttachmentToUnallocatedController.cls
public class AddAttachmentToUnallocatedController {
    public static string EstateNumber{get;set;}
    public case caseObj{get;set;}
    public String insolvencyAccNumbers{set;get;}
    public Id attachmentSelected{set;get;}
    public Id paymentSelected{set;get;}
    public Boolean searchResultsFound{get;set;}
    public Boolean errorOccured{get;set;}
    // Stores all attachments that are selected by user
    public Set<Id> mySelectedAtt = new Set<Id>();
    // Stores all Payments that are selected by user
    public Set<Id> mySelectedPaymts = new Set<Id>();
    public Set<ID> recordsNotToSearch = new Set<ID>();
    
    //Attachment for Dividend
    public List<caseAttachment> attachDocument{get;set;}
    
    //Unallocated Payments list
    public list<unallPayments> showUnallPay{get;set;}
    public list<unallPayments> displayUnallPay{get;set;}
    
    //Constructor
    public AddAttachmentToUnallocatedController(ApexPages.StandardController controller) {
        caseObj = new case();
        caseObj = [select Id, CaseNumber, Subject, Insolvency__c, Insolvency_Account__c, Assign_To__c, Assigned_To__c, Insolvency_Assignment_Type__c, Form_Types__c, CreatedDate 
                    from Case where Id =: ApexPages.currentPage().getParameters().get('id')];
    
        fetchAttachment();
        displayUnallPay = new List<unallPayments>();
        List<Unallocated_Payment__c> listUnallocPayment = [select id, name, Bank_Name__c, Account_Number__c, Allocated__c, Customer_Name__c, Debtor_Name__c, Estate_Number__c, Payment_Date__c, Payment_Reference_Number__c, Reviewed_status__c, Unallocated_Amount__c from Unallocated_Payment__c where assignment__c =: caseObj.id];
        for(Unallocated_Payment__c unPayRec : listUnallocPayment){
            unallPayments payRecord = new unallPayments();
            payRecord.selected = True;
            payRecord.unallPay = unPayRec;
            displayUnallPay.add(payRecord);
            recordsNotToSearch.add(unPayRec.id);
        }
        
        errorOccured = false;
    }
    
    void fetchAttachment(){
          attachDocument = new list<caseAttachment>();
          Datetime now = Datetime.now();
          Integer offset = UserInfo.getTimezone().getOffset(now);
        
          for(Attachment attchmt : [select id, name, Description, CreatedDate, LastModifiedDate, parentID, BodyLength 
                           from attachment where parentID =:caseObj.ID ORDER BY CreatedDate DESC]){
         
              caseAttachment temp = new caseAttachment();
              temp.attId = attchmt.Id;
              temp.selected =false;
              temp.fileName=attchmt.Name;
              temp.fileDesc=attchmt.Description;
              temp.fileCreatedDate = attchmt.createdDate.addSeconds(offset/1000);
              temp.displaySize = InsolvencyUtil.fileSizeToString((attchmt.BodyLength));
              attachDocument.add(temp);                   
          }
         
          for(Attachment attch : [SELECT Id, Name, Description, CreatedDate, LastModifiedDate, parentId, BodyLength  
                          FROM Attachment WHERE ParentId in (select id from EMailMessage where relatedToid =: caseObj.id)]){
              caseAttachment temp = new caseAttachment();
              temp.attId = attch.Id;
              temp.selected =false;
              temp.fileName=attch.Name;
              temp.fileDesc=attch.Description;
              temp.fileCreatedDate = attch.createdDate.addSeconds(offset/1000);
              temp.displaySize = InsolvencyUtil.fileSizeToString((attch.BodyLength));
              attachDocument.add(temp);
          }
                          
         //attachDocument.addAll(listAttach);
    }
    
    // Method search for given Insolvency account, Estate Number, Primary Borrower and Debtor
    public PageReference searchUnallPayments(){
        
        fillShowUnallPay();
        List<ID> listInsolvAccIDs = new List<ID>();
        if(insolvencyAccNumbers.trim().length()==0){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter data in search field.'));
            return null;
        }
      
        // Perform search only if user entered some text in search field
        if(!String.isEmpty(insolvencyAccNumbers)){
            List<String> searchList = New List<String>();
            List<String> accNumList = insolvencyAccNumbers.split(',');
            for(Integer i=0; i<accNumList.size(); i++){
                String temp = accNumList.get(i).trim();
                temp = '%'+temp+'%';
                searchList.add(temp);
            }
            searchResultsFound = false;
            
            for(Unallocated_Payment__c unPay : [SELECT Id, name, Bank_Name__c, Account_Number__c, Allocated__c, Customer_Name__c, Debtor_Name__c, Estate_Number__c, Payment_Date__c, Payment_Reference_Number__c, Reviewed_status__c, Unallocated_Amount__c FROM Unallocated_Payment__c WHERE (Name LIKE : searchList OR Debtor_Name__c LIKE : searchList OR Customer_Name__c LIKE : searchList OR Estate_Number__c LIKE : searchList OR Account_Number__c LIKE : searchList ) AND ( Not id in :recordsNotToSearch ) AND Allocated__c = FALSE AND Is_Payment_Remitted__c = FALSE AND Is_Payments_Reversed__c = NULL ORDER BY NAME,Customer_Name__c,Debtor_Name__c ASC]){
                unallPayments UnallPay = new unallPayments();
            
                UnallPay.selected = false;
                UnallPay.unallPay = unPay;
                showUnallPay.add(UnallPay);
                
                searchResultsFound = true;
            }
            if(!searchResultsFound){
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No search results found.'));
            }
        }
        return null;
    }
    
    //attach selected document to selected unallocated payments
    public void attachDocument(){
        list<Attachment> createAttach = new list<Attachment>();
        Attachment newAttch;
        system.debug('mySelectedAtt='+mySelectedAtt);
        system.debug('mySelectedPaymts='+mySelectedPaymts);
        if(mySelectedPaymts.size() < 1){
            errorOccured = True;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select unallocated payment record to attach the document.'));
            return;
        }
        if(mySelectedAtt.size() < 1){
            errorOccured = True;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select attachment record.'));
            fillShowUnallPay();
            return;
        }
        for(Unallocated_Payment__c unPay : [select Id, Name, assignment__c, Bank_Name__c, Account_Number__c, Allocated__c, Customer_Name__c, Debtor_Name__c, Estate_Number__c, Payment_Date__c, Payment_Reference_Number__c, Reviewed_status__c, Unallocated_Amount__c  from Unallocated_Payment__c where Id IN: mySelectedPaymts]){
            //if(unPay.assignment__c == null){
                for(Attachment attch : [select Id, Name, Body, parentId from Attachment where Id IN: mySelectedAtt]){
                    newAttch = new Attachment();
                    newAttch.Body = attch.Body;
                    newAttch.Name = attch.Name;
                    newAttch.ParentId = unPay.Id;
                    createAttach.add(newAttch);
                    
                }
                
                unPay.Assignment__c = caseObj.id;
                unallPayments payRecord = new unallPayments();
                payRecord.selected = True;
                payRecord.unallPay = unPay;
                displayUnallPay.add(payRecord);
                recordsNotToSearch.add(unPay.id);
                update unPay;
            //}
        }
        insert createAttach;
        system.debug('createAttach='+createAttach);
        system.debug('displayUnallPay='+displayUnallPay);
        showUnallPay = new List<unallPayments>();
        mySelectedPaymts = new Set<ID>();
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Document has been attached to selected unallocated record/s.'));
        
    }
    
     //Handles to store list of attachments selected by user
    public void attachmentSelected(){
        if(attachmentSelected != null){
            mySelectedAtt.add(attachmentSelected );
            attachmentSelected = null;
        }
    }
    
    //Handles to remove attachments un selected by user
    public void attachmentRemoved(){
        if(attachmentSelected != null){
            mySelectedAtt.remove(attachmentSelected );
            attachmentSelected = null;
        }
        
    }
    
    //Handles to store list of payments selected by user
    public void paymentSelected(){
        if(paymentSelected != null){
            mySelectedPaymts.add(paymentSelected );
            paymentSelected = null;
        }
    }
    
    //Handles to remove payments un selected by user
    public void paymentRemoved(){
        if(paymentSelected != null){
            mySelectedPaymts.remove(paymentSelected );
            paymentSelected = null;
        }
        
    }
    
    //to fill the show list after search
    public void fillShowUnallPay(){
        showUnallPay = new list<unallPayments>();
        List<Unallocated_Payment__c> listUnallocatedPayments = [select Id, Name, Bank_Name__c, Account_Number__c, Allocated__c, Customer_Name__c, Debtor_Name__c, Estate_Number__c, Payment_Date__c, Payment_Reference_Number__c, Reviewed_status__c, Unallocated_Amount__c from Unallocated_Payment__c where Id IN: mySelectedPaymts];
        for(Unallocated_Payment__c unAllocPay : listUnallocatedPayments){
            unallPayments payRecord = new unallPayments();
            payRecord.selected = True;
            payRecord.unallPay = unAllocPay;
            showUnallPay.add(payRecord);
            recordsNotToSearch.add(unAllocPay.id);
        }
    }
    
    // Wrapper class used to frame attachments with checkboxes 
    public class caseAttachment{
        public Boolean selected{set;get;}
        public Id attId{set;get;}
        public String filename{set;get;}
        public String fileDesc{set;get;}
        public DateTime fileCreatedDate {set;get;}
        public String displaySize {set;get;}
    }
    
    //Wrapper class used to frame unallocated payments with checkboxes
    public class unallPayments{
        public Boolean selected{get;set;}
        public Unallocated_Payment__c unallPay;
         
         public void setunallPay(){
             unallPay = unallPay;
         }
         public Unallocated_Payment__c getunallPay(){
             return unallPay;
         }
    }
}