force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Type_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Service__c</fullName>
    <description>Type of Service</description>
    <inlineHelpText>Type of Service</inlineHelpText>
    <label>Type of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Only</fullName>
            </value>
            <value>
                <fullName>Service and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsolvencyAccountDataValidationCntrl.cls
public class InsolvencyAccountDataValidationCntrl {
    public Boolean showErrorDiv {set;get;}
    public String errorMessage {set;get;}
    public String SECURED_NOT_MATCH_WITH_SERVICE = 'Warning: Secured Claim types should have Type of Service as \"Service Only\"';
    public String UNSECURED_NOT_MATCH_WITH_SERVICE = 'Warning: Unsecured Claim types should have Type of Service as \"Service and Sale\"';
    
    public InsolvencyAccountDataValidationCntrl(ApexPages.StandardController controller) {
        showErrorDiv = true;
        Insolvency_Account__c insolvAcc = [SELECT Id, 
                                                  Claim_Type__c,
                                                  Insolvency_Type__c,
                                                  Type_of_Service__c  
                                           FROM 
                                               Insolvency_Account__c 
                                           WHERE 
                                               ID =: controller.getId()];
        if(insolvAcc.Insolvency_Type__c != NULL && insolvAcc.Insolvency_Type__c.equalsignorecase('Division 1 Proposal')){
            showErrorDiv = false;
        }else if(insolvAcc.Claim_Type__c != NULL && insolvAcc.Type_of_Service__c != NULL){
            if(insolvAcc.Claim_Type__c == 'Unsecured' && insolvAcc.Type_of_Service__c != 'Service and Sale'){
                errorMessage = UNSECURED_NOT_MATCH_WITH_SERVICE;
            }
            if(insolvAcc.Claim_Type__c == 'Secured' && insolvAcc.Type_of_Service__c != 'Service Only'){
                errorMessage = SECURED_NOT_MATCH_WITH_SERVICE;
            }
        }
    }
}