force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Cheque_Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Payment_Reference_Number__c</fullName>
    <description>A payment reference number.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A payment reference number.</inlineHelpText>
    <label>Cheque/ Payment Reference Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Insolvency Account.</description>
    <inlineHelpText>The amount to be applied to the Insolvency Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Insolvency Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Insolvency Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/recordTypes/Remittance.recordType-meta.xml
<RecordType>
    <fullName>Remittance</fullName>
    <active>true</active>
    <description>Remittance Insolvency Payments</description>
    <label>Remittance</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Allocated_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Amount__c</fullName>
    <label>Allocated Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Allocated_Payments_Count__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Count__c</fullName>
    <label>Allocated Payments Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Cheque_Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Payment_Reference_Number__c</fullName>
    <description>A payment reference number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A payment reference number</inlineHelpText>
    <label>Cheque/ Payment Reference Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <description>Payment Posting Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Posting Date</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Striplist_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Striplist_User_ID__c</fullName>
    <description>ID if the user who uploaded the striplist for parsing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ID if the user who uploaded the striplist for parsing</inlineHelpText>
    <label>Striplist User ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Unallocated_Payment_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment_Processing_Status__c</fullName>
    <label>Unallocated Payment Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisplayStriplistInsolUnallocController.cls
public class DisplayStriplistInsolUnallocController {
    public Remittance__c remittanceInstance { get; set; }
    public Map<Integer, StriplistUtil.paymentRecordsWrapper> wrapperMap { get; set; }
    StriplistUtil eftUtilInstance;
    public boolean disableSave { get; set; }
    public boolean showTable { get; set; }

    public DisplayStriplistInsolUnallocController() {
        wrapperMap = new Map<Integer, StriplistUtil.paymentRecordsWrapper>();
        List<List<StriplistUtil.paymentRecordsWrapper>> paymentRecordList = new List<List<StriplistUtil.paymentRecordsWrapper>>();
        List<StriplistUtil.paymentRecordsWrapper> paymentRecordListInner = new List<StriplistUtil.paymentRecordsWrapper>();
        disableSave = false;
        showTable = true;
        String dividendId = ApexPages.currentPage().getParameters().get('id');
        remittanceInstance = new Remittance__c();
        if (dividendId != null) {
            remittanceInstance = [
                SELECT
                    ID,
                    Unallocated_Payment_Processing_Status__c,
                    Striplist_User_ID__c,
                    Cheque_Payment_Reference_Number__c,
                    Payment_Posting_Date__c,
                    Allocated_Payments_Amount__c,
                    Allocated_Payments_Count__c
                FROM Remittance__c
                WHERE ID = :dividendId
            ][0];
            if (remittanceInstance.Unallocated_Payment_Processing_Status__c == 'Completed') {
                disableSave = true;
            }
            list<Attachment> unallocatedPayment = [
                SELECT id, name, body
                FROM attachment
                WHERE Name = 'Un-allocated Payments.csv' AND parentId = :dividendId
            ];
            Blob csvFileBody = unallocatedPayment[0].body;
            String dataAsString = csvFileBody.toString();
            eftUtilInstance = new StriplistUtil();
            paymentRecordList = eftUtilInstance.readCSVFile(dataAsString);
            if (paymentRecordList.isEmpty()) {
                showTable = false;
                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO, 'There are no Unallocated Insolvency Payments to display!'));
                return;
            }
            for (List<StriplistUtil.paymentRecordsWrapper> payWrap : paymentRecordList) {
                paymentRecordListInner.addAll(payWrap);
            }
            for (Integer i = 0; i < paymentRecordListInner.size(); i++) {
                wrapperMap.put(i, paymentRecordListInner[i]);
            }
        }
    }

    public pageReference Save() {
        Id insolvencyPaymentRecordTypeID = Schema.SObjectType.Insolvency_Payment__c.getRecordTypeInfosByName().get('Remittance').getRecordTypeId();
        List<StriplistUtil.paymentRecordsWrapper> listUnallocatedPayment = new List<StriplistUtil.paymentRecordsWrapper>();
        List<Insolvency_Payment__c> listInsolvencyPayment = new List<Insolvency_Payment__c>();
        for (Integer key : wrapperMap.keySet()) {
            StriplistUtil.paymentRecordsWrapper wrapRecord = wrapperMap.get(key);
            if (wrapRecord.insolvencyAccInstance.Insolvency_Account__c == null) {
                listUnallocatedPayment.add(wrapRecord);
            } else {
                Insolvency_Payment__c paymentInstance = new Insolvency_Payment__c();
                paymentInstance.Created_by_Striplist_Parsing__c = true;
                if (remittanceInstance.Payment_Posting_Date__c != null) {
                    paymentInstance.Payment_Posting_Date__c = remittanceInstance.Payment_Posting_Date__c;
                } else {
                    paymentInstance.Payment_Posting_Date__c = system.today();
                }
                paymentInstance.Cheque_Payment_Reference_Number__c = remittanceInstance.Cheque_Payment_Reference_Number__c;
                if (wrapRecord.amount != null && wrapRecord.amount != 'null') {
                    paymentInstance.Payment_Amount__c = Decimal.valueOf(wrapRecord.amount);
                }
                paymentInstance.Insolvency_Account__c = wrapRecord.insolvencyAccInstance.Insolvency_Account__c;
                paymentInstance.Remittance__c = remittanceInstance.Id;
                paymentInstance.RecordTypeId = insolvencyPaymentRecordTypeID;
                listInsolvencyPayment.add(paymentInstance);
            }
        }
        try {
            if (!listInsolvencyPayment.isEmpty()) {
                insert listInsolvencyPayment;
            }
        } catch (Exception ex) {
            system.debug('Exception ex: ' + ex);
        }
        InsertUnallocatedPaymentsStriplistBatch instance = new InsertUnallocatedPaymentsStriplistBatch(
            listUnallocatedPayment,
            remittanceInstance,
            'Insolvency'
        );
        database.executeBatch(instance);
        disableSave = true;
        showTable = false;
        Apexpages.addMessage(
            new ApexPages.message(Apexpages.Severity.INFO, 'Your file is being processed. You will receive email once processing is completed.')
        );
        return null;
    }

    public pageReference Cancel() {
        PageReference retURL = new PageReference('/apex/StriplistInsolvencyPaymentUpload?id=' + remittanceInstance.Id);
        retURL.setRedirect(true);
        return retURL;
    }
}