force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>This field is created as a part of CTB Automation and this field will be used to store unique identifier of Insolvency Account which is used by CTB Business user to reference Insolvency account back to SF system.</description>
    <displayFormat>{0000000000}</displayFormat>
    <label>Correlation Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/Insolvency_Error__c.object-meta.xml
<CustomObject>
    <description>An object to store error/exception related to Insolvency flow</description>
    <label>Insolvency Error</label>
    <nameField>
        <displayFormat>IErr-{0000}</displayFormat>
        <label>Insolvency Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Error__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error / Exception Details</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Error / Exception Details</inlineHelpText>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insolvency_Error__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Insolvency Account record</description>
    <inlineHelpText>Related Insolvency Account record</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Errors</relationshipLabel>
    <relationshipName>Insolvency_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsolvencyAccountStatusUpdateBatch.cls
/**
 * @description       : Batch class to update Insolvency status on Insolvency accounts
 * @author            : adesh.ikhar@canaccede.com
 * @last modified on  : 01-28-2025
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class InsolvencyAccountStatusUpdateBatch implements Database.Batchable<SObject> {
    Set<String> correlationIdSet = new Set<String>();
    public InsolvencyAccountStatusUpdateBatch(Set<String> correlationIdSet) {
        this.correlationIdSet = correlationIdSet;
    }

    public Database.Querylocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id FROM Insolvency_Account__c WHERE Correlation_Id__c IN :correlationIdSet AND Insolvency_Status__c = \'New\'');
    }

    public void execute(Database.BatchableContext bc, List<Insolvency_Account__c> records) {
        for (Insolvency_Account__c acc : records) {
            acc.Insolvency_Status__c = 'For Owner Review';
        }
        try {
            Database.update(records);
        } catch (DmlException de) {
            System.debug('Exception during record updation ' + de.getDmlMessage(0));
            Insolvency_Error__c error = new Insolvency_Error__c(Error__c = de.getDmlMessage(0));
            insert error;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}