force-app/main/default/objects/Agency_User__c/Agency_User__c.object-meta.xml
<CustomObject>
    <label>Agency User</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Agency User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_User__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>User email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User email address</inlineHelpText>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agency_User__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAgencyPortalUtil.cls
/**************************************************************************************************      
 *  @description : Test class for AgencyPortalUtil class 
 *  @author : A5E Consulting
 *  @date : 07/13/2022
 
 *************************************************************************************************/
@isTest
private class TestAgencyPortalUtil{
    // Test data for testgetUserNamefromEmail test method
    @TestSetup
    static void dataSetup() {
    
        Test.startTest();
        
        Agency_User__c agusr = new Agency_User__c();       
        agusr.Email_Address__c = 'test1@mymail.com';
        agusr.Role__c = 'Regular User'; 
        agusr.First_Name__c='FirstName';
        agusr.Last_Name__c ='LastName';
        
        AgencyUserTriggerHandler.runAgencyUserTrigger = false;
        insert agusr;
        AgencyUserTriggerHandler.runAgencyUserTrigger = true;
        
        Test.stopTest();
    }
    
    @isTest
    public static void testgetUserNamefromEmail() {
        Test.startTest();
        
        //Agency user exists
        system.assertEquals('FirstName LastName', AgencyPortalUtil.getUserNamefromEmail('test1@mymail.com'));
        
        //Agency user does not exist
        system.assertEquals('test2@mymail.com', AgencyPortalUtil.getUserNamefromEmail('test2@mymail.com'));
        
        Test.stopTest();
    }    
}