force-app/main/default/objects/Agency_User__c/Agency_User__c.object-meta.xml
<CustomObject>
    <label>Agency User</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Agency User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_User__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>User email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User email address</inlineHelpText>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agency_User__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Agency Users</relationshipLabel>
    <relationshipName>Agency_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPortalAgencyUserProcessor.cls
@isTest
public class TestPortalAgencyUserProcessor {
     public static testMethod void testPortalAgencyUser(){        
        RestRequest req = new RestRequest ();
        RestResponse res = new RestResponse();
        system.debug('req: '+req);
        String jsonTokenResponse = '{"First_Name":"Test", "Last_Name": "Test Agency User",'+
                                    '"Created_By": "TestABC","Is_Active": "True","Last_Modified_By": "test",'+
                                    '"Email_Address": "test@gmail.com","Role": "Regular User","Placement_Identifier":null}';      
                                    
        system.debug('JSONPaymentTransaction: '+jsonTokenResponse);
        req.requestBody  = Blob.valueof(jsonTokenResponse);
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        PortalAgencyUserProcessor.postAgencyUser();
    }
    
    public static testMethod void testPortalAgencyUtil(){  
        
        Placement__c plcmnt= new Placement__c();      
        plcmnt.Name='89';       
        insert plcmnt;
        
        Agency_User__c agusr = new Agency_User__c();       
        agusr.Placement__c = plcmnt.id;
        agusr.Email_Address__c = 'test@gmail.com';
        agusr.Role__c = 'Regular User';       
        AgencyUserTriggerHandler.runAgencyUserTrigger = false;
        insert agusr;
        AgencyUserTriggerHandler.runAgencyUserTrigger = true;
        
        map<String, String> paramMap = new map<String, String>();
        paramMap.put('First_Name', 'Test');
        paramMap.put('Last_Name','Test Agency User');
        paramMap.put('Created_By','TestABC');
        paramMap.put('Last_Modified_By','test');
        paramMap.put('Email_Address','test@gmail.com');
        paramMap.put('Role','Regular User');
        paramMap.put('Placement_Identifier',null);
        paramMap.put('Is_Active','True');
        PortalAgencyUserProcessorUtil.processAgencyUser(paramMap, agusr);
    }

}