force-app/main/default/objects/Deposit_Accounts__c/Deposit_Accounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deposit Accounts</label>
</CustomObject>

force-app/main/default/objects/Deposit_Accounts__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/CCS_Account__c.field-meta.xml
<CustomField>
    <fullName>CCS_Account__c</fullName>
    <description>CCS Account</description>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distressed_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GoEasy_CCS_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <description>Cheque / Payment Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cheque / Payment Reference Number</inlineHelpText>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Dividend__c.field-meta.xml
<CustomField>
    <fullName>Dividend__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dividend</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/FairShare_Amount__c.field-meta.xml
<CustomField>
    <fullName>FairShare_Amount__c</fullName>
    <description>FairShare Amount = Gross_Payment_Amount__c * CCS_Account__r.FairShare_Percentage__c</description>
    <inlineHelpText>FairShare Amount = Gross_Payment_Amount__c * FairShare_Percentage__c on CCS Account</inlineHelpText>
    <label>FairShare Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Payment Remitted</description>
    <inlineHelpText>Is Payment Remitted</inlineHelpText>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Product Account.</description>
    <inlineHelpText>The amount to be applied to the Product Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Product Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Product Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Posting_Month__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Month__c</fullName>
    <defaultValue>TEXT( YEAR(TODAY())) +  IF(MONTH( TODAY())&gt;9, TEXT(MONTH( TODAY() ) ), &apos;0&apos;+TEXT(MONTH( TODAY() ) ))</defaultValue>
    <description>Payment Posting Month</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Reporting Month</inlineHelpText>
    <label>Payment Reporting Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to unallocated payment reocord</description>
    <inlineHelpText>Link to unallocated payment reocord</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/recordTypes/CCS_Dividend_Payment.recordType-meta.xml
<RecordType>
    <fullName>CCS_Dividend_Payment</fullName>
    <active>true</active>
    <description>Payments created by payment processing for CCS</description>
    <label>CCS Dividend Payment</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Cheque_Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Payment_Reference_Number__c</fullName>
    <description>A payment reference number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A payment reference number</inlineHelpText>
    <label>Cheque/ Payment Reference Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Fairshare_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fairshare_Amount__c</fullName>
    <description>Total fairshare amount on the striplist</description>
    <inlineHelpText>Total fairshare amount on the striplist</inlineHelpText>
    <label>Fairshare Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <description>Payment Posting Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Posting Date</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Trustee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trustee Company lookup</description>
    <inlineHelpText>Trustee Company lookup</inlineHelpText>
    <label>Trustee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>012f10000015HcqAAE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Remittance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Store Insolvency Account number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To know whether this is unallocated amount is allocated to some Insolvency Account or not</description>
    <label>Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the generated Deposit Slip</description>
    <inlineHelpText>Link to the generated Deposit Slip</inlineHelpText>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Is_Payment_Remitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment_Remitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if unallocated payment has been remitted back to bank</description>
    <inlineHelpText>To track if unallocated payment has been remitted back to bank</inlineHelpText>
    <label>Is Payment Remitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Store unallocated amount for Remittance</description>
    <label>Unallocated Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Fairshare_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Fairshare_Amount__c</fullName>
    <label>Unallocated Fairshare Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

force-app/main/default/classes/ProcessingUnallocatedProductController.cls
public class ProcessingUnallocatedProductController {

    public Product_Payments__C insolvPay {set;get;}
    public Unallocated_Payment__c unAloccPay{set;get;}
    public Boolean isAllocated {set;get;}
    Map<String, Deposit_Accounts__c> depositAccountMap = Deposit_Accounts__c.getAll();
    public Deposit_Accounts__c depositAcc {set;get;}
    
    public ProcessingUnallocatedProductController(ApexPages.StandardController controller){
        insolvPay = new Product_Payments__C();
        if(ApexPages.currentPage().getParameters().get('insolvAcc') != null)
        insolvPay.CCS_Account__c = ApexPages.currentPage().getParameters().get('insolvAcc');
        unAloccPay = [SELECT id, Remittance__c, Remittance__r.Cheque_Payment_Reference_Number__c, Remittance__r.Payment_Posting_Date__c, 
                      Allocated__c, Unallocated_Amount__c, Account_Number__c, Deposit_Slip__c, Is_Payment_Remitted__c, Cheque_Number__c, Payment_Posting_Date__c, deposit_Slip__r.createdDate,
                      Unallocated_Fairshare_Amount__c
                      FROM Unallocated_Payment__c WHERE ID=: ApexPages.currentPage().getParameters().get('id')];
        if(unAloccPay.Allocated__c){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Unallocated payment is allocated to another CCS Account '+ unAloccPay.Account_Number__c);
             ApexPages.addMessage(myMsg);
        }
        if(unAloccPay.Is_Payment_Remitted__c){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Unallocated payment is remitted back to bank ');
             ApexPages.addMessage(myMsg);
        }
    }
    
    public void save(){ 
        insolvPay.Dividend__C = unAloccPay.Remittance__c;
        insolvPay.Payment_Amount__c = unAloccPay.Unallocated_Amount__c;
        if(unAloccPay.Remittance__c == null){
        insolvPay.Payment_Posting_Date__c = unAloccPay.Payment_Posting_Date__c;
        insolvPay.Cheque_Number__c = unAloccPay.Cheque_Number__c;
        }else{
        insolvPay.Payment_Posting_Date__c = unAloccPay.Remittance__r.Payment_Posting_Date__c;
        insolvPay.Cheque_Number__c = unAloccPay.Remittance__r.Cheque_Payment_Reference_Number__c;     
        }
        insolvPay.Deposit_Slip__c = unAloccPay.Deposit_Slip__c;
        insolvPay.Unallocated_Payment__c = unAloccPay.id;
        insolvPay.FairShare_Amount__c = unAloccPay.Unallocated_Fairshare_Amount__c;
        String month = ((System.today()).Month() < 10 ? ('0' + (System.today()).Month()) : (''+(System.today()).Month()));
        insolvPay.Payment_Posting_Month__c = ''+ (System.today()).Year()+month;
        
        insolvPay.recordTypeid =  [select id from RecordType where SobjectType = 'Product_Payments__c' and developername = 'CCS_Dividend_Payment'].id;
        
        Product__c insolAcc = [select id, name, Portfolio_Group_Name__c 
                                         from Product__c where id = :insolvPay.CCS_Account__C];
        System.debug(insolAcc);  
        
        if(insolAcc.Portfolio_Group_Name__c != null){
            insolvPay.Deposit_Account_Type__c = (insolAcc.Portfolio_Group_Name__c).subString(0,3);
        }else{
            insolvPay.Deposit_Account_Type__c = 'CIML';
        }
        try{
            Application_Config_Settings__c appConfig = Application_Config_Settings__c.getOrgDefaults();
            appConfig.Do_Not_Run_Payment_Validation__c = true;
            update appConfig;
            insert insolvPay;
            
            System.debug(insolAcc);
            
            appConfig.Do_Not_Run_Payment_Validation__c = false;
            update appConfig;
            
            unAloccPay.Account_Number__c = [SELECT Name FROM Product__c WHERE ID =:insolvPay.CCS_Account__c LIMIT 1].Name;
            unAloccPay.Allocated__c = true;
            update unAloccPay;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'CCS Account is allocated now.'));
            
            DateTime dT = System.now();
            Date todayDate = date.newinstance(dT.year(), dT.month(), dT.day());
            
            if(null != unAloccPay.Deposit_Slip__c){
                
                DateTime dateTimeValue = unAloccPay.deposit_Slip__r.createdDate;
                Date createdDatewithoutTime = date.newinstance(dateTimeValue.year(), dateTimeValue.month(), dateTimeValue.day());
            
                if(createdDatewithoutTime <> todayDate ){
                    return;
                }
            }
            
            List<Remittance__c> remList = [select id, name, Deposit_Account_Name__c from Remittance__C where id = :unAloccPay.Remittance__c];
            Remittance__c rem = new Remittance__c();
            if(remList.size()==1){
                rem = remList.get(0);
            }else{
                return;
            }
                
            
            
            List<Unallocated_payment__C> listUnallocPay = [select id from Unallocated_payment__C where Allocated__c = FALSE and Remittance__c = :rem.id ];
            
            List<AggregateResult> listAggregateResults = [select count(id) total, Deposit_Account_Type__c 
                                              from Product_Payments__C
                                              where Dividend__c = :unAloccPay.Remittance__c
                                              group by Deposit_Account_Type__c ];
            
            List<String> listDepositAccountName = new List<String>();
            for(AggregateResult aggrRecord : listAggregateResults ){
                listDepositAccountName.add((String)aggrRecord.get('Deposit_Account_Type__c'));
            }
            system.debug('Deposit Slip : ' + listAggregateResults + listAggregateResults.size());
            system.debug('Deposit Name : ' + listDepositAccountName + listDepositAccountName.size());
            system.debug('UnallocPay Size : ' + listUnallocPay + listUnallocPay.size());
            
            if(listUnallocPay.size() == 0 && listAggregateResults.size() == 0){
                //Do Nothing
            }else if(listUnallocPay.size() > 0 && listAggregateResults.size() == 0){
                rem.Deposit_Account_Name__c = insolvPay.Deposit_Account_Type__c;
            }else if(listUnallocPay.size() > 0 && listAggregateResults.size() == 1){
                if(listDepositAccountName.contains('CCL') || listDepositAccountName.contains('CLP') ||
                   listDepositAccountName.contains('CIA') || listDepositAccountName.contains('CAL') ||
                   listDepositAccountName.contains('CIH')){
                    rem.Deposit_Account_Name__c = 'CIML';
                }else if(listDepositAccountName.contains('ETC') || listDepositAccountName.contains('AFF') ||
                        listDepositAccountName.contains('AAL') || listDepositAccountName.contains('AFL')){
                    rem.Deposit_Account_Name__c = 'AFSI';
                }
                
            }else if(listUnallocPay.size() > 0 && listAggregateResults.size() > 1){
                
                if(listDepositAccountName.contains('CIH')){
                    if(listDepositAccountName.contains('CCL') || listDepositAccountName.contains('CLP') ||
                      listDepositAccountName.contains('CIA') || listDepositAccountName.contains('CAL') ){
                        rem.Deposit_Account_Name__c = 'CIML';
                    }else if(listDepositAccountName.contains('ETC') || listDepositAccountName.contains('AFF') ||
                            listDepositAccountName.contains('AAL') || listDepositAccountName.contains('AFL')){
                        rem.Deposit_Account_Name__c = 'AFSI';
                    }
                }else if(listDepositAccountName.contains('CCL') || listDepositAccountName.contains('CLP') ||
                        listDepositAccountName.contains('CIA') || listDepositAccountName.contains('CAL') ){
                    rem.Deposit_Account_Name__c = 'CIML';
                }else if(listDepositAccountName.contains('ETC') || listDepositAccountName.contains('AFF') ||
                        listDepositAccountName.contains('AAL') || listDepositAccountName.contains('AFL')){
                    rem.Deposit_Account_Name__c = 'AFSI';
                }
            }else if(listUnallocPay.size() == 0 && listAggregateResults.size() == 1){
                if(listDepositAccountName[0] == insolvPay.Deposit_Account_Type__c){
                    rem.Deposit_Account_Name__c = insolvPay.Deposit_Account_Type__c;
                }else {
                    //No Changes
                }
            }else if(listUnallocPay.size() == 0 && listAggregateResults.size() > 1){
                if(listDepositAccountName.contains('CCL') && listDepositAccountName.contains('CLP')){
                    rem.Deposit_Account_Name__c = 'CCL';
                }else if(listDepositAccountName.contains('ETC') && listDepositAccountName.contains('AFF')){
                    rem.Deposit_Account_Name__c = 'ETC';
                }else
                if(listDepositAccountName.contains('CIH')){
                    if(listDepositAccountName.contains('CCL') || listDepositAccountName.contains('CLP') ||
                      listDepositAccountName.contains('CIA') || listDepositAccountName.contains('CAL') ){
                        rem.Deposit_Account_Name__c = 'CIML';
                    }else if(listDepositAccountName.contains('ETC') || listDepositAccountName.contains('AFF') ||
                            listDepositAccountName.contains('AAL') || listDepositAccountName.contains('AFL')){
                        rem.Deposit_Account_Name__c = 'AFSI';
                    }
                }else if(listDepositAccountName.contains('CCL') || listDepositAccountName.contains('CLP') ||
                        listDepositAccountName.contains('CIA') || listDepositAccountName.contains('CAL') ){
                    rem.Deposit_Account_Name__c = 'CIML';
                }else if(listDepositAccountName.contains('ETC') || listDepositAccountName.contains('AFF') ||
                        listDepositAccountName.contains('AAL') || listDepositAccountName.contains('AFL')){
                    rem.Deposit_Account_Name__c = 'AFSI';
                }
            }
            
            Application_Config_Settings__c acs = Application_Config_Settings__c.getOrgDefaults();
            system.debug('acs.Final_Deposit_Slip__c : ' + acs.Final_Deposit_Slip__c );
            if(acs.Final_Deposit_Slip__c == null || acs.Final_Deposit_Slip__c <= system.TODAY()){
                if(null != rem.Deposit_Account_Name__c ){
                    depositAcc = depositAccountMap.get(rem.Deposit_Account_Name__c);
                }else{
                    depositAcc = depositAccountMap.get('CIML');
                } 
                 rem.Bank_Account_Number__c = depositAcc.Account_Number__c;
                 rem.Transit_Code__c = depositAcc.Transit_Number__c;
                 rem.Entity_Name__c = depositAcc.Entity_Name__c;
                 rem.Deposit_Account_Name__c = depositAcc.Name;
                
                acs.Run_Remittance_Validation__c = false;
                update acs;
                update rem;
                acs.Run_Remittance_Validation__c = true;
                update acs;
            }
        }catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, ex.getMessage())); 
            system.debug(ex);       
        }
    }
}