force-app/main/default/objects/Case/recordTypes/Remittance.recordType-meta.xml
<RecordType>
    <fullName>Remittance</fullName>
    <active>true</active>
    <businessProcess>Remittance</businessProcess>
    <description>Remittance</description>
    <label>Remittance</label>
</RecordType>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remittance Record Reference</description>
    <inlineHelpText>Remittance Record Reference</inlineHelpText>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Unallocated payment record</description>
    <inlineHelpText>Lookup field to Unallocated payment record</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/recordTypes/Remittance.recordType-meta.xml
<RecordType>
    <fullName>Remittance</fullName>
    <active>true</active>
    <description>Remittance Insolvency Payments</description>
    <label>Remittance</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned To</description>
    <inlineHelpText>Assigned To</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Dividends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Email_to_Case_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Email_to_Case_Reference_Number__c</fullName>
    <description>Email to Case Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email to Case Reference Number</inlineHelpText>
    <label>Email to Case Reference Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/TestDividendsDelete.cls
@isTest
public class TestDividendsDelete {

    @isTest
    static void testDeleteDividend() {
                   
        RecordType remittanceRecType = [Select Id 
                                            from RecordType 
                                            where 
                                            SObjectType = 'Case' and 
                                            DeveloperName = 'Remittance'];
        
        //Case record creation
        Case caseObj = new Case();
        caseObj.SuppliedEmail = 'abc@testOrg.com';
        caseObj.Assigned_To__c = UserInfo.getUserId();
        caseObj.recordTypeId = remittanceRecType.Id;
        caseObj.Status = 'New';
        insert caseObj;
        
        //EmailMessage record creation
        EmailMessage emailMsg =  new EmailMessage();
        emailMsg.relatedToid = caseObj.Id;
        emailMsg.TextBody = 'Test Email';
        emailMsg.FromAddress = 'abc@gmail.com';
        emailMsg.ToAddress = 'xyz@gmail.com';
        insert emailMsg;

        //Attachment record creation
        Attachment att = new Attachment();
        att.parentId = emailMsg.Id;
        att.Body = Blob.valueOf('Test Attach');
        att.Name= 'Test';
        insert att;
        
        //Remittance record creation
        Remittance__c remittance1 = new Remittance__c();
        remittance1.Status__c = 'New';
        remittance1.Email_to_Case_Reference_Number__c = caseObj.Id;
        insert remittance1;
        
        //Insolvency Record
        Insolvency__c insolv1 = new Insolvency__c();
        insolv1.Name = '12456780';
        insert insolv1;
        
        //Insolvency Account Record
        Insolvency_Account__c insAcc1 = new Insolvency_Account__c();
        insAcc1.Insolvency_Status__c = 'For Owner Review';
        insAcc1.Claim_Type__c = 'Unsecured';
        insAcc1.Insolvency__c = insolv1.id;
        insert insAcc1;        
        
        //Insolvency Payments
        Insolvency_Payment__c payment1 = new Insolvency_Payment__c();
        payment1.Remittance__c = remittance1.Id;
        payment1.Insolvency_Account__c = insAcc1.Id;
        insert payment1;
               
        //Unallocated Payments
        Unallocated_Payment__c payment2 = new Unallocated_Payment__c();
        payment2.Remittance__c = remittance1.Id;
        insert payment2;
        
        ApexPages.currentPage().getParameters().put('id', remittance1.Id);
        
        // Create a StandardController for the Remittance__c object
        ApexPages.StandardController sc = new ApexPages.StandardController(remittance1);
        
        // Instantiate the DividendsDelete class
        DividendsDelete controller = new DividendsDelete(sc);
         
        // Call the deleteDividend method
        DividendsDelete.deleteDividend();
        DividendsDelete.closePopup();
   }
 
@isTest
    static void testExceptionDeleteDividend() {                      
        ApexPages.currentPage().getParameters().put('id', '111111111111111');
         
        // Call the deleteDividend method
        DividendsDelete.deleteDividend();
    }
}