force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <label>Dividends</label>
    <nameField>
        <displayFormat>IDiv-{00000}</displayFormat>
        <label>Dividends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/Cheque_Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Payment_Reference_Number__c</fullName>
    <description>A payment reference number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A payment reference number</inlineHelpText>
    <label>Cheque/ Payment Reference Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <description>Payment Posting Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Posting Date</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Payment Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Striplist_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Striplist_User_ID__c</fullName>
    <description>ID if the user who uploaded the striplist for parsing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ID if the user who uploaded the striplist for parsing</inlineHelpText>
    <label>Striplist User ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Unallocated_Payment_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment_Processing_Status__c</fullName>
    <label>Unallocated Payment Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Unallocated_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payments_Amount__c</fullName>
    <label>Unallocated Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/Unallocated_Payments_Count__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payments_Count__c</fullName>
    <label>Unallocated Payments Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Store Insolvency Account number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Created_by_Striplist_Parsing__c.field-meta.xml
<CustomField>
    <fullName>Created_by_Striplist_Parsing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to set to true when payment is created by Striplist parsing</description>
    <inlineHelpText>Checkbox to set to true when payment is created by Striplist parsing</inlineHelpText>
    <label>Created by Striplist Parsing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Debtor_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Debtor / Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Estate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Remittance__c.field-meta.xml
<CustomField>
    <fullName>Remittance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dividends</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Store unallocated amount for Remittance</description>
    <label>Unallocated Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/InsertUnallocatedPaymentsStriplistBatch.cls
/**************************************************************************************************
 *
 *  Class:
 *
 *  @description : Batch class to insert Unallocated insolvency payments from Striplist parsing
 *  @author : A5E Consulting
 *  @date : 19/10/2020
 *
 *************************************************************************************************/

public class InsertUnallocatedPaymentsStriplistBatch implements Database.Batchable<StriplistUtil.paymentRecordsWrapper>, Database.Stateful {
    String unallocatedPaymentType;
    String exceptionMessage;
    ID unallocatedPaymentRecordTypeID;
    Integer unallocatedCount = 0;
    Decimal unallocatedAmount = 0;

    StriplistUtil striplistUtilInstance;

    public Remittance__c dividendRecord = new Remittance__C();

    list<Attachment> unallocatedPayment = new List<Attachment>();
    list<StriplistUtil.paymentRecordsWrapper> paymentRecordList = new List<StriplistUtil.paymentRecordsWrapper>();

    //Constructor
    public InsertUnallocatedPaymentsStriplistBatch(
        List<StriplistUtil.PaymentRecordsWrapper> listUnallocatedPayment,
        Remittance__C dividendRecord,
        String UnAllocatedType
    ) {
        unallocatedPaymentType = UnAllocatedType;
        this.paymentRecordList.addAll(listUnallocatedPayment);
        this.dividendRecord = dividendRecord;
        unallocatedPaymentRecordTypeID = Schema.SObjectType.Unallocated_Payment__c.getRecordTypeInfosByName().get('Insolvency').getRecordTypeId();
    }

    //Start method to return list of parsed payments wrapper
    public List<StriplistUtil.paymentRecordsWrapper> start(Database.BatchableContext bc) {
        striplistUtilInstance = new StriplistUtil();
        return paymentRecordList;
    }

    //execute method to insert Unallocated Payments
    public void execute(Database.BatchableContext BC, List<StriplistUtil.paymentRecordsWrapper> wrapList) {
        List<StriplistUtil.paymentRecordsWrapper> unallocatedWrapList = new List<StriplistUtil.paymentRecordsWrapper>();
        List<Unallocated_Payment__c> listUnallocatedPayment = new List<Unallocated_Payment__c>();
        for (StriplistUtil.paymentRecordsWrapper wrapRecord : wrapList) {
            Unallocated_Payment__c paymentInstance = new Unallocated_Payment__c();
            paymentInstance.Created_by_Striplist_Parsing__c = true;
            paymentInstance.Remittance__C = dividendRecord.Id;
            paymentInstance.Account_Number__c = wrapRecord.accountNumber;
            paymentInstance.Estate_Number__c = wrapRecord.estateNumber;
            paymentInstance.Unallocated_Amount__c = Decimal.valueOf(wrapRecord.amount);
            paymentInstance.Debtor_Name__c = wrapRecord.debtorName;
            unallocatedAmount += paymentInstance.Unallocated_Amount__c;
            paymentInstance.Cheque_Number__c = dividendRecord.Cheque_Payment_Reference_Number__c;
            if (dividendRecord.Payment_Posting_Date__c != null) {
                paymentInstance.Payment_Posting_Date__c = dividendRecord.Payment_Posting_Date__c;
            } else {
                paymentInstance.Payment_Posting_Date__c = system.today();
            }
            if (unallocatedPaymentType == 'Insolvency' && String.isNotBlank(unallocatedPaymentRecordTypeID)) {
                paymentInstance.RecordTypeId = unallocatedPaymentRecordTypeID;
            }
            listUnallocatedPayment.add(paymentInstance);
        }
        try {
            insert listUnallocatedPayment;
            unallocatedCount += listUnallocatedPayment.size();
        } catch (Exception ex) {
            system.debug('Exception ex: ' + ex);
            exceptionMessage = ex.getMessage() + ' ' + ex.getStackTraceString();
        }
    }

    //FInish method to update dividend and send email to user
    public void finish(Database.BatchableContext bc) {
        //Update Unallocated payments details in Dividend record
        if (String.isBlank(exceptionMessage)) {
            Remittance__c updatedDividenRecord = new Remittance__c(Id = dividendRecord.Id);
            updatedDividenRecord.Unallocated_Payments_Count__c = unallocatedCount;
            try {
                striplistUtilInstance.assignBankInformation(dividendRecord.Id);
                updatedDividenRecord.Status__c = 'Processed';
                updatedDividenRecord.Payment_Posting_Date__c = system.today();
                updatedDividenRecord.Unallocated_Payment_Processing_Status__c = 'Completed';
                updatedDividenRecord.Unallocated_Payments_Amount__c = unallocatedAmount;
                update updatedDividenRecord;
            } catch (Exception ex) {
                exceptionMessage = ex.getMessage() + ' ' + ex.getStackTraceString();
            }
        }
        //Send process completion email to user
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        //message.toAddresses = new String[] {dividendRecord.User_ID__c};
        message.setTargetObjectId(dividendRecord.Striplist_User_ID__c);
        message.setSaveAsActivity(false);
        message.optOutPolicy = 'FILTER';
        message.subject = 'Unallocated Insolvency Payments Upload Status';
        if (unallocatedPaymentType == 'Insolvency') {
            if (String.isBlank(exceptionMessage)) {
                message.plainTextBody =
                    'Unallocated Insolvency Payments are processed. Please click the link below to view records: \n' +
                    URL.getSalesforceBaseUrl().toExternalForm() +
                    '/' +
                    dividendRecord.Id;
            } else {
                message.plainTextBody =
                    'Unallocated Insolvency Payment Processing failed! \nReason: ' +
                    exceptionMessage +
                    '\n\n' +
                    'Please click the link below to view page :\n' +
                    URL.getSalesforceBaseUrl().toExternalForm() +
                    '/' +
                    dividendRecord.Id;
            }
        }
        if (!Test.isRunningTest()) {
            Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{ message };
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            if (results[0].success) {
                System.debug('The email was sent successfully.');
            } else {
                System.debug('The email failed to send: ' + results[0].errors[0].message);
            }
        }
    }
}