force-app/main/default/objects/Account_Judgment__c/Account_Judgment__c.object-meta.xml
<CustomObject>
    <description>To maintain many to many relationship between Product and Judgment objects</description>
    <label>Account-Judgment</label>
    <nameField>
        <displayFormat>ACC-JD-{000000}</displayFormat>
        <label>Account-Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Judgment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Judgment__c/fields/Judgment__c.field-meta.xml
<CustomField>
    <fullName>Judgment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Judgment ID</label>
    <referenceTo>Judgment__c</referenceTo>
    <relationshipLabel>Account-Judgment</relationshipLabel>
    <relationshipName>Account_Judgment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Judgment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Account-Judgment</relationshipLabel>
    <relationshipName>Account_Judgment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment__c/Judgment__c.object-meta.xml
<CustomObject>
    <description>To store the data for Judgement data</description>
    <label>Judgment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/fields/Collection_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Agency Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgment__c/fields/External_Collection_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>External_Collection_Agency_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>External Collection Agency Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgment__c/recordTypes/Judgment.recordType-meta.xml
<RecordType>
    <fullName>Judgment</fullName>
    <active>true</active>
    <label>Judgment</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CorrectJudgmentIdentifierBatch.cls
/**
 * @description       : This is a Batch class for Judgment object to correct Collection Agency identifier based on related Products
 * @author            : adesh.ikhar@canaccede.com
 * @group             :
 * @last modified on  : 03-20-2024
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class CorrectJudgmentIdentifierBatch implements Database.Batchable<sObject> {
    public static final string SEPARATOR = 'A';
    public static final string UNPLACED = 'unplaced';

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator('SELECT Id, Product__c, Judgment__C FROM Account_Judgment__c');
    }

    public void execute(Database.BatchableContext bc, List<Account_Judgment__c> prodJudgList) {
        Map<Id, String> placementIDMap = new Map<Id, String>();
        Set<Id> judgmentSet = new Set<Id>();
        Set<Id> productSet = new Set<Id>();
        Map<Id, Judgment__C> judgmentMap = new Map<Id, Judgment__C>();
        Map<Id, Product__C> productMap = new Map<Id, Product__C>();

        for (Account_Judgment__c prodJudg : prodJudgList) {
            judgmentSet.add(prodJudg.Judgment__C);
            productSet.add(prodJudg.Product__c);
        }

        //Fetch all related products
        //Fetch all accounts judgments related to Judgments
        List<Account_Judgment__c> listAccountJudgment = [SELECT Id, Judgment__C, Product__c FROM Account_Judgment__c WHERE Judgment__C IN :judgmentSet];
        for (Account_Judgment__c prodJudg : listAccountJudgment) {
            judgmentSet.add(prodJudg.Judgment__C);
            productSet.add(prodJudg.Product__c);
        }

        List<Product__c> listProduct = [SELECT Id, Collection_Agency__C FROM Product__C WHERE Id IN :productSet];
        for (Account_Judgment__c prodJudg : listAccountJudgment) {
            for (Product__C prod : listProduct) {
                if (prod.Id == prodJudg.Product__C) {
                    productMap.put(prodJudg.Id, prod);
                }
            }
        }

        //recalculate the Collection agency identifer for all related judgmets
        Map<Id, String> judgmentUpdate = new Map<Id, String>();
        String collectionAgencyidentifier = '';
        for (Account_Judgment__c prodJudg : listAccountJudgment) {
            Product__c prod = productMap.get(prodJudg.Id);
            if (prod == null) {
                continue;
            }
            if (prod.Collection_Agency__c == null || prod.Collection_Agency__c == 9999) {
                collectionAgencyidentifier = SEPARATOR + UNPLACED + SEPARATOR;
            } else {
                collectionAgencyidentifier = SEPARATOR + prod.Collection_Agency__C + SEPARATOR;
            }

            String identifierList = '';
            identifierList = judgmentUpdate.get(prodJudg.Judgment__c);
            if (String.isBlank(identifierList)) {
                identifierList = collectionAgencyidentifier;
                judgmentUpdate.put(prodJudg.Judgment__c, identifierList);
            } else if ((identifierList).contains(collectionAgencyidentifier)) {
                //Do Nothing
            } else {
                identifierList += collectionAgencyidentifier;
                judgmentUpdate.put(prodJudg.Judgment__c, identifierList);
            }
        }

        //Save the Judgments
        List<Judgment__C> listJudgment = new List<Judgment__c>();
        if (judgmentUpdate.size() > 0) {
            for (Id judgmentID : judgmentUpdate.keySet()) {
                Judgment__c judge = new Judgment__c();
                judge.Collection_Agency_Identifier__c = judgmentUpdate.get(judgmentID);
                //Update the external Collection Agency Identifier for Agency Group Sharing Rule
                judge.External_Collection_Agency_Identifier__c = judge.Collection_Agency_Identifier__c.replace('A68A', '')
                    .replace('A6A', '')
                    .replace(SEPARATOR + UNPLACED + SEPARATOR, '')
                    .replace(',', '');
                judge.Id = judgmentID;
                if (null != judge.Id) {
                    listJudgment.add(judge);
                }
            }
            JudgmentTriggerHandler.runJudgmentTrigger = false;
            update listJudgment;
            JudgmentTriggerHandler.runJudgmentTrigger = true;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}