force-app/main/default/objects/Account_Judgment__c/Account_Judgment__c.object-meta.xml
<CustomObject>
    <description>To maintain many to many relationship between Product and Judgment objects</description>
    <label>Account-Judgment</label>
    <nameField>
        <displayFormat>ACC-JD-{000000}</displayFormat>
        <label>Account-Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Judgment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Judgment__c/fields/Judgment__c.field-meta.xml
<CustomField>
    <fullName>Judgment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Judgment ID</label>
    <referenceTo>Judgment__c</referenceTo>
    <relationshipLabel>Account-Judgment</relationshipLabel>
    <relationshipName>Account_Judgment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Judgment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Account-Judgment</relationshipLabel>
    <relationshipName>Account_Judgment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Judgment__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <formula>Product__r.Originating_Creditor__c</formula>
    <label>Seller</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Custom_Setting__c/fields/Contact_Counter_Code__c.field-meta.xml
<CustomField>
    <fullName>Contact_Counter_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Counter Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Collection_Custom_Setting__c/fields/Run_Task_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Task_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Task Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Distress_Setting__c/Distress_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Distress Setting</label>
</CustomObject>

force-app/main/default/objects/Distress_Setting__c/fields/Distressed_Task_Eligible_Objects__c.field-meta.xml
<CustomField>
    <fullName>Distressed_Task_Eligible_Objects__c</fullName>
    <description>Distressed Task Eligible Objects</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Distressed Task Eligible Objects</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docomotion_Custom_Setting__c/Docomotion_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Docomotion Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Docomotion_Custom_Setting__c/fields/Document_type_for_objects__c.field-meta.xml
<CustomField>
    <fullName>Document_type_for_objects__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document type for objects</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgment__c/Judgment__c.object-meta.xml
<CustomObject>
    <description>To store the data for Judgement data</description>
    <label>Judgment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/fields/Collection_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Agency Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgment__c/recordTypes/Judgment.recordType-meta.xml
<RecordType>
    <fullName>Judgment</fullName>
    <active>true</active>
    <label>Judgment</label>
</RecordType>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Canaccede_API_User__c.field-meta.xml
<CustomField>
    <fullName>Canaccede_API_User__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Canaccede API User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/No_of_times_contact_collection_in_n_days__c.field-meta.xml
<CustomField>
    <fullName>No_of_times_contact_collection_in_n_days__c</fullName>
    <label>No of times contact collection in n days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/No_of_times_contacted__c.field-meta.xml
<CustomField>
    <fullName>No_of_times_contacted__c</fullName>
    <label>No of times contacted</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/No_of_times_contacted_in_current_cycle__c.field-meta.xml
<CustomField>
    <fullName>No_of_times_contacted_in_current_cycle__c</fullName>
    <label>No of times contacted in current cycle</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Originating_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Originating_Creditor__c</fullName>
    <description>DebtNext-specific</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DebtNext-specific</inlineHelpText>
    <label>Originating Creditor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Seller Customer</description>
    <inlineHelpText>Seller Customer</inlineHelpText>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (Seller)</relationshipLabel>
    <relationshipName>Products4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Object to store the data for Judgement</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Settlement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement__c/fields/Judgment__c.field-meta.xml
<CustomField>
    <fullName>Judgment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Judgment ID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Post-Judgment-Vacated can&apos;t be linked to settlement</errorMessage>
        <filterItems>
            <field>Judgment__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Post-Judgment-Vacated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Judgment__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/fields/Judgment_Collection_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Collection_Agency_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Judgment Collection Agency Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/fields/Product_Collection_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Product_Collection_Agency_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field is used for Distressed Accounts Only</inlineHelpText>
    <label>Product Collection Agency Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement__c/recordTypes/Judgment.recordType-meta.xml
<RecordType>
    <fullName>Judgment</fullName>
    <active>true</active>
    <label>Judgment</label>
</RecordType>

force-app/main/default/objects/Settlement__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/TaskTriggerHandler.cls
/**************************************************************************************************
*
*  Trigger:   
*
*  @description : This is a Trigger Handler Class for Task and Activities object 
*  @author : A5E Consulting
*  @date : 29/08/2016
* 
*************************************************************************************************/

public class TaskTriggerHandler{
    
    public static Loan_ReEngineering__c lrpSetting = Loan_ReEngineering__c.getOrgDefaults();
    public static Collection_Custom_Setting__c collCustSett = Collection_Custom_Setting__c.getOrgDefaults();
    public static Docomotion_Custom_Setting__c docomotionCS = Docomotion_Custom_Setting__c.getOrgDefaults();
    public static Distress_Setting__c distressCS = Distress_Setting__c.getOrgDefaults();
    
    //Changes for: Ticket#309 All Tasks List
    public static void handleBeforeInsert(List<Task> taskNew1){
        
        List<String> DistressedTaskList1 = distressCS.Distressed_Task_Eligible_Objects__c.split(',');
        
        system.debug('Final Distress '+DistressedTaskList1[0]);
        
        if(collCustSett.Run_Task_Trigger__c == true){
        
        
            // Product__c prodList = new Product__c();
            List<String> forObjId = new List<String>();
            for(Task forId : taskNew1){
                
                if(forId.whatID !=Null){
                String objId =forId.whatID;
                
                forObjId.add(objId.substring(0,3));
                
                //forObjId.add(objId.substring(0,objId.length()-15));
                }
                
            }
            
            system.debug('Final OBJ ' +forObjId);
            
            for(Task tskForId : taskNew1){
                for(String disTask : forObjId){
                    if(DistressedTaskList1[0] == disTask){
                        for(Product__c ProductList : [select id,Collection_Agency__c,recordType.name,First_Name__c,Last_Name__c,Originating_Creditor__c from Product__c where id =: tskForId.whatid]){
                            if(ProductList.recordType.Name.contains('Distressed')){
                                for(Task t : taskNew1){
                                    t.Collection_Agency__c = 'A'+ String.ValueOf(ProductList.Collection_Agency__c) +'A';
                                    t.First_Name__c = String.ValueOf(ProductList.First_Name__c);
                                    t.Last_Name__c = String.ValueOf(ProductList.Last_Name__c);
                                    t.Seller__c = String.ValueOf(ProductList.Originating_Creditor__c);
                                }
                            }
                        } 
                    }else if(DistressedTaskList1[1] == disTask){
                        for(Judgment__c judgeList : [select id,Collection_Agency_Identifier__c from Judgment__c where id =: tskForId.whatid]){
                            for(Account_Judgment__c[] AccJudgList : [select id,Judgment__c,Product__r.First_Name__c,Product__r.Last_Name__c,Product__r.Originating_Creditor__c from Account_Judgment__c where Judgment__c =:  tskForId.whatid order by createddate asc]){
                                for(Task t : taskNew1){
                                    t.Collection_Agency__c = String.ValueOf(judgeList.Collection_Agency_Identifier__c);
                                    t.First_Name__c = String.ValueOf(AccJudgList[0].Product__r.First_Name__c);
                                    t.Last_Name__c = String.ValueOf(AccJudgList[0].Product__r.Last_Name__c);
                                    t.Seller__c = String.ValueOf(AccJudgList[0].Product__r.Originating_Creditor__c);
                                    
                                }system.debug('LIST ACCOUNT_judgment '+AccJudgList);
                            }
                        }
                    }else if(DistressedTaskList1[2] == disTask){
                        for(Settlement__c settleList : [select id,Product__c,Judgment__c,Judgment_Collection_Agency_Identifier__c,Product_Collection_Agency_Identifier__c,Product__r.First_Name__c,Product__r.Last_Name__c,Product__r.Originating_Creditor__c from Settlement__c  where id =: tskForId.whatid]){
                            for(Account_Judgment__c[] AccJudgList1 : [select id,Judgment__c,Product__r.First_Name__c,Product__r.Last_Name__c,Product__r.Originating_Creditor__c from Account_Judgment__c where Judgment__c =: settleList.Judgment__c order by createddate asc]){
                                for(Task t : taskNew1){
                                    if(settleList.Product__c != Null){
                                        
                                        t.Collection_Agency__c = String.ValueOf(settleList.Product_Collection_Agency_Identifier__c); 
                                        t.First_Name__c = String.ValueOf(settleList.Product__r.First_Name__c);
                                        t.Last_Name__c = String.ValueOf(settleList.Product__r.Last_Name__c);
                                        t.Seller__c = String.ValueOf(settleList.Product__r.Originating_Creditor__c);
                                        
                                    }else if(settleList.Judgment__c !=Null){
                                        t.Collection_Agency__c = String.ValueOf(settleList.Judgment_Collection_Agency_Identifier__c);
                                        t.First_Name__c = String.ValueOf(AccJudgList1[0].Product__r.First_Name__c);
                                        t.Last_Name__c = String.ValueOf(AccJudgList1[0].Product__r.Last_Name__c);
                                        t.Seller__c = String.ValueOf(AccJudgList1[0].Product__r.Originating_Creditor__c);
                                        
                                        
                                    }
                                }
                            }system.debug('List OF settlement ' +settleList);
                        }
                        
                    }
                }
            }  
        }
        
    }
    
    //Handle after insert
    public static void handleAfterInsert(List<Task> taskNew) {
        
        List<Product__c> listProd = new List<Product__c>();
        List<Account> listAcc = new List<Account>();
        List<String> contactCountCodeList = collCustSett.Contact_Counter_Code__c.split(',');
        
        if(collCustSett.Run_Task_Trigger__c == true){
            
            for(Task tsk : taskNew){
                if(null != tsk.whatid){
                    if(String.valueOf(tsk.whatid).startsWith('a0D') && tsk.status != 'Generated by Docomotion'){
                        Product__c prod = [select id, Delinquency_Cycles__c, Delinquency_Days__c,
                                           No_of_times_contacted__c, No_of_times_contacted_in_current_cycle__c,
                                           No_of_times_contact_collection_in_n_days__c
                                           from Product__c where id =: tsk.whatid];
                        

                        if((tsk.Subject.contains('Send Email')) || (tsk.Subject.contains('Print Email'))){
                            if(null == prod.No_of_times_contacted__c){
                                prod.No_of_times_contacted__c = 1;
                            }else{
                                prod.No_of_times_contacted__c++;
                            }
                            if(null == prod.No_of_times_contact_collection_in_n_days__c){
                                prod.No_of_times_contact_collection_in_n_days__c = 1;
                            }else{
                                prod.No_of_times_contact_collection_in_n_days__c++;
                            }
                            if(prod.Delinquency_Cycles__c > 0){
                                if(null == prod.No_of_times_contacted_in_current_cycle__c ){
                                    prod.No_of_times_contacted_in_current_cycle__c = 1;
                                }else{
                                    prod.No_of_times_contacted_in_current_cycle__c++;
                                }
                            }
                        }
                        if(listProd.contains(prod)){
                            //do nothing    
                        }else{
                            listProd.add(prod);
                        }
                    }else if(String.valueOf(tsk.whatid).startswith('001')){
                        Account acc = [select id,
                                      No_of_times_contacted_for_collection__c,
                                      No_of_times_contact_collection_in_n_days__c, No_of_times_contacted__c
                                      from account where id =: tsk.whatid];
                        
                        if(null == acc.No_of_times_contacted__c){
                            acc.No_of_times_contacted__c = 1;
                        }else{
                            acc.No_of_times_contacted__c++;
                        }
                        if((tsk.Subject.contains('Collection') || (tsk.Type_of_Activity__c == 'Collection'))){
                            for(String contactCode : contactCountCodeList){
                                if(contactCode == tsk.CallClassification1__c){
                                    
                                    if(null == acc.No_of_times_contacted_for_collection__c){
                                        acc.No_of_times_contacted_for_collection__c = 1;
                                    }else{
                                        acc.No_of_times_contacted_for_collection__c++;
                                    }
                                    if(null == acc.No_of_times_contact_collection_in_n_days__c){
                                        acc.No_of_times_contact_collection_in_n_days__c = 1;
                                    }else{
                                        acc.No_of_times_contact_collection_in_n_days__c++;
                                    }
                                    break;
                                }
                            }
                        }
                        
                        if(listAcc.contains(acc)){
                            //do nothing    
                        }else{
                            listAcc.add(acc);
                        }
                    }
                    
                    //for Docomotion to populate document type on attachment
                    //a1c for settlement, a1Y for Judgment and a0D for Product
                    List<String> listwhatIDforObject = docomotionCS.Document_type_for_objects__c.split(',');
                    
                    for(String startValue : listwhatIDforObject ){
                        if(String.valueOf(tsk.whatid).startsWith(startValue)){
                            if(tsk.status == 'Generated by Docomotion' && tsk.subject.contains('Docomotion')){
                                updateDocumentDescription(tsk.id);
                            }
                        }
                    }
                    
                }
            }
            
            ProductTriggerHandler.runProductTrigger = false;
            update listProd;
            ProductTriggerHandler.runProductTrigger = true;
            update listAcc;
            
        }
    }
    
    // Validating current context user
    public static Boolean isCanaccedeAPIUser(){
        String uName = userInfo.getUserName();
        System.debug('uName :'+uName);
        if(uName.equalsIgnoreCase(lrpSetting.Canaccede_API_User__c)){
            return true;
        }
        return false;
    }
    
    //Future method to get documetns generated after task generation 
    @Future
    private static void updateDocumentDescription(Id taskID){
        
        List<ContentDocumentLink> ConDocLnk = new List<ContentDocumentLink>();
        List<ContentDocument> ConDoc = new List<ContentDocument>();
        List<ContentDocument> ConDoctoUpdate = new List<ContentDocument>();
        
        Long startingTime = System.now().getTime(); // Num milliseconds since Jan 1 1970
        Integer delayInMilliseconds = 60000; // 60-second delay
        while (System.now().getTime() - startingTime < delayInMilliseconds)  {
                    // Do nothing until desired delay has passed
        }
        
        Task tsk = [select id, subject, status, whatId, createdDate from Task where id =: taskID];
        ConDocLnk = new List<ContentDocumentLink>();
        ConDoc = new List<ContentDocument>();
        
        dateTime createdDateValueSub = tsk.createdDate.addSeconds(-60);
        system.debug('Created Date : ' + createdDateValueSub);
        dateTime createdDateValueAdd = tsk.createdDate.addSeconds(60);
        system.debug('Created Date : ' + createdDateValueAdd );

        ConDocLnk=[SELECT id,LinkedEntityId,ContentDocumentId,Visibility, ShareType FROM ContentDocumentLink WHERE LinkedEntityId =: tsk.whatid and SystemModstamp <= :createdDateValueAdd and SystemModstamp > :createdDateValueSub]; 
        System.debug('ConDoc : ' + ConDoc);
        
        List <Id> CDIdList = new List <Id> ();
        for (ContentDocumentLink nextCDL : ConDocLnk) 
        {      
            nextCDL.Visibility='AllUsers'; 
            CDIdList.add(nextCDL.ContentDocumentId); 
        }
        
        system.debug('CDIdList : ' + CDIdList);
        system.debug('Created Date : ' + tsk.createdDate);
        
        ConDoc = [SELECT Id, Title, FileType,Description,CreatedDate,LastModifiedDate FROM ContentDocument WHERE Id IN :CDIdList and createdDate <= :createdDateValueAdd and createdDate > :createdDateValueSub];
        System.debug('ConDoc : ' + ConDoc);
        
        if(conDoc.size() > 0){
            ConDoc[0].Description = tsk.subject.split('-')[0];
            
            ConDoctoUpdate.add(ConDoc[0]);
        }
        
        update ConDoctoUpdate;
    }
}