force-app/main/default/objects/NotificationSuccessMessages__c/NotificationSuccessMessages__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NotificationSuccessMessages</label>
</CustomObject>

force-app/main/default/objects/NotificationSuccessMessages__c/fields/NotificationMessage__c.field-meta.xml
<CustomField>
    <fullName>NotificationMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NotificationMessage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <description>Notification Message to be sent to Portal with Work Assignment</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Notification Message to be sent to Portal with Work Assignment</inlineHelpText>
    <label>Notification Message</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <description>Notification Type of Work Assignment for Agency</description>
    <inlineHelpText>Notification Type of Work Assignment for Agency</inlineHelpText>
    <label>Notification Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Payment</fullName>
            </value>
            <value>
                <fullName>Agency Payment</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Recalled Account</fullName>
            </value>
            <value>
                <fullName>Transactions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Placement_Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency_Identifier__c</fullName>
    <description>Placement Agency Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field is used for Distressed Account</inlineHelpText>
    <label>Placement Agency Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Placement_Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency_Name__c</fullName>
    <formula>Placement_Agency__r.Agency_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <description>Task Number</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Task Number</inlineHelpText>
    <label>Task Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Title</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Total_Amount_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Payments__c</fullName>
    <description>Total Amount of Payments</description>
    <inlineHelpText>Total Amount of Payments</inlineHelpText>
    <label>Total Amount of Payments</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CallToNotificationApi.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : This is a Batch class to send Notifications for Direct Payments to Portal
 *  @author : A5E Consulting
 *  @date : 08/07/2022
 
 *************************************************************************************************/
public class CallToNotificationApi implements Database.Batchable<sObject>, Database.AllowsCallouts {
	public NotificationSuccessMessages__c notificationMessage;
    public string TRANSACTIONS = 'Transactions';
    public string ACCOUNT_UPDATES = 'Account Update';
    public string ACCOUNT_STATUS_UPDATES = 'Account Status Update';
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        //Get work assignments created today with Notifictaion Type = Direct Payment
        return Database.getQueryLocator(
            [SELECT ID, Notification_Message__c, Notification_Type__c, Placement_Agency_Name__c,Task_Number__c,
             		Placement_Agency_Identifier__c, Total_Amount_of_Payments__c
             FROM Work_Assignment__c 
             WHERE CreatedDate = TODAY 
             AND ( Notification_Type__c = :TRANSACTIONS 
                  OR Notification_Type__c = :ACCOUNT_UPDATES
                 OR Notification_Type__c = :ACCOUNT_STATUS_UPDATES)
             ORDER BY Task_Number__c]
        );
    }
    
    public void execute(Database.BatchableContext bc, List<Work_Assignment__c> listWorkAssignments){
        //system.debug('listWorkAssignments::'+listWorkAssignments);
        String Title = '';
        String Message = '';
        String Type = '';
        for(Work_Assignment__c workAssignment : listWorkAssignments){
            if(workAssignment.Notification_Type__c == TRANSACTIONS) {
                notificationMessage = NotificationSuccessMessages__c.getInstance('Direct Payment Notification');
                system.debug('notificationMessage::'+notificationMessage);
                system.debug('notificationMessage.Title__c::'+notificationMessage.Title__c);
                system.debug('workAssignment.Placement_Agency_Identifier__c::'+workAssignment.Placement_Agency_Identifier__c);
                system.debug('workAssignment.Placement_Agency_Name__c::'+workAssignment.Placement_Agency_Name__c);
                if(workAssignment.Placement_Agency_Identifier__c != null && workAssignment.Placement_Agency_Name__c != null){
                	//Title = notificationMessage.Title__c.replace('Agency_Number',workAssignment.Placement_Agency_Identifier__c).replace('Agency_Name','(' + workAssignment.Placement_Agency_Name__c +')');
                	Title = notificationMessage.Title__c;
                    //Message = notificationMessage.NotificationMessage__c.replace('Total_Amount',String.valueOf(workAssignment.Total_Amount_of_Payments__c));    
                	Message = notificationMessage.NotificationMessage__c;
                    Type = TRANSACTIONS;
                }
                
            }
            else if(workAssignment.Notification_Type__c == ACCOUNT_UPDATES) {
                if(workAssignment.Placement_Agency_Identifier__c != null && workAssignment.Placement_Agency_Name__c != null){
                    notificationMessage = NotificationSuccessMessages__c.getInstance('Account Updated');
                    //Title = notificationMessage.Title__c.replace('Agency_Number',workAssignment.Placement_Agency_Identifier__c).replace('Agency_Name','(' + workAssignment.Placement_Agency_Name__c +')');
                    Title = notificationMessage.Title__c;
                    Message = notificationMessage.NotificationMessage__c;
                    Type = 'Account';
                }
            } 
            else if(workAssignment.Notification_Type__c == ACCOUNT_STATUS_UPDATES) {
                if(workAssignment.Placement_Agency_Identifier__c != null && workAssignment.Placement_Agency_Name__c != null){
                    notificationMessage = NotificationSuccessMessages__c.getInstance('Account Status Updated');
                    //Title = notificationMessage.Title__c.replace('Agency_Number',workAssignment.Placement_Agency_Identifier__c).replace('Agency_Name','(' + workAssignment.Placement_Agency_Name__c +')');
                    Title = notificationMessage.Title__c;
                    Message = notificationMessage.NotificationMessage__c;
                    Type = 'Account';
                }
            } 
            
            //cal to portal API to send payment notification
            PortalNotificationAPI.sendPaymentNotification(workAssignment.Placement_Agency_Identifier__c, 
                                                                 Type, 
                                                                 Title, workAssignment.Task_Number__c,
                                                                 Message);
		}														 
    }
    
    public void finish(Database.BatchableContext bc){
    	Database.executeBatch(new AgencyPaymentNotificationBatch());
    }    
}