force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PO_Box__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PO_Box__c</fullName>
    <description>Permanent Address PO Box</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Permanent Address PO Box</inlineHelpText>
    <label>Permanent Address PO Box</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PostalCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address PostalCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Province__c</fullName>
    <label>Permanent Address Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_Account_Import_Code__c.field-meta.xml
<CustomField>
    <fullName>Megasys_Account_Import_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys Account Import Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Megasys_Client_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys Client Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Megasys_End_Point__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_Password__c.field-meta.xml
<CustomField>
    <fullName>Megasys_Password__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys Password</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Megasys_User_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>The primary account holder&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s email address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Agreed Payment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <description>The primary account holder&apos;s Social Insurance Number</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s Social Insurance Number</inlineHelpText>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMegasysWSUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Util class for MegaSys
*  @author : A5E Consulting
*  @date : 08/25/2016   

*************************************************************************************************/
@isTest
public class TestMegasysWSUtil{
    
    private static Loan_ReEngineering__c loanReCS;
    private static Application__c app;
    
    static void insertTestData() {
        
        loanReCS = New  Loan_ReEngineering__c();  
        loanReCS.Megasys_Account_Import_Code__c = 'Affirm Term Loan Import';
        loanReCS.Megasys_Client_Number__c = '420';
        loanReCS.Megasys_End_Point__c = 'https://omegasandbox.megasys.net/Client/WebServices/CustomerPortal.asmx';
        loanReCS.Megasys_Password__c = 'testPass';
        loanReCS.Megasys_User_Name__c = 'testUserName';
        loanReCS.Request_Timeout__c=60000;
        insert loanReCS;
        
        //create test Application record
        app = createApplicationTest();
        System.debug('Created Date:' +app.CreatedDate);
    }
    
    public static testmethod void testMegaSysWSUtil() {
        insertTestData();
        MegasysWSUtil.execute(app);
        
        HttpCalloutMock  loginResponse = new MegasysWSUtilReqMock (getLoginBody());
        Test.setMock(HttpCalloutMock.class, loginResponse);
        
        //MegasysWSUtil.getRespoceLogin(app);
        Product__c prod = MegaSysUtilities.createProdRecord(app);
        MegasysWSUtil.getRespoceLogin(app, prod);
        
        HttpResponse resTest = MegasysWSUtil.getXMLSingleNewAccountImport(app, prod, 'jnaslkdandsdas');
        
        MegasysWSUtil.getRespoceLogout(app, prod, 'jnaslkdandsdas');
        MegasysWSUtil.parseAccntImportResponse(createHttpReq(), resTest, app, prod);
        MegasysWSUtil.getDataFromResponse(getLoginBody(),'LoginResult');
    }
    
    //return httprequest
    public static HttpRequest createHttpReq(){
        HttpRequest req=new HttpRequest();
        req.setEndpoint('endPoint');
        req.setMethod('POST');
        req.setBody('jsonBody');
        return req;
    }    
    //return Application record from TestRecordFactory
    public static Application__c createApplicationTest(){
        
        Date testBirthDate = System.today().addYears(-30);
        
        //Create Account
        TestRecordsFactory.TestAccountWrapper accntWrapper = new TestRecordsFactory.TestAccountWrapper();
        accntWrapper.firstName = 'firstName';
        accntWrapper.lastName = 'lastName';
        accntWrapper.email = 'testuser@testOrg.com';
        accntWrapper.sin = 'dummysin'; 
        accntWrapper.birthDate = testBirthDate;     
        Account accnt = TestRecordsFactory.createAccountRecordAndInsert(accntWrapper, true);
        
        //Create Application
        app = New Application__c();
        String appJSON = '{"attributes":{"type":"CasSe","url":"/services/data/v25.0/sobjects/Application__c/500E0000002nH2fIAE"},"CreatedDate":"2012-10-04T17:54:26.000+0000"}'; 
        app = (Application__c) JSON.deserialize(appJSON, Application__c.class );
        app.Home_Owner__c = 'Rent';
        app.Last_Name__c = 'Rent';
        app.First_Name__c = 'Rent';
        app.Permanent_Address_City__c = 'city';
        app.Permanent_Address_PO_Box__c = '1';
        app.Permanent_Address_PostalCode__c = 'S5R5G7';
        app.Permanent_Address_Province__c = 'MB';
        app.Permanent_Address_Street_Name__c = 'Name';
        app.Months_At_Permanent_Address__c = 1;
        app.Years_At_Permanent_Address__c = 1;
        app.Home_Phone__c = '1233211233';
        app.Work_Phone__c = '1233211233';
        app.Cell_Phone__c = '1233211233';
        app.SIN__c = '123';
        app.Email_Address__c = 'test@test.com';
        app.Birth_Date__c = System.today().addYears(-30);
        app.Employment_Years__c = 1;
        app.Employment_Months__c = 1;
        app.Interest_Rate__c = 0;
        app.Number_of_Payments__c = 0;
        app.First_Payment_Amount__c = 0;
        //app.Regular_Payment_Amount__c = 0;
        app.Regular_Payment_Amount__c = 100;
        app.Total_of_Payment__c = 0;
        app.Loan_Start_Date__c = System.today();
        app.Loan_Amount__c = 0;
        app.Permanent_Address_PostalCode__c = 'F3 D3 f4';
        
        insert app;
        return app;
    }
    
    private static String getLoginBody(){
        
        string loginXML = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><LoginResponse xmlns="http://omega.megasys.net/Client/WebServices/"><LoginResult>a0e2e142-124b-42c8-b69c-a8b3bbd4d807</LoginResult></LoginResponse></soap:Body></soap:Envelope>';
        return loginXML;
    }
    
}