force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <inlineHelpText>Application Status</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFSI Scripting</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>CC Creation</fullName>
            </value>
            <value>
                <fullName>CLI Scripting</fullName>
            </value>
            <value>
                <fullName>Completed - CLI</fullName>
            </value>
            <value>
                <fullName>Completed - Loan</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Email-Auth Sent</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Fraud Investigation</fullName>
            </value>
            <value>
                <fullName>Loan Delivery</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Scripting Required</fullName>
            </value>
            <value>
                <fullName>Waiting for Loan Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Loan Docs - Auth Passed</fullName>
            </value>
            <value>
                <fullName>BK/CP No Disch</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Scripting</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Interest Rate Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Lender_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Lender_Approved_Amount__c</fullName>
    <label>Lender Approved Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Verification_Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Verification_Auth_Token__c</fullName>
    <description>Verification Auth Token</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Verification Auth Token</inlineHelpText>
    <label>Verification Auth Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Verification_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Verification_Completion_Date__c</fullName>
    <description>Verification Completion Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Verification Completion Date</inlineHelpText>
    <label>Verification Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Verification_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Verification_Expiration_Date__c</fullName>
    <description>Verification Expiration Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Verification Expiration Date</inlineHelpText>
    <label>Verification Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Verification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Verification_Sent_Date__c</fullName>
    <description>Verification Sent Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Verification Sent Date</inlineHelpText>
    <label>Verification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <description>Verification Status</description>
    <inlineHelpText>Verification Status</inlineHelpText>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Sent – Analyst</fullName>
            </value>
            <value>
                <fullName>Email Sent – System</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/fields/Site_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Profile_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Site Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/fields/Verification_Expiration_Days__c.field-meta.xml
<CustomField>
    <fullName>Verification_Expiration_Days__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Verification Expiration Days</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSendVerificationEmailController.cls
@isTest
public class TestSendVerificationEmailController {
    
    //Variables
    private static Application_Form_Settings__c afSettings;
    private static Application__c noEmailApp;
    private static Application__c elgibleApp;
    
    // App has no email
    static testMethod void testNoEmail() {
        init();
        
        ApexPages.currentPage().getParameters().put('id', noEmailApp.Id);        
        SendVerificationEmailController cntrl = new SendVerificationEmailController();        
        System.assertEquals(false, cntrl.elgibleForEmail);
        System.assertNotEquals(cntrl.NO_EMAIL, cntrl.inelgibleReason);        
        cntrl.invokeEmail();
        
        Application__c newApp = getApplicationById(noEmailApp.Id);        
        System.assertEquals(null, newApp.Verification_Status__c);
        System.assertEquals(null, newApp.Verification_Auth_Token__c);
        System.assertEquals(null, newApp.Verification_Sent_Date__c);
    }
    
    // App elgible for email
    static testMethod void testElgible() {
        init();
        
        ApexPages.currentPage().getParameters().put('id', elgibleApp.Id);        
        SendVerificationEmailController cntrl = new SendVerificationEmailController();  
        cntrl.invokeEmail();        
        System.assertEquals(true, cntrl.elgibleForEmail);       
        
        Application__c newApp = getApplicationById(elgibleApp.Id);        
        System.assertEquals('Email Sent – Analyst', newApp.Verification_Status__c);
        System.assertNotEquals(null, newApp.Verification_Auth_Token__c);
        System.assertNotEquals(null, newApp.Verification_Sent_Date__c);
        System.assertNotEquals(null, newApp.Verification_Expiration_Date__c);
    }
    
   //Custom setting insertion 
   static void init() { 
        afSettings = new Application_Form_Settings__c(
           Site_Profile_Id__c = '00eK0000000MDqzIAG',
           Verification_Expiration_Days__c = '20'
           );
        insert afSettings;
        
        insertTestData();
        initPageRef();
        }
    
    // Application records Insertions
    static void insertTestData(){
        noEmailApp = new Application__c(
            Salutation__c = 'Mr.', 
            First_Name__c = 'No', 
            Last_Name__c = 'Email' 
        );
        insert noEmailApp;
        
        elgibleApp = new Application__c(
            Salutation__c = 'Ms.', 
            First_Name__c = 'Elgible', 
            Last_Name__c = 'Email',
            Email_Address__c = 'ee@test.com',
            Application_Status__c='Analyst Approved',
            Lender_Approved_amount__c = 1234,
            interest_rate__C = 24.99,
            interest_rate_code__c = 'OTB123'
            //Verification_Status__c='Email Sent – Analyst'
            //Verification_Auth_Token__c='7d6349d59afb5fc1172b52bde66bea1c'
    
            );
        insert elgibleApp;
    }
    
    //Update Application record
    static void UpdateTestData(){
       elgibleApp.Verification_Auth_Token__c='7d6349d59afb5fc1172b52bde66bea1c';
        ApplicationTriggerHandler.runApplicationLoadTrigger = false;
        update elgibleApp;
        ApplicationTriggerHandler.runApplicationLoadTrigger = true; 
    }
    
    // Page refering to VF
    static void initPageRef(){ 
        PageReference pageRef = Page.SendVerificationEmail;
        Test.setCurrentPage(pageRef);
    }
    
    //Fetching Application Verification fields
    static Application__c getApplicationById(Id applicationId) {
        List<Application__c> applications = [
            SELECT Id, Verification_Sent_Date__c, Verification_Status__c, Verification_Auth_Token__c, Verification_Expiration_Date__c, Verification_Completion_Date__c 
            FROM Application__c WHERE Id =: applicationId
        ];
    
        return (applications.size() > 0) ? applications[0] : null;
    }
}