force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit_Slip__c/Deposit_Slip__c.object-meta.xml
<CustomObject>
    <description>View the deposit slips for today generated in previous step/tab - &quot;Generate Deposit Slip&quot;</description>
    <label>Deposit Slip</label>
    <nameField>
        <displayFormat>DS-{000}</displayFormat>
        <label>Deposit Slip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Slips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Deposit_Slip__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Slip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the generated Deposit Slip</description>
    <inlineHelpText>Link to the generated Deposit Slip</inlineHelpText>
    <label>Deposit Slip</label>
    <referenceTo>Deposit_Slip__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHandler.cls
/**************************************************************************************************
*
*  Trigger:   
*
*  @description : This is a Trigger Handler Class for Attachment object 
*  @author : A5E Consulting
*  @date : 10/06/2016
* 
*************************************************************************************************/

public class AttachmentTriggerHandler{
    
    //Handle Befor Delete
    public static void handleBeforeDelete(List<Attachment> oldList){
        
        Profile profileInfo = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() limit 1];
        
        //Loan re-engineering
        if('System Administrator' != profileInfo.Name && 'CFG - Application Admin' != profileInfo.Name ){
            for(Attachment attach : oldList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Application__C.sObjectType || 
                       attach.ParentId.getSObjectType() == Product__c.sObjectType ||
                       attach.ParentId.getSObjectType() == Funding_Batch__c.sObjectType ||
                       attach.ParentId.getSObjectType() == Deposit_Slip__c.sObjectType){
                           attach.ParentId.addError('You can not delete an Attachment from Application, Product and Funding Batch Records');
                       }
                }
            }
        }
        
        //Payment Processing
        if('System Administrator' != profileInfo.Name){
            for(Attachment attach : oldList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Deposit_Slip__c.sObjectType){
                           attach.ParentId.addError('You can not delete an Attachment from Deposit Slip Records');
                       }
                }
            }
        }
        //Loan re-engineering
        if('System Administrator' != profileInfo.Name){
            for(Attachment attach : oldList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Unallocated_Payment__c.sObjectType){
                           attach.ParentId.addError('You can not delete an Attachment from Unallocated Payment Records');
                       }
                }
            }
        }
        
        /*
        //Scotia Forward Flow
        Boolean isCommunityUser = false;
        if(profileInfo.Name.contains('Community User')){
            isCommunityUser = true;
        }        
        //Community user can't delete attachment
        if(isCommunityUser){
            for(Attachment attach : oldList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Insolvency_Account__c.sObjectType){
                        attach.ParentId.addError('Sorry, you can\'t remove an attached document; contact Canaccede for more information, or if you require assistance with this action');
                    }
                }
            }
        }
        */
    }
    
    //Handle Befor Update
    public static void handleBeforeEdit(List<Attachment> newList){
        
        Profile profileInfo = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() limit 1];
        if('System Administrator' != profileInfo.Name && 'CFG - Application Admin' != profileInfo.Name ){
            for(Attachment attach : newList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Funding_Batch__c.sObjectType ){
                           attach.ParentId.addError('You can not edit an Attachment from Funding Batch Records');
                       }
                }
            }
        }
    }
    
    //After Attachment is Deleted
    public static void handleAfterDelete(List<Attachment> oldList) {
        List<Task> activities = new List<Task>();
        
        for(Attachment attach : oldList){
            if (attach.ParentId != null){
                if(attach.ParentId.getSObjectType() == Insolvency_Account__c.sObjectType || attach.ParentId.getSObjectType() == Insolvency__c.sObjectType){
                    Task activity = new Task();
                    activity.Subject = 'Deleted-'+attach.Name;
                    activity.WhatId = attach.ParentId;
                    activity.Status = 'Completed';
                    activities.add(activity);
                }
            }
        }
        
        if(activities.size() > 0){
            insert activities;
        }
    }
}