force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Fullfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Fullfillment_Status__c</fullName>
    <label>Application Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loan Calculator Completed</fullName>
            </value>
            <value>
                <fullName>Tele-Scripting Completed</fullName>
            </value>
            <value>
                <fullName>Executing Loan Document</fullName>
            </value>
            <value>
                <fullName>Loan Document Executed</fullName>
            </value>
            <value>
                <fullName>CSR Reviewed</fullName>
            </value>
            <value>
                <fullName>PAP Information uploaded</fullName>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
            </value>
            <value>
                <fullName>Approved for Funding</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Ready For Export</fullName>
            </value>
            <value>
                <fullName>CSR Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_City__c.field-meta.xml
<CustomField>
    <fullName>Employer_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Province__c.field-meta.xml
<CustomField>
    <fullName>Employer_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employer Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Street_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employer Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Employer_Street_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employer Street Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Employer_Unit_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employer Unit Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Megasys_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Megasys_Loan_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Megasys Loan Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Number_of_Dependants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Dependants__c</fullName>
    <label>Number of Dependants</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PO_Box__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PO_Box__c</fullName>
    <description>Permanent Address PO Box</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Permanent Address PO Box</inlineHelpText>
    <label>Permanent Address PO Box</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Province__c</fullName>
    <label>Permanent Address Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address Street Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Unit_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Permanent Address Unit Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/TestExportToMegasysController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : ExportToMegasysController for Validate Application.
*  @author : A5E Consulting
*  @date : 08/25/2016   

*************************************************************************************************/
@isTest
public class TestExportToMegasysController{
    
    static testMethod void testMegaSys(){
        
        Date testBirthDate = System.today().addYears(-30);
        
        //Create Account
        TestRecordsFactory.TestAccountWrapper accntWrapper = new TestRecordsFactory.TestAccountWrapper();
        accntWrapper.firstName = 'firstName';
        accntWrapper.lastName = 'lastName';
        accntWrapper.email = 'testuser@testOrg.com';
        accntWrapper.sin = 'dummysin'; 
        accntWrapper.birthDate = testBirthDate;     
        Account accnt = TestRecordsFactory.createAccountRecordAndInsert(accntWrapper, true);
        
        //Create Application
        TestRecordsFactory.TestApplicationWrapper applnWrapper = new TestRecordsFactory.TestApplicationWrapper();
        applnWrapper.name = 'RedecideApp';
        applnWrapper.firstName = 'firstName';
        applnWrapper.lastName = 'lastName';
        applnWrapper.email = 'testuser@testOrg.com';
        applnWrapper.sin = 'dummysin';  
        applnWrapper.birthDate = testBirthDate;
        Application__c appln = TestRecordsFactory.createApplicationRecordAndInsert(applnWrapper, true);
        
        appln.Application_Fullfillment_Status__c = 'Completed';
        appln.Loan_Type__c = 'Affirm Financial MasterCard';  
        appln.Megasys_Loan_Number__c = null;
        update appln;
        
        //Application with credit card
        testCrediCardApp(appln);
        
        //Application with Term Loan 
        testTermLoanApp(appln);
        
        //Fulfillment status is Blank
        testFulfillmentBlank(appln);
        
        //application with incomplete information
        testIncompleteApplication(appln);
        
        //Execute Error Messages
        testDataApplication(appln);
        
        //calling Megasys with complete application
        testFullApplication(appln);
        
    }
    
    //Application Fulfillment Status is balnk
    private static void testFulfillmentBlank(Application__c appln){
        appln.Application_Fullfillment_Status__c = '';
        update appln;
        
        PageReference pageRef1 = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef1);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        
        ExportToMegasysController ctrl1 = New ExportToMegasysController();
        ctrl1.callMegasys();
    }
    
    //Application with credit card
    private static void testCrediCardApp(Application__c appln){
        
        PageReference pageRef = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        System.currentPageReference().getParameters().put('appFulfill', appln.Application_Fullfillment_Status__c);  
        
        ExportToMegasysController ctrl = New ExportToMegasysController();
        ctrl.callMegasys();       
    }
    
    //Application with Term Loan
    private static void testTermLoanApp(Application__c appln){
        
        appln.Loan_Type__c = 'Affirm Financial Term Loan';
        appln.Application_Fullfillment_Status__c = null;
        appln.Megasys_Loan_Number__c = '';
        update appln;
        PageReference pageRef = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        
        ExportToMegasysController ctrl = New ExportToMegasysController();
        ctrl.callMegasys();       
    }
    
    //application with incomplete information
    private static void testIncompleteApplication(Application__c appln){
        appln.Application_Fullfillment_Status__c = 'Completed';
        appln.Loan_Type__c = 'Affirm Financial Term Loan';
        appln.Birth_Date__c = system.today() - 30;
        appln.Gender__c = null;
        appln.Marital_Status__c = null;
        appln.Number_of_Dependants__c = null;
        appln.work_Phone__c = null;
        appln.Cell_Phone__c = null;
        appln.Home_Phone__c = null;
        appln.Permanent_Address_Type__c = null;
        appln.Permanent_Address_Province__c = null;
        appln.Months_At_Permanent_Address__c = null;
        appln.Years_At_Permanent_Address__c = null;
        appln.Employer_Province__c = null;
        appln.Employer_Address_Type__c = null;
        appln.Employment_Years__c = null;
        appln.Employment_Months__c = null;
        appln.Gross_Monthly_Income__c = null;
        appln.Monthly_Expenses__c = null;
        appln.Payment__c = null;
        appln.Loan_Start_Date__c = null;
        appln.First_Payment_Date__c = null;
        appln.Number_of_Payments__c = null;
        appln.First_Payment_Amount__c = null;
        appln.Regular_Payment_Amount__c = null;
        appln.Total_of_Payment__c = null;
        appln.Loan_Amount__c = null;
        appln.Birth_Date__c = null;
        appln.First_Name__c = null;
        appln.Last_Name__c = null;
        update appln;
        
        PageReference pageRef1 = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef1);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        System.currentPageReference().getParameters().put('appFulfill', appln.Application_Fullfillment_Status__c);  
        
        ExportToMegasysController ctrl1 = New ExportToMegasysController();
        ctrl1.callMegasys();
    }
    
    //calling Megasys with complete application
    private static void testFullApplication(Application__c appln){
        
        appln.Application_Fullfillment_Status__c = 'Ready For Export';
        appln.Loan_Type__c = 'Affirm Financial Term Loan';
        appln.Gender__c = 'Male';
        appln.Marital_Status__c = 'Single';
        appln.Number_of_Dependants__c = '0';
        appln.work_Phone__c = '1233211233';
        appln.Cell_Phone__c = '1233211233';
        appln.Home_Phone__c = '1233211233';
        appln.SIN__c='123';
        appln.Permanent_Address_PO_Box__c = '1';
        appln.Permanent_Address_City__c = 'StreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCity';
        appln.Permanent_Address_Unit_Number__c = '11222222';
        appln.Permanent_Address_Street_Number__c = '1StreetNumber';
        appln.Permanent_Address_Street_Name__c = '121 StreetName StreetName StreetNameStreetName';
        appln.Permanent_Address_Unit_Number__c = '11222222';
        appln.Employer_Street_Number__c = '1StreetNumber';
        appln.Employer_Unit_Number__c = '1';
        appln.Employer_Street_Name__c = '121 StreetName StreetName StreetNameStreetName';
        appln.Employer_City__c = 'StreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCityStreetCity ';
        appln.Permanent_Address_Type__c = 'Physical';
        appln.Permanent_Address_Province__c = 'null';
        appln.Months_At_Permanent_Address__c = 0;
        appln.Years_At_Permanent_Address__c = 0;
        appln.Employer_Province__c = '12';
        appln.Employer_Address_Type__c = 'Physical';
        appln.Employment_Years__c = 0;
        appln.Employment_Months__c = 0;
        appln.Gross_Monthly_Income__c = 0;
        appln.Monthly_Expenses__c = 0;
        appln.Payment__c = 'Monthly';
        appln.Loan_Start_Date__c = System.today();
        appln.First_Payment_Date__c = System.today();
        appln.Number_of_Payments__c = 0;
        appln.First_Payment_Amount__c = 0;
        appln.Regular_Payment_Amount__c = 0;
        appln.Total_of_Payment__c = 0;
        appln.Loan_Amount__c = 0;
        appln.Birth_Date__c = System.today() - 30000;
        update appln;
        
        PageReference pageRef2 = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef2);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        System.currentPageReference().getParameters().put('appFulfill', appln.Application_Fullfillment_Status__c);  
        
        ExportToMegasysController ctrl2 = New ExportToMegasysController();
        ctrl2.callMegasys();
    }
    
    //calling Megasys with Incomplete Data
    private static void testDataApplication(Application__c appln){
        
        appln.Application_Fullfillment_Status__c = 'Ready For Export';
        appln.Loan_Type__c = 'Affirm Financial Term Loan';
        appln.Gender__c = null;
        appln.Marital_Status__c = null;
        appln.Number_of_Dependants__c = null;
        appln.work_Phone__c = null;
        appln.Cell_Phone__c = null;
        appln.Home_Phone__c = null;
        appln.Permanent_Address_Type__c = null;
        appln.Permanent_Address_Province__c = null;
        appln.Months_At_Permanent_Address__c = null;
        appln.Years_At_Permanent_Address__c = null;
        appln.Employer_Province__c = null;
        appln.Employer_Address_Type__c = null;
        appln.Employment_Years__c = null;
        appln.Employment_Months__c = null;
        appln.Gross_Monthly_Income__c = null;
        appln.Monthly_Expenses__c = null;
        appln.Payment__c = null;
        appln.Loan_Start_Date__c = null;
        appln.First_Payment_Date__c = null;
        appln.Number_of_Payments__c = null;
        appln.First_Payment_Amount__c = null;
        appln.Regular_Payment_Amount__c = null;
        appln.Total_of_Payment__c = null;
        appln.Loan_Amount__c = null;
        update appln;
        
        PageReference pageRef2 = Page.ExportToMegasys;
        Test.setCurrentPage(pageRef2);  
        System.currentPageReference().getParameters().put('id', appln.Id);
        System.currentPageReference().getParameters().put('appFulfill', appln.Application_Fullfillment_Status__c);  
        
        ExportToMegasysController ctrl2 = New ExportToMegasysController();
        ctrl2.callMegasys();
    }
}