force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Fullfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Fullfillment_Status__c</fullName>
    <label>Application Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loan Calculator Completed</fullName>
            </value>
            <value>
                <fullName>Tele-Scripting Completed</fullName>
            </value>
            <value>
                <fullName>Executing Loan Document</fullName>
            </value>
            <value>
                <fullName>Loan Document Executed</fullName>
            </value>
            <value>
                <fullName>CSR Reviewed</fullName>
            </value>
            <value>
                <fullName>PAP Information uploaded</fullName>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
            </value>
            <value>
                <fullName>Approved for Funding</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Ready For Export</fullName>
            </value>
            <value>
                <fullName>CSR Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Adjudication Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>Also known as MICR code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/File_Formats__c.field-meta.xml
<CustomField>
    <fullName>File_Formats__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Formats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPAPInformationController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class contains unit tests for validating behavior of PAPInformationController 
*  @author : A5E Consulting
*  @date : 08/02/2016
*
*************************************************************************************************/

@isTest
private class TestPAPInformationController{
    
    
    //Loan_ReEngineering__c Custom Settings
    static {
        
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.File_Formats__c = '.pdf,.jpeg,.jpg';
        loanSettings.File_Size__c = 2097152;
        insert loanSettings;         
    }
    
    //Test Various Scenarios   
    static testMethod void paymentTest(){
        //Dummy Attachment
        Attachment attInvalid = new Attachment();
        attInvalid.body = Blob.valueof('Invalid File');
        attInvalid.name = 'invalid.xyz';
        
        //Dummy Attachment
        Attachment attValid = new Attachment();
        attValid.body = Blob.valueof('Valid File');
        attValid.name = 'valid.pdf';
        
        //Test Application
        Application__c app = new Application__c();
        app.loan_type__c  = 'Affirm Financial MasterCard';
        insert app;
        
        ApexPages.currentPage().getParameters().put('id', app.id);
        ApexPages.currentPage().getParameters().put('loanType', 'Affirm Financial MasterCard');
        
        //Credit Card App
        PAPInformationController papInfoCtrl = new PAPInformationController();
        
        //Loan App
        ApexPages.currentPage().getParameters().put('loanType', 'Affirm Financial Term Loan');
        
        //Declined Loan App
        app.Decision__c = 'Declined';
        app.loan_type__c  = 'Affirm Financial Term Loan';
        update app;
        papInfoCtrl = new PAPInformationController();
        
        //Wrong Authentication
        app.Decision__c = 'Approved';
        app.Authentication_Result__c = 'Failed';
        app.Authentication_Choice__c = 'Declined';
        update app;
        papInfoCtrl = new PAPInformationController();
        
        //Wrong Fullfillment Status
        app.Authentication_Result__c = 'Passed';
        app.Authentication_Choice__c = 'Completed';
        app.Application_Fullfillment_Status__c = 'Completed';
        update app;
        papInfoCtrl = new PAPInformationController();
        
        //Wrong PAP Information
        app.Application_Fullfillment_Status__c = 'Loan Calculator Completed';
        update app;
        papInfoCtrl = new PAPInformationController();
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.application.PAP_Transit_Code__c = 'abc';
        papInfoCtrl.application.PAP_Account_Number__c = 'xyz';
        papInfoCtrl.application.PAP_Bank_Code__c = 'pqr';
        papInfoCtrl.updatePaymentMethod();
        
        //No File Attachment
        app.Application_Fullfillment_Status__c = 'Loan Calculator Completed';
        update app;
        papInfoCtrl = new PAPInformationController();
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.application.PAP_Transit_Code__c = '123';
        papInfoCtrl.application.PAP_Account_Number__c = '456';
        papInfoCtrl.application.PAP_Bank_Code__c = '789';
        papInfoCtrl.updatePaymentMethod();
        
        //Invalid File Attachment 
        papInfoCtrl = new PAPInformationController();
        papInfoCtrl.papSupportDocument = attInvalid;
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.application.PAP_Transit_Code__c = '123';
        papInfoCtrl.application.PAP_Bank_Code__c = '456';
        papInfoCtrl.application.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        
        //Terms Conditionas not accepted
        papInfoCtrl = new PAPInformationController();
        papInfoCtrl.papSupportDocument = attValid;
        papInfoCtrl.acceptTermsCondition = false;
        papInfoCtrl.application.PAP_Transit_Code__c = '123';
        papInfoCtrl.application.PAP_Bank_Code__c = '456';
        papInfoCtrl.application.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        
        //All OK
        papInfoCtrl = new PAPInformationController();
        papInfoCtrl.papSupportDocument = attValid;
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.application.PAP_Transit_Code__c = '123';
        papInfoCtrl.application.PAP_Bank_Code__c = '456';
        papInfoCtrl.application.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        papInfoCtrl.navigatePrevious();
        papInfoCtrl.upload();
        papInfoCtrl.closePopup();
        papInfoCtrl.showPopup();    
    }    
}