force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/AML_Decision__c.field-meta.xml
<CustomField>
    <fullName>AML_Decision__c</fullName>
    <description>AML Decision</description>
    <inlineHelpText>AML Decision</inlineHelpText>
    <label>AML Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <inlineHelpText>Application Status</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFSI Scripting</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>CC Creation</fullName>
            </value>
            <value>
                <fullName>CLI Scripting</fullName>
            </value>
            <value>
                <fullName>Completed - CLI</fullName>
            </value>
            <value>
                <fullName>Completed - Loan</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Email-Auth Sent</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Fraud Investigation</fullName>
            </value>
            <value>
                <fullName>Loan Delivery</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Scripting Required</fullName>
            </value>
            <value>
                <fullName>Waiting for Loan Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Loan Docs - Auth Passed</fullName>
            </value>
            <value>
                <fullName>BK/CP No Disch</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Scripting</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Adjudication Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationDecisionController.cls
public class ApplicationDecisionController {
    public Application_Form_Settings__c AppFormSettings {get;set;}
    public String adjudicationDecsion{get;set;}
    public String amlDecision{get;set;}
    public String applicationStatus{get;set;}
    public String applicationId {get;set;}
    
    //Decline Page updates
    public String loanType {get;set;}
    
    public Boolean cardNotInBKCP {get;set;}
    public String DECISION_ACCEPTED {get;set;} 
    public String DECISION_DECLINED {get;set;}
    public String DECISION_ERROR {get;set;}
    
    private Application__c application;

    public ApplicationDecisionController() {
        final String BKCP_NOT_DISCHARGED = 'BKCP Not Discharged';

        AppFormSettings = Application_Form_Settings__c.getOrgDefaults();
        
        DECISION_ACCEPTED = 'System Approved';
        DECISION_DECLINED = 'System Declined';
        DECISION_ERROR = 'Needs Review';
        
        applicationId = ApexPages.currentPage().getParameters().get('id');
        
        //Updated By A5E Consulting
        //Appilcation Workflow and Data Sync changes
        application = Utilities.getApplicationById(applicationId);
                     
        //Decline Page updates
        loanType = application.Loan_Type__c;
        adjudicationDecsion = application.Decision__c;
        amlDecision = application.AML_Decision__c;
        if(String.isBlank(amlDecision)){
            amlDecision = '';
        }
        applicationStatus = application.Application_Status__c;
    }

}