force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_URL__c</fullName>
    <description>Document URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document URL</inlineHelpText>
    <label>Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Placement Agency</description>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Work_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Work Assignment</description>
    <inlineHelpText>Work Assignment</inlineHelpText>
    <label>Work Assignment</label>
    <referenceTo>Work_Assignment__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/Product_Staging__c.object-meta.xml
<CustomObject>
    <description>Product staging table used for excel/csv processing</description>
    <label>Product Staging</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Staging__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Current_Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Commission_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Current Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Current_Settlement_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Settlement_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Current Settlement Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Data_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Id__c</fullName>
    <description>Data Id</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Data Id</inlineHelpText>
    <label>Data Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Document Storage</description>
    <inlineHelpText>Document Storage</inlineHelpText>
    <label>Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Product Stagings</relationshipLabel>
    <relationshipName>Product_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placed_Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Placed_Commission_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Placed Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placed_Settlement_Rate__c.field-meta.xml
<CustomField>
    <fullName>Placed_Settlement_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Placed Settlement Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Placement Agency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Pool_Name__c.field-meta.xml
<CustomField>
    <fullName>Pool_Name__c</fullName>
    <description>Pool Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Pool Name</inlineHelpText>
    <label>Pool Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>TestLow</fullName>
                <isActive>false</isActive>
                <label>TestLow</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Value_Tier_at_Time_of_Placement__c.field-meta.xml
<CustomField>
    <fullName>Value_Tier_at_Time_of_Placement__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Value Tier at Time of Placement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Work Assignment</description>
    <label>Agency Work Assignment</label>
</RecordType>

force-app/main/default/classes/PortalSnapshotCompletionProcessor.cls
/*========================================================================
*
* Class: PortalSnapshotCompletionProcessor
*
* @description : This used to for allocation process to create error file.
* @author : A5E Consulting
* @date : 03/02/2023
* @Developer Name: Satyajit Patil
========================================================================*/

@RestResource(urlMapping='/PortalSnapshotCompletionProcessor')


global with sharing class PortalSnapshotCompletionProcessor {
   
    @HttpPost
    global static void doPost() {
        String jsonString = RestContext.request.requestBody.toString();
        parseJson(jsonString);    
    }
    
    public static void parseJson(string jsonString ){
        Map<String, String> dataIDs = new Map<String,String>();
        ProductStagingResponse prResponse = (ProductStagingResponse)JSON.deserialize(jsonString, ProductStagingResponse.class); 
       string documentStorageId = prResponse.DocumentStorageId;
        
        dataIDs = getDataIds(prResponse);
        
        //Add and update comment on product staging record based on the parsed response.
        if(!documentStorageId.contains('DS_ACC')){
             updateProductStagings( dataIDs, documentStorageId );
        }
       
   	}
    
    // Updating Product Staging records
    public static void updateProductStagings(Map<String, String> dataIDs, String documentStorageId ){
        
        List<Product_Staging__c> pstgs = [SELECT Id, Identifier__c, Comment__c, 
                                          Document_Storage__r.Work_Assignment__c,
                                          Document_Storage__r.Document_Id__c,
                                          Document_Storage__r.Document_URL__c,
                                          Name__c,Data_Id__c,
                                          Placement_Agency__c,
                                          Pool_Name__c,
                                          Current_Commission_Rate__c,
                                          Placed_Commission_Rate__c,
                                          Current_Settlement_Rate__c,
                                          Placed_Settlement_Rate__c,
                                          Value_Tier_at_Time_of_Placement__c
                                          FROM Product_Staging__c 
                                          WHERE 
                                          Data_Id__c IN: dataIDs.keySet() 
                                          AND 
                                          Identifier__c=:documentStorageId ]; 
       
        for(Product_Staging__c pstg: pstgs){
            String msg = '';
            if(pstg.Comment__c == null){
                //pstg.Comment__c = dataIDs.get(pstg.Data_Id__c);
                msg = dataIDs.get(pstg.Data_Id__c);
            }
            else{
                //pstg.Comment__c = '<b>ERROR</b>- '+ dataIDs.get(pstg.Data_Id__c)+';'+pstg.Comment__c;
                msg = '<b>ERROR</b>- '+ dataIDs.get(pstg.Data_Id__c)+';'+pstg.Comment__c;
            }
            
            if(msg.length() > 254){
                msg = msg.substring(0,254);
            }
            
            pstg.Comment__c = msg;
            pstg.Include_in_Processing__c = false;
        }
        if(!pstgs.isEmpty()){
            update pstgs;
        } 
        
        //Create error file
        //Commented by satyajit
        //createDocumentStorage(documentStorageId);
        
        //Added by satyajit
        Database.executeBatch(new ErrorCSVFileGenerationBatch(documentStorageId,'Product Allocation File'),200);
        
    }
    
    // Prepare DataID Map with Comments from Request
    public static Map<String, String> getDataIds( ProductStagingResponse prResponse ){
        Map<String, String> dataIDs = new Map<String,String>();
        for(AllocationsClass result : prResponse.Allocations){
          	 for(ErrorsClass error : result.Errors){
            dataIDs.put(error.DataId, error.Detail);
        }
        }
         return dataIDs;
    }
    
   /* @future(Callout = true)
    public static void createDocumentStorage(String docID){
        String failedData = 'data_id,place_id,pool_name,current_commission_rate,commission_rate_at_time_of_placement,settlement_rate,settlement_rate_at_time_of_placement,value_tier_at_time_of_placement,error';
        failedData += '\n';
      
        List<Product_Staging__c> pstgs = [SELECT Id, Identifier__c, Comment__c, 
                                          Document_Storage__r.Work_Assignment__c,
                                          Document_Storage__r.Document_Id__c,
                                          Document_Storage__r.Document_URL__c,
                                          Name__c,Data_Id__c,
                                          Placement_Agency__c,
                                          Pool_Name__c,
                                          Current_Commission_Rate__c,
                                          Placed_Commission_Rate__c,
                                          Current_Settlement_Rate__c,
                                          Placed_Settlement_Rate__c,
                                          Value_Tier_at_Time_of_Placement__c
                                          FROM Product_Staging__c 
                                          WHERE
                                          (Include_in_Processing__c = false
                                           OR
                                          Status__c = 'Pending')
                                          AND
                                          Identifier__c=:docID]; 
        List<Product_Staging__c> prodStagingErrorList = new List<Product_Staging__c>();
        for(Product_Staging__c prodStag : pstgs){
            if(prodStag.Comment__c.contains('ERROR')){
                
                prodStagingErrorList.add(prodStag);
            }
        }
        
        //List<Product_Staging__c> successCount = new List<Product_Staging__c>();
        Integer successCount = 0;
       
        Integer successCountList = [SELECT count() FROM Product_Staging__c 
                                WHERE
                                Identifier__c=:docID];
       
        successCount = successCountList - pstgs.size();
       
        String documentID;
        String workAssignmentID;
        
        //Create Error file
        if(!pstgs.isEmpty()){
            
             documentID = pstgs[0].Identifier__c;
             workAssignmentID = pstgs[0].Document_Storage__r.Work_Assignment__c;
            
            for(Product_Staging__c prodStag: prodStagingErrorList){
                
                String CommentError;  
                if(prodStag.Comment__c!= null){
                    CommentError = prodStag.Comment__c;
                   
                    CommentError = CommentError.replaceAll('<br/>','');
                    CommentError = CommentError.replaceAll('</b>','');
                    CommentError = CommentError.replaceAll('<b>','');
                }
               
                failedData = failedData+ prodStag.Name__c+','+prodStag.Placement_Agency__c
                    +','+prodStag.Pool_Name__c+','+prodStag.Current_Commission_Rate__c
                    +','+prodStag.Placed_Commission_Rate__c+','+prodStag.Current_Settlement_Rate__c
                    +','+prodStag.Placed_Settlement_Rate__c+','+prodStag.Value_Tier_at_Time_of_Placement__c
                    +','+(prodStag.Comment__c!= null ? CommentError : NULL);
                
                failedData = failedData + '\n';
            }    
           
           
        }else{
            documentID = docID;
           	document_storage__c docData = [Select id,work_assignment__c from document_storage__c where id = :docID];
            workAssignmentID = docData.work_assignment__c;
        }
        //Send Document to Azure
         DistressedUtilities.postDocumentAPI(documentID, workAssignmentID, successCount, pstgs.size() ,null,
                                                                    null,failedData, null,null,null);
        
    }*/
   
    public class ProductStagingResponse{
        public string DocumentStorageId {get;set;}
        public List<AllocationsClass> Allocations {get;set;}
    }
    
    public class AllocationsClass{
        public string Agency {get;set;}
        public ErrorsClass[]Errors ;
    }
    
    public class ErrorsClass{
        public string DataId {get;set;}
        public String Detail {get;set;}
    }
}