force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Work_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Work Assignment</description>
    <inlineHelpText>Work Assignment</inlineHelpText>
    <label>Work Assignment</label>
    <referenceTo>Work_Assignment__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Purpose</description>
    <inlineHelpText>Purpose</inlineHelpText>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Media Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Excel File Processing</fullName>
            </value>
            <value>
                <fullName>Bulk Media Request</fullName>
                <default>true</default>
                <label>Bulk Media Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Sub_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sub_Purpose__c</fullName>
    <description>Sub-Purpose</description>
    <inlineHelpText>Sub-Purpose</inlineHelpText>
    <label>Sub-Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Media Request Sub-Purpose 1</fullName>
            </value>
            <value>
                <fullName>Media Request Sub-Purpose 2</fullName>
            </value>
            <value>
                <fullName>Complaint Sub-Purpose 1</fullName>
            </value>
            <value>
                <fullName>Complaint Sub-Purpose 2</fullName>
            </value>
            <value>
                <fullName>Invalid Submission</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Approved Sub-Purpose 2</fullName>
            </value>
            <value>
                <fullName>Ministry (provincial governing body, etc.)</fullName>
            </value>
            <value>
                <fullName>Better Business Bureau</fullName>
            </value>
            <value>
                <fullName>Credit Bureau (Equifax or TU sending us requests)</fullName>
            </value>
            <value>
                <fullName>Letter from lawyer / law firm / paralegal</fullName>
            </value>
            <value>
                <fullName>Verbal (from consumer, not any of the above)</fullName>
            </value>
            <value>
                <fullName>Written (from consumer, not any of the above)</fullName>
            </value>
            <value>
                <fullName>Media Request</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Product Payment Upload File</fullName>
            </value>
            <value>
                <fullName>Account Status Update File</fullName>
            </value>
            <value>
                <fullName>Account Status (having Judgment) Update File</fullName>
            </value>
            <value>
                <fullName>Customer Contact Information Update File</fullName>
            </value>
            <value>
                <fullName>Product Allocation File</fullName>
            </value>
            <value>
                <fullName>Product Recall File</fullName>
            </value>
            <value>
                <fullName>Product Bulk Pool Update File</fullName>
            </value>
            <value>
                <fullName>General Inquiries</fullName>
            </value>
            <value>
                <fullName>Distressed Notes Bulk Upload File</fullName>
            </value>
            <value>
                <fullName>Direct Payment Upload File</fullName>
            </value>
            <value>
                <fullName>Bulk Media Request</fullName>
            </value>
            <value>
                <fullName>Work Assignment Upload File</fullName>
            </value>
        </valueSetDefinition>
        
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Title</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCFG_EmailNotification.cls
@isTest
public class TestCFG_EmailNotification {
    static testMethod void emailNotify(){
        
        Work_Assignment__c workAssignment = new Work_Assignment__c();
        workAssignment.Purpose__c = 'Excel Processing';
        workAssignment.Sub_Purpose__c = 'Product Allocation File';
        workAssignment.Title__c = 'Allocation file';
        insert workAssignment;
        
        Document_Storage__c docStorage = new Document_Storage__c();
        docStorage.Work_Assignment__c = workAssignment.ID;
        insert docStorage;
        Work_assignment__c workAssign = [select id,name,title__c from work_assignment__c where id =: workAssignment.id];
        
        CFG_EmailNotification.sendEmailNotification('xyz@gmail.com','https://cfgroup--psb.sandbox.my.salesforce.com/apex/DisplayProductAllocateStaging?id='+docStorage.id,
                                                    workAssignment.Name,workAssignment.Title__c,'Account Status Update File');
        
        CFG_EmailNotification.sendEmailNotificationOnErrorFile('xyz@gmail.com', 'Success records', workAssignment.Name, workAssignment.Title__c, workAssignment.id,'Account Status Update File');
        CFG_EmailNotification.sendEmailNotificationOnProcessLinkFail('xyz@gmail.com', 'fail records', workAssignment.Name, workAssignment.Title__c, workAssignment.id,'Account Status Update File');
        
        CFG_EmailNotification.sendEmailNotification('xyz@gmail.com','https://cfgroup--psb.sandbox.my.salesforce.com/apex/DisplayProductAllocateStaging?id='+docStorage.id,
                                                    workAssignment.Name,workAssignment.Title__c,'Product Allocation File');
        
        CFG_EmailNotification.sendEmailNotificationOnErrorFile('xyz@gmail.com', 'Success records', workAssignment.Name, workAssignment.Title__c, workAssignment.id,'Product Allocation File');
        CFG_EmailNotification.sendEmailNotificationOnProcessLinkFail('xyz@gmail.com', 'fail records', workAssignment.Name, workAssignment.Title__c, workAssignment.id,'Product Allocation File');
        CFG_EmailNotification.snapshotFailedEmailNotification('xyz@gmail.com', 'fail records', docStorage.id);

    }
}