force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/Product_Staging__c.object-meta.xml
<CustomObject>
    <description>Product staging table used for excel/csv processing</description>
    <label>Product Staging</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Staging__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Document Storage</description>
    <inlineHelpText>Document Storage</inlineHelpText>
    <label>Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Product Stagings</relationshipLabel>
    <relationshipName>Product_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StagingRecordsDeleteScheduler.cls
/**
 * @description       : Batch class to delete staging records created for putback/buyback and product status update after 3 days
 * @author            : adesh.ikhar@canaccede.com
 * @last modified on  : 02-12-2025
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class StagingRecordsDeleteScheduler implements Schedulable, Database.Batchable<sObject> {
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new StagingRecordsDeleteScheduler());
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Identifier__c FROM Product_Staging__c WHERE CreatedDate < LAST_N_DAYS:3');
    }

    public void execute(Database.BatchableContext bc, List<Product_Staging__c> listProductStaging) {
        List<String> eligibleDocumentTypes = new List<String>{
            DocumentStorageTriggerHandler.PRODUCT_BUYBACK_PUTBACK_UPDATE_FILE,
            DocumentStorageTriggerHandler.PRODUCT_STATUS_UPDATE_FILE
        };
        Map<String, List<Product_Staging__c>> docStorageIdProductStagingMap = new Map<String, List<Product_Staging__c>>();
        List<Product_Staging__c> productStagingToDelete = new List<Product_Staging__c>();
        // Map document storage Id against related product staging records
        for (Product_Staging__c productStaging : listProductStaging) {
            if (docStorageIdProductStagingMap.containsKey(productStaging.Identifier__c)) {
                docStorageIdProductStagingMap.get(productStaging.Identifier__c).add(productStaging);
            } else {
                docStorageIdProductStagingMap.put(productStaging.Identifier__c, new List<Product_Staging__c>{ productStaging });
            }
        }
        // Only delete staging records which have related document storage record of type putback/buyback update or product status update
        for (Document_Storage__c docStorage : [
            SELECT Id
            FROM Document_Storage__c
            WHERE Id IN :docStorageIdProductStagingMap.keySet() AND Document_Type__c IN :eligibleDocumentTypes
        ]) {
            productStagingToDelete.addAll(docStorageIdProductStagingMap.get(docStorage.Id));
        }
        if (!productStagingToDelete.isEmpty()) {
            Database.delete(productStagingToDelete);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}