force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/BuyBack_Request__c.field-meta.xml
<CustomField>
    <fullName>BuyBack_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BuyBack Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Creator</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_URL__c</fullName>
    <description>Document URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document URL</inlineHelpText>
    <label>Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>File_Processing_Date__c</fullName>
    <description>File Processing Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>File Processing Date</inlineHelpText>
    <label>File Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Media_Request__c.field-meta.xml
<CustomField>
    <fullName>Media_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Media request record</description>
    <inlineHelpText>Media request record</inlineHelpText>
    <label>Media Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom Product Lookup</description>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/recordTypes/MM.recordType-meta.xml
<RecordType>
    <fullName>MM</fullName>
    <active>true</active>
    <description>Record Type for MM file storage</description>
    <label>MM</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Charged_Off_Amount__c.field-meta.xml
<CustomField>
    <fullName>Charged_Off_Amount__c</fullName>
    <description>The total amount that was charged off on this account, if applicable</description>
    <inlineHelpText>The total amount that was charged off on this account, if applicable</inlineHelpText>
    <label>Charge Off Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Charged_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Charged_Off_Date__c</fullName>
    <description>The date that this account charged off, if applicable</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that this account charged off, if applicable</inlineHelpText>
    <label>Charge Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Originating_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Originating_Creditor__c</fullName>
    <description>DebtNext-specific</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DebtNext-specific</inlineHelpText>
    <label>Originating Creditor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Previous_Primary_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Primary_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Previous Primary Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Previous_Secondary_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Secondary_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Previous Secondary Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The specific product this record represents</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The specific product this record represents</inlineHelpText>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <description>Purchase Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Purchase Date</inlineHelpText>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Face_Value__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Face_Value__c</fullName>
    <description>The purchase face value of this account to date</description>
    <inlineHelpText>The purchase face value of this account to date</inlineHelpText>
    <label>Purchase Face Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <inlineHelpText>Purchase Price</inlineHelpText>
    <label>Purchase Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Purchase Status</description>
    <inlineHelpText>Purchase Status</inlineHelpText>
    <label>Buyback/Putback Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buyback Putback Initiated</fullName>
                <label>Buyback/Putback Initiated</label>
            </value>
            <value>
                <fullName>Buyback Putback Submitted to Seller</fullName>
                <label>Buyback/Putback Submitted to Seller</label>
            </value>
            <value>
                <fullName>Buyback Putback Rejected</fullName>
                <label>Buyback/Putback Rejected</label>
            </value>
            <value>
                <fullName>Buyback Putback Approved</fullName>
                <label>Buyback/Putback Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Putback_Buyback_Amount__c.field-meta.xml
<CustomField>
    <fullName>Putback_Buyback_Amount__c</fullName>
    <description>Putback / Buyback Amount</description>
    <inlineHelpText>Putback / Buyback Amount</inlineHelpText>
    <label>Buyback / Putback Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Putback_Reason__c.field-meta.xml
<CustomField>
    <fullName>Putback_Reason__c</fullName>
    <description>Putback Reason</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Putback Reason</inlineHelpText>
    <label>Buyback/Putback Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Product Account.</description>
    <inlineHelpText>The amount to be applied to the Product Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BuybackSellerExportController.cls
public class BuybackSellerExportController {
    public String documentID {get;set;}
    public String blobContents {get;set;}
    public String contentType {get;set;}
    public list<Product__c> listProducts {get;set;} 
    public list<Id> listProd; 
    public Map<Id, Decimal> totalPaymentsMap;      
    public String ERROR_MSG {get;set;}
    public boolean DisableExportBtn{get;set;}
    public list<Document_Storage__c> listDocStorage {get;set;}
    String headerCSV ;
    
    public BuybackSellerExportController (ApexPages.StandardController stdController){
        listProducts = [Select id,Name,Originating_Creditor__c,Purchase_Date__c,Customer__c, Customer__r.Name,First_Name__c,Last_Name__c,
                        Previous_Secondary_Account_Number__c,Previous_Primary_Account_Number__c,Product_Type__c,Charged_Off_Date__c,
                        Charged_Off_Amount__c,Purchase_Price__c,Putback_Buyback_Amount__c,Putback_Reason__c, Purchase_Status__c,
                        Purchase_Face_Value__c
                        from Product__c Where Purchase_Status__c = 'Buyback Initiated' 
                       OR Purchase_Status__c = 'Putback Initiated'];
            
        if(listProducts.isEmpty()){
            ERROR_MSG = '&nbsp;&nbsp;No Eligible Product Records to Export';
            DisableExportBtn = true;
        }

        listDocStorage =  [Select id,Name,Media_Request__c,File_Processing_Date__c,
                          Document_Type__c,Creator__c,Document_Id__c,Document_URL__c
                         from Document_Storage__c Where BuyBack_Request__c = TRUE ORDER BY Name DESC LIMIT 8];
    }
    
    public  PageReference getDocumentInfo(){
        DocumentDetails docDetails = DocumentAPIClient.getDocumentInfo(documentId);
        system.debug('docDetails: '+docDetails);
        if(docDetails.document != NULL){
            blobContents = EncodingUtil.base64Encode(docDetails.document);
            contentType = docDetails.contentType;
        }
        else{
            blobContents ='';
        }
        system.debug('docDetails.fileString: '+docDetails.fileString); 
        return null;  
    }
   
    public  PageReference createCSV(){
       headerCSV = 'Seller'+',' 
            + 'Purchase Date' +','                
            + 'Name' +','
            + 'Last Name' +',' 
            + 'First Name' +',' 
            + 'Account Number' +',' 
            + 'Secondary Account number' +',' 
            + 'Product Type' +','
            + 'Charge Off Date' +',' 
            + 'Charge Off Amount' +',' 
            + 'Total Amount of Payments Received' +',' 
            + 'Purchase Price' +','            
            + 'Purchased Amount' +','            
            + 'BuyBack/PutBack Amount' +',' 
            + 'BuyBack/Putback Reason' +',' 
            + 'Note' +','
            + '\n';
        list<Id> stringList = new list<Id>();
        for(Product__c prodList : listProducts){
           stringList.add(formatString(prodList.id)); 
        }
        decimal amount = 0;
        List<Product_Payments__c> prodpay = [SELECT Payment_Amount__c, CCS_Account__c,Payment_Type__c FROM Product_Payments__c WHERE CCS_Account__c IN: stringList AND Payment_Type__c = '1000'];
        
        for(Product_Payments__c pp: prodpay ){
            amount += pp.Payment_Amount__c;
        }
        system.debug('amount check**'+amount);
        for(Product__c prodObj : listProducts){
            system.debug('prodObj'+prodObj.Id);
            String strSeller = formatString(prodObj.Originating_Creditor__c);
            String purchaseDate = convertDateToString(prodObj.Purchase_Date__c);
            String Name = prodObj.Customer__c != null ? formatString(prodObj.Customer__r.Name): '';
            String lastName = formatString(prodObj.Last_Name__c);
            String firstName = formatString(prodObj.First_Name__c);
            String accountNo = formatString(prodObj.Previous_Primary_Account_Number__c);
            String secondoryAccountNo = formatString(prodObj.Previous_Secondary_Account_Number__c);
            String productType = formatString(prodObj.Product_Type__c);
            String chargeOffDate = convertDateToString(prodObj.Charged_Off_Date__c);
            String chargeOffAmount = prodObj.Charged_Off_Amount__c != null ? String.valueOf(prodObj.Charged_Off_Amount__c) : '';
            String totalAmountOfPaymentsReceived = (amount != null ? String.valueOf(amount): '0');
            String purchasePrice = prodObj.Purchase_Price__c != null ? String.valueOf(prodObj.Purchase_Price__c +'%') : '';
            String purchasedAmount = prodObj.Purchase_Face_Value__c != null ? String.valueOf(prodObj.Purchase_Face_Value__c) : '';
            String buyBackAmount = prodObj.Putback_Buyback_Amount__c != null ? String.valueOf('$'+prodObj.Putback_Buyback_Amount__c) : '';
            String putbackReason = formatString(prodObj.Putback_Reason__c);
            
            String mediaRqstCSV = checkComma(strSeller)+',' 
                                + checkComma(purchaseDate)+',' 
                                + checkComma(Name) +','
                                + checkComma(lastName) +',' 
                                + checkComma(firstName) +','
                                + checkComma(accountNo) +','
                                + checkComma(secondoryAccountNo) +','
                                + checkComma(productType) +','
                                + checkComma(chargeOffDate) +','
                                + checkComma(chargeOffAmount) +',' 
                                + checkComma(totalAmountOfPaymentsReceived) +','
                                + checkComma(purchasePrice) +','
                                + checkComma(purchasedAmount) +',' 
                                + checkComma(buyBackAmount) +','
                                + checkComma(putbackReason) +','
                                + '' + '\n'; 
            
              if(String.isNotBlank(mediaRqstCSV)){
                headerCSV += mediaRqstCSV;
              } 
        }
        system.debug('headerCSV***' +headerCSV);
        postDocumentAPI(headerCSV);
        return null;
    }   
    
    public void postDocumentAPI(String cSV){
        Map<String,Object> rawObj;       
        DocumentAPIClientUtil.ParsedResponse parsedResponse = new DocumentAPIClientUtil.ParsedResponse();
        system.debug('123');
        Blob fileBlob;
        
        if(Test.isRunningTest()) {
        	fileBlob = Blob.valueOf('test');
        }else{
            fileBlob = Blob.valueOf(cSV);
        }
        
        if(!Test.isRunningTest()) {
        	parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Buyback/Putback Initiated file Exported.csv', 'Task');
        }else{
            parsedResponse.DocUrl = 'Test';
            parsedResponse.docId = 'Test';
        }    
        system.debug('parsedResponse in controller: '+parsedResponse);
        //rawObj = (Map<String,Object>) JSON.deserializeUntyped(parsedResponse.response); 
        
        //Create  CSV Document Storage Record
        Document_Storage__c  DocStorage = new Document_Storage__c();
        if(null != parsedResponse 
           && String.isnotBlank(parsedResponse.docId)){
            DocStorage.Document_Name__c = 'Buyback/Putback Initiated Export Document.csv';
            DocStorage.Document_Extension__c = 'csv';
            //DocStorage.Document_ID__c = String.valueOf(rawObj.get('docId'));
            DocStorage.Document_ID__c = parsedResponse.docId;
            DocStorage.Document_Type__C = 'Buyback/Putback Initiated File';
            //DocStorage.Document_URL__c = String.valueOf(rawObj.get('docUrl'));
            DocStorage.Document_URL__c = parsedResponse.DocUrl;
            DocStorage.Uploaded_By__c = 'Internal User';
            DocStorage.Creator__c = UserInfo.getName();
            DocStorage.Document_Related_To__c = 'Buyback/Putback Initiated';
            DocStorage.BuyBack_Request__c = TRUE;
            DocStorage.File_Processed_By__c = UserInfo.getName();
            DocStorage.File_Processing_Date__c = Date.today();
            insert DocStorage;
            system.debug('DocStorage: '+DocStorage);
        }
        
        List<Product__c> listProductUpdate = New List<Product__c>();
        for(Product__c updateProduct : listProducts){
            if(updateProduct.Purchase_Status__c == 'Buyback Initiated'){
                updateProduct.Purchase_Status__c = 'Buyback Requested';
            }
            if(updateProduct.Purchase_Status__c == 'Putback Initiated'){
                updateProduct.Purchase_Status__c = 'Putback Requested';
            }
            
            listProductUpdate.add(updateProduct);
        }
        
        update listProductUpdate;
        ERROR_MSG = '&nbsp;&nbsp;Buyback/Putback Requested Records Exported Successfully';
        DisableExportBtn = true;
        listDocStorage = [Select id,Name,BuyBack_Request__c,File_Processing_Date__c,
                          Document_Type__c,Creator__c,Document_Id__c,Document_URL__c
                         from Document_Storage__c Where BuyBack_Request__c = TRUE ORDER BY Name DESC LIMIT 8];
    }
    
    
     //Convert Date to String
    @testvisible
    private static String convertDateToString(DateTime dt){
        if(dt != null){
            return (dt.formatGMT('MM/dd/yyyy'));
        }
        else{
            return '';
        }
    }
    
    @testvisible
    private static String checkComma(String str){
        if(String.isNotBlank(str) && str.contains(',')){
                return +' \"'+str+'\" ';
        }
        else{
            return str;
        }
    }

    @testvisible
    private static String formatString(String str){
        return String.isNotBlank(str) ? str : '';
    }
}