force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is the lookup to Insolvency Account to which the statement is related to</description>
    <inlineHelpText>This field is the lookup to Insolvency Account to which the statement is related to</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Document_Storage__c/recordTypes/MM.recordType-meta.xml
<RecordType>
    <fullName>MM</fullName>
    <active>true</active>
    <description>Record Type for MM file storage</description>
    <label>MM</label>
</RecordType>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Date_of_Birth__c</fullName>
    <description>Date of Birth of the primary filer</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Date of Birth of the primary filer</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_City__c</fullName>
    <description>The primary debtor&apos;s address city.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address city.</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Country__c</fullName>
    <defaultValue>&quot;Canada&quot;</defaultValue>
    <description>The primary debtor&apos;s address country.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address country.</inlineHelpText>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Postal_Code__c</fullName>
    <description>The primary debtor&apos;s address postal code.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address postal code.</inlineHelpText>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Street__c</fullName>
    <description>The primary debtor&apos;s address street name and number.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary debtor&apos;s address street name and number.</inlineHelpText>
    <label>Street Name &amp; Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_SIN__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_SIN__c</fullName>
    <description>Social Insurance Number of the primary debtor, if available.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Social Insurance Number of the primary debtor, if available.</inlineHelpText>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Date__c</fullName>
    <description>The effective date of the insolvency filing as noted in the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The effective date of the insolvency filing as noted in the creditor’s package</inlineHelpText>
    <label>Insolvency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Received_Date__c</fullName>
    <description>The date that the creditor’s package was received.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the creditor’s package was received.</inlineHelpText>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Date_of_Birth__c</fullName>
    <description>Debtor DOB</description>
    <formula>Insolvency__r.Debtor_1_Date_of_Birth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Debtor DOB</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Last_Name__c</fullName>
    <description>Last name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the primary debtor</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_City__c</fullName>
    <formula>Insolvency__r.Debtor_1_Mailing_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Postal_Code__c</fullName>
    <formula>Insolvency__r.Debtor_1_Mailing_Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postal Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_Street__c</fullName>
    <formula>Insolvency__r.Debtor_1_Mailing_Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Name &amp; Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_SIN__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_SIN__c</fullName>
    <formula>Insolvency__r.Debtor_1_SIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Received_Date__c</fullName>
    <description>The date that the creditor’s package was received.</description>
    <formula>Insolvency__r.Insolvency_Received_Date__c</formula>
    <inlineHelpText>The date that the creditor’s package was received.</inlineHelpText>
    <label>Insolvency Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Province_Formula__c.field-meta.xml
<CustomField>
    <fullName>Province_Formula__c</fullName>
    <formula>TEXT(Insolvency__r.Debtor_1_Mailing_State_Province__c)</formula>
    <label>Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Trustee_Company__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Company__c</fullName>
    <description>The company name of the debtor&apos;s insolvency trustee</description>
    <formula>Insolvency__r.Trustee_Company_Name_Formula__c</formula>
    <inlineHelpText>The company name of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InsolvencyDailyUpdateBatch.cls
/*****************************************************************************************************************
* Author         : A5E Consultancy
* Created On     : 02 Nov 2023
* Description    : This file layout is used for DRN to send insolvency updates to an Insolvency Client and 
for the Client to send return detailed information to DRN.
							
******************************************************************************************************************/

public class InsolvencyDailyUpdateBatch implements Database.Batchable<sobject>, Database.Stateful, Database.AllowsCallouts{
   
    public static string headbody;
    public static string mainbody = '';
   	public static string trailerbody = '';
    public string finalHeaderBody = '';
    public Integer bodyCount = 1;
    public static map<String, CTB_File_Automation__mdt> mapCTBFileAutomation = CTB_File_Automation__mdt.getAll();
    public static map<String, CTB_File_Automation__mdt> mapCTBFileAuto = new map<String, CTB_File_Automation__mdt>();
    public static String memberType;
    public static String memberID;
        
    // Start Method
    public Database.Querylocator start(Database.BatchableContext BC) {
        List<String> listNames = new List<String>{'101010','010101'};
        return Database.getQueryLocator([ Select id,name,Insolvency_Received_Date__c,Insolvency__r.Insolvency_Type__c,Debtor_1_First_Name__c,
                                         Debtor_1_Last_Name__c,Province_Formula__c,Insolvency__r.Debtor_1_Mailing_Country__c,Debtor_1_Mailing_Postal_Code__c,
                                         Debtor_1_SIN__c,Debtor_1_Date_of_Birth__c,Insolvency__r.Insolvency_Date__c,Insolvency__r.name,Trustee_Company__c,
                                         Insolvency__r.Trustee__r.BillingStreet,Insolvency__r.Trustee__r.BillingCity,Insolvency__r.Trustee__r.BillingState,
                                         Insolvency__r.Trustee__r.BillingPostalCode,Debtor_1_Mailing_Street__c,Debtor_1_Mailing_City__c

                                         from Insolvency_Account__c 
                                         where Name IN: listNames AND
                                         Recordtype.name = 'Canadian Tire Insolvency Account' AND
                                         (Insolvency_Status__c = 'Annulled' OR
                                         Insolvency_Status__c = 'Refused' OR
                                         Insolvency_Status__c = 'Withdrawn') 
                                         ]
										);
        
    }
    
    //Execute Method
    public void execute(Database.BatchableContext BC, List<Insolvency_Account__c> scope) {
        for(CTB_File_Automation__mdt metaData : mapCTBFileAutomation.values()){
            mapCTBFileAuto.put(metaData.MasterLabel,metaData);
        }
        memberType = mapCTBFileAuto.get('Insolvency Daily Update').Member_Type__c;
        memberID = mapCTBFileAuto.get('Insolvency Daily Update').Member_ID__c;
        system.debug('memberType@@'+memberType); 
        system.debug('memberID@@'+memberID); 
		String bodyData = getCSVBodyData(scope);
        string csvHeaders = getCSVHeaderData();
        finalHeaderBody = csvHeaders + bodyData;
        bodyCount ++;
    }
    public static string getCSVHeaderData(){ 
        Integer BatchCount = 1;
        String createdDate = convertDateToString(System.today());
        system.debug('today date'+System.today());
        system.debug('createdDate date'+createdDate);
        
        String headerType = mapCTBFileAuto.get('Insolvency Daily Update').Header_Record_Type__c;
        system.debug('headerType'+headerType);
        
        String fileType = mapCTBFileAuto.get('Insolvency Daily Update').File_Type__c;
        String fileFormatIdenfier = mapCTBFileAuto.get('Insolvency Daily Update').File_Format_Identifier__c;
        system.debug('fileType@@'+fileType); 
        headbody = headerType +','+memberType+','+memberID+','+BatchCount+','+createdDate+','+Datetime.now().format('HH:mm:ss')+','+fileType+','+fileFormatIdenfier+' \n';
        BatchCount ++;
        return headbody;
    }
    public static string getCSVBodyData(List<Insolvency_Account__c> insolvencyAccData){ 
        for(Insolvency_Account__c insolAccData : insolvencyAccData){
            String DebtorFirstName = '';
            if(insolAccData.Debtor_1_First_Name__c!=null){
                if(insolAccData.Debtor_1_First_Name__c.length() > 40){
                    DebtorFirstName =insolAccData.Debtor_1_First_Name__c.subString(0,40);
                }else{
                    DebtorFirstName = insolAccData.Debtor_1_First_Name__c;
                }
            }
			String DebtorLaseName = '';
            if(insolAccData.Debtor_1_Last_Name__c!=null){
                if(insolAccData.Debtor_1_Last_Name__c.length() > 40){
                    DebtorLaseName =insolAccData.Debtor_1_Last_Name__c.subString(0,40);
                }else{
                    DebtorLaseName = insolAccData.Debtor_1_Last_Name__c;
                }
            }
			String addressLine1 = '';
            if(insolAccData.Debtor_1_Mailing_Street__c!=null){
                if(insolAccData.Debtor_1_Mailing_Street__c.length() > 80){
                    addressLine1 =insolAccData.Debtor_1_Mailing_Street__c.subString(0,80);
                }else{
                    addressLine1 = insolAccData.Debtor_1_Mailing_Street__c;
                }
            }
            String DebtorMailingCity = '';
            if(insolAccData.Debtor_1_Mailing_City__c!=null){
                if(insolAccData.Debtor_1_Mailing_City__c.length() > 40){
                    DebtorMailingCity =insolAccData.Debtor_1_Mailing_City__c.subString(0,40);
                }else{
                    DebtorMailingCity = insolAccData.Debtor_1_Mailing_City__c;
                }
            }   
            String province = '';
            if(insolAccData.Province_Formula__c!=null){
                province = CustomerProcessingBatchHelper.getProvinceCode(insolAccData.Province_Formula__c);
            }
            String mailingCountry = '';
            if(insolAccData.Insolvency__r.Debtor_1_Mailing_Country__c!=null){
                mailingCountry = CustomerProcessingBatchHelper.getMailingCountry(insolAccData.Insolvency__r.Debtor_1_Mailing_Country__c); 
            }
			String mailingPostalCode = '';
            if(insolAccData.Debtor_1_Mailing_Postal_Code__c!=null){
                if(insolAccData.Debtor_1_Mailing_Postal_Code__c.length() > 15){
                    mailingPostalCode =insolAccData.Debtor_1_Mailing_Postal_Code__c.subString(0,15);
                }else{
                    mailingPostalCode = insolAccData.Debtor_1_Mailing_Postal_Code__c;
                }
            }
            String SIN = '';
            if(insolAccData.Debtor_1_SIN__c!=null){
                if(insolAccData.Debtor_1_SIN__c.length() > 50){
                    SIN =insolAccData.Debtor_1_SIN__c.subString(0,50);
                }else{
                    SIN = insolAccData.Debtor_1_SIN__c;
                }
            }
            String dateOfBirth = '';
            /*if(insolAccData.CTB_Date_of_Birth__c!=null){
                dateOfBirth = insolAccData.CTB_Date_of_Birth__c;
            }else{*/
                dateOfBirth = convertDateToString(insolAccData.Debtor_1_Date_of_Birth__c);
           // }
           String insolvencyDate = '';
           if(insolAccData.Insolvency__r.Insolvency_Date__c!=null){
               insolvencyDate = convertDateToString(insolAccData.Insolvency__r.Insolvency_Date__c);
           }
           String openDate = '';
           if(insolAccData.Insolvency_Received_Date__c!=null){
               openDate = convertDateToString(insolAccData.Insolvency_Received_Date__c);
           }
           String estateNumber = '';
           if(insolAccData.Insolvency__r.name!=null){
               estateNumber = insolAccData.Insolvency__r.name;
           }
           String trusteeCompany = '';
           if(insolAccData.Trustee_Company__c!=null){
               if(insolAccData.Trustee_Company__c.length() > 80){
                    trusteeCompany =insolAccData.Trustee_Company__c.subString(0,80);
                }else{
                    trusteeCompany = insolAccData.Trustee_Company__c;
                }
           }
           String trusteeAddress = '';
           if(insolAccData.Insolvency__r.Trustee__r.BillingStreet!=null){
               if(String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingStreet).length() > 80){
                    trusteeAddress =String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingStreet).subString(0,80);
                }else{
                    trusteeAddress = String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingStreet);
                }
           }
           String trusteeCity = '';
           if(insolAccData.Insolvency__r.Trustee__r.BillingCity!=null){
               if(String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingCity).length() > 50){
                    trusteeCity =String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingCity).subString(0,50);
                }else{
                    trusteeCity = String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingCity);
                }
           }
           String trusteeState = '';
           if(insolAccData.Insolvency__r.Trustee__r.BillingState!=null){
               if(String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingState).length() > 2){
                    trusteeState =String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingState).subString(0,2);
                }else{
                    trusteeState = String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingState);
                }
           }
           String trusteePostalCode = '';
           if(insolAccData.Insolvency__r.Trustee__r.BillingPostalCode!=null){
               if(String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingPostalCode).length() > 15){
                    trusteePostalCode =String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingPostalCode).subString(0,15);
                }else{
                    trusteePostalCode = String.valueOf(insolAccData.Insolvency__r.Trustee__r.BillingPostalCode);
                }
           }
		   String detailRecordType = mapCTBFileAuto.get('Insolvency Daily Update').Detail_Record_Type__c;
           String productDesc = mapCTBFileAuto.get('Insolvency Daily Update').Product_Description__c;
           String productID = mapCTBFileAuto.get('Insolvency Daily Update').DRN_Debt_Product_ID__c;
           system.debug('productID@@'+productID);  
            mainbody += detailRecordType+','+memberType+','+memberID+','+openDate+','+insolAccData.name+','+insolAccData.Insolvency__r.Insolvency_Type__c+','+
                productDesc+','+DebtorFirstName+','+DebtorLaseName+','+addressLine1+','+''+','+DebtorMailingCity+','+province+','+
                mailingCountry+','+mailingPostalCode+','+SIN+','+dateOfBirth+','+insolvencyDate+','+estateNumber+','+'1'+','+trusteeCompany+','+trusteeAddress+','+''+','+
                trusteeCity+','+trusteeState+','+trusteePostalCode+','+productID+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+','+''+' \n';
        }
    	
        return mainbody;
    }

    @testvisible
    private static String convertDateToString(DateTime dt){
        if(dt != null){
            return (dt.formatGMT('MM/dd/yyyy'));
        }
        else{
            return '';
        }
    }
    // Finish Method to generate TAILER record
    public void finish(Database.BatchableContext BC) {
        system.debug('finalHeaderBody@@'+finalHeaderBody);
        system.debug('finalHeaderBody length@@'+finalHeaderBody.length());
        system.debug('trailerbody@@'+trailerbody);
        system.debug('bodyCount@@'+bodyCount);
       Integer finalrecordCount = 2 + bodyCount;
       for(CTB_File_Automation__mdt metaData : mapCTBFileAutomation.values()){
            mapCTBFileAuto.put(metaData.MasterLabel,metaData);
       }
       String trailerRecordType = mapCTBFileAuto.get('Insolvency Daily Update').Trailer_Record_Type__c;
       memberType = mapCTBFileAuto.get('Insolvency Daily Update').Member_Type__c;
       memberID = mapCTBFileAuto.get('Insolvency Daily Update').Member_ID__c;
       system.debug('trailerRecordType@@'+trailerRecordType); 
       String createdDate = convertDateToString(System.today()); 
       trailerbody = trailerRecordType+','+memberType+','+memberID+','+finalrecordCount+','+bodyCount+','+createdDate+','+Datetime.now().format('HH:mm:ss')+' \n';
       String FinalData = finalHeaderBody + trailerbody;
        
       DocumentAPIClientUtil.ParsedResponse parsedResponse = new DocumentAPIClientUtil.ParsedResponse();
        System.debug('@@base64Data '+FinalData);
        Blob fileBlob = Blob.valueOf(FinalData);

        if(!Test.isRunningTest()) {
            parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'DRN_DailyUpdate_'+Datetime.now().format('yyyy-MM-dd HH:mm:ss')+'.csv', 'account');
            system.debug('parsedResponse in controller: '+parsedResponse);
        }else{
            parsedResponse.docUrl = 'Test';
            parsedResponse.docId = 'Test';
        }
       
        Document_Storage__c docInfo = new Document_Storage__c();
        docInfo.Document_Type__c = 'Insolvency Daily Update';
        docInfo.Work_Assignment__c = 'a3LS0000000h6NCMAY';    
        docInfo.Document_URL__c = parsedResponse.docUrl;
        docInfo.Document_Extension__c = 'csv';
        docInfo.Document_Name__c = 'DRN_DailyUpdate_'+Datetime.now().format('yyyy-MM-dd HH:mm:ss')+'.csv';
        docInfo.Document_Id__c = parsedResponse.docId;
        docInfo.Visibility__c = 'CFG Only';
        DocumentStorageTriggerHandler.runDocumentStorageTrigger = false;
        insert docInfo;
        DocumentStorageTriggerHandler.runDocumentStorageTrigger = true;
    }
}