force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Creator</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Extension__c.field-meta.xml
<CustomField>
    <fullName>Document_Extension__c</fullName>
    <description>Document Extension</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Extension</inlineHelpText>
    <label>Document Extension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Document_Related_To__c</fullName>
    <description>Document Related To</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Related To</inlineHelpText>
    <label>Document Related To</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_URL__c</fullName>
    <description>Document URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document URL</inlineHelpText>
    <label>Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processed_By__c.field-meta.xml
<CustomField>
    <fullName>File_Processed_By__c</fullName>
    <description>File Processed By</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>File Processed By</inlineHelpText>
    <label>File Processed By</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>File_Processing_Date__c</fullName>
    <description>File Processing Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>File Processing Date</inlineHelpText>
    <label>File Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Placement Agency</description>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <label>Uploaded By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal User</fullName>
                <default>true</default>
                <label>Internal User</label>
            </value>
            <value>
                <fullName>External User</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CFG only</fullName>
            </value>
            <value>
                <fullName>CFG + Requesting Agency</fullName>
            </value>
            <value>
                <fullName>CFG + All Agencies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Work_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Work Assignment</description>
    <inlineHelpText>Work Assignment</inlineHelpText>
    <label>Work Assignment</label>
    <referenceTo>Work_Assignment__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/Product_Staging__c.object-meta.xml
<CustomObject>
    <description>Product staging table used for excel/csv processing</description>
    <label>Product Staging</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Staging__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Current_Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Commission_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Current Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Current_Settlement_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Settlement_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Current Settlement Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Document Storage</description>
    <inlineHelpText>Document Storage</inlineHelpText>
    <label>Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Product Stagings</relationshipLabel>
    <relationshipName>Product_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placed_Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Placed_Commission_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Placed Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placed_Settlement_Rate__c.field-meta.xml
<CustomField>
    <fullName>Placed_Settlement_Rate__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <label>Placed Settlement Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Placement Agency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Placement_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status_Code__c</fullName>
    <description>Placement Status Code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Placement Status Code</inlineHelpText>
    <label>Placement Status Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Pool_Name__c.field-meta.xml
<CustomField>
    <fullName>Pool_Name__c</fullName>
    <description>Pool Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Pool Name</inlineHelpText>
    <label>Pool Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>TestLow</fullName>
                <isActive>false</isActive>
                <label>TestLow</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Changed_Date__c</fullName>
    <description>Status Changed Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Status Changed Date</inlineHelpText>
    <label>Status Changed Date</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Staging__c/fields/Value_Tier_at_Time_of_Placement__c.field-meta.xml
<CustomField>
    <fullName>Value_Tier_at_Time_of_Placement__c</fullName>
    <description>Use for Product Allocation File Processing</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Value Tier at Time of Placement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG.recordType-meta.xml
<RecordType>
    <fullName>CFG</fullName>
    <active>true</active>
    <description>CFG Work Assignment</description>
    <label>CFG Work Assignment</label>
</RecordType>

force-app/main/default/classes/ErrorCSVFileGenerationBatch.cls
/**************************************************************************************************
*
* Class: ErrorCSVFileGenerationBatch
*
* @description : This class can be used to generate and attach the Error CSV file during allocation/recall

* @author : A5E Consulting
* @date : 23/03/2023

*************************************************************************************************/
public class ErrorCSVFileGenerationBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public string csvHeaderSuccess;
    public string csvHeaderError;
    //public string finalstr;
    public integer failedRecords;
    public integer successRecords;
    //public string DocType;
    //public String failed;
    //public String success;
    //public Id workAssignmentId;
    //public String visiblity;
    //public Id documentID;
    public String documentStorageId;
    //public String documentType;
    public String SUCCESS_STR = 'SUCCESS';
    public String workAssignmentID;
     public String documentType;
    public static String allocate = 'Product Allocation File';
    public static String recall = 'Account Status Update File';
    
    public ErrorCSVFileGenerationBatch(String documentStorageId, String documentType){ 
        this.documentStorageId = documentStorageId;
        this.documentType = documentType;
        successRecords = 0;
        failedRecords = 0;
        //this.documentType = documentType;
        if(documentType == recall){
           csvHeaderError = 'data_id,placement_status_code,status_changed_date,error'+'\n'; 
        }else{
            csvHeaderError = 'data_id,place_id,pool_name,current_commission_rate,commission_rate_at_time_of_placement,settlement_rate,settlement_rate_at_time_of_placement,value_tier_at_time_of_placement,error'+'\n';
        }
        csvHeaderSuccess = 'data_id,placement_status_code,status_changed_date,success'+'\n';
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT id,name,Status__c,Include_in_Processing__c,Placement_Agency__c,Pool_Name__c,Current_Commission_Rate__c,Placed_Commission_Rate__c,placement_status_code__c,Placed_Settlement_Rate__c,Current_Settlement_Rate__c,Value_Tier_at_Time_of_Placement__c,status_changed_date__c,name__c,comment__c,Identifier__c,Document_Storage__r.Work_Assignment__c FROM Product_Staging__c where Identifier__c =:documentStorageId LIMIT 50000]);
    }
    
    public void execute(Database.BatchableContext BC, List<Product_Staging__c> scope){
        string description;
        workAssignmentID = scope[0].Document_Storage__r.Work_Assignment__c;
        for(Product_Staging__c ps:scope){
            //fetch failed Records
            if((ps.Include_in_Processing__c == false || ps.Status__c == 'Pending') && documentType == recall){
                description = ps.comment__c.replaceAll('<b>', '').replaceAll('</b>', '').replaceAll('<br/>', '');
                csvHeaderError +='"'+ps.Name__c+'","'+ps.placement_status_code__C+'","'+ps.status_changed_date__c+'","'+description +'"\n';
                failedRecords = failedRecords + 1;
            }else if((ps.Include_in_Processing__c == false || ps.Status__c == 'Pending') && documentType == allocate){
                description = ps.comment__c.replaceAll('<b>', '').replaceAll('</b>', '').replaceAll('<br/>', '');
                csvHeaderError +='"'+ps.Name__c+'","'+ps.Placement_Agency__c+'","'+ps.Pool_Name__c+'","'+ps.Current_Commission_Rate__c+'","'+ps.Placed_Commission_Rate__c+'","'+ps.Current_Settlement_Rate__c+'","'+ps.Placed_Settlement_Rate__c+'","'+ps.Value_Tier_at_Time_of_Placement__c+'","'+description +'"\n';
                failedRecords = failedRecords + 1;
            }
            
            //fetch Success Records
            if(ps.Include_in_Processing__c == true && ps.Status__c == 'Processed' && documentType != allocate){
                csvHeaderSuccess +='"'+ps.Name__c+'","'+ps.placement_status_code__C+'","'+ps.status_changed_date__c+'","'+SUCCESS_STR +'"\n';
                successRecords = successRecords + 1;
            }
        }  
    }
    public void finish(Database.BatchableContext BC) {
        
        Map<String,Object> rawObj;
        Map<String,Object> rawObj1;
              system.debug('workAssignmentID%%%'+workAssignmentID);  
        //Failed CSV API Call
        system.debug('csvHeaderError: '+csvHeaderError);
        DocumentAPIClientUtil.ParsedResponse parsedResponse = new DocumentAPIClientUtil.ParsedResponse();
        System.debug('@@base64Data '+csvHeaderError);
        Blob fileBlob = Blob.valueOf(csvHeaderError);
        
        if(failedRecords > 0 && !test.isRunningTest()){
            parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Product Failed.csv', 'Task');
            rawObj = (Map<String,Object>) JSON.deserializeUntyped(parsedResponse.response);
        }
        
        //Success CSV API Call
        DocumentAPIClientUtil.ParsedResponse parsedResponse1 = new DocumentAPIClientUtil.ParsedResponse();
        Blob fileBlobSuccess = Blob.valueOf(csvHeaderSuccess);
        if(successRecords > 0 && !test.isRunningTest()){
            parsedResponse1 = DocumentAPIClient.postDocument(fileBlobSuccess, 'Product Success.csv', 'Task');
            rawObj1 = (Map<String,Object>) JSON.deserializeUntyped(parsedResponse1.response);
        }
        
        //Create Failed CSV Document Storage
        Document_Storage__c  failedDocStorage = new Document_Storage__c();
        DocumentStorageTriggerHandler.runDocumentStorageTrigger=false;
        if(null != parsedResponse && failedRecords > 0){
            failedDocStorage.Work_Assignment__c = workAssignmentID;
            failedDocStorage.Document_Name__c = 'Product Failed.xls';
            if(documentType == recall){
                failedDocStorage.Document_Type__C = 'Account Status Update File';
            }else if(documentType == allocate){
               failedDocStorage.Document_Type__C = allocate; 
            }
            
            failedDocStorage.Document_Extension__c = 'xls';
            failedDocStorage.Document_ID__c = parsedResponse.docId;
            failedDocStorage.Visibility__c = 'CFG Only';
            failedDocStorage.Document_URL__c = parsedResponse.DocUrl;
            failedDocStorage.Uploaded_By__c = 'Internal User';
            failedDocStorage.Creator__c = UserInfo.getName();
            failedDocStorage.Document_Related_To__c = 'Task';
            failedDocStorage.File_Processed_By__c = UserInfo.getName();
            failedDocStorage.File_Processing_Date__c = Date.today();
            failedDocStorage.File_Processing_Status__c = 'Processed';
            insert failedDocStorage;
        }
        
        //Create Success CSV Document Storage
        Document_Storage__c  SuccessDocStorage = new Document_Storage__c();
        
        if(null != parsedResponse1 && successRecords > 0){
            SuccessDocStorage.Work_Assignment__c = workAssignmentID;
            SuccessDocStorage.Document_Name__c = 'Product Success.xls';
            SuccessDocStorage.Document_Type__C = 'Account Status Update File';
            SuccessDocStorage.Document_Extension__c = 'xls';
            SuccessDocStorage.Document_ID__c = parsedResponse1.docId;
            SuccessDocStorage.Visibility__c = 'CFG Only';
            SuccessDocStorage.Document_URL__c = parsedResponse1.DocUrl;
            SuccessDocStorage.Uploaded_By__c = 'Internal User';
            SuccessDocStorage.Creator__c = UserInfo.getName();
            SuccessDocStorage.Document_Related_To__c = 'Task';
            SuccessDocStorage.File_Processed_By__c = UserInfo.getName();
            SuccessDocStorage.File_Processing_Date__c = Date.today();
            SuccessDocStorage.File_Processing_Status__c = 'Processed';
            insert SuccessDocStorage;
        }
        
        Document_Storage__c docStorageToUpdate = new Document_Storage__c(ID= documentStorageId, File_Processing_Status__c = 'Processed');
        update docStorageToUpdate;
        
        DateTime dT = System.now();
        String oldComments = '';
        system.debug('workAssignmentID%%%'+workAssignmentID);
        Work_Assignment__c workAssignment = [select id,name,title__c,Created_By__c,Status__c,Latest_Comment__c,Comments_History__c,Comment_Reply__c from Work_Assignment__c where id = : workAssignmentID];
        workAssignment.Status__c = 'Completed';
        if(failedRecords > 0){
            workAssignment.Comment_Reply__c = 'No. of Records Failed: '+ failedRecords +'\n';
        }else{
            workAssignment.Comment_Reply__c = 'No. of Records Failed: 0'+'\n';
        }
        if(successRecords == 0 && documentType == allocate){
            successRecords = [SELECT count() FROM Product_Staging__c 
                                WHERE
                                Identifier__c=:documentStorageId];
            successRecords = successRecords - failedRecords;
        }
        if(successRecords > 0){
            workAssignment.Comment_Reply__c += 'No. of Records Succeeded: '+ successRecords;
        }else{
            workAssignment.Comment_Reply__c += 'No. of Records Succeeded: 0';
        }
        if(workAssignment.Comments_History__c !=null){
            oldComments = workAssignment.Comments_History__c;
        }
        workAssignment.Latest_Comment__c = workAssignment.Comment_Reply__c;
        //bug:4743 : changes starts
        workAssignment.Comments_History__c = 'System Generated Comment on behalf off' + ' ' +UserInfo.getName()+' '+ 'on' + ' ' + dT.month() + '/' + dT.day() + '/' + dT.year() + ';' + ' ' + ' ' + workAssignment.Comment_Reply__c + '\n' + '\n';
        //bug:4743 : changes ends
        if(oldComments != null){
            workAssignment.Comments_History__c += oldComments;
        }
        
        workAssignment.Comment_Reply__c = '';
        
        WorkAssignmentTriggerHandler.runWorkAssignmentTrigger = false;
        update workAssignment;
        WorkAssignmentTriggerHandler.runWorkAssignmentTrigger = true;
        DocumentStorageTriggerHandler.runDocumentStorageTrigger=true; 
        
        //Added by satyajit for ticket: 4424
        if(documentType == recall) {
            // Database.executeBatch(new CFG_ProcessWorkAssignment(workAssignmentId),200);
            
            // Call the work Assignment API to update portal.
            system.enqueueJob(new CFG_ProcessWorkAssignment(workAssignment.Id));
        }
        
        Document_Storage__c docStorage = [select id,name,uploaded_By__c,Created_By__c from Document_Storage__c where id = : documentStorageId];

        if(!Test.isRunningTest() && docStorage.uploaded_By__c != 'External User'){
            CFG_EmailNotification.sendEmailNotificationOnErrorFile(docStorage.Created_By__c,workAssignment.Latest_Comment__c,workAssignment.name,workAssignment.title__c,workAssignment.id,documentType);
       }
    }
}