force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Created_By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Creator</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Extension__c.field-meta.xml
<CustomField>
    <fullName>Document_Extension__c</fullName>
    <description>Document Extension</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Extension</inlineHelpText>
    <label>Document Extension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Document_Related_To__c</fullName>
    <description>Document Related To</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Related To</inlineHelpText>
    <label>Document Related To</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_URL__c</fullName>
    <description>Document URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document URL</inlineHelpText>
    <label>Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processed_By__c.field-meta.xml
<CustomField>
    <fullName>File_Processed_By__c</fullName>
    <description>File Processed By</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>File Processed By</inlineHelpText>
    <label>File Processed By</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>File_Processing_Date__c</fullName>
    <description>File Processing Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>File Processing Date</inlineHelpText>
    <label>File Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>File_Processing_Status__c</fullName>
    <description>File Processing Status</description>
    <inlineHelpText>File Processing Status</inlineHelpText>
    <label>File Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Staging Table Created</fullName>
            </value>
            <value>
                <fullName>Staging Table Creation Failed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Placement Agency</description>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Placement_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Placement_Identifier__c</fullName>
    <description>Placement Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Placement Identifier</inlineHelpText>
    <label>Placement Identifier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <label>Uploaded By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal User</fullName>
                <default>true</default>
                <label>Internal User</label>
            </value>
            <value>
                <fullName>External User</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CFG only</fullName>
            </value>
            <value>
                <fullName>CFG + Requesting Agency</fullName>
            </value>
            <value>
                <fullName>CFG + All Agencies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Work_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Work Assignment</description>
    <inlineHelpText>Work Assignment</inlineHelpText>
    <label>Work Assignment</label>
    <referenceTo>Work_Assignment__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Work_Assignment_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment_Identifier__c</fullName>
    <description>Work_Assignment _Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Work_Assignment _Identifier</inlineHelpText>
    <label>Work_Assignment _Identifier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Comment_Reply__c.field-meta.xml
<CustomField>
    <fullName>Comment_Reply__c</fullName>
    <description>Comment/Reply</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comment/Reply</inlineHelpText>
    <label>Comment/Reply</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Comments_History__c.field-meta.xml
<CustomField>
    <fullName>Comments_History__c</fullName>
    <description>Comments History</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comments History</inlineHelpText>
    <label>Comments History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <description>Created_By</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Created_By</inlineHelpText>
    <label>Created_By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Latest_Comment__c.field-meta.xml
<CustomField>
    <fullName>Latest_Comment__c</fullName>
    <description>Store the latest comment used for the back end purposes</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Store the latest comment used for the back end purposes</inlineHelpText>
    <label>Latest Comment</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <description>Task Number</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Task Number</inlineHelpText>
    <label>Task Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Title</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PostDocumentAPI.cls
public class PostDocumentAPI implements Queueable, Database.AllowsCallouts {
    String failed;
    String success;
    Integer failedRecords;
    Integer successRecords;
    Id workAssignmentId;
    String visiblity;
    Id documentID;
    String DocType;
    public static Boolean stopSuccessfilegenaration = true;
    public Document_Storage__c docData;
    
    public PostDocumentAPI(String DocType,String failed,String success,Integer failedRecords,Integer successRecords,Id workAssignmentId,String visiblity,Id documentID) {
        system.debug('run bacth');
        this.failed = failed;
        this.success = success;
        this.failedRecords = failedRecords;
        this.successRecords = successRecords;
        this.workAssignmentId = workAssignmentId;
        this.visiblity = visiblity;
        this.documentID = documentID;
        this.DocType = DocType;

        docData = [select id,Visibility__c,Placement_Agency__c,Placement_Agency__r.name from Document_Storage__c where id =: documentID];
    }
    public void execute(QueueableContext context) {
        //Database.executeBatch(new ErrorCSVFileGenerationBatch(DocType,failed,success,failedRecords,successRecords,workAssignmentId,visiblity,documentID),2000);                                              
        Map<String,Object> rawObj;
        Map<String,Object> rawObj1;
        DateTime dT = System.now();
        String oldComments = '';
		
        Work_Assignment__c workAssignment = [select id,name,title__c,Task_Number__c,Created_By__c,Status__c,Latest_Comment__c,Comments_History__c,Comment_Reply__c from Work_Assignment__c where id = : workAssignmentId];
        
        //Failed CSV API Call
        DocumentAPIClientUtil.ParsedResponse parsedResponse = new DocumentAPIClientUtil.ParsedResponse();

        Blob fileBlob = Blob.valueOf(failed);

        if(failedRecords > 0){
            if(String.isNotBlank(DocType)){
                if(DocType == 'Product Payment Upload File' || DocType == 'Direct Payment Upload File' ||
                   DocType == 'Balance Adjustment Upload File'){
                       parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Product Payment Failed.csv', 'Task');
                   }else if(DocType == 'Customer Contact Information Update File'){
                       parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Customer Contact Information Failed.csv', 'Task');
                   }else if(DocType == 'Account Status (having Judgment) Update File'){
                       parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Account Judgment Failed.csv', 'Task');
                   }else if(DocType == 'Account Status Update File'){
                       parsedResponse = DocumentAPIClient.postDocument(fileBlob, 'Account Status Failed.csv', 'Task');
                   }
            }
            rawObj = (Map<String,Object>) JSON.deserializeUntyped(parsedResponse.response); 
        }
        
        //Success CSV API Call
        DocumentAPIClientUtil.ParsedResponse parsedResponse1 = new DocumentAPIClientUtil.ParsedResponse();
        Blob fileBlobSuccess = Blob.valueOf(success);

        if(successRecords > 0){
            if(String.isNotBlank(DocType)){
                if(DocType == 'Product Payment Upload File' || DocType == 'Direct Payment Upload File'||
                   DocType == 'Balance Adjustment Upload File'){
                       parsedResponse1 = DocumentAPIClient.postDocument(fileBlobSuccess, 'Product Payment Success.csv', 'Task');
                   }else if(DocType == 'Customer Contact Information Update File'){
                       parsedResponse1 = DocumentAPIClient.postDocument(fileBlobSuccess, 'Customer Contact Information Success.csv', 'Task');
                   }else if(DocType == 'Account Status (having Judgment) Update File'){
                       parsedResponse1 = DocumentAPIClient.postDocument(fileBlobSuccess, 'Account Judgment Success.csv', 'Task');
                   }else if(DocType == 'Account Status Update File'){
                       parsedResponse1 = DocumentAPIClient.postDocument(fileBlobSuccess, 'Account Status Success.csv', 'Task');
                   }
            }
            rawObj1 = (Map<String,Object>) JSON.deserializeUntyped(parsedResponse1.response); 
        }

        //Create Failed CSV Document Storage
        Document_Storage__c  failedDocStorage = new Document_Storage__c();
        DocumentStorageTriggerHandler.runDocumentStorageTrigger=false;
        if(null != parsedResponse && failedRecords > 0){
            failedDocStorage.Work_Assignment__c = workAssignmentID;
            if(DocType == 'Product Payment Upload File' || DocType == 'Direct Payment Upload File' ||
               DocType == 'Balance Adjustment Upload File'){
                   failedDocStorage.Document_Name__c = 'Product Payment Failed.xls';
                   failedDocStorage.Document_Type__C = 'Product Payment Upload File';
               }else if(DocType == 'Customer Contact Information Update File'){
                   failedDocStorage.Document_Name__c = 'Customer Contact Information Failed.xls';
                   failedDocStorage.Document_Type__C = 'Customer Contact Information Update File';
               }else if(DocType == 'Account Status (having Judgment) Update File'){
                   failedDocStorage.Document_Name__c = 'Account Judgment Failed.xls';
                   failedDocStorage.Document_Type__C = 'Account Judgment Processing File';
               }else if(DocType == 'Account Status Update File'){
                   failedDocStorage.Document_Name__c = 'Account Status Failed.csv';
                   failedDocStorage.Document_Type__C = 'Account Status Update';
               }
            
            failedDocStorage.Document_Extension__c = 'xls';
            failedDocStorage.Document_ID__c = parsedResponse.docId;
            //Ticket 4097: visibility should be same as uploaded document
            failedDocStorage.Visibility__c = docData.Visibility__c;
            failedDocStorage.Document_URL__c = parsedResponse.DocUrl;
            failedDocStorage.Uploaded_By__c = 'Internal User';
            failedDocStorage.Creator__c = UserInfo.getName();
            failedDocStorage.Document_Related_To__c = 'Task';
            failedDocStorage.File_Processed_By__c = UserInfo.getName();
            failedDocStorage.File_Processing_Date__c = Date.today();
            failedDocStorage.File_Processing_Status__c = 'Processed';
            failedDocStorage.Placement_Agency__c = docData.Placement_Agency__c;
            failedDocStorage.Placement_Identifier__c = docData.Placement_Agency__r.name;
            failedDocStorage.Work_Assignment_Identifier__c = workAssignment.Task_Number__c;
            insert failedDocStorage;
        }
        //API call to portal to visisble failure file on portal
        if(DocType == 'Product Payment Upload File' || DocType == 'Account Status Update File'
          || DocType == 'Customer Contact Information Update File'){
              if(failedDocStorage.ID != NULL){
                  PortalDocumentStorageProcessingAPI.processDocumentStorage(failedDocStorage.ID); 
              }
        }
        //Create Success CSV Document Storage
        Document_Storage__c  SuccessDocStorage = new Document_Storage__c();
        
        if(null != parsedResponse1 && successRecords > 0){
            SuccessDocStorage.Work_Assignment__c = workAssignmentID;
            if(DocType == 'Product Payment Upload File' || DocType == 'Direct Payment Upload File' ||
               DocType == 'Balance Adjustment Upload File'){
                   SuccessDocStorage.Document_Name__c = 'Product Payment Success.xls';
                   SuccessDocStorage.Document_Type__C = 'Product Payment Upload File';
               }else if(DocType == 'Customer Contact Information Update File'){
                   SuccessDocStorage.Document_Name__c = 'Customer Contact Information Success.xls';
                   SuccessDocStorage.Document_Type__C = 'Customer Contact Information Update File';
               }else if(DocType == 'Account Status (having Judgment) Update File'){
                   SuccessDocStorage.Document_Name__c = 'Account Judgment Success.xls';
                   SuccessDocStorage.Document_Type__C = 'Account Judgment Processing File';
               }else if(DocType == 'Account Status Update File'){
                   SuccessDocStorage.Document_Name__c = 'Account Status Success.csv';
                   SuccessDocStorage.Document_Type__C = 'Account Status Update';
               }

            SuccessDocStorage.Document_Extension__c = 'xls';
            SuccessDocStorage.Document_ID__c = parsedResponse1.docId;
            //Ticket 4097: visibility should be same as uploaded document
            SuccessDocStorage.Visibility__c = docData.Visibility__c;
            SuccessDocStorage.Document_URL__c = parsedResponse1.DocUrl;
            SuccessDocStorage.Uploaded_By__c = 'Internal User';
            SuccessDocStorage.Creator__c = UserInfo.getName();
            SuccessDocStorage.Document_Related_To__c = 'Task';
            SuccessDocStorage.File_Processed_By__c = UserInfo.getName();
            SuccessDocStorage.File_Processing_Date__c = Date.today();
            SuccessDocStorage.File_Processing_Status__c = 'Processed';
            SuccessDocStorage.Placement_Agency__c = docData.Placement_Agency__c;
            SuccessDocStorage.Placement_Identifier__c = docData.Placement_Agency__r.name;
            SuccessDocStorage.Work_Assignment_Identifier__c = workAssignment.Task_Number__c;
            insert SuccessDocStorage;
        }
        //API call to portal to visisble failure file on portal
        if(DocType == 'Product Payment Upload File' || DocType == 'Account Status Update File'
          || DocType == 'Customer Contact Information Update File'){
              if(SuccessDocStorage.ID != NULL){
                  PortalDocumentStorageProcessingAPI.processDocumentStorage(SuccessDocStorage.ID); 
              }
        }
        Document_Storage__c docStorageToUpdate = new Document_Storage__c(ID= documentID, File_Processing_Status__c = 'Processed');
        update docStorageToUpdate;
        
        workAssignment.Status__c = 'Completed';
        
        if(DocType == 'Product Payment Upload File' && failedRecords > 0 && successRecords == 0){
            stopSuccessfilegenaration = false;
        }
        workAssignment.Comment_Reply__c = '';
        if(stopSuccessfilegenaration == true){
            if(failedRecords > 0){
                workAssignment.Comment_Reply__c = 'No. of Records Failed: '+ failedRecords +'\n';
            }else{
                workAssignment.Comment_Reply__c = 'No. of Records Failed: 0'+'\n';
            }
            if(successRecords > 0){
                workAssignment.Comment_Reply__c += 'No. of Records Succeeded: '+ successRecords;
            }else{
                workAssignment.Comment_Reply__c += 'No. of Records Succeeded: 0';
            }
        }else if(stopSuccessfilegenaration == false){
            workAssignment.Comment_Reply__c += 'Whole transaction is failed because of exception please check the error file and share with support team';
        }
        
        if(workAssignment.Comments_History__c !=null){
            oldComments = workAssignment.Comments_History__c;
        }
        workAssignment.Latest_Comment__c = workAssignment.Comment_Reply__c;
        //Bug: 4743 - changes starts
        workAssignment.Comments_History__c = 'System Generated Comment on behalf of' + ' ' +UserInfo.getName()+' '+ 'on' + ' ' + dT.month() + '/' + dT.day() + '/' + dT.year() + ';' + ' ' + ' ' + workAssignment.Comment_Reply__c + '\n' + '\n';
        //Bug: 4743 - changes ends
        if(oldComments != null){
            workAssignment.Comments_History__c += oldComments;
        }
        
        workAssignment.Comment_Reply__c = '';
        
        WorkAssignmentTriggerHandler.runWorkAssignmentTrigger = false;
        update workAssignment;
        stopSuccessfilegenaration = true;
        WorkAssignmentTriggerHandler.runWorkAssignmentTrigger = true;
        
        DocumentStorageTriggerHandler.runDocumentStorageTrigger=true; 
        
        //Changes are done by ticket: 4496
        if(!Test.isRunningTest()){
            system.enqueueJob(new CFG_ProcessWorkAssignment(workAssignment.Id));
        }
    }
}