force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Document_Extension__c.field-meta.xml
<CustomField>
    <fullName>Document_Extension__c</fullName>
    <description>Document Extension</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Extension</inlineHelpText>
    <label>Document Extension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom Product Lookup</description>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/recordTypes/Distressed.recordType-meta.xml
<RecordType>
    <fullName>Distressed</fullName>
    <active>true</active>
    <label>Distressed</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Buyback_Putback_Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Buyback_Putback_Status_Change_Date__c</fullName>
    <description>Buyback/Putback Status Change Date is used for distressed collection</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Buyback/Putback Status Change Date is used for distressed collection</inlineHelpText>
    <label>Buyback/Putback Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Originating_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Originating_Creditor__c</fullName>
    <description>DebtNext-specific</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DebtNext-specific</inlineHelpText>
    <label>Originating Creditor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <description>Purchase Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Purchase Date</inlineHelpText>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Purchase Status</description>
    <inlineHelpText>Purchase Status</inlineHelpText>
    <label>Buyback/Putback Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buyback Putback Initiated</fullName>
                <label>Buyback/Putback Initiated</label>
            </value>
            <value>
                <fullName>Buyback Putback Submitted to Seller</fullName>
                <label>Buyback/Putback Submitted to Seller</label>
            </value>
            <value>
                <fullName>Buyback Putback Rejected</fullName>
                <label>Buyback/Putback Rejected</label>
            </value>
            <value>
                <fullName>Buyback Putback Approved</fullName>
                <label>Buyback/Putback Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Putback_buyback_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Putback_buyback_Completed_Date__c</fullName>
    <description>Putback / buyback Completed Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Putback / buyback Completed Date</inlineHelpText>
    <label>Buyback / Putback Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Putback_Provision_Days__c.field-meta.xml
<CustomField>
    <fullName>Putback_Provision_Days__c</fullName>
    <description>Putback Provision Days is used for distressed collection</description>
    <inlineHelpText>Putback Provision Days is used for distressed collection</inlineHelpText>
    <label>Putback Provision Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestBuybackSellerExportController.cls
@isTest
public class TestBuybackSellerExportController {
    public static testMethod void testBuybackSellerExport(){
        list<Product__c> accs=new list<Product__c>();
        
        Product__c prod1 = new Product__c();
        prod1.Name = '1566P430';
        prod1.Purchase_Status__c = 'Buyback Initiated';
        //prod1.Purchase_Date__c = Date.newInstance(2022, 07, 19);
        prod1.Putback_Provision_Days__c = 15;
        prod1.collection_agency__c = 29;
        prod1.Buyback_Putback_Status_Change_Date__c = Date.newInstance(2022, 08, 03);
        prod1.Putback_buyback_Completed_Date__c = Date.newInstance(2022, 08, 03);
        prod1.RecordTypeId = Schema.SObjectType.Product__C.getRecordTypeInfosByName().get('Distressed Account').getRecordTypeId();
        prod1.Originating_Creditor__c = 'Test';
        ProductTriggerHandler.runProductTrigger = False;
        insert prod1;
        ProductTriggerHandler.runProductTrigger = True;
        accs.add(prod1);
        
        Document_Storage__c  DocStorage = new Document_Storage__c();
        DocStorage.Document_Name__c = 'Buyback/Putback Initiated Export Document.csv';
        DocStorage.Document_Extension__c = 'csv';
        DocStorage.Document_Type__C = 'Buyback/Putback Initiated File';
        DocumentStorageTriggerHandler.runDocumentStorageTrigger = False;
        insert DocStorage;
        DocumentStorageTriggerHandler.runDocumentStorageTrigger = True;
        
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(prod1);
        BuybackSellerExportController list1 = new BuybackSellerExportController(sc);
        list1.createCSV();
        Test.stopTest();
    }
    
    public static String formatString(String str){
        return String.isNotBlank(str) ? str : '';
    }
}