force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Amended_Claim_Flag__c.field-meta.xml
<CustomField>
    <fullName>Amended_Claim_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to drive a change on the PoC Form 31 letter when checked, indicating the PoC has been amended from a previous submission.</description>
    <inlineHelpText>Used to drive a change on the PoC Form 31 letter when checked, indicating the PoC has been amended from a previous submission.</inlineHelpText>
    <label>Amended Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Balance_Owed__c.field-meta.xml
<CustomField>
    <fullName>Balance_Owed__c</fullName>
    <description>The balance owed on this account.</description>
    <inlineHelpText>The balance owed on this account.</inlineHelpText>
    <label>Balance Owed</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Borrower_Primary__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Primary__c</fullName>
    <description>Provide the full name of the primary borrower on this account, in order of &quot;First Middle Last&quot;.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide the full name of the primary borrower on this account, in order of &quot;First Middle Last&quot;.</inlineHelpText>
    <label>Primary Borrower</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Last_Name__c</fullName>
    <description>Last name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the primary debtor</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Follow_up_Email__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Email__c</fullName>
    <formula>Insolvency__r.Trustee__r.Follow_up_Email__c</formula>
    <label>Follow-up Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_City__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Fax_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Fax Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Phone Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province_Short_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province_Short_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province Short Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Website__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Website</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Payment_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Payment_Postal_Code__c</fullName>
    <description>This field is used for CFG Mailing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field is used for CFG Mailing</inlineHelpText>
    <label>CFG Payment Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Trustee_Email_Default_Content__c.field-meta.xml
<CustomField>
    <fullName>CFG_Trustee_Email_Default_Content__c</fullName>
    <description>Contains the (HTML optional) default content to be pre-populated when the Email Trustee page is opened from an Insolvency Account record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Contains the (HTML optional) default content to be pre-populated when the Email Trustee page is opened from an Insolvency Account record.</inlineHelpText>
    <label>CFG Trustee Email Default Content</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Trustee_Email_Default_Subject__c.field-meta.xml
<CustomField>
    <fullName>CFG_Trustee_Email_Default_Subject__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Trustee Email Default Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name_French__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name_French__c</fullName>
    <description>French Client Company Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name French</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoPocAutomationBatchTest.cls
/**
 * @description       : Test class for NoPocAutomationBatch
 * @author            : adesh.ikhar@canaccede.com
 * @last modified on  : 02-25-2025
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
@isTest
public class NoPocAutomationBatchTest {
    @TestSetup
    static void makeData() {
        PoC_Package_Settings__c poc = new PoC_Package_Settings__c(
            Name = 'Scotia Bank',
            CFG_Trustee_Email_Default_content__c = 'test',
            CFG_Trustee_Email_Default_Subject__c = 'test',
            CFG_Office_Name__c = 'Test',
            CFG_Office_Address_1__c = 'PO Box 758 STN B',
            CFG_Office_Address__c = 'PO Box 758 STN B',
            CFG_Office_Fax_Number__c = '844-827-9220',
            CFG_Office_Phone_Number__c = '844-827-9222',
            CFG_Office_City__c = 'London',
            CFG_Office_Province_Short_Code__c = 'ON',
            CFG_Office_Postal_Code__c = 'N6A 4Y8',
            CFG_Payment_Postal_Code__c = 'N6A 4Y8',
            CFG_Office_Email_Address__c = 'test@canaccede.com',
            CFG_Office_Website__c = 'www.google.com',
            CFG_Office_Province__c = 'Test',
            Company_Name__c = 'Test',
            Client_Company_Name_French__c = 'Test',
            Client_Company_Name__c = 'Test'
        );
        PoC_Package_Settings__c ctb = new PoC_Package_Settings__c(
            Name = 'Canadian Tire',
            CFG_Trustee_Email_Default_content__c = 'test',
            CFG_Trustee_Email_Default_Subject__c = 'test',
            CFG_Office_Name__c = 'Test',
            CFG_Office_Address_1__c = 'PO Box 758 STN B',
            CFG_Office_City__c = 'London',
            CFG_Office_Province_Short_Code__c = 'ON',
            CFG_Office_Postal_Code__c = 'N6A 4Y8',
            CFG_Payment_Postal_Code__c = 'N6A 4Y8',
            CFG_Office_Fax_Number__c = '844-827-9220',
            CFG_Office_Phone_Number__c = '844-827-9222',
            CFG_Office_Email_Address__c = 'test@canaccede.com',
            CFG_Office_Website__c = 'www.google.com',
            CFG_Office_Province__c = 'Test',
            Company_Name__c = 'Test',
            Client_Company_Name_French__c = 'Test',
            Client_Company_Name__c = 'Test'
        );
        insert new List<PoC_Package_Settings__c>{ poc, ctb };

        Account acct = new Account();
        acct.Name = 'Test Account';
        acct.fax = '651426256';
        acct.Follow_up_Email__c = 'test283@yopmail.com';
        acct.Business_Email__c = 'test11283@yopmail.com';
        acct.Preferred_Language__c = 'French';
        insert acct;

        Insolvency__c inslv = new Insolvency__c();
        inslv.Name = 'Test-Email0010';
        inslv.Debtor_1_First_Name__c = 'first';
        inslv.Debtor_1_Last_Name__c = 'last';
        inslv.Trustee__c = acct.Id;
        insert inslv;

        Insolvency_Account__c acc = new Insolvency_Account__c();
        acc.RecordTypeId = Schema.SObjectType.Insolvency_Account__c.getRecordTypeInfosByName().get('Scotia Bank Insolvency Account').getRecordTypeId();
        acc.Name = 'Test- 001';
        acc.Insolvency__c = [SELECT Id FROM Insolvency__c LIMIT 1][0].Id;
        acc.Borrower_Primary__c = 'TestData';
        acc.Client_Identifier__c = 'Scotia Bank';
        acc.Balance_Owed__c = 20.0;
        acc.Amended_Claim_Flag__c = false;
        acc.Insolvency_Status__c = 'No PoC Required';
        acc.Reason_for_No_PoC_Required_Dropdown__c = 'Unable to Locate Account';
        acc.Claim_Amount__c = 100;
        acc.Insolvency_Status_Last_Changed__c = System.Today();
        acc.Account_Number_Without_Space__c = 'Test-001';
        acc.Insolvency_Type__c = 'Consumer Proposal';
        acc.Acknowledgement_date__c = System.today();
        insert acc;
    }

    @isTest
    static void automationBatchTest() {
        Test.startTest();
        NoPocAutomationBatch noPocBatch = new NoPocAutomationBatch();
        Database.executeBatch(noPocBatch);
        Test.stopTest();
    }

    @isTest
    static void schedulerTest() {
        Test.startTest();
        NoPocAutomationBatch noPocBatch = new NoPocAutomationBatch();
        String sch = '0 0 23 * * ?';
        System.schedule('Test automation Check', sch, noPocBatch);
        Test.stopTest();
    }
}