force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Reason_for_No_PoC_Required_Dropdown__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_No_PoC_Required_Dropdown__c</fullName>
    <description>Reason for No PoC Required</description>
    <inlineHelpText>Reason for No PoC Required</inlineHelpText>
    <label>Reason for No PoC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Open Accounts</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unable to Locate Account</fullName>
            </value>
            <value>
                <fullName>Account Sold</fullName>
            </value>
            <value>
                <fullName>Proposal: Secured file</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SDA Account</fullName>
            </value>
            <value>
                <fullName>Scotia Private Label Account</fullName>
            </value>            
            <value>
                <fullName>BNS Account</fullName>
            </value>
            <value>
                <fullName>Not SDA Account</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
            <value>
                <fullName>Repo’d – Seize or Sue</fullName>
            </value>
            <value>
                <fullName>Unable to Locate</fullName>
            </value>
            <value>
                <fullName>Below Threshold</fullName>
            </value>
            <value>
                <fullName>Settled/PIF</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>DOB mismatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Secured_Name__c.field-meta.xml
<CustomField>
    <fullName>Secured_Name__c</fullName>
    <formula>IF((LEN(Name) &gt; 12 &amp;&amp;  Insolvency__r.Trustee__r.Parent.Name = &apos;Service Nova Scotia&apos;), ( LEFT( Name ,  (LEN(Name) - 3) ) + &apos;XXX&apos;), Name)</formula>
    <label>Secured Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/PoC_Package_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These setting are used by the Insolvency Stream solution, as input into the Proof of Claims form generation.</description>
    <label>PoC Package Settings</label>
</CustomObject>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_City__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Province_Short_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Province_Short_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Province Short Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Office_Website__c.field-meta.xml
<CustomField>
    <fullName>CFG_Office_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Office Website</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/CFG_Payment_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>CFG_Payment_Postal_Code__c</fullName>
    <description>This field is used for CFG Mailing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field is used for CFG Mailing</inlineHelpText>
    <label>CFG Payment Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Client_Company_Name_French__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name_French__c</fullName>
    <description>French Client Company Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Company Name French</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoC_Package_Settings__c/fields/Trustee_Email_Org_Wide_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Email_Org_Wide_Address_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trustee Email Org Wide Address Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoPocAutomationBatch.cls
/**
 * @description       : Batch to automate additional information/Trustee follow up
 * @author            : adesh.ikhar@canaccede.com
 * @last modified on  : 02-25-2025
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class NoPocAutomationBatch implements Schedulable, Database.Batchable<SObject> {
    public Map<String, String> clientIdentifierTemplateNameMap = new Map<String, String>{
        'Fidem' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Goeasy' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Fairstone' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Money Mart' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Canadian Tire' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Canaccede' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE',
        'Scotia Bank' => 'ADDITIONAL_INFORMATION_REQUIRE',
        'SPL' => 'ADDITIONAL_INFORMATION_REQUIRE',
        'SDA' => 'ADDITIONAL_INFORMATION_REQUIRE',
        'Goeasy_French' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE_French',
        'Fairstone_French' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE_French',
        'Money Mart_French' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE_French',
        'Canaccede_French' => 'ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE_French',
        'Scotia Bank_French' => 'ADDITIONAL_INFORMATION_REQUIRE_French',
        'SPL_French' => 'ADDITIONAL_INFORMATION_REQUIRE_French',
        'SDA_French' => 'ADDITIONAL_INFORMATION_REQUIRE_French',
        'Canadian Tire_French' => 'ADDITIONAL_INFORMATION_REQUIRE_CANADIAN_TIRE_French'
    };
    public Database.Querylocator start(Database.BatchableContext bc) {
        List<String> eligibleStatuses = System.Label.Additional_Info_Required_Statuses.split(',');
        List<String> eligibleReasons = System.Label.Additional_Info_Required_Reasons.split(',');
        return Database.getQueryLocator(
            'SELECT Id, Insolvency__r.Trustee__r.Preferred_Language__c, Insolvency__r.Trustee__r.Business_Email__c, Client_Identifier__c, Secured_Name__c, Name, Insolvency__r.Name From Insolvency_Account__c WHERE Insolvency_Status__c IN :eligibleStatuses AND Reason_for_No_PoC_Required_Dropdown__c IN :eligibleReasons'
        );
    }

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new NoPocAutomationBatch(), 10);
    }

    public void execute(Database.BatchableContext bc, List<Insolvency_Account__c> insolvAccList) {
        Savepoint sp = Database.setSavepoint();
        try {
            startProcessing(insolvAccList);
            updateAccountStatus(insolvAccList);
        } catch (Exception ex) {
            Database.rollback(sp);
            System.debug('Exception in PocAutomationBatch ' + ex.getStackTraceString());
            insert PocDocUtility.handleException(ex, insolvAccList[0].Id);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

    /**
     * @description : Method to update account status to 'Trustee Followup'
     * @author adesh.ikhar@canaccede.com | 02-24-2025
     * @param insolvAccList
     **/
    public void updateAccountStatus(List<Insolvency_Account__c> insolvAccList) {
        for (Insolvency_Account__c insolvAcc : insolvAccList) {
            insolvAcc.Insolvency_Status__c = 'Trustee Followup';
        }
        Database.update(insolvAccList);
    }

    /**
     * @description : Process accounts to send email
     * @author adesh.ikhar@canaccede.com | 02-24-2025
     * @param insolvAccList
     **/
    public void startProcessing(List<Insolvency_Account__c> insolvAccList) {
        List<Messaging.SingleEmailMessage> singleEmailMessages = new List<Messaging.SingleEmailMessage>();
        Map<String, EmailTemplate> templateMap = new Map<String, EmailTemplate>();
        Map<String, PoC_Package_Settings__c> clientIdentifierPocPackageMap = new Map<String, PoC_Package_Settings__c>();
        Set<String> templateDevNameSet = new Set<String>(clientIdentifierTemplateNameMap.values());
        for (EmailTemplate template : [
            SELECT DeveloperName, Subject, Body
            FROM EmailTemplate
            WHERE DeveloperName IN :templateDevNameSet
        ]) {
            templateMap.put(template.DeveloperName, template);
        }
        for (PoC_Package_Settings__c pocSettings : PoC_Package_Settings__c.getall().values()) {
            clientIdentifierPocPackageMap.put(pocSettings.Name, pocSettings);
        }
        for (Insolvency_Account__c insolvAcc : insolvAccList) {
            String language = String.isBlank(insolvAcc.Insolvency__r.Trustee__r.Preferred_Language__c)
                ? 'English'
                : insolvAcc.Insolvency__r.Trustee__r.Preferred_Language__c;
            String templateName = language == 'English' ? insolvAcc.Client_Identifier__c : insolvAcc.Client_Identifier__c + '_French';
            EmailTemplate template = clientIdentifierTemplateNameMap.containsKey(templateName)
                ? templateMap.get(clientIdentifierTemplateNameMap.get(templateName))
                : templateMap.get('ADDITIONAL_INFORMATION_REQUIRE_FAIRSTONE');
            PoC_Package_Settings__c pocPackageSettings = clientIdentifierPocPackageMap.get(insolvAcc.Client_Identifier__c);
            // Generate email message record
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new List<String>{ insolvAcc.Insolvency__r.Trustee__r.Business_Email__c });
            mail.setSubject(updateSubject(template.subject, insolvAcc));
            mail.setHTMLBody(updateBody(template.Body, pocPackageSettings, insolvAcc, language));
            // Set activity true to create activity once email is send
            mail.setSaveAsActivity(true);
            mail.setWhatId(insolvAcc.Id);
            mail.setOrgWideEmailAddressId(pocPackageSettings.Trustee_Email_Org_Wide_Address_Id__c);
            singleEmailMessages.add(mail);
        }
        // Send emails
        if (!singleEmailMessages.isEmpty()) {
            Messaging.sendEmail(singleEmailMessages);
        }
    }

    /**
     * @description : Method to update subject using merge fields
     * @author adesh.ikhar@canaccede.com | 02-24-2025
     * @param subject
     * @param insolvAcc
     **/
    public String updateSubject(String subject, Insolvency_Account__c insolvAcc) {
        if (subject.contains('{!Insolvency_Account__c.Secured_Name__c}')) {
            subject = subject.replace('{!Insolvency_Account__c.Secured_Name__c}', (insolvAcc.Secured_Name__c != null ? insolvAcc.Secured_Name__c : ''));
        }
        if (subject.contains('{!Insolvency_Account__c.Name}')) {
            subject = subject.replace('{!Insolvency_Account__c.Name}', (insolvAcc.Name != null ? insolvAcc.Name : ''));
        }
        if (subject.contains('{!Insolvency__r.Name}')) {
            subject = subject.replace('{!Insolvency__r.Name}', insolvAcc.Insolvency__r.Name);
        }
        return subject;
    }

    /**
     * @description : Method to update email body using merge fields
     * @author adesh.ikhar@canaccede.com | 02-24-2025
     * @param emailBody
     * @param pocPackage
     * @param insolvAcc
     * @param language
     **/
    public String updateBody(String emailBody, PoC_Package_Settings__c pocPackage, Insolvency_Account__c insolvAcc, String language) {
        if (emailBody.contains('{!Insolvency_Account__c.Secured_Name__c}')) {
            emailBody = emailBody.replace('{!Insolvency_Account__c.Secured_Name__c}', (insolvAcc.Secured_Name__c != null ? insolvAcc.Secured_Name__c : ''));
        }
        if (emailBody.contains('{!Insolvency__r.Name}')) {
            emailBody = emailBody.replace('{!Insolvency__r.Name}', insolvAcc.Insolvency__r.Name);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Name__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Name__c}', pocPackage.CFG_Office_Name__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Website__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Website__c}', pocPackage.CFG_Office_Website__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Province__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Province__c}', pocPackage.CFG_Office_Province__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Address_1__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Address_1__c}', pocPackage.CFG_Office_Address_1__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Address__c}')) {
            emailBody = emailBody.replace(
                '{!pocPackage.CFG_Office_Address__c}',
                (pocPackage.CFG_Office_Address__c != null ? pocPackage.CFG_Office_Address__c : '')
            );
        }
        if (emailBody.contains('{!pocPackage.Name}')) {
            emailBody = emailBody.replace('{!pocPackage.Name}', pocPackage.Name);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_City__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_City__c}', pocPackage.CFG_Office_City__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Province_Short_Code__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Province_Short_Code__c}', pocPackage.CFG_Office_Province_Short_Code__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Postal_Code__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Postal_Code__c}', pocPackage.CFG_Office_Postal_Code__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Payment_Postal_Code__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Payment_Postal_Code__c}', pocPackage.CFG_Payment_Postal_Code__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Email_Address__c}')) {
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Email_Address__c}', pocPackage.CFG_Office_Email_Address__c);
        }
        if (emailBody.contains('{!pocPackage.Company_Name__c}')) {
            emailBody = emailBody.replace('{!pocPackage.Company_Name__c}', pocPackage.Company_Name__c);
        }
        if (emailBody.contains('{!pocPackage.Client_Company_Name_French__c}')) {
            emailBody = emailBody.replace('{!pocPackage.Client_Company_Name_French__c}', pocPackage.Client_Company_Name_French__c);
        }
        if (emailBody.contains('{!pocPackage.Client_Company_Name__c}')) {
            emailBody = emailBody.replace('{!pocPackage.Client_Company_Name__c}', pocPackage.Client_Company_Name__c);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Fax_Number__c}')) {
            String numberVal = pocPackage.CFG_Office_Fax_Number__c;
            if (language == 'French') {
                numberVal = numberVal.replace('-', '.');
            }
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Fax_Number__c}', numberVal);
        }
        if (emailBody.contains('{!pocPackage.CFG_Office_Phone_Number__c}')) {
            String numberVal = pocPackage.CFG_Office_Phone_Number__c;
            if (language == 'French') {
                numberVal = numberVal.replace('-', '.');
            }
            emailBody = emailBody.replace('{!pocPackage.CFG_Office_Phone_Number__c}', numberVal);
        }
        if (language == 'French') {
            emailBody = emailBody.replace(
                '{!Additional_Info_Text}',
                'Comme vous le savez, Canaccede International Management Ltd. traite les comptes insolvables de ' + pocPackage.Client_Company_Name__c
            );
        } else {
            emailBody = emailBody.replace(
                '{!Additional_Info_Text}',
                'As you are aware, Canaccede International Management Ltd is processing ' + pocPackage.Client_Company_Name__c + ' insolvent accounts'
            );
        }
        String emailBodyCustomized = '';
        if (emailBody != null) {
            for (String s : emailBody.split('\n')) {
                emailBodyCustomized = emailBodyCustomized + s + '<br/>';
            }
        }
        String htmlBody = '<body style="clear:both;">' + emailBodyCustomized + '</body>';
        return htmlBody;
    }
}