force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Co_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Co_Debtor__c</fullName>
    <description>Name of the co-debtor</description>
    <formula>Debtor_2_First_Name__c + &apos; &apos; + Debtor_2_Last_Name__c</formula>
    <inlineHelpText>Name of the co-debtor</inlineHelpText>
    <label>Co-Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <formula>Debtor_1_First_Name__c + &apos; &apos; + Debtor_1_Last_Name__c</formula>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status_Last_Changed__c</fullName>
    <description>The date and time of the most recent insolvency status change.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date and time of the most recent insolvency status change.</inlineHelpText>
    <label>Insolvency Status Last Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fidem</fullName>
            </value>
            <value>
                <fullName>Canaccede</fullName>
            </value>
            <value>
                <fullName>Scotia Bank</fullName>
            </value>
            <value>
                <fullName>SDA</fullName>
            </value>
            <value>
                <fullName>SPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Co_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Co_Debtor__c</fullName>
    <description>Name of the co-debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the co-debtor</inlineHelpText>
    <label>Co-Debtor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Date_LOR_received_for_Secured__c.field-meta.xml
<CustomField>
    <fullName>Date_LOR_received_for_Secured__c</fullName>
    <description>The date that the Letter of Release was received for the account&apos;s security.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the Letter of Release was received for the account&apos;s security.</inlineHelpText>
    <label>Date LoR Received For Secured</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Last_Name__c</fullName>
    <description>Last name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the primary debtor</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status_Last_Changed__c</fullName>
    <description>The date and time of the most recent insolvency status change.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date and time of the most recent insolvency status change.</inlineHelpText>
    <label>Processing Status Last Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Indicates whether Trustee Office is active or not</description>
    <formula>Insolvency__r.Trustee__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether Trustee Office is active or not</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/PoC_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PoC_Created_Date__c</fullName>
    <description>Proof of Claim Created Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proof of Claim Created Date</inlineHelpText>
    <label>Original PoC Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Security_Description__c.field-meta.xml
<CustomField>
    <fullName>Security_Description__c</fullName>
    <description>A description of the asset secured against this account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A description of the asset secured against this account.</inlineHelpText>
    <label>Security Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Security_Type__c.field-meta.xml
<CustomField>
    <fullName>Security_Type__c</fullName>
    <description>The type of asset secured against this account.</description>
    <inlineHelpText>The type of asset secured against this account.</inlineHelpText>
    <label>Security Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Property</fullName>
            </value>
            <value>
                <fullName>Movable Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Trustee_Company__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Company__c</fullName>
    <description>The company name of the debtor&apos;s insolvency trustee</description>
    <formula>Insolvency__r.Trustee_Company_Name_Formula__c</formula>
    <inlineHelpText>The company name of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Trustee_Office__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Office__c</fullName>
    <description>The company office name of the debtor&apos;s insolvency trustee</description>
    <formula>Insolvency__r.Trustee_Name_Formula__c</formula>
    <inlineHelpText>The company office name of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LorVfTemplateController.cls
/**
 * @description       : Controller class for LOR demand VF email templates
 * @author            : adesh.ikhar@canaccede.com
 * @last modified on  : 07-30-2024
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class LorVfTemplateController {
    public Insolvency_Account__c insolvAcc { get; set; }
    public PoC_Package_Settings__c pocPackage { get; set; }
    public LorInformationWrapper otherInfo { get; set; }
    public LorVfTemplateController() {
        insolvAcc = [
            SELECT
                Id,
                Insolvency__r.Trustee__r.Communication_Preference__c,
                Insolvency__r.Trustee__r.Business_Email__c,
                Insolvency__r.Trustee__r.Fax,
                Trustee_Company__c,
                Trustee_Office__c,
                Insolvency__r.Trustee__r.Preferred_Language__c,
                Insolvency__r.Debtor__c,
                Is_Active__c,
                Insolvency__r.Co_Debtor__c,
                Security_Type__c,
                Security_Description__c,
                Insolvency_Status_Last_Changed__c,
                Client_Identifier__c,
                Claim_Type__c,
                Insolvency__r.Name,
                Name,
                Insolvency__r.Debtor_1_First_Name__c,
                Insolvency__r.Debtor_1_Last_Name__c,
                Date_LOR_received_for_Secured__c,
                PoC_Created_Date__c,
                Insolvency_Status__c,
                Secured_Name__c,
                LOR_Notice_1_Sent_Date__c,
                LOR_Notice_2_Sent_Date__c,
                LoR_Notice_1_FollowUp_Date__c,
                Vehicle_Identification_Number__c,
                Account_Type__c,
                Bank_Name__c
            FROM Insolvency_Account__c
            WHERE Id = :ApexPages.currentPage().getParameters().get('Id')
        ];
        populateInformation(insolvAcc, ApexPages.currentPage().getParameters().get('selectedLanguage'));
    }

    /**
     * @description : Method to assign/reassign correct values as per conditions
     * @author adesh.ikhar@canaccede.com | 07-30-2024
     * @param insolvAcc
     * @param languageValue
     **/
    public void populateInformation(Insolvency_Account__c insolvAcc, String languageValue) {
        Set<String> fairstoneProductTypes = new Set<String>{ 'Secured', 'PL Unsecured', 'PL Secured', 'PL Auto Secured', 'Retail', 'Auto Loans' };
            
        pocPackage = PoC_Package_Settings__c.getValues(insolvAcc.Client_Identifier__c);
        Date dateToday = System.Today();
        otherInfo = new LorInformationWrapper();
        // Convert DateTime to Date format ex: May 01, 2018
        String formattedDate = DateTime.newInstance(dateToday.year(), dateToday.month(), dateToday.day()).formatGMT('MMM dd, YYYY');
        String companyName = pocPackage.Company_Name__c;
        String clientCompanyName = pocPackage.Client_Company_Name__c;
        String bankNameWiseCompanyName = pocPackage.Client_Company_Name__c;
        String bankNameWiseFrenchCompanyName = pocPackage.Client_Company_Name_French__c;
        // Only used in French template
        String clientCompanyNameSuffix = ' (« Banque Scotia »)';
        if (insolvAcc.Client_Identifier__c == 'Goeasy' && insolvAcc.Account_Type__c == 'Leasing product') {
            pocPackage.Client_Company_Name__c = pocPackage.CFG_Office_Name_2__c;
            clientCompanyNameSuffix = '';
            companyName = pocPackage.CFG_Office_Name_2__c;
            clientCompanyName = pocPackage.CFG_Office_Name_2__c.toUppercase();
            bankNameWiseCompanyName = pocPackage.Company_Name__c;
            bankNameWiseFrenchCompanyName = pocPackage.Company_Name__c;
            if (languageValue == 'fr') {
                pocPackage.Client_Company_Name_French__c = pocPackage.CFG_Office_Name_2__c;
            }
        }
        if (insolvAcc.Client_Identifier__c == 'Goeasy' && insolvAcc.Account_Type__c != 'Leasing product') {
            clientCompanyNameSuffix = '';
            companyName = 'Easyfinancial';
            clientCompanyName = companyName.toUppercase();
            bankNameWiseCompanyName = pocPackage.Company_Name__c;
            bankNameWiseFrenchCompanyName = pocPackage.Company_Name__c;
            if (languageValue == 'fr') {
                pocPackage.Client_Company_Name_French__c = 'Easyfinancial';
            }
        }
        if (insolvAcc.Client_Identifier__c == 'Fairstone' && fairstoneProductTypes.contains(insolvAcc.Account_Type__c)) {
            clientCompanyName = pocPackage.Fairstone_New_Product_Company_Detail__c;
            companyName = pocPackage.Fairstone_New_Product_Company_Detail__c;
            pocPackage.Client_Company_Name_French__c = pocPackage.Fairstone_New_Product_Company_Detail__c;
        }
        
        pocPackage.Client_Company_Name__c = pocPackage.Client_Company_Name__c.toUppercase();
        pocPackage.CFG_Office_Phone_Number__c = pocPackage.CFG_Office_Phone_Number__c.replace('-', '.');
        pocPackage.CFG_Office_Fax_Number__c = pocPackage.CFG_Office_Fax_Number__c.replace('-', '.');
        // Populate wrapped fields which cannot be reassigned to object fields
        otherInfo.isEnglish = languageValue != 'fr';
        otherInfo.imageUrl = insolvAcc.Client_Identifier__c == 'Goeasy'
            ? LoRDemandController.getImageUrl('CFG_monogram_Logo')
            : LoRDemandController.getImageUrl('CFG_Logo_Temp1');
        otherInfo.today = formattedDate;
        otherInfo.debitors =
            (insolvAcc.Insolvency__r.Debtor__c != null ? insolvAcc.Insolvency__r.Debtor__c : '') +
            (insolvAcc.Insolvency__r.Co_Debtor__c != null
                ? (insolvAcc.Insolvency__r.Debtor__c != null ? ', ' : '') + insolvAcc.Insolvency__r.Co_Debtor__c
                : '');
        otherInfo.companyName = companyName;
        otherInfo.clientCompanyName = clientCompanyName;
        otherInfo.clientCompanyNameSuffix = clientCompanyNameSuffix;
        otherInfo.fiveBusinessDays = LoRDemandController.WeekdayCalculate();
        otherInfo.bankNameWiseCompanyName = bankNameWiseCompanyName;
        otherInfo.bankNameWiseFrenchCompanyName = bankNameWiseFrenchCompanyName;
        otherInfo.insolvencyStatusLastChanged = String.valueOf(insolvAcc.Insolvency_Status_Last_Changed__c.formatGMT('MMM dd, YYYY'));
        otherInfo.noticeOneSentDate = (insolvAcc.LOR_Notice_1_Sent_Date__c != null
            ? DateTime.newInstance(
                      insolvAcc.LOR_Notice_1_Sent_Date__c.year(),
                      insolvAcc.LOR_Notice_1_Sent_Date__c.month(),
                      insolvAcc.LOR_Notice_1_Sent_Date__c.day()
                  )
                  .format('MMM dd, YYYY')
            : '');
    }

    // Wrapper class for extra fields
    public class LorInformationWrapper {
        public Boolean isEnglish { get; set; }
        public String imageUrl { get; set; }
        public String noticeOneSentDate { get; set; }
        public String insolvencyStatusLastChanged { get; set; }
        public String today { get; set; }
        public String debitors { get; set; }
        public String companyName { get; set; }
        public String clientCompanyName { get; set; }
        public String clientCompanyNameSuffix { get; set; }
        public String fiveBusinessDays { get; set; }
        public String bankNameWiseCompanyName { get; set; }
        public String bankNameWiseFrenchCompanyName { get; set; }
    }
}