force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Follow_Up_Counter__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Counter__c</fullName>
    <description>This field will be default to zero and it will be incremented for each follow-up email sent.</description>
    <label>Follow Up Counter</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Missing_payment_Follow_Up_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Missing_payment_Follow_Up_Sent_Date__c</fullName>
    <description>Date when missing payment follow up reminder was sent to trustee</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date when missing payment follow up reminder was sent to trustee</inlineHelpText>
    <label>Missing Payment Follow-up Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company office of the debtor&apos;s insolvency trustee</description>
    <inlineHelpText>The company office of the debtor&apos;s insolvency trustee</inlineHelpText>
    <label>Trustee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insolvencies (Trustee)</relationshipLabel>
    <relationshipName>InsolvencyRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee_Communication_Preference_Formula__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Communication_Preference_Formula__c</fullName>
    <description>Trustee Communication Preference</description>
    <formula>Text(Trustee__r.Communication_Preference__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Trustee Communication Preference</inlineHelpText>
    <label>Trustee Communication Preference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee_Email_Address_Formula__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Email_Address_Formula__c</fullName>
    <description>The email address of the debtor’s insolvency trustee office</description>
    <formula>Trustee__r.Business_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The email address of the debtor’s insolvency trustee office</inlineHelpText>
    <label>Trustee Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee_Fax_Formula__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Fax_Formula__c</fullName>
    <description>The trustee&apos;s FAX number</description>
    <formula>Trustee__r.Fax</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The trustee&apos;s FAX number</inlineHelpText>
    <label>Trustee Fax</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <description>This field tracks the status of this account as an asset to Canaccede.</description>
    <inlineHelpText>This field tracks the status of this account as an asset to Canaccede.</inlineHelpText>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>De-securitized by Seller</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Putback</fullName>
            </value>
            <value>
                <fullName>De-securitization requested</fullName>
            </value>
            <value>
                <fullName>Bulk Purchased</fullName>
            </value>
            <value>
                <fullName>Duplicate Purchased</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Putback Pending</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>Debt Purchase</fullName>
            </value>
            <value>
                <fullName>Buyback Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <formula>CASE(TEXT(Client_Identifier__c), &apos;Goeasy&apos;, &apos;Easyfinancial&apos;, TEXT(Client_Identifier__c))</formula>
    <inlineHelpText>Bank Name</inlineHelpText>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The debtor estate number as noted on the creditor’s package</inlineHelpText>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Last_Name__c</fullName>
    <description>Last name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the primary debtor</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Excluded_from_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Excluded_from_Purchase__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Excluded from Purchase</description>
    <inlineHelpText>Excluded from Purchase</inlineHelpText>
    <label>Excluded from Purchase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Missing_Payment_Follow_up_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Missing_Payment_Follow_up_Sent_Date__c</fullName>
    <description>Date when missing payment follow up reminder was sent to trustee</description>
    <formula>Insolvency__r.Missing_payment_Follow_Up_Sent_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Date when missing payment follow up reminder was sent to trustee</inlineHelpText>
    <label>Missing Payment Follow up Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Portfolio_Name_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Name_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Portfolio Name object</description>
    <inlineHelpText>Lookup to Portfolio Name object</inlineHelpText>
    <label>Portfolio Name</label>
    <referenceTo>Portfolio_Name__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio_Name__c/Portfolio_Name__c.object-meta.xml
<CustomObject>
    <label>Portfolio Name</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Name__c/fields/Non_Servicing_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Non_Servicing_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Portfolio not serviced by Canaccede</description>
    <inlineHelpText>Portfolio not serviced by Canaccede</inlineHelpText>
    <label>Non Servicing Portfolio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trustee_Payment_Followup_Setting__c/Trustee_Payment_Followup_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trustee Payment Followup Setting</label>
</CustomObject>

force-app/main/default/objects/Trustee_Payment_Followup_Setting__c/fields/Additional_Follow_up_After_X_Months__c.field-meta.xml
<CustomField>
    <fullName>Additional_Follow_up_After_X_Months__c</fullName>
    <description>The value in this field will be used to do second follow-up after the mentioned number of months</description>
    <label>Additional Follow-up After X Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trustee_Payment_Followup_Setting__c/fields/Follow_up_Max_Limit__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Max_Limit__c</fullName>
    <description>The value in this field will be used to decide on how many follow-ups needs to be made</description>
    <label>Follow-up Max Limit</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrusteeFollowupBatch.cls
/***************************************************
 * Author         : A5E Consultancy
 * Created On     : 1 March 2020
 * Description    : Send email to trustee if they are unsecured and doesnt do payment for 18 months
 *
 ***************************************************/
public class TrusteeFollowupBatch implements Database.Batchable<sobject> {
    public Time myTime = Time.newInstance(0, 0, 0, 0);
    // Start Method
    public Database.Querylocator start(Database.BatchableContext bc) {
        // List values to be used as filters in SOQL query
        List<String> assetStatus = new List<String>{ '', 'Purchased', 'Debt Purchase', 'Bulk Purchased' };
        List<String> insolvencyTypes = new List<String>{ 'Consumer Proposal', 'Division 1 Proposal' };
        List<String> insolvencyAccntRecordTypes = System.Label.Trustee_Follow_Up_Record_Types.split(',');

        Trustee_Payment_Followup_Setting__c tpfs = Trustee_Payment_Followup_Setting__c.getValues('Trustee Payment Followup');
        Integer additionalFollowupXMonths = Integer.ValueOf(tpfs.Additional_Follow_up_After_X_Months__c);
        DateTime monthsPriorFromToday = DateTime.newInstance(System.today().addmonths(-additionalFollowupXMonths), myTime);
        Integer followUpMaxLimit = Integer.ValueOf(tpfs.Follow_up_Max_Limit__c);

        // Fetch all active unsecured accounts
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Trustee__c,
                    Name,
                    Missing_Payment_Follow_up_Sent_Date__c,
                    Trustee_Email_Address_Formula__c,
                    Trustee_Communication_Preference_Formula__c,
                    Trustee_Fax_Formula__c,
                    Client_Identifiers__c,
                    Debtor_1_First_Name__c,
                    Debtor_1_Last_Name__c,
                    Follow_Up_Counter__c,
                    (
                        SELECT Id, Name, Debtor_1_Estate_Number__c, Bank_Name__c
                        FROM Insolvency_Accounts__r
                        WHERE
                            Portfolio_Name_Lookup__r.Non_Servicing_Portfolio__c = FALSE
                            AND Asset_Status__c IN :assetStatus
                            AND Excluded_from_Purchase__c = FALSE
                            AND Insolvency_Status__c = 'Claim Filed'
                            AND RecordType.DeveloperName IN :insolvencyAccntRecordTypes
                            AND Claim_Type__c = 'Unsecured'
                            AND Claim_Amount__c >= 250
                            AND Date_NOD_received__c = NULL
                            AND Disallowance_Reasons__c = NULL
                            AND (((Latest_Payment_Date__c = NULL
                            OR Send_Follow_up_Email__c = TRUE)
                            AND Missing_Payment_Follow_up_Sent_Date__c = NULL)
                            OR (Latest_Payment_Date__c = NULL
                            AND Missing_Payment_Follow_up_Sent_Date__c != NULL
                            AND Missing_Payment_Follow_up_Sent_Date__c <= :monthsPriorFromToday))
                    )
                FROM Insolvency__c
                WHERE
                    Insolvency_Status__c = 'Active'
                    AND Insolvency_Type__c IN :insolvencyTypes
                    AND ((Send_Follow_up_Email__c = TRUE
                    AND Missing_Payment_Follow_up_Sent_Date__c = NULL)
                    OR ((Follow_Up_Counter__c = NULL
                    OR Follow_Up_Counter__c <= :followUpMaxLimit)
                    AND Missing_Payment_Follow_up_Sent_Date__c != NULL
                    AND Missing_Payment_Follow_up_Sent_Date__c <= :monthsPriorFromToday))
                    AND Trustee__c != NULL
                    AND Trustee__r.Is_Active__c = TRUE
                    AND Trustee__r.Exclude_From_Missing_Payment_Mail_List__c = FALSE
            ]
        );
    }

    // Execute method
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        Trustee_Payment_Followup_Setting__c tpfs = Trustee_Payment_Followup_Setting__c.getValues('Trustee Payment Followup');
        Integer maxEmailsSentPerDay = Integer.ValueOf(tpfs.Maximum_Emails_Per_Day__c);
        List<Insolvency__c> insolvencies = (List<Insolvency__c>) scope;
        List<Messaging.SingleEmailMessage> singleEmailMessages = new List<Messaging.SingleEmailMessage>();
        Map<String, EmailTemplate> templateMap = new Map<String, EmailTemplate>();

        //Eligible Insolvencies to update
        List<Insolvency__c> insolvenciesToUpdate = new List<Insolvency__c>();
        DateTime local = DateTime.newInstance(System.today(), myTime);

        Set<Id> trusteeIds = new Set<Id>();
        for (Insolvency__c insolvency : insolvencies) {
            if (insolvency.Trustee__c != null) {
                trusteeIds.add(insolvency.Trustee__c);
            }
        }

        Map<Id, Account> trusteeMap = new Map<Id, Account>(
            [
                SELECT
                    Id,
                    Number_Of_Emails_Sent_Today__c,
                    Communication_Preference__c,
                    Business_Email__c,
                    Fax,
                    Last_Trustee_Followup_Sent_Date__c,
                    Follow_up_Email__c,
                    Preferred_Language__c
                FROM Account
                WHERE Id IN :trusteeIds
            ]
        );

        for (EmailTemplate template : [
            SELECT DeveloperName, Subject, HtmlValue
            FROM EmailTemplate
            WHERE DeveloperName IN ('Trustee_Followup_Email_Template', 'Trustee_Followup_Email_Template_French')
        ]) {
            templateMap.put(template.DeveloperName, template);
        }

        for (Insolvency__c insolvency : insolvencies) {
            Account trustee = trusteeMap.get(insolvency.Trustee__c);
            // Get Insolvency Account related to Account
            List<Insolvency_Account__c> insolvencyAccounts = insolvency.Insolvency_Accounts__r;
            if (!insolvencyAccounts.isEmpty()) {
                // Use custom setting to read maximum emails to be sent
                if (trustee.Number_Of_Emails_Sent_Today__c < maxEmailsSentPerDay && insolvencyAccounts != null && insolvencyAccounts.size() > 0) {
                    String templateName = 'Trustee_Followup_Email_Template';
                    if (String.isNotBlank(trustee.Preferred_Language__c) && trustee.Preferred_Language__c == 'French') {
                        templateName = templateName + '_French';
                    }
                    //Create Email
                    Messaging.SingleEmailMessage email = TrusteeFollowUpBatchHelper.generateSingleEmailMessage(
                        trustee,
                        insolvency,
                        insolvencyAccounts,
                        templateMap.get(templateName)
                    );
                    if (email != null) {
                        singleEmailMessages.add(email);
                        trustee.Number_Of_Emails_Sent_Today__c = trustee.Number_Of_Emails_Sent_Today__c + 1; // Increment number of emails Sent
                        trusteeMap.put(insolvency.Trustee__c, trustee);

                        // Increment follow up counter
                        if (insolvency.Follow_Up_Counter__c == null) {
                            insolvency.Follow_Up_Counter__c = 0;
                        }
                        insolvency.Follow_Up_Counter__c = insolvency.Follow_Up_Counter__c + 1;

                        //Set Missing Follow up Date
                        insolvency.Missing_payment_Follow_Up_Sent_Date__c = local;

                        //Set Last Trustee Followup Sent Date
                        trustee.Last_Trustee_Followup_Sent_Date__c = local;

                        //Insolvency is eligible for update
                        insolvenciesToUpdate.add(insolvency);
                    }
                }
            }
        }

        // Send emails and update Trustee, and Accounts
        if (!singleEmailMessages.isEmpty()) {
            if (!Test.isRunningTest()) {
                Messaging.SendEmailResult[] emailResult = Messaging.sendEmail(singleEmailMessages);
            }
            if (!trusteeMap.isEmpty()) {
                update trusteeMap.values();
            }

            if (!insolvenciesToUpdate.isEmpty()) {
                InsolvencyTriggerHandler.runInsolvencyTrigger = false;
                update insolvenciesToUpdate;
                InsolvencyTriggerHandler.runInsolvencyTrigger = true;
            }
        }
    }

    // Finish Method
    public void finish(Database.BatchableContext bc) {
        //Do Nothing
    }
}