force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Co_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Co_Debtor__c</fullName>
    <description>Name of the co-debtor</description>
    <formula>Debtor_2_First_Name__c + &apos; &apos; + Debtor_2_Last_Name__c</formula>
    <inlineHelpText>Name of the co-debtor</inlineHelpText>
    <label>Co-Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Date_of_Birth__c</fullName>
    <description>Date of Birth of the primary filer</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Date of Birth of the primary filer</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Date_of_Birth__c</fullName>
    <description>Date of Birth of the secondary filer</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Date of Birth of the secondary filer</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <formula>Debtor_1_First_Name__c + &apos; &apos; + Debtor_1_Last_Name__c</formula>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Date__c</fullName>
    <description>The effective date of the insolvency filing as noted in the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The effective date of the insolvency filing as noted in the creditor’s package</inlineHelpText>
    <label>Insolvency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Co_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Co_Debtor__c</fullName>
    <description>Name of the co-debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the co-debtor</inlineHelpText>
    <label>Co-Debtor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Date_of_Birth__c</fullName>
    <description>Debtor DOB</description>
    <formula>Insolvency__r.Debtor_1_Date_of_Birth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Debtor DOB</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_2_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Date_of_Birth__c</fullName>
    <description>Debtor DOB</description>
    <formula>Insolvency__r.Debtor_2_Date_of_Birth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Debtor DOB</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The debtor estate number as noted on the creditor’s package</inlineHelpText>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsolvencyAccountCopyDataController.cls
/**************************************************************************************************
 *
 *  Class:   InsolvencyAccountCopyDataController
 *
 *  @description : This is a controller class for Insolvency Account Copy Data page
 *  @author : A5E Consulting
 *  @date : 04/04/2018
 
 *************************************************************************************************/
 
 public class InsolvencyAccountCopyDataController {

    // Insolvency Account variable to use in vf page
    public Insolvency_Account__c insolvAcc {set;get;}
    public InsolvencyAccountCopyDataController(ApexPages.StandardController controller) {
        insolvAcc = [Select Insolvency__r.Name, Insolvency__r.Debtor_2_Estate_Number__c, 
                            Insolvency__r.Insolvency_Type__c, Insolvency__r.Insolvency_Date__c, 
                            Insolvency__r.Debtor__c, Insolvency__r.Debtor_1_Date_of_Birth__c, 
                            Insolvency__r.Co_Debtor__c, Insolvency__r.Debtor_2_Date_of_Birth__c 
                            from insolvency_Account__c 
                            where Id =: ApexPages.currentPage().getParameters().get('Id')];
    }
}