force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Is_Record_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Record_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Record Locked</description>
    <inlineHelpText>Is Record Locked</inlineHelpText>
    <label>Is Record Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInsolvencyLockUnlockController.cls
@isTest(seeAllData = false)
public class TestInsolvencyLockUnlockController{
    @testSetup
    static void testData() {
          // insert insolvency account
         Insolvency_Account__c insolvAacc = new Insolvency_Account__c();
         insert insolvAacc ;
         
         // insert insolvency record
         Insolvency__c insolv = new Insolvency__c(name = 'test-insolLock', Is_Record_Locked__c = true);
         insert insolv; 
    }
    
    public testmethod static void  InsolvencyLockUnlock(){
        Insolvency__c insolv = [SELECT Id FROM Insolvency__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('id', insolv.Id);  
        InsolvencyLockUnlockController obj = new InsolvencyLockUnlockController(new ApexPages.StandardController(insolv));
        obj.lockInsolvency();
        obj.unLockInsolvency();
        obj = new InsolvencyLockUnlockController(new ApexPages.StandardController(insolv));
        obj.lockInsolvency();
    }
}