force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Comment_Reply__c.field-meta.xml
<CustomField>
    <fullName>Comment_Reply__c</fullName>
    <description>Comment/Reply</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comment/Reply</inlineHelpText>
    <label>Comment/Reply</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Comments_History__c.field-meta.xml
<CustomField>
    <fullName>Comments_History__c</fullName>
    <description>Comments History</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comments History</inlineHelpText>
    <label>Comments History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Judgment_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Identifier__c</fullName>
    <description>Judgment_Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Judgment_Identifier</inlineHelpText>
    <label>Judgment_Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Latest_Comment__c.field-meta.xml
<CustomField>
    <fullName>Latest_Comment__c</fullName>
    <description>Store the latest comment used for the back end purposes</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Store the latest comment used for the back end purposes</inlineHelpText>
    <label>Latest Comment</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Original_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Original_Creditor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Original Creditor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Settlement_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Identifier__c</fullName>
    <description>Settlement_Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Settlement_Identifier</inlineHelpText>
    <label>Settlement_Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <description>Task Number</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Task Number</inlineHelpText>
    <label>Task Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Work Assignment</description>
    <label>Agency Work Assignment</label>
</RecordType>

force-app/main/default/classes/PortalComplaintProcessor.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : API for portal to saleforce to process Complaint record(consume API)
*  @author : A5E Consulting
*  @date : 23/02/2022

*************************************************************************************************/
@RestResource(urlMapping='/PortalComplaintProcessor/*') 
global class PortalComplaintProcessor {
    
    @HttpPost
    global static string postComplaint(){    
        //Store Response
        RestRequest req = RestContext.request;
        system.debug('req.requestBody: '+req);
        Map<String, Object> mapJSONResponse = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        system.debug('mapJSONResponse: '+mapJSONResponse);
        //Map<String, Object> mapData = (Map<String, Object>) mapJSONResponse.get('Data');
        Map<String, String> mapParameters = new Map<String, String>();
        //system.debug('mapData: '+mapData);
        
        map<String, String> mapHeaders = req.headers;
        
        //iterate through they keys, to store string values
        for(String paramKey : mapJSONResponse.keySet()){
            mapParameters.put(paramKey, String.valueOf(mapJSONResponse.get(paramKey)));
            system.debug('header: ' + paramKey + ' value: ' + mapJSONResponse.get(paramKey));
        } 
        system.debug('authetincated');
        //Decision variables
        //Process the Customer based on Identfier in portal request
        system.debug('param'+mapParameters.get('Identifier'));
        List<Work_Assignment__c> listComplaint = [SELECT ID, Comment_Reply__c, Comments_History__c,Latest_Comment__c,
                                                  Status__c, Original_Creditor__c,Last_Modified_By__c,Settlement_Identifier__c,Judgment_Identifier__c
                                             FROM Work_Assignment__c 
                                             WHERE Task_Number__c =: mapParameters.get('Task_Number')
                                             //AND RecordType.Developername= :'Agency'
                                             LIMIT 1];
        String StatusResponse; 
        Map<String, Object> stringMap = new Map<String, Object>();
        Work_Assignment__c complaint = new Work_Assignment__c();
        if(!listComplaint.isEmpty()){
            complaint = listComplaint[0];    
        }
        StatusResponse = PortalComplaintProcessorUtil.processComplaint(mapParameters, complaint); 

          
        if(StatusResponse == 'success'){     
            stringMap.put('success', true);
            createResponse(JSON.serialize(stringMap, true), 200);               
        }
        else{
            stringMap.put('errors', true);
            stringMap.put('reason', StatusResponse);
            createResponse( JSON.serialize(stringMap, true), 500);
        }
        
        system.debug('StatusResponse:'+StatusResponse);
        return  JSON.serialize(stringMap, true);
    }
    
     public static void createResponse(String responseBody, Integer statusCode) {
        System.debug('statusCode '+statusCode);
        RestContext.response.statusCode = statusCode;
        RestContext.response.responseBody = Blob.valueOf(responseBody);
        RestContext.response.addHeader('Content-Type', 'application/json');
    }

}