force-app/main/default/objects/Customer_Portal_Setting__c/Customer_Portal_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Customer Portal Setting</description>
    <label>Customer Portal Setting</label>
</CustomObject>

force-app/main/default/objects/Customer_Portal_Setting__c/fields/Eligible_Placement_ID__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Placement_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Eligible Placement ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment Transaction</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount</description>
    <inlineHelpText>Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <description>Collection Agency on Product at the time of Payment Transaction</description>
    <inlineHelpText>Collection Agency on Product at the time of Payment Transaction</inlineHelpText>
    <label>Collection Agency</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Record_Type_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/One_time_Payment.recordType-meta.xml
<RecordType>
    <fullName>One_time_Payment</fullName>
    <active>true</active>
    <description>One time Payment</description>
    <label>One time Payment</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Recurring_Payment_Master.recordType-meta.xml
<RecordType>
    <fullName>Recurring_Payment_Master</fullName>
    <active>true</active>
    <description>Recurring Payment Master</description>
    <label>Recurring Payment Master</label>
</RecordType>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Include_In_Portal_Search__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Portal_Search__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Include In Portal Search</description>
    <inlineHelpText>Include In Portal Search</inlineHelpText>
    <label>Include In Portal Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Total Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Effective_Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Effective_Current_Balance__c</fullName>
    <description>Effective current balance is used for backend purpose only to populate effective balance after payment transactions on Product</description>
    <inlineHelpText>Effective current balance is used for backend purpose only to populate effective balance after payment transactions on Product</inlineHelpText>
    <label>Effective Current Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <description>Placement Status</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Placement Status</inlineHelpText>
    <label>Placement Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portfolio_Name_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Name_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Portfolio Name</description>
    <inlineHelpText>Lookup to Portfolio Name</inlineHelpText>
    <label>Portfolio Name</label>
    <referenceTo>Portfolio_Name__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestPaymentController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class is for Request Fund functionality
*  @author : A5E Consulting
*  @date : 14 July 2021  
*
*************************************************************************************************/
    public class RequestPaymentController {
    
    public Payment_Transaction__C transctRecord{get;set;}
    
    @AuraEnabled
    public static Product__C getproduct(String recordId){
        
        Product__c prodRecord = [select id, name, Customer__r.PersonEmail, Customer__r.Secondary_Email__pc, 
                                 Current_Balance__c, Collection_Agency__c, Portfolio_Name_Lookup__r.Name, 
                                 Purchase_ID_Formula__c, Placement_Status__c 
                                 from Product__c
                                 where id =: recordId];
        
        List<Payment_Transaction__C> listPayment = [select id, name, status__c, Amount__c 
                                                    from Payment_Transaction__c 
                                                    where ((Record_type_name__c = 'One_time_Payment' and Status__c = 'In Progress')
                                                    OR (Record_type_name__c = 'Recurring_Payment_Master' and (Status__c = 'In Progress' OR Status__c = 'New')))
                                                    and product__c =: recordId];
        
        Decimal effectiveBalance = prodRecord.Current_Balance__c;
        if(listPayment.size() > 0){
            for(Payment_Transaction__C pay : listPayment){
                effectiveBalance -= pay.Amount__c;
            }
        }
        prodRecord.Effective_Current_Balance__c = effectiveBalance;
        
        return prodRecord;
    }
    
    @AuraEnabled
    public static String eligibleProduct(String recordId){
    
        Product__c prodRecord = [select id, name, Customer__r.PersonEmail, Customer__r.Secondary_Email__pc, 
        Purchase_ID_Formula__c, Portfolio_Name_Lookup__r.Name, 
                                 		Collection_Agency__c, Current_Balance__c, Placement_Status__c  
                                from Product__c 
                                where id =: recordId];
        
        List<Payment_Transaction__C> listPayment = [select id, name, status__c, Amount__c 
                                                    from Payment_Transaction__c 
                                                    where 
                                                    ((Record_type_name__c = 'One_time_Payment' and Status__c = 'In Progress')
                                                     OR (Record_type_name__c = 'Recurring_payment_Master' and Status__c = 'In Progress'))
                                                    and product__c =: recordId];
        
        Decimal effectiveBalance = prodRecord.Current_Balance__c;
        if(listPayment.size() > 0){
            for(Payment_Transaction__C pay : listPayment){
                effectiveBalance -= pay.Amount__c;
            }
        }
        prodRecord.Effective_Current_Balance__c = effectiveBalance;
        
        Customer_Portal_Setting__c setting = Customer_Portal_Setting__c.getOrgDefaults();
        
        /*Set<Decimal> setPlacementsToInclude = new Set<Decimal>();
        for(Placement__c placement : [SELECT Name 
                                      FROM Placement__c 
                                      WHERE Include_In_Portal_Search__c = True]){
            setPlacementsToInclude.add(decimal.valueOf(placement.Name));                                              
        }*/
        
        list<String> listPlacementToInclude = String.isNotBlank(setting.Eligible_Placement_ID__c) ? 
                setting.Eligible_Placement_ID__c.split(',') : new list<String>{};
                    
        list<String> listPurchaseGroupToExclude = String.isNotBlank(setting.Exclude_Account_Purchase_Group__c) ? 
                setting.Exclude_Account_Purchase_Group__c.split(',') : new list<String>{};
            
        //get the Portfolio Names to exclude from Portal Search
        list<String> listPortfolioNameToExclude = String.isNotBlank(setting.Exclude_Portfolio_Name__c) ? 
                setting.Exclude_Portfolio_Name__c.split(',') : new list<String>{};
        
        String msg = '';
        if(!listPlacementToInclude.contains(String.valueOf(prodRecord.Collection_Agency__c)) 
            || (prodRecord.Purchase_ID_Formula__c != NULL 
              && listPurchaseGroupToExclude.contains(String.valueOf(prodRecord.Purchase_ID_Formula__c)))
            || ((prodRecord.Portfolio_Name_Lookup__r.Name != NULL 
              && listPortfolioNameToExclude.contains(String.valueOf(prodRecord.Portfolio_Name_Lookup__r.Name)))
            /*|| (prodRecord.Portfolio_Name_Lookup__r.Name != NULL 
              && listPortfolioNameToExclude.contains(String.valueOf(prodRecord.Portfolio_Name_Lookup__r.Name)))*/   
               )
            ){
            msg += 'Product record is not eligible for payment setup</br>';
            msg += 'Because Collection Agency is '+ (prodRecord.Collection_Agency__c == null? 'blank' : (String.valueOf(prodRecord.Collection_Agency__c))) + '<br/>';
            msg += 'Portfolio is ' + (prodRecord.Portfolio_Name_Lookup__r.Name == null ? 'blank': prodRecord.Portfolio_Name_Lookup__r.Name) + '<br/>';
            msg += 'Portfolio Group Name is '+ (prodRecord.Purchase_ID_Formula__c == null? 'blank': String.valueOf(prodRecord.Purchase_ID_Formula__c)) + '<br/>';
        }
        
        if(String.isBlank(prodRecord.Customer__r.PersonEmail) && String.isBlank(prodRecord.Customer__r.Secondary_Email__pc)){
            msg += '<br/>Email address is required';
        }
        
        if(null == prodRecord.Current_Balance__c || prodRecord.Current_Balance__c <= 0){
        	msg += '<br/>Current Balance is less than or equal to 0';
        }
        if(prodRecord.Placement_Status__c != NULL && prodRecord.Placement_Status__c.startsWith('2')){
        	msg += '<br/>Product has Invalid Placement Status';
        }
        
        if(msg == ''){
        	return 'None';    
        }
        
        return msg;
    }
    
    @AuraEnabled
    public static Boolean saveTransaction(String productrecordId, String transactionType, String recurranceType, Decimal paymentAmount, String dayOfWeek, String dayOfMonth, Date endDate, String NumberOfPayments, String emailAddress){
        system.debug('transactionType:'+transactionType);
        system.debug('recurranceType:'+recurranceType);
        system.debug('dayOfWeek:'+dayOfWeek);
        system.debug('dayOfMonth:'+dayOfMonth);
        system.debug('endDate:'+endDate);
        system.debug('NumberOfPayments:'+NumberOfPayments);
        Boolean paymentSuccessful = true;
        Payment_Transaction__C transactionRecord = new Payment_Transaction__C();
        
        transactionRecord.Product__c = ProductrecordId;
        transactionRecord.Payment_Type__c = transactionType;
        system.debug('transaction Type' + transactionType);
        Product__c prodRecord = [select id, Collection_Agency__c from Product__c where id =: ProductrecordId LIMIT 1][0];
        if(transactionType == 'Recurring Payment'){
            transactionRecord.RecordTypeId = Schema.SObjectType.Payment_Transaction__C.getRecordTypeInfosByName().get('Request Funds Recurring').getRecordTypeId();
        }else{
            transactionRecord.RecordTypeId = Schema.SObjectType.Payment_Transaction__C.getRecordTypeInfosByName().get('Request Funds One Time').getRecordTypeId();
        }
        transactionRecord.Amount__c = paymentAmount;
        transactionRecord.Recurrence_Type__c = recurranceType;
        transactionRecord.Day_Of_Month__c = dayOfMonth;
        transactionRecord.Day_Of_Week__c = dayOfWeek;
        transactionRecord.End_Date__c = (DateTime)endDate;
        transactionRecord.Payment_Initiated_By__c = 'Internal User';
        transactionRecord.Number_of_Payments__c = NumberOfPayments;
        transactionRecord.Customer_Email_Address__c = emailAddress;
        transactionRecord.Collection_Agency__c = prodRecord.Collection_Agency__c;
            
        try{
            insert transactionRecord;
            if(!Test.isRunningTest()){
            	PaymentTransactionCreator.postPaymentToZumrails(transactionRecord.id);    
            }
            paymentSuccessful = true;
        
        }catch(Exception e){
            paymentSuccessful = false;
        }
        
        return paymentSuccessful;
    }
    
}