force-app/main/default/objects/Agency_Portal_Settings__c/Agency_Portal_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Agency Portal Settings</description>
    <label>Agency Portal Settings</label>
</CustomObject>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <description>Number of Days for Interest Calculation</description>
    <inlineHelpText>Number of Days for Interest Calculation</inlineHelpText>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/API_Error__c/API_Error__c.object-meta.xml
<CustomObject>
    <label>API Error</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Error__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Error__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>API Errors</relationshipLabel>
    <relationshipName>API_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Accepted_Interest_rate__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Interest_rate__c</fullName>
    <label>Accepted Interest rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/CCS_Stage__c.field-meta.xml
<CustomField>
    <fullName>CCS_Stage__c</fullName>
    <description>CCS Stages</description>
    <inlineHelpText>CCS Stages</inlineHelpText>
    <label>CCS Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>Completed / Paid in Full</fullName>
            </value>
            <value>
                <fullName>Customer paying direct NLOP</fullName>
            </value>
            <value>
                <fullName>Dropped Notifications</fullName>
            </value>
            <value>
                <fullName>Failed (3 payments missed)</fullName>
            </value>
            <value>
                <fullName>In Progress (notice has been sent)</fullName>
            </value>
            <value>
                <fullName>Missed Payment</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
            <value>
                <fullName>For Owner  Review</fullName>
                <label>For Owner Review</label>
            </value>
            <value>
                <fullName>Putback / Buyback Pending</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Insolvent After Purchase</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>DMP Details provided</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Putback</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>Failed (Program closed by Creditor)</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Total Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Amount__c</fullName>
    <description>The total amount of interest accrued on this insolvency account to date</description>
    <inlineHelpText>The total amount of interest accrued on this insolvency account to date</inlineHelpText>
    <label>Current Interest Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Accrued_for_the_Day__c.field-meta.xml
<CustomField>
    <fullName>Interest_Accrued_for_the_Day__c</fullName>
    <description>Interest Accrued for the day updated by Daily Interest calculation job. read only on page layout</description>
    <inlineHelpText>Interest Accrued for the day updated by Daily Interest calculation job</inlineHelpText>
    <label>Interest Accrued for the Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Amount_Last_Calculated_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_Last_Calculated_Date__c</fullName>
    <description>Interest Amount Last Calculated Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Interest Amount Last Calculated Date</inlineHelpText>
    <label>Interest Amount Last Calculated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>OO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Flexiti_CCS_Account.recordType-meta.xml
<RecordType>
    <fullName>Flexiti_CCS_Account</fullName>
    <active>true</active>
    <description>Record Type of Flexiti CCS Account</description>
    <label>Flexiti CCS Account</label>
</RecordType>

force-app/main/default/objects/Product__c/recordTypes/GoEasy_CCS_Account.recordType-meta.xml
<RecordType>
    <fullName>GoEasy_CCS_Account</fullName>
    <active>true</active>
    <label>Easyfinancial CCS Account</label>
</RecordType>

force-app/main/default/classes/CCSProductInterestCalculation.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : This is a Batch class to calculate Interest Amount on Go Easy Product on daily basis
 *  @author : A5E Consulting
 *  @date : 19/08/2023
 
 *************************************************************************************************/
public class CCSProductInterestCalculation implements Database.Batchable<sobject> {
    
public static List<String> RECORDTYPE = new List<String>{'GoEasy_CCS_Account', 'Flexiti_CCS_Account'};
public static List<String> CCSSTAGE = new List<String>{'Missed Payment', 'In Progress (notice has been sent)'};
    

    
public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            [SELECT ID,  Interest_Rate__c,Accepted_Interest_rate__C, Current_Interest_Amount__c,CCS_Stage__c, 
                    Interest_Amount_Last_Calculated_Date__c,   State__c, Current_Balance__c                     
             FROM Product__c 
             WHERE RecordType.DeveloperName IN :RECORDTYPE 
             AND Current_Balance__c != null 
             AND Current_Balance__c > 0 
             // Interest_Rate__c or Accepted_Interest_rate__c should be present 
             AND ((Interest_Rate__c != NULL 
             AND Interest_Rate__c != 0) OR (Accepted_Interest_rate__C != NULL and Accepted_Interest_rate__C !=0))
             AND (CCS_Stage__c IN :CCSSTAGE)
            ]
        );
        
    }     
    
    public void execute(Database.BatchableContext bc, List<Product__c> listProducts){
        
        Agency_Portal_Settings__c config = Agency_Portal_Settings__c.getOrgDefaults();
        
        system.debug('config'+config);
        List<API_Error__c> listAPIErrors = New List<API_Error__c>();
         
        Decimal InterestRate;
        Decimal InterestAmount = 0;
        Decimal Principal_Balance = 0;
        Decimal NoOfDaysInYear = config.Number_of_Days__c;
        Date Today = Date.today();
       	//Simplify no of days to 1/365;
        Decimal NoOfDays = (1 / NoOfDaysInYear);
        
        for(Product__c productObj :listProducts){
            //updating Interest Last Calculated date to current date
            productObj.Interest_Amount_Last_Calculated_Date__c = Date.today();
            // If Interest_Rate__C is blank or null then Interest will be calculated on Accepted_Interest_Rate__C
            if(productObj.Interest_Rate__c!=Null &&  productObj.Interest_Rate__c!=0){
                InterestRate = productObj.Interest_Rate__c;
            }else if(productObj.Accepted_Interest_rate__C!=Null &&  productObj.Accepted_Interest_rate__C!=0){
                InterestRate = productObj.Accepted_Interest_rate__C;
            }
            
                //Round of the Principal Balance to 2 decimal places
                Principal_Balance = productObj.Current_Balance__c.setScale(2,RoundingMode.HALF_UP);
                //Interest Amount calculation = ((P*N*R)/100)/365
                //NoOfDaysInYear is set to 365 in Custom Setting
                if(InterestRate != NULL && Principal_Balance != NULL && NoOfDaysInYear != NULL){
                    system.debug('Principal_Balance:: '+Principal_Balance);
                    system.debug('InterestRate:: '+InterestRate);
                    system.debug('NoOfDaysInYear:: '+NoOfDaysInYear);
                    //Run Batch for one day at time
                    
                    //round of no of days to 5 decimal places
                    NoOfDays = NoOfDays.setScale(5,RoundingMode.HALF_UP);
                    
                    //convert interest rate percent to decimal
                    InterestRate = InterestRate / 100;
                    
                    //I=Prt
                    InterestAmount = Principal_Balance * InterestRate * NoOfDays;
                    //Round off Interest Amount accrued to 2 decimal places
                    InterestAmount = InterestAmount.setScale(2,RoundingMode.HALF_UP);
                    
                    system.debug('productObj.Current_Interest_Amount__c:: '+productObj.Current_Interest_Amount__c);
                    system.debug('InterestAmount::'+InterestAmount);
                    
                    //Update Current Interest Amount
                    if(productObj.Current_Interest_Amount__c == NULL){
                        productObj.Current_Interest_Amount__c = interestAmount;  
                    }
                    else {
                        system.debug('productObj.Current_Interest_Amount__c before: '+productObj.Current_Interest_Amount__c);
                        productObj.Current_Interest_Amount__c += interestAmount;     
                        system.debug('productObj.Current_Interest_Amount__c after: '+productObj.Current_Interest_Amount__c);
                    }
                    
                    //Populate Interest Amount Accrued for the Day
                    productObj.Interest_Accrued_for_the_Day__c = InterestAmount;
                    //Update total balance on Product
                    productObj.Current_Balance__c = ( productObj.Current_Balance__c!=NULL 
                                                    ? productObj.Current_Balance__c + InterestAmount
                                                    : InterestAmount);
                    //Set total balance to 2 decimal round off
                    productObj.Current_Balance__c = productObj.Current_Balance__c.setScale(2,RoundingMode.HALF_UP);
    
                    system.debug('productObj: '+productObj);
                }    
            
            Principal_Balance = 0;
            InterestRate = Null;
        }
        
        system.debug('listProducts update: '+listProducts);
        
        ProductTriggerHandler.runProductTrigger = false;

        Database.SaveResult[] srList = Database.update(listProducts, false);

        // Iterate through each returned result
        for (Integer i=0; i<srList.size(); i++) {
            if (srList.get(i).isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                //System.debug('Successfully updated account. Account` ID: ' + sr.getId());
            }
            //in  case of failure, create database Error records
            else if (!srList.get(i).isSuccess()){
                // DML operation failed
                Database.Error error = srList.get(i).getErrors().get(0);
                String failedDML = error.getMessage();
                listProducts.get(i);//failed record from the list
                system.debug('Failed ID'+listProducts.get(i).Id);
                API_Error__c apiError = New API_Error__c();
                apiError.Product__c = listProducts.get(i).Id;
                apiError.Error__c = failedDML;
                apiError.End_Point__c = 'Process CCS';
                apiError.Action__c = 'Daily CCS Interest Calculation';
                listAPIErrors.add(apiError); 
            }
        }
        insert listAPIErrors;
        
        ProductTriggerHandler.runProductTrigger = true;
        
        system.debug('current time after product update'+system.now());
    }

    //Finish method
    public void finish(Database.BatchableContext bc){  
        //switch on metadata
        //MetadataSwitchJob.activateProductMetadata();
        system.enqueueJob(new MetaDataActivation());
    }
 
}