force-app/main/default/objects/Agency_Portal_Settings__c/Agency_Portal_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Agency Portal Settings</description>
    <label>Agency Portal Settings</label>
</CustomObject>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/Agency_Complaint_Status__c.field-meta.xml
<CustomField>
    <fullName>Agency_Complaint_Status__c</fullName>
    <description>Agency Complaint Status</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Agency Complaint Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/CFG_Complaint_Status__c.field-meta.xml
<CustomField>
    <fullName>CFG_Complaint_Status__c</fullName>
    <description>CFG Complaint Status</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CFG Complaint Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/Excel_File_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Excel_File_Processing_Status__c</fullName>
    <description>Excel File Processing Status</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Excel File Processing Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/Media_Status__c.field-meta.xml
<CustomField>
    <fullName>Media_Status__c</fullName>
    <description>Media Status</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Media Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/Work_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment_Status__c</fullName>
    <description>Work Assignment Status</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Work Assignment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Work Assignment</description>
    <label>Agency Work Assignment</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency_Complaint.recordType-meta.xml
<RecordType>
    <fullName>Agency_Complaint</fullName>
    <active>true</active>
    <description>Agency Complaint</description>
    <label>Agency Complaint</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency_Excel_Processing.recordType-meta.xml
<RecordType>
    <fullName>Agency_Excel_Processing</fullName>
    <active>true</active>
    <description>Agency Excel Processing</description>
    <label>Agency Excel Processing</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/Agency_Media.recordType-meta.xml
<RecordType>
    <fullName>Agency_Media</fullName>
    <active>true</active>
    <description>Agency Media</description>
    <label>Agency Media</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG.recordType-meta.xml
<RecordType>
    <fullName>CFG</fullName>
    <active>true</active>
    <description>CFG Work Assignment</description>
    <label>CFG Work Assignment</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG_Complaint.recordType-meta.xml
<RecordType>
    <fullName>CFG_Complaint</fullName>
    <active>true</active>
    <description>CFG Complaint</description>
    <label>CFG Complaint</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG_Excel_Processing.recordType-meta.xml
<RecordType>
    <fullName>CFG_Excel_Processing</fullName>
    <active>true</active>
    <description>CFG Excel Processing</description>
    <label>CFG Excel Processing</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG_Media.recordType-meta.xml
<RecordType>
    <fullName>CFG_Media</fullName>
    <active>true</active>
    <description>CFG Media</description>
    <label>CFG Media</label>
</RecordType>

force-app/main/default/classes/BulkUpdateTaskAndMediaController.cls
public with sharing class BulkUpdateTaskAndMediaController {
    private ApexPages.StandardSetController standardController;
    Public string selectedname{get;set;}
    public Work_Assignment__c objEmp {get;set;}
    public list<selectoption> checkStatus{set;get;}
    public boolean showWorkAssRecordType {get;set;}
    public boolean showComplaintRecordType {get;set;}
    public boolean showMediaRecordType {get;set;}
    public boolean showExcelFileProcssingRecordType {get;set;}
    public List<Work_Assignment__c> selectedCases{get; set;}
    
    public BulkUpdateTaskAndMediaController(ApexPages.StandardSetController standardController){    
        this.standardController = standardController;
    }
    
    public PageReference bulkUpdatemethod(){ 
        Agency_Portal_Settings__c portalSettings = Agency_Portal_Settings__c.getOrgDefaults();
        list<String> validWrkAssStatus = new list<String>();
        list<String> validAgencyComplaintStatus = new list<String>();
        list<String> validCFGComplaintStatus = new list<String>();
        list<String> validMediaStatus = new list<String>();
        list<String> validExcelFileProcessingStatus = new list<String>();
        Map<String,Id> rectordTypeCheck = new Map<String,Id>();
        
        validWrkAssStatus = portalSettings.Work_Assignment_Status__c.split(',');
        validAgencyComplaintStatus = portalSettings.Agency_Complaint_Status__c.split(',');
        validCFGComplaintStatus = portalSettings.CFG_Complaint_Status__c.split(',');
        validMediaStatus = portalSettings.Media_Status__c.split(',');
        validExcelFileProcessingStatus = portalSettings.Excel_File_Processing_Status__c.split(',');
        
        List <RecordType> recordTypes = [Select Id, DeveloperName From RecordType where sobjecttype = 'Work_Assignment__c'];
        for(RecordType recordType : recordTypes){
            rectordTypeCheck.put(recordType.DeveloperName, recordType.Id);
        } 
        system.debug('standardController' +standardController);
        // Get the selected records
        selectedCases = (List<Work_Assignment__c>) standardController.getSelected();
        
        checkStatus =  new list<selectoption>();
        checkStatus.add(new selectoption('None','None'));
        
        if(selectedCases!=null && !selectedCases.isEmpty()){
            if(selectedCases[0].RecordTypeId == rectordTypeCheck.get('CFG') ||
              selectedCases[0].RecordTypeId == rectordTypeCheck.get('Agency')){
                  showWorkAssRecordType=true;
                  showComplaintRecordType=false;
                  showMediaRecordType=false;
                  showExcelFileProcssingRecordType=false;
                for(String WrkAssStatus : validWrkAssStatus){           
                    checkStatus.add(new selectoption(WrkAssStatus,WrkAssStatus));
                    system.debug('checkStatus workAss::' +checkStatus);
                }
            }else if(selectedCases[0].RecordTypeId == rectordTypeCheck.get('CFG_Complaint')){
                  showWorkAssRecordType=false;
                  showComplaintRecordType=true;
                  showMediaRecordType=false;
                  showExcelFileProcssingRecordType=false;
                for(String CFGComplaintStatus : validCFGComplaintStatus){           
                    checkStatus.add(new selectoption(CFGComplaintStatus,CFGComplaintStatus));
                    system.debug('checkStatus complaint::' +checkStatus);
                }
            }else if(selectedCases[0].RecordTypeId == rectordTypeCheck.get('Agency_Complaint')){
                showWorkAssRecordType=false;
                  showComplaintRecordType=true;
                  showMediaRecordType=false;
                  showExcelFileProcssingRecordType=false; 
                for(String AgencyComplaintStatus : validAgencyComplaintStatus){           
                    checkStatus.add(new selectoption(AgencyComplaintStatus,AgencyComplaintStatus));
                    system.debug('checkStatus complaint::' +checkStatus);
                }
            }else if(selectedCases[0].RecordTypeId == rectordTypeCheck.get('CFG_Media') ||
                    selectedCases[0].RecordTypeId == rectordTypeCheck.get('Agency_Media')){
                  showWorkAssRecordType=false;
                  showComplaintRecordType=false;
                  showMediaRecordType=true;
                  showExcelFileProcssingRecordType=false;
                  for(String MediaStatus : validMediaStatus){           
                    checkStatus.add(new selectoption(MediaStatus,MediaStatus));
                    system.debug('checkStatus complaint::' +checkStatus);
                }
             }else if(selectedCases[0].RecordTypeId == rectordTypeCheck.get('CFG_Excel_Processing') ||
                    selectedCases[0].RecordTypeId == rectordTypeCheck.get('Agency_Excel_Processing')){
                  showWorkAssRecordType=false;
                  showComplaintRecordType=false;
                  showMediaRecordType=false;
                  showExcelFileProcssingRecordType=true;
                  for(String ExcelFileProcessingStatus : validExcelFileProcessingStatus){           
                    checkStatus.add(new selectoption(ExcelFileProcessingStatus,ExcelFileProcessingStatus));
                    system.debug('checkStatus complaint::' +checkStatus);
                }
              }
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select records from list view before you proceed.'));
        }
        system.debug('checkStatus outside if::' +checkStatus);
        // Update records       
        for(Work_Assignment__c selectedCase : selectedCases){
            objEmp = new Work_Assignment__c(RecordTypeId = selectedCase.RecordTypeId);
            selectedCase.Status__c = selectedCase.Status__c;
        }     
        return null;         
    }
    
    public PageReference updateCases(){     
        List<Work_Assignment__c> selectedCases = (List<Work_Assignment__c>) standardController.getSelected();
        List<Work_Assignment__c> StatusUpdate = new List<Work_Assignment__c>();
        
        if(selectedname == 'None' || selectedname == NULL){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select new status value before you proceed.'));
            return null; 
        }
        system.debug('selectedCases test::' +selectedCases);
        for(Work_Assignment__c selectedCase : selectedCases){
                selectedCase.Status__c = selectedname;
        }
        //update StatusUpdate;
         return standardController.save();
    }
    
    public pageReference Redirect(){
        PageReference retURL = new PageReference('/apex/BulkUpdateTaskAndMedia');
        retURL.setRedirect(true);
        return retURL;
    }
        
}