force-app/main/default/objects/Agency_Portal_Settings__c/Agency_Portal_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Agency Portal Settings</description>
    <label>Agency Portal Settings</label>
</CustomObject>

force-app/main/default/objects/Agency_Portal_Settings__c/fields/CFGWorkAssignmentRecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>CFGWorkAssignmentRecordTypeId__c</fullName>
    <description>CFGWorkAssignmentRecordTypeId</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CFGWorkAssignmentRecordTypeId</inlineHelpText>
    <label>CFGWorkAssignmentRecordTypeId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>Commission Rate</description>
    <inlineHelpText>Commission Rate</inlineHelpText>
    <label>Commission Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency_Placement__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup against Placement</description>
    <inlineHelpText>Lookup against Placement</inlineHelpText>
    <label>Agency ID - NOT AUTHORITATIVE</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>Current commission rate on distressed Product record</description>
    <inlineHelpText>Current commission rate on distressed Product record</inlineHelpText>
    <label>Current Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Value_Tier_at_Time_of_Placement__c.field-meta.xml
<CustomField>
    <fullName>Value_Tier_at_Time_of_Placement__c</fullName>
    <description>Value Tier at Time of Placement</description>
    <inlineHelpText>Value Tier at Time of Placement</inlineHelpText>
    <label>Value Tier at Time of Placement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending Agency Action</fullName>
            </value>
            <value>
                <fullName>In Progress - Pending CFG Action</fullName>
            </value>
            <value>
                <fullName>Completed – Agency Confirms Complaint Resolved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Justified</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified</fullName>
            </value>
            <value>
                <fullName>Request to Reopen</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Closed - Unjustified - Cease and Desist Request</fullName>
            </value>
            <value>
                <fullName>Unjustified - Cease and Desist - Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/recordTypes/CFG.recordType-meta.xml
<RecordType>
    <fullName>CFG</fullName>
    <active>true</active>
    <description>CFG Work Assignment</description>
    <label>CFG Work Assignment</label>
</RecordType>

force-app/main/default/classes/ProductUpdatesDocumentCreationTest.cls
@isTest
public class ProductUpdatesDocumentCreationTest {
   
    public static testMethod void testProductUpdates() {
        Test.setMock(HttpCalloutMock.class, new PortalAPIMockResponse());
        String recordId = Schema.SObjectType.Work_Assignment__c.getRecordTypeInfosByName().get('CFG Work Assignment').getRecordTypeId();
        Agency_Portal_Settings__c portalSettings = new Agency_Portal_Settings__c();
        portalSettings.CFGWorkAssignmentRecordTypeId__c = recordId;
        insert portalSettings;
        
        Placement__c plcgy = new  Placement__c();      
        plcgy.Name='12233';
        insert plcgy;
        
        Product__c prod = new Product__c();
        prod.RecordTypeId = Schema.SObjectType.Product__C.getRecordTypeInfosByName().get('Distressed Account').getRecordTypeId();
        prod.Name = '1566P000';
        prod.Commission_Rate__c=13;
        prod.Collection_Agency__c = 12233;
        prod.Collection_Agency_Placement__c = plcgy.Id;
        prod.Value_Tier_at_Time_of_Placement__c = 'A';
        prod.Status__c = 'New Allocation - New Allocation';
        prod.Sub_Status__c = 'Ready';
        prod.Product_Status__c = 'Test';
        insert prod;
        
        Product__History prodHistory2 = new Product__History();
        prodHistory2.Field = 'Collection_Agency__c';
        prodHistory2.ParentId = prod.Id;
        insert prodHistory2;
        
        Product__History prodHistory3 = new Product__History();
        prodHistory3.Field = 'Collection_Agency_Placement__c';
        prodHistory3.ParentId = prod.Id;
        insert prodHistory3;
        
        Product__History prodHistory4 = new Product__History();
        prodHistory4.Field = 'Status__c';
        prodHistory4.ParentId = prod.Id;
        insert prodHistory4;
        
        prod.Codebtor_Address_Line1__c='SHN';
        update prod;
        
    	Test.startTest();
        String hour = String.valueOf(Datetime.now().hour());
        String min = String.valueOf(Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()+3);
        
        //parse to cron expression
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        
        ProductUpdatesDocumentCreation s = new ProductUpdatesDocumentCreation(); 
        System.schedule('Account Update Job Started At ' + String.valueOf(Datetime.now()), nextFireTime, s);
        Test.stopTest();
    }
}