force-app/main/default/objects/Merchant_Account__c/Merchant_Account__c.object-meta.xml
<CustomObject>
    <description>Merchant Account Object</description>
    <label>Merchant Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>LeadId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Account__c/fields/Collective_Cash_Collections_CAD__c.field-meta.xml
<CustomField>
    <fullName>Collective_Cash_Collections_CAD__c</fullName>
    <description>Total sums collected on account in Canadian dollars</description>
    <inlineHelpText>Total sums collected on account in Canadian dollars</inlineHelpText>
    <label>Collective Cash Collections CAD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>current balance (advance amount minus payments)</description>
    <inlineHelpText>current balance (advance amount minus payments)</inlineHelpText>
    <label>Current Balance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Last_Pay_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Pay_Amount__c</fullName>
    <description>Last Payment Amount</description>
    <inlineHelpText>Last Payment Amount</inlineHelpText>
    <label>Last Pay Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <description>Last Payment Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last Payment Date</inlineHelpText>
    <label>LastPayDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/Merchant_Account_Payment__c.object-meta.xml
<CustomObject>
    <description>Merchant Account Payment Object</description>
    <label>Merchant Account Payment</label>
    <nameField>
        <displayFormat>MAP-{000000}</displayFormat>
        <label>Merchant Account Payment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Account Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the transaction</description>
    <inlineHelpText>The amount of the transaction</inlineHelpText>
    <label>amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Current_CAD__c.field-meta.xml
<CustomField>
    <fullName>Current_CAD__c</fullName>
    <description>Current CAD</description>
    <inlineHelpText>Current CAD</inlineHelpText>
    <label>Current CAD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <label>leadId</label>
    <referenceTo>Merchant_Account__c</referenceTo>
    <relationshipLabel>Merchant Account Payments</relationshipLabel>
    <relationshipName>Merchant_Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Payment_Processed__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to check whether the payment has been processed while calculating Current Balance and CAD on Merchant Account</description>
    <inlineHelpText>Checks if amount on the record is used to calculate Current Balance and CAD on Merchant Account</inlineHelpText>
    <label>Payment Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Previous_Balance__c.field-meta.xml
<CustomField>
    <fullName>Previous_Balance__c</fullName>
    <description>Previous Balance</description>
    <inlineHelpText>Previous Balance</inlineHelpText>
    <label>Previous Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Previous_CAD__c.field-meta.xml
<CustomField>
    <fullName>Previous_CAD__c</fullName>
    <description>Previous CAD</description>
    <inlineHelpText>Previous CAD</inlineHelpText>
    <label>Previous CAD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/TranDate__c.field-meta.xml
<CustomField>
    <fullName>TranDate__c</fullName>
    <description>The date of the transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date of the transaction</inlineHelpText>
    <label>trandate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MerchantAccountPaymentUpdatesBatch.cls
/**************************************************************************************************
 *
 *  Class:   Batch clas to update Merchant Account Payment fields
 *  @description : 
 *  @author : A5E Consulting
 *  @date : 31/03/2021
 
 *************************************************************************************************/
global class MerchantAccountPaymentUpdatesBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT tranDate__c, amount__c, Current_CAD__c, Previous_CAD__c,Previous_Balance__c,Current_Balance__c,leadId__c, leadId__r.Current_Balance__c,leadId__r.Last_Payment_Date__c,leadId__r.Last_Pay_Amount__c,'+
            ' leadId__r.Collective_Cash_Collections_CAD__c FROM Merchant_Account_payment__c'+
            ' WHERE CreatedDate = Today AND Payment_Processed__c = false ORDER BY tranDate__c ASC'
            ); 
    }
    
    global void execute(Database.BatchableContext bc, List<Merchant_Account_Payment__c> listMerchantAccountPayments){ 
        map<ID, Decimal> merchantAccountBalanceMap = new map<ID, Decimal>();
        map<ID, Decimal> merchantAccountCADMap = new map<ID, Decimal>();
        map<ID, Merchant_Account__c> mapIDMerchantAccounts= new map<ID, Merchant_Account__c>();
        Merchant_Account__c merchantAccountInstance;
        system.debug('listMerchantAccountPayments: '+listMerchantAccountPayments);
        list<Merchant_Account_Payment__c> listMerchantAccountPaymentToUpdate = new list<Merchant_Account_Payment__c>();
        for(Merchant_Account_payment__c paymentInstance : listMerchantAccountPayments){
             merchantAccountInstance = new Merchant_Account__c(Last_Payment_Date__c = paymentInstance.tranDate__c,
                                                              Current_Balance__c = paymentInstance.leadId__r.Current_Balance__c,
                                                              Collective_Cash_Collections_CAD__c = paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c);
            //mapIdMerchantAccounts.put(paymentInstance.leadId__c, merchantAccountInstance);
            system.debug('paymentInstance.leadID__c'+paymentInstance.leadID__c);                                                
            
            //Check if map contains MerchantAccount ID
            if(!mapIdMerchantAccounts.containsKey(paymentInstance.leadID__c)){
                //Calculate Collective Cash Collections CAD on Merchant Account 29.03.21
                //update last payment details of Last Payment Date is less than transaction date
                if(paymentInstance.leadId__r.Last_Payment_Date__c <= paymentInstance.TranDate__c
                && paymentInstance.amount__c > 0){
                    mapIdMerchantAccounts.put(paymentInstance.leadID__c, 
                    new Merchant_Account__c(Id=paymentInstance.leadID__c,
                        Last_Payment_Date__c = paymentInstance.tranDate__c,
                        Last_Pay_Amount__c = paymentInstance.amount__c,
                        Current_Balance__c = 
                        paymentInstance.leadId__r.Current_Balance__c != NULL ? 
                        paymentInstance.leadId__r.Current_Balance__c - paymentInstance.amount__c : 
                        0,
                        Collective_Cash_Collections_CAD__c = 
                        paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c != NULL ? 
                        paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c + paymentInstance.amount__c : 
                        0));    
                }
                else{
                    mapIdMerchantAccounts.put(paymentInstance.leadID__c, 
                    new Merchant_Account__c(Id=paymentInstance.leadID__c,
                        Last_Payment_Date__c = paymentInstance.leadId__r.Last_Payment_Date__c,
                        Last_Pay_Amount__c = paymentInstance.leadId__r.Last_Pay_Amount__c,
                        Current_Balance__c = 
                        paymentInstance.leadId__r.Current_Balance__c != NULL ? 
                        paymentInstance.leadId__r.Current_Balance__c - paymentInstance.amount__c : 
                        0,
                        Collective_Cash_Collections_CAD__c = 
                        paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c != NULL ? 
                        paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c + paymentInstance.amount__c : 
                        0));
                }
            }
            else{
                system.debug('already present');
                //update last payment details if previous Transaction date in sheet is less than new transaction date
                if(mapIdMerchantAccounts.get(paymentInstance.leadId__c).Last_Payment_Date__c <= paymentInstance.TranDate__c
                && paymentInstance.amount__c > 0){
                    system.debug('lesser date');
                    system.debug('map value: '+mapIdMerchantAccounts.get(paymentInstance.leadId__c).Last_Payment_Date__c);
                    system.debug('paymentInstance.TranDate__c:'+paymentInstance.TranDate__c);
                    mapIdMerchantAccounts.put(paymentInstance.leadID__c, 
                    new Merchant_Account__c(Id=paymentInstance.leadID__c,
                        Last_Payment_Date__c = paymentInstance.tranDate__c,
                        Last_Pay_Amount__c = paymentInstance.amount__c,
                        Current_Balance__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Current_Balance__c - paymentInstance.amount__c,
                        Collective_Cash_Collections_CAD__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Collective_Cash_Collections_CAD__c + paymentInstance.amount__c));   
                }
                else{
                    system.debug('greater date');
                    system.debug('map value: '+mapIdMerchantAccounts.get(paymentInstance.leadId__c).Last_Payment_Date__c);
                    system.debug('lesser date'+paymentInstance.TranDate__c);
                    mapIdMerchantAccounts.put(paymentInstance.leadID__c, 
                    new Merchant_Account__c(Id=paymentInstance.leadID__c,
                        Last_Payment_Date__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Last_Payment_Date__c,
                        Last_Pay_Amount__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Last_Pay_Amount__c,
                        Current_Balance__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Current_Balance__c - paymentInstance.amount__c,
                        Collective_Cash_Collections_CAD__c = mapIdMerchantAccounts.get(paymentInstance.leadId__c).Collective_Cash_Collections_CAD__c + paymentInstance.amount__c));   
                }                                                      
            }
            
            system.debug('merchantAccountBalanceMap first: '+merchantAccountBalanceMap);
            //Calculate Balance amounts on Merchant Account Payment
            if(!merchantAccountBalanceMap.containsKey(paymentInstance.leadId__c)){
                system.debug('not contains');
                merchantAccountBalanceMap.put(paymentInstance.leadId__c,paymentInstance.leadId__r.Current_Balance__c);
            }
            if(merchantAccountBalanceMap.containsKey(paymentInstance.leadId__c)){
                system.debug('contains');
                paymentInstance.Previous_Balance__c = merchantAccountBalanceMap.get(paymentInstance.leadId__c);
                paymentInstance.Current_Balance__c = paymentInstance.Previous_Balance__c - paymentInstance.amount__c;
                merchantAccountBalanceMap.put(paymentInstance.leadId__c,paymentInstance.Current_Balance__c);    
            }                                              
            
            if(!merchantAccountCADMap.containsKey(paymentInstance.leadId__c)){
                system.debug('not contains CAD');
                merchantAccountCADMap.put(paymentInstance.leadId__c,paymentInstance.leadId__r.Collective_Cash_Collections_CAD__c);
            }
            //Calculate Collection CAD amounts on Merchant Account Payment
            if(merchantAccountCADMap.containsKey(paymentInstance.leadId__c)){
                system.debug('contains CAD');
                system.debug('merchantAccountCADMap.get(paymentInstance.leadId__c):'+merchantAccountCADMap.get(paymentInstance.leadId__c));
                paymentInstance.Previous_CAD__c = merchantAccountCADMap.get(paymentInstance.leadId__c);
                system.debug('paymentInstance.Current_CAD__c:'+paymentInstance.Current_CAD__c);
                system.debug('paymentInstance.Previous_CAD__c:'+paymentInstance.Previous_CAD__c);
                paymentInstance.Current_CAD__c = paymentInstance.Previous_CAD__c + paymentInstance.amount__c;
                merchantAccountCADMap.put(paymentInstance.leadId__c,paymentInstance.Current_CAD__c);    
            }
            //Set Payment Processed checkbox to true
            paymentInstance.Payment_Processed__c = true;
            system.debug('paymentInstance: '+paymentInstance);
            listMerchantAccountPaymentToUpdate.add(paymentInstance);
        }
        
        update mapIdMerchantAccounts.values();
        update listMerchantAccountPaymentToUpdate;
    }
    
    global void finish(Database.BatchableContext bc){
        //Call batch to update Max Deliquency Days on Merchant Accounts
        Database.executeBatch(new MerchantAccountUpdatesBatch(), 200);
    }
}