force-app/main/default/objects/Merchant_Account__c/Merchant_Account__c.object-meta.xml
<CustomObject>
    <description>Merchant Account Object</description>
    <label>Merchant Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>LeadId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Account__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>BorrowerAddress1</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>BorrowerAddress1</inlineHelpText>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Borrower City</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Borrower City</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>current balance (advance amount minus payments)</description>
    <inlineHelpText>current balance (advance amount minus payments)</inlineHelpText>
    <label>Current Balance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Current_Balance_When_Payments_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance_When_Payments_Loaded__c</fullName>
    <label>Current Balance When Payments Loaded</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Date_when_payments_loaded__c.field-meta.xml
<CustomField>
    <fullName>Date_when_payments_loaded__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date when payments loaded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <description>Merchant this product is related to</description>
    <inlineHelpText>Merchant this product is related to</inlineHelpText>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Merchant_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Borrower Postal Code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Borrower Postal Code</inlineHelpText>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Account__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Borrower Province</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Borrower Province</inlineHelpText>
    <label>Province</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/Merchant_Account_Payment__c.object-meta.xml
<CustomObject>
    <description>Merchant Account Payment Object</description>
    <label>Merchant Account Payment</label>
    <nameField>
        <displayFormat>MAP-{000000}</displayFormat>
        <label>Merchant Account Payment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Account Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the transaction</description>
    <inlineHelpText>The amount of the transaction</inlineHelpText>
    <label>amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <label>leadId</label>
    <referenceTo>Merchant_Account__c</referenceTo>
    <relationshipLabel>Merchant Account Payments</relationshipLabel>
    <relationshipName>Merchant_Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Previous_Balance__c.field-meta.xml
<CustomField>
    <fullName>Previous_Balance__c</fullName>
    <description>Previous Balance</description>
    <inlineHelpText>Previous Balance</inlineHelpText>
    <label>Previous Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <description>How the transaction was processed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>How the transaction was processed</inlineHelpText>
    <label>processor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/TranDate__c.field-meta.xml
<CustomField>
    <fullName>TranDate__c</fullName>
    <description>The date of the transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date of the transaction</inlineHelpText>
    <label>trandate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Merchant_Account_Payment__c/fields/TranType__c.field-meta.xml
<CustomField>
    <fullName>TranType__c</fullName>
    <description>The type of transaction</description>
    <inlineHelpText>The type of transaction</inlineHelpText>
    <label>trantype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH Rejection Fees</fullName>
            </value>
            <value>
                <fullName>ACH Rejections</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Daily/Weekly ACH - US Bank</fullName>
            </value>
            <value>
                <fullName>Daily ACH</fullName>
            </value>
            <value>
                <fullName>Debit Memo</fullName>
            </value>
            <value>
                <fullName>Deferred Interest</fullName>
            </value>
            <value>
                <fullName>Deferred Premium</fullName>
            </value>
            <value>
                <fullName>Merchant Refund</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Recovery Payment</fullName>
            </value>
            <value>
                <fullName>Recovery Settlement</fullName>
            </value>
            <value>
                <fullName>US Bank ACH</fullName>
            </value>
            <value>
                <fullName>US Bank Daily ACH</fullName>
            </value>
            <value>
                <fullName>US Bank Rejection Fees</fullName>
            </value>
            <value>
                <fullName>US Bank Rejections</fullName>
            </value>
            <value>
                <fullName>Wells Daily ACH</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MCAEmailStatementController.cls
/**************************************************************************************************
 *
 *  Class:   Controller class for email statement generation
 *  @description : 
 *  @author : A5E Consulting
 *  @date : 19/05/2021
 
*************************************************************************************************/
public class MCAEmailStatementController {
    //public list<paymentWrapper> listPaymentWrapper {get;set;}
    public list<Merchant_Account_Payment__c> listPaymentsToDisplay {get;set;}
    public Merchant_Account__c merchantAcc {get;set;}
    public String strTodayDate {get;set;}
    public Double totalDue {get;set;}
    public String statementMonth {get;set;}
    
    public static String BALANCE_FORWARD = 'Balance Forward';

    public MCAEmailStatementController(){
        Id merchantRecordId = ApexPages.currentPage().getParameters().get('id');
        listPaymentsToDisplay = new list<Merchant_Account_Payment__c>();
        merchantAcc = new Merchant_Account__c();
        merchantAcc = [SELECT ID, Name, 
                                // Former_BFS_Capital_Account_Number_XXXX__c,
                                // Former_BFS_Capital_Account_Number__c,
                                Address__c, City__c, Province__c, Postal_Code__c, 
                                Merchant__r.DBA__c,Current_Balance__c, Current_Balance_When_Payments_Loaded__c,
                       			Date_When_payments_loaded__c 
                       FROM Merchant_Account__c 
                       WHERE id = :merchantRecordId
                       LIMIT 1];
        strTodayDate = DateTime.now().format('MMMM d\',\' yyyy', UserInfo.getTimeZone().toString());
        statementMonth = DateTime.now().addMonths(-1).format('MMMM', UserInfo.getTimeZone().toString());
        getPaymentDetails(merchantRecordId);
    }
    
    public list<Merchant_Account_Payment__c> getPaymentDetails(ID merchantRecordId){
        Date lastDayPreviousMonth = Date.today().toStartOfMonth().addDays(-1);
        Date firstDayPreviousMonth = lastDayPreviousMonth.toStartOfMonth();
        system.debug('firstDayPreviousMonth: '+firstDayPreviousMonth);
        system.debug('lastDayPreviousMonth: '+lastDayPreviousMonth);
		
		//----Calculate the Current Balance value before the first transaction of Statement Month Starts---//
        Double Current_Balance = merchantAcc.Current_Balance_When_Payments_Loaded__c;
		system.debug('Current_Balance from Merchant Account: '+Current_Balance);
		for(Merchant_Account_Payment__c paymentInstance : [SELECT ID, Amount__c 
                                                           FROM Merchant_Account_Payment__c
                                                           WHERE TranDate__c > :merchantAcc.Date_when_payments_loaded__c
                                                           AND TranDate__c < :firstDayPreviousMonth
                                                           AND LeadID__c = :merchantAcc.Id]){
            Current_Balance = Current_Balance - paymentInstance.Amount__c;
        }        
        system.debug('Current_Balance after prev deduction: '+Current_Balance);
        //----Calculate the Current Balance value before the first transaction of Statement Month ENDS---//
        
        //Get Statement Month transactions
        Integer i = 0;
        for(Merchant_Account_Payment__c paymentInstance : [SELECT ID, Amount__c, Processor__c, TranType__c, TranDate__c
                                                           FROM Merchant_Account_Payment__c
                                                           WHERE TranDate__c >= :firstDayPreviousMonth
                                                           AND TranDate__c <= :lastDayPreviousMonth
                                                           AND LeadID__c = :merchantAcc.Id
                                                           ORDER BY TranDate__c ASC,
                                                           Amount__c DESC]){
            //Get Balance Forward as first row
            if(i == 0){
                listPaymentsToDisplay.add(new Merchant_Account_Payment__c(Amount__c = Current_Balance,
                Processor__c = BALANCE_FORWARD, TranType__c = BALANCE_FORWARD,TranDate__c = firstDayPreviousMonth.addDays(-1),
                                                                Current_Balance__c = Current_Balance));
            }
			Current_Balance = Current_Balance - paymentInstance.Amount__c;
			listPaymentsToDisplay.add(new Merchant_Account_Payment__c(Amount__c = paymentInstance.Amount__c,
                Processor__c = paymentInstance.Processor__c, TranType__c = paymentInstance.TranType__c,
                                                                           TranDate__c = paymentInstance.TranDate__c,
                                                                		   Current_Balance__c = Current_Balance)); 
			
			totalDue = Current_Balance;
            //listPaymentsToDisplay.add(merchantAccountPayment);  
            i++;            
        }
		system.debug('listPaymentsToDisplay: '+listPaymentsToDisplay.size());
        //Check if Payments List is empty, display Balance Forward and Total Due
        if(listPaymentsToDisplay.isEmpty()){
            //if no transactions made for the statement month, get the Balance Forward calculated based on
            //payment amount from previous month 
            for(Merchant_Account_Payment__c merchantAccountPayment : [SELECT ID, Amount__c, TranDate__c, TranType__c,
                                                                 	  Processor__c,Current_Balance__c, Previous_Balance__c,
                                                                      leadId__r.Current_Balance__c
                                                                 	  FROM Merchant_Account_Payment__c
                                                                 	  WHERE leadId__c= :merchantRecordId
                                                                 	  AND TranDate__c <= :firstDayPreviousMonth
                                                                      ORDER BY TranDate__c DESC
                                                                      LIMIT 1]){
				if(merchantAccountPayment.Current_Balance__c == NULL){
					listPaymentsToDisplay.add(new Merchant_Account_Payment__c(Amount__c = merchantAccountPayment.leadId__r.Current_Balance__c,
                	Processor__c = BALANCE_FORWARD, TranType__c = BALANCE_FORWARD,TranDate__c = firstDayPreviousMonth.addDays(-1),
                                                                Current_Balance__c = merchantAccountPayment.leadId__r.Current_Balance__c));                                        
                }
				else{
                    listPaymentsToDisplay.add(new Merchant_Account_Payment__c(Amount__c = merchantAccountPayment.Current_Balance__c,
                	Processor__c = BALANCE_FORWARD, TranType__c = BALANCE_FORWARD,TranDate__c = firstDayPreviousMonth.addDays(-1),
                                                                Current_Balance__c = merchantAccountPayment.Current_Balance__c));                                       
                }
				//totalDue will be set to Current Balance if no new transactions are made 
				totalDue = merchantAccountPayment.Current_Balance__c;
				
			}
        }
        
        return listPaymentsToDisplay;
    }
}