force-app/main/default/objects/EFT_Files__c/EFT_Files__c.object-meta.xml
<CustomObject>
    <label>EFT Files</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>EFT Files  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Files__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <description>Cheque Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cheque Number</inlineHelpText>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/CCS_Account__c.field-meta.xml
<CustomField>
    <fullName>CCS_Account__c</fullName>
    <description>CCS Account</description>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distressed_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GoEasy_CCS_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <description>Cheque / Payment Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cheque / Payment Reference Number</inlineHelpText>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to EFT Record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/FairShare_Amount__c.field-meta.xml
<CustomField>
    <fullName>FairShare_Amount__c</fullName>
    <description>FairShare Amount = Gross_Payment_Amount__c * CCS_Account__r.FairShare_Percentage__c</description>
    <inlineHelpText>FairShare Amount = Gross_Payment_Amount__c * FairShare_Percentage__c on CCS Account</inlineHelpText>
    <label>FairShare Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Product Account.</description>
    <inlineHelpText>The amount to be applied to the Product Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Product Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Product Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Source__c</fullName>
    <description>Payment Source</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1 OR 2 OR 3
1 - Placement,
2 - CFG,
3 - Seller,</inlineHelpText>
    <label>Payment Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayAllocatedProductController.cls
public class DisplayAllocatedProductController {
    public list<Product_Payments__c> listProductPayment {get;set;}
    Id EFTRecordId;
    public DisplayAllocatedProductController(){
        EFTRecordId = ApexPages.currentPage().getParameters().get('id');
        if(EFTRecordId != null){
        	listProductPayment = [SELECT ID, CCS_Account__c, Cheque_Number__c, Payment_Posting_Date__c,
                              		 	 Payment_Source__c, FairShare_Amount__c, Payment_Amount__c, CCS_Account__r.First_Name__c,
                                  		 CCS_Account__r.Last_Name__c
                              	  FROM Product_Payments__c 
                                  WHERE EFT_Files__c = :EFTRecordId];    
        }
        
        if(listProductPayment.isEmpty()){
            Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'There are no Allocated Product Payments to display!'));
        }
    }
    public pageReference redirectPaymentUpload(){
        PageReference retURL = new PageReference('/apex/PaymentUpload?id='+EFTRecordId);
        retURL.setRedirect(true);
        return retURL;
    }
}