force-app/main/default/objects/EFT_Files__c/EFT_Files__c.object-meta.xml
<CustomObject>
    <label>EFT Files</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>EFT Files  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Files__c/fields/Allocated_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Amount__c</fullName>
    <description>Total Allocated Payment Amount</description>
    <inlineHelpText>Total Allocated Payment Amount</inlineHelpText>
    <label>Allocated Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Allocated_Payments_Count__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Allocated Payments Count</description>
    <inlineHelpText>Allocated Payments Count</inlineHelpText>
    <label>Allocated Payments Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <description>Cheque Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cheque Number</inlineHelpText>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <description>Posting Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Posting Date</inlineHelpText>
    <label>Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Product_Custom__c.field-meta.xml
<CustomField>
    <fullName>Product_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created for the development purpose to have in the EFTUtil Wrapper</description>
    <label>Product_Custom</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>EFT Files</relationshipLabel>
    <relationshipName>EFT_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Text_URL__c.field-meta.xml
<CustomField>
    <fullName>Text_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Text URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Unallocated_Payments_count__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payments_count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Unallocated Payments count</description>
    <inlineHelpText>Unallocated Payments count</inlineHelpText>
    <label>Unallocated Payments count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Unallocated_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Processing_Status__c</fullName>
    <description>Unallocated Processing Status</description>
    <inlineHelpText>Unallocated Processing Status</inlineHelpText>
    <label>Unallocated Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/EFT_Processing_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>EFT Processing Config</label>
</CustomObject>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Product_Payment_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Product_Payment_RecordTypeID__c</fullName>
    <description>Product Payment RecordTypeID EFT</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Product Payment RecordTypeID EFT</inlineHelpText>
    <label>Product Payment RecordTypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/CCS_Account__c.field-meta.xml
<CustomField>
    <fullName>CCS_Account__c</fullName>
    <description>CCS Account</description>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distressed_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GoEasy_CCS_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <description>Cheque / Payment Reference Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Cheque / Payment Reference Number</inlineHelpText>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to EFT Record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/FairShare_Amount__c.field-meta.xml
<CustomField>
    <fullName>FairShare_Amount__c</fullName>
    <description>FairShare Amount = Gross_Payment_Amount__c * CCS_Account__r.FairShare_Percentage__c</description>
    <inlineHelpText>FairShare Amount = Gross_Payment_Amount__c * FairShare_Percentage__c on CCS Account</inlineHelpText>
    <label>FairShare Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Product Account.</description>
    <inlineHelpText>The amount to be applied to the Product Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Product Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Product Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Source__c</fullName>
    <description>Payment Source</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1 OR 2 OR 3
1 - Placement,
2 - CFG,
3 - Seller,</inlineHelpText>
    <label>Payment Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to unallocated payment reocord</description>
    <inlineHelpText>Link to unallocated payment reocord</inlineHelpText>
    <label>Unallocated Payment</label>
    <referenceTo>Unallocated_Payment__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/Unallocated_Payment__c.object-meta.xml
<CustomObject>
    <description>This will store unallocated amounts for Insolvency Account on Remittance</description>
    <label>Unallocated Payment</label>
    <nameField>
        <displayFormat>UPN - {0000}</displayFormat>
        <label>Unallocated Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unallocated Payment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unallocated_Payment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Store Insolvency Account number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cheque Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to EFT record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Unallocated Payment</relationshipLabel>
    <relationshipName>Unallocated_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Source_File_Link__c.field-meta.xml
<CustomField>
    <fullName>Source_File_Link__c</fullName>
    <description>Source file URL for payments from EFT Processing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Source file URL for payments from EFT Processing</inlineHelpText>
    <label>Source File Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Store unallocated amount for Remittance</description>
    <label>Unallocated Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/fields/Unallocated_Fairshare_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Fairshare_Amount__c</fullName>
    <label>Unallocated Fairshare Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unallocated_Payment__c/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

force-app/main/default/classes/DisplayUnAllocatedPaymentController.cls
public class DisplayUnAllocatedPaymentController {
    public EFT_Files__c eftInstance { get; set; }
    EFT_Processing_Config__c eftConfigInstance;
    public Map<Integer, EFTUtil.paymentRecordsWrapper> wrapperMap { get; set; }
    public boolean disableSave { get; set; }
    public boolean showTable { get; set; }

    public DisplayUnAllocatedPaymentController() {
        List<List<EFTUtil.paymentRecordsWrapper>> paymentRecordList = new List<List<EFTUtil.paymentRecordsWrapper>>();
        List<EFTUtil.paymentRecordsWrapper> paymentRecordListInner = new List<EFTUtil.paymentRecordsWrapper>();
        wrapperMap = new Map<Integer, EFTUtil.paymentRecordsWrapper>();
        List<Unallocated_Payment__c> listUnallocatedPayments = new List<Unallocated_Payment__c>();
        eftConfigInstance = EFT_Processing_Config__c.getOrgDefaults();
        disableSave = false;
        showTable = true;
        String eftRecordId = ApexPages.currentPage().getParameters().get('id');
        eftInstance = new EFT_Files__c();
        if (eftRecordId != null) {
            eftInstance = [
                SELECT
                    ID,
                    Unallocated_Processing_Status__c,
                    User_Id__c,
                    Allocated_Payments_Count__c,
                    Unallocated_Payments_count__c,
                    Allocated_Payments_Amount__c,
                    Posting_Date__c,
                    Text_URL__c
                FROM EFT_Files__c
                WHERE ID = :eftRecordId
            ][0];
            if (eftInstance.Unallocated_Processing_Status__c == 'Completed') {
                listUnallocatedPayments = [
                    SELECT ID, Payment_Posting_Date__c, Account_Number__c, Cheque_Number__c, Unallocated_Fairshare_Amount__c, Unallocated_Amount__c
                    FROM Unallocated_Payment__c
                    WHERE EFT_Files__c = :eftRecordId
                ];
                disableSave = true;
            }
            list<Attachment> unallocatedPayment = [
                SELECT id, name, body
                FROM attachment
                WHERE Name = 'Un-allocated Payments.csv' AND parentId = :eftRecordId
            ];
            Blob csvFileBody = unallocatedPayment[0].body;
            String dataAsString = csvFileBody.toString();
            EFTUtil eftUtilInstance = new EFTUtil();
            try {
                paymentRecordList = eftUtilInstance.readCSVFile(dataAsString);
            } catch (Exception ex) {
                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO, ex.getMessage()));
            }
            if (paymentRecordList.isEmpty()) {
                showTable = false;
                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO, 'There are no Unallocated Product Payments to display!'));
                return;
            }
            for (List<EFTUtil.paymentRecordsWrapper> payWrap : paymentRecordList) {
                paymentRecordListInner.addAll(payWrap);
            }
            for (Integer i = 0; i < paymentRecordListInner.size(); i++) {
                wrapperMap.put(i, paymentRecordListInner[i]);
            }
        }
    }

    public PageReference Save() {
        List<EFTUtil.paymentRecordsWrapper> listUnallocatedPayment = new List<EFTUtil.paymentRecordsWrapper>();
        List<Product_Payments__c> listProductPayment = new List<Product_Payments__c>();
        for (Integer key : wrapperMap.keySet()) {
            EFTUtil.paymentRecordsWrapper wrapRecord = wrapperMap.get(key);
            if (wrapRecord.prodLookup.Product_Custom__c == null) {
                listUnallocatedPayment.add(wrapRecord);
            } else {
                Product_Payments__c paymentInstance = new Product_Payments__c();
                paymentInstance.Created_by_EFT_Processing__c = true;
                paymentInstance.Source_File_Link__c = eftInstance.Text_URL__c;
                if (null != wrapRecord.postingDate && wrapRecord.postingDate != 'null') {
                    paymentInstance.Payment_Posting_Date__c = Date.valueOf(wrapRecord.postingDate);
                }
                if (String.isNotBlank(wrapRecord.paymentSource) && wrapRecord.paymentSource != 'null') {
                    paymentInstance.Payment_Source__c = wrapRecord.paymentSource;
                }
                if (wrapRecord.netPayment != null && wrapRecord.netPayment != 'null') {
                    paymentInstance.Payment_Amount__c = Decimal.valueOf(wrapRecord.netPayment);
                    eftInstance.Allocated_Payments_Amount__c += paymentInstance.Payment_Amount__c;
                }
                paymentInstance.Cheque_Number__c = wrapRecord.chequeNumber;
                paymentInstance.CCS_Account__c = wrapRecord.prodLookup.Product_Custom__c;
                if (String.isNotBlank(wrapRecord.fairsharePayment) && wrapRecord.fairsharePayment != 'null') {
                    paymentInstance.FairShare_Amount__c = Decimal.valueOf(wrapRecord.fairsharePayment);
                }
                paymentInstance.EFT_Files__c = eftInstance.Id;
                if (String.isNotBlank(eftConfigInstance.Product_Payment_RecordTypeID__c)) {
                    paymentInstance.RecordTypeId = eftConfigInstance.Product_Payment_RecordTypeID__c;
                }
                listProductPayment.add(paymentInstance);
            }
        }

        try {
            insert listProductPayment;
            eftInstance.Allocated_Payments_Count__c += listProductPayment.size();
            update eftInstance;
        } catch (Exception ex) {
            system.debug('Exception ex');
        }
        InsertUnallocatedPaymentsBatch instance = new InsertUnallocatedPaymentsBatch(listUnallocatedPayment, eftInstance, 'CCS');
        database.executeBatch(instance);
        eftInstance.Unallocated_Processing_Status__c = 'Completed';
        //disableSave = true;
        showTable = false;
        Apexpages.addMessage(
            new ApexPages.message(Apexpages.Severity.INFO, 'Your file is being processed. You will receive email once processing is completed.')
        );
        return null;
    }

    public pageReference Cancel() {
        PageReference retURL = new PageReference('/apex/PaymentUpload?id=' + eftInstance.Id);
        retURL.setRedirect(true);
        return retURL;
    }
}