force-app/main/default/objects/EFT_Files__c/EFT_Files__c.object-meta.xml
<CustomObject>
    <label>EFT Files</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>EFT Files  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Files__c/fields/Allocated_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Amount__c</fullName>
    <description>Total Allocated Payment Amount</description>
    <inlineHelpText>Total Allocated Payment Amount</inlineHelpText>
    <label>Allocated Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Allocated_Payments_Count__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Payments_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Allocated Payments Count</description>
    <inlineHelpText>Allocated Payments Count</inlineHelpText>
    <label>Allocated Payments Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>EFT Files</relationshipLabel>
    <relationshipName>EFT_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <description>Posting Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Posting Date</inlineHelpText>
    <label>Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Text_URL__c.field-meta.xml
<CustomField>
    <fullName>Text_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Text URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Total_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments_Amount__c</fullName>
    <description>Total Payments Amount</description>
    <inlineHelpText>Total Payments Amount</inlineHelpText>
    <label>Total Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EFT_Files__c/fields/Unallocated_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Processing_Status__c</fullName>
    <description>Unallocated Processing Status</description>
    <inlineHelpText>Unallocated Processing Status</inlineHelpText>
    <label>Unallocated Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EFT_Processing_Config__c/EFT_Processing_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>EFT Processing Config</label>
</CustomObject>

force-app/main/default/objects/EFT_Processing_Config__c/fields/Insolvency_Payment_Record_TypeID__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Payment_Record_TypeID__c</fullName>
    <description>Record type id of Insolvency Payment for EFT</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record type id of Insolvency Payment for EFT</inlineHelpText>
    <label>Insolvency Payment Record TypeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/Cheque_Payment_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Payment_Reference_Number__c</fullName>
    <description>A payment reference number.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A payment reference number.</inlineHelpText>
    <label>Cheque/ Payment Reference Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Created_by_EFT_Processing__c.field-meta.xml
<CustomField>
    <fullName>Created_by_EFT_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>set to true when records are created from EFT processing</description>
    <inlineHelpText>set to true when records are created from EFT processing</inlineHelpText>
    <label>Created by EFT Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/EFT_Files__c.field-meta.xml
<CustomField>
    <fullName>EFT_Files__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to EFT Record</description>
    <label>EFT Files</label>
    <referenceTo>EFT_Files__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Insolvency Account.</description>
    <inlineHelpText>The amount to be applied to the Insolvency Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Insolvency Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Insolvency Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Source__c</fullName>
    <description>Payment Source</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Source</inlineHelpText>
    <label>Payment Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type</description>
    <inlineHelpText>Payment Type</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1003</fullName>
            </value>
            <value>
                <fullName>1001</fullName>
            </value>
            <value>
                <fullName>3000</fullName>
            </value>
            <value>
                <fullName>1002</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>4003</fullName>
            </value>
            <value>
                <fullName>3400</fullName>
            </value>
            <value>
                <fullName>4000</fullName>
            </value>
            <value>
                <fullName>5000</fullName>
            </value>
            <value>
                <fullName>7001</fullName>
            </value>
            <value>
                <fullName>4002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisplayInsolUnAllocatedPaymentController.cls
public class DisplayInsolUnAllocatedPaymentController {
    public EFT_Files__c eftInstance { get; set; }
    public Map<Integer, EFTUtil.paymentRecordsWrapper> wrapperMap { get; set; }
    EFT_Processing_Config__c eftConfigInstance;
    public boolean disableSave { get; set; }
    public boolean showTable { get; set; }

    public DisplayInsolUnAllocatedPaymentController() {
        wrapperMap = new Map<Integer, EFTUtil.paymentRecordsWrapper>();
        List<List<EFTUtil.paymentRecordsWrapper>> paymentRecordList = new List<List<EFTUtil.paymentRecordsWrapper>>();
        List<EFTUtil.paymentRecordsWrapper> paymentRecordListInner = new List<EFTUtil.paymentRecordsWrapper>();
        eftConfigInstance = EFT_Processing_Config__c.getOrgDefaults();
        disableSave = false;
        showTable = true;
        String eftRecordId = ApexPages.currentPage().getParameters().get('id');
        eftInstance = new EFT_Files__c();
        if (eftRecordId != null) {
            eftInstance = [
                SELECT
                    ID,
                    Posting_Date__c,
                    Allocated_Payments_Count__c,
                    Unallocated_Processing_Status__c,
                    User_Id__c,
                    Allocated_Payments_Amount__c,
                    Total_Payments_Amount__c,
                    Text_URL__c
                FROM EFT_Files__c
                WHERE ID = :eftRecordId
            ][0];
            if (eftInstance.Unallocated_Processing_Status__c == 'Completed') {
                disableSave = true;
            }
            list<Attachment> unallocatedPayment = [
                SELECT id, name, body
                FROM attachment
                WHERE Name = 'Un-allocated Payments.csv' AND parentId = :eftRecordId
            ];
            Blob csvFileBody = unallocatedPayment[0].body;
            String dataAsString = csvFileBody.toString();
            EFTUtil eftUtilInstance = new EFTUtil();
            paymentRecordList = eftUtilInstance.readCSVFile(dataAsString);
            if (paymentRecordList.isEmpty()) {
                showTable = false;
                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO, 'There are no Unallocated Product Payments to display!'));
                return;
            }
            for (List<EFTUtil.paymentRecordsWrapper> payWrap : paymentRecordList) {
                paymentRecordListInner.addAll(payWrap);
            }
            for (Integer i = 0; i < paymentRecordListInner.size(); i++) {
                wrapperMap.put(i, paymentRecordListInner[i]);
            }
        }
    }

    public PageReference Save() {
        List<EFTUtil.paymentRecordsWrapper> listUnallocatedPayment = new List<EFTUtil.paymentRecordsWrapper>();
        List<Insolvency_Payment__c> listInsolvencyPayment = new List<Insolvency_Payment__c>();
        for (Integer key : wrapperMap.keySet()) {
            EFTUtil.paymentRecordsWrapper wrapRecord = wrapperMap.get(key);
            if (wrapRecord.prodLookup.Insolvency_Account__c == null) {
                listUnallocatedPayment.add(wrapRecord);
            } else {
                Insolvency_Payment__c paymentInstance = new Insolvency_Payment__c();
                paymentInstance.Created_by_EFT_Processing__c = true;
                paymentInstance.Source_File_Link__c = eftInstance.Text_URL__c;
                paymentInstance.Payment_Posting_Date__c = eftInstance.Posting_Date__c;
                if (wrapRecord.paymentSource != 'null') {
                    paymentInstance.Payment_Source__c = wrapRecord.paymentSource;
                }
                if (wrapRecord.paymentType != 'null') {
                    paymentInstance.Payment_Type__c = wrapRecord.paymentType;
                }
                paymentInstance.Cheque_Payment_Reference_Number__c = wrapRecord.chequeNumber;
                if (wrapRecord.netPayment != null && wrapRecord.netPayment != 'null') {
                    paymentInstance.Payment_Amount__c = Decimal.valueOf(wrapRecord.netPayment);
                    eftInstance.Allocated_Payments_Amount__c += paymentInstance.Payment_Amount__c;
                }
                paymentInstance.Insolvency_Account__c = wrapRecord.prodLookup.Insolvency_Account__c;
                paymentInstance.EFT_Files__c = eftInstance.Id;
                if (String.isNotBlank(eftConfigInstance.Insolvency_Payment_Record_TypeID__c)) {
                    paymentInstance.RecordTypeId = eftConfigInstance.Insolvency_Payment_Record_TypeID__c;
                }
                listInsolvencyPayment.add(paymentInstance);
            }
        }
        try {
            insert listInsolvencyPayment;
            eftInstance.Allocated_Payments_Count__c += listInsolvencyPayment.size();
            update eftInstance;
        } catch (Exception ex) {
            system.debug('Exception ex: ' + ex);
        }
        InsertUnallocatedPaymentsBatch instance = new InsertUnallocatedPaymentsBatch(listUnallocatedPayment, eftInstance, 'Insolvency');
        database.executeBatch(instance);
        //disableSave = true;
        showTable = false;
        Apexpages.addMessage(
            new ApexPages.message(Apexpages.Severity.INFO, 'Your file is being processed. You will receive email once processing is completed.')
        );
        return null;
    }

    public pageReference Cancel() {
        PageReference retURL = new PageReference('/apex/InsolvencyPaymentUpload?id=' + eftInstance.Id);
        retURL.setRedirect(true);
        return retURL;
    }
}