force-app/main/default/objects/Data_Status_Mapping__c/Data_Status_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Data Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Data_Status_Mapping__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Current_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Amount__c</fullName>
    <description>The total amount of interest accrued on this insolvency account to date</description>
    <inlineHelpText>The total amount of interest accrued on this insolvency account to date</inlineHelpText>
    <label>Current Interest Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Principal_Balance__c</fullName>
    <description>The total current principal amount on this account to date</description>
    <inlineHelpText>The total current principal amount on this account to date</inlineHelpText>
    <label>Current Principal Balance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Data_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Data_Status_Description__c</fullName>
    <description>Description for the Product Status value</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Description for the Product Status value</inlineHelpText>
    <label>Data Status Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Previously_Reviewed_for_Legal_Action__c.field-meta.xml
<CustomField>
    <fullName>Previously_Reviewed_for_Legal_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Previously Reviewed for Legal Action</inlineHelpText>
    <label>Previously Reviewed for Legal Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>Sub Status</description>
    <inlineHelpText>Sub Status</inlineHelpText>
    <label>Placement Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Accepted by agency</fullName>
            </value>
            <value>
                <fullName>Initial Letter Sent</fullName>
            </value>
            <value>
                <fullName>Follow-Up Letter Sent</fullName>
            </value>
            <value>
                <fullName>Return To Sender</fullName>
            </value>
            <value>
                <fullName>Added To Dialer</fullName>
            </value>
            <value>
                <fullName>Message Left</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
            </value>
            <value>
                <fullName>Email Contact Established</fullName>
            </value>
            <value>
                <fullName>Possible Payer</fullName>
            </value>
            <value>
                <fullName>Settlement Pending</fullName>
            </value>
            <value>
                <fullName>Refusal</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Debtor Claims Paid - Awaiting Proof</fullName>
            </value>
            <value>
                <fullName>Proof of Payment Submitted to Client</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Client Request</fullName>
            </value>
            <value>
                <fullName>Checking for Assets - Possible Legal</fullName>
            </value>
            <value>
                <fullName>Claim Issued</fullName>
            </value>
            <value>
                <fullName>Claim Served</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement</fullName>
            </value>
            <value>
                <fullName>Defended Action</fullName>
            </value>
            <value>
                <fullName>Media Requested - Awaiting</fullName>
            </value>
            <value>
                <fullName>Counterclaim</fullName>
            </value>
            <value>
                <fullName>Abandonned Claim</fullName>
            </value>
            <value>
                <fullName>Recommended for Legal Action</fullName>
            </value>
            <value>
                <fullName>Approved for Legal Action</fullName>
            </value>
            <value>
                <fullName>Reviewing for Legal action</fullName>
            </value>
            <value>
                <fullName>Demand Letter Sent</fullName>
            </value>
            <value>
                <fullName>Legal Action Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestProductStatusUpdateController.cls
@istest
public class TestProductStatusUpdateController {
    @isTest
    static void TestMethod1(){
        //Product Record Creation
        Product__C prod = new Product__c();
        string recrdid= [SELECT id from RecordType where sobjecttype='product__c' 
                         AND RecordType.Name='Distressed Account'].id;
        prod.RecordTypeId=recrdid;
        prod.Name ='123456789';
        prod.Previously_Reviewed_for_Legal_Action__c=True;
        prod.Current_Principal_Balance__c=101;
        prod.Current_Interest_Amount__c=1000;
        prod.Status__c = 'New Allocation - New Allocation';
        prod.Sub_Status__c = 'Ready';
        prod.Product_Status__c = 'Test';
        prod.OwnerId= UserInfo.getUserId();
        prod.Data_Status_Description__c='Warehouse:';
        ProductTriggerHandler.runProductTrigger = False;
        insert prod;
        ProductTriggerHandler.runProductTrigger = True;
        
        //Data Status Mapping Custom Settings records insertion
        Data_Status_Mapping__c dataMap = new Data_Status_Mapping__c();
        dataMap.name = '310000';
        dataMap.Description__C = 'Pending Allocation test';
        insert dataMap;
        
        Data_Status_Mapping__c dataMap1 = new Data_Status_Mapping__c();
        dataMap1.name = 'Test1';
        dataMap1.Description__C = 'Warehouse Test';
        insert dataMap1;
        
        Data_Status_Mapping__c dataMap2 = new Data_Status_Mapping__c();
        dataMap2.name = 'Test2';
        dataMap2.Description__C = 'close Test';
        insert dataMap2;
        
        ApexPages.currentPage().getParameters().put('id', prod.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(prod);
        ProductStatusUpdateIndividualController controller1 = new ProductStatusUpdateIndividualController(sc);
        controller1.redirectToProduct();
        controller1.selectedValueAction = 'Warehouse Test';
        controller1.updateProduct();        
        
    }
    @isTest
    static void TestMethod2(){
        
        string recrdid= [SELECT id from RecordType where sobjecttype='product__c' 
                         AND RecordType.Name='Distressed Account'].id;
        
        //Data Status Mapping Custom Settings records insertion
        Data_Status_Mapping__c dataMap = new Data_Status_Mapping__c();
        dataMap.name = '310000';
        dataMap.Description__C = 'Pending Allocation test';
        insert dataMap;
        
        Data_Status_Mapping__c dataMap1 = new Data_Status_Mapping__c();
        dataMap1.name = 'Test1';
        dataMap1.Description__C = 'Warehouse Test';
        insert dataMap1;
        
        Data_Status_Mapping__c dataMap2 = new Data_Status_Mapping__c();
        dataMap2.name = 'Test2';
        dataMap2.Description__C = 'close Test';
        insert dataMap2;
        //Product Record Creation
        Product__C prod1 = new Product__c();
        
        prod1.RecordTypeId=recrdid;
        prod1.Name ='123456789';
        prod1.Previously_Reviewed_for_Legal_Action__c=True;
        prod1.Current_Principal_Balance__c=101;
        prod1.Current_Interest_Amount__c=1000;
        prod1.Status__c = 'New Allocation - New Allocation';
        prod1.Sub_Status__c = 'Ready';
        prod1.Product_Status__c = 'Test';
        prod1.OwnerId= UserInfo.getUserId();
        prod1.Data_Status_Description__c='Pending Allocation:';
        ProductTriggerHandler.runProductTrigger = False;
        insert prod1;
        ProductTriggerHandler.runProductTrigger = True;
        
        
        ApexPages.currentPage().getParameters().put('id', prod1.Id);
        
        ApexPages.StandardController sc1 = new ApexPages.standardController(prod1);
        ProductStatusUpdateIndividualController controller2 = new ProductStatusUpdateIndividualController(sc1);
        controller2.redirectToProduct();
        controller2.selectedValueAction = 'Warehouse Test';
        controller2.updateProduct();        
        
    }
    @isTest
    static void Testmethod3(){
        
        string recrdid= [SELECT id from RecordType where sobjecttype='product__c' 
                         AND RecordType.Name='Distressed Account'].id;
        
        //Data Status Mapping Custom Settings records insertion
        Data_Status_Mapping__c dataMap = new Data_Status_Mapping__c();
        dataMap.name = '310000';
        dataMap.Description__C = 'Pending Allocation test';
        insert dataMap;
        
        Data_Status_Mapping__c dataMap1 = new Data_Status_Mapping__c();
        dataMap1.name = 'Test1';
        dataMap1.Description__C = 'Warehouse Test';
        insert dataMap1;
        
        Data_Status_Mapping__c dataMap2 = new Data_Status_Mapping__c();
        dataMap2.name = 'Test2';
        dataMap2.Description__C = 'close Test';
        insert dataMap2;
        
        //Product Record Creation
        Product__C prod2 = new Product__c();
        
        prod2.RecordTypeId=recrdid;
        prod2.Name ='123456789';
        prod2.Previously_Reviewed_for_Legal_Action__c=True;
        prod2.Current_Principal_Balance__c=101;
        prod2.Current_Interest_Amount__c=1000;
        prod2.Status__c = 'New Allocation - New Allocation';
        prod2.Sub_Status__c = 'Ready';
        prod2.Product_Status__c = 'Test';
        prod2.OwnerId= UserInfo.getUserId();
        prod2.Data_Status_Description__c='closed:';
        
        ProductTriggerHandler.runProductTrigger = False;
        insert prod2;
        ProductTriggerHandler.runProductTrigger = True;
        
        ApexPages.currentPage().getParameters().put('id', prod2.Id);
        ApexPages.StandardController sc2 = new ApexPages.standardController(prod2);
        ProductStatusUpdateIndividualController controller3 = new ProductStatusUpdateIndividualController(sc2);
        controller3.redirectToProduct();
        controller3.selectedValueAction = 'Warehouse Test';
        controller3.updateProduct();  
        controller3.statusFlag=true;
        
    }
}