force-app/main/default/objects/Data_Status_Mapping__c/Data_Status_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Data Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Data_Status_Mapping__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement_Status_Mapping__c/Placement_Status_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Placement Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Date__c</fullName>
    <description>Date on which CFG user allocated Placement to account</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date on which CFG user allocated Placement to account</inlineHelpText>
    <label>Placement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Data_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Data_Status_Description__c</fullName>
    <description>Description for the Product Status value</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Description for the Product Status value</inlineHelpText>
    <label>Data Status Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <description>Placement Status</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Placement Status</inlineHelpText>
    <label>Placement Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>OO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductStatusUpdateIndividualController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Controller class to update Product Status individually from Product record
*  @author : A5E Consulting
*  @date : 28/03/2022

*************************************************************************************************/
public with sharing class ProductStatusUpdateIndividualController {
    public map<String, Data_Status_Mapping__c> dataStatusMap = Data_Status_Mapping__c.getAll();
    public map<String, Placement_Status_Mapping__c> placementStatusMap = Placement_Status_Mapping__c.getAll();
    public boolean warehouse{get;set;}
    public boolean pendingAllocation{get;set;}
    public boolean closed{get;set;}
    public boolean updateProductButtonFlag{get;set;}
    public boolean statusFlag{get;set;}
    public boolean positiveFlag{get;set;}
    public string currentStatus{get;set;}
    public list<SelectOption> listDataStatusOptions {get;set;}
    public string StatusText{get;set;}
    public boolean StatusTextFlag{get;set;}
    public boolean labelDisplay{get;set;}
    public string buyBackText='Closed: Buyback';
    public string putBackText='Closed: Putback';
    public string soldText='Closed: Sold';
    
    public String SUCCESS_MSG {get;set;}
    public String productID {get;set;}
    public String selectedValueAction {get;set;}
    public List<Product__c> listProduct = new List<Product__c>();
    public Product__c product {get;set;}
    public String valiError{get;set;}
    
    public ProductStatusUpdateIndividualController(ApexPages.StandardController stdController) {
        listDataStatusOptions=new list<selectOption>();
        productID =  ApexPages.currentPage().getParameters().get('id');
        product = [SELECT ID, Name, Data_Status_Description__c,State__c, Placement_Status__c,Product_Status__c, Status__c,Collection_Agency__c,Assignment_Date__c
                   FROM Product__c WHERE ID= :productID];
        
        Integer persmiss = [SELECT count() FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Product_Status_Update_Access' AND AssigneeId =: Userinfo.getUserId()];
        
        System.debug('persmiss'+persmiss);
        System.debug('UserId'+Userinfo.getUserId());
        if(persmiss == 0){
            system.debug('inside debug'+userinfo.getUserName());
            valiError = 'You are not authorized to access';
        }else{
            system.debug('else debug'+userinfo.getUserName());
        }

        if(product.Data_Status_Description__c <> NULL){    
            StatusTextFlag=false;
            currentStatus=product.Data_Status_Description__c;
            system.debug('currentStatus--->'+currentStatus);
            system.debug('product.Data_Status_Description__c: '+product.Data_Status_Description__c);
            system.debug('buy back checking-->'+product.Data_Status_Description__c.Equals(buyBackText));
            system.debug('put back checking-->'+product.Data_Status_Description__c.Equals(putBackText));
            system.debug('sold checking-->'+product.Data_Status_Description__c.Equals(soldText));
            if(product.Data_Status_Description__c.startsWith('Warehouse') && (!product.Product_Status__c.startsWith('998') && !product.Product_Status__c.startsWith('997') && !product.Product_Status__c.startsWith('499000'))){
                system.debug('Inside warehouse');
                warehouse = true;
                positiveFlag=true;
                updateProductButtonFlag=true;
                labelDisplay=true;
            }
            if(product.Data_Status_Description__c.startsWith('Pending Allocation') && (!product.Product_Status__c.startsWith('998') && !product.Product_Status__c.startsWith('997') && !product.Product_Status__c.startsWith('499000'))){
                system.debug('Inside Pending Allocation');
                positiveFlag=true;
                pendingAllocation = true;
                updateProductButtonFlag=true;
                labelDisplay=true;
            }
            if(product.Data_Status_Description__c.startsWith('Closed') && (!product.Product_Status__c.startsWith('998') && !product.Product_Status__c.startsWith('997') && !product.Product_Status__c.startsWith('499000')) && product.Data_Status_Description__c!=soldText){
                system.debug('Inside Closed');
                positiveFlag=true;
                closed=true;
                updateProductButtonFlag=true;
                labelDisplay=true;
            }
            system.debug('warehouse -->'+warehouse);
            system.debug('pendingAllocation -->'+pendingAllocation);
            system.debug('closed -->'+closed);
            if(warehouse!=true && pendingAllocation!=true && closed!=true){
                system.debug('IF Loop -->');
                updateProductButtonFlag=false;
                labelDisplay=false;
                positiveFlag=false;
                StatusTextFlag=false;
                StatusText='We can not update status from "' +currentStatus+'" to another status. Please click on below BACK button';
            }
            list<Data_Status_Mapping__c> CSRecords=[select id,name,Description__c from Data_Status_Mapping__c where Description__c like 'Pending%' OR Description__c like 'Warehouse%' OR Description__c like 'Close%'];
            if(!CSRecords.isEmpty()){
                for(Data_Status_Mapping__c d:CSRecords){
                    listDataStatusOptions.add(new SelectOption(d.Description__c,d.Description__c));
                }
            }
        }
    }
    
    //Update Product  
    public void updateProduct(){ 
        system.debug('product update method');
        system.debug('selectedValueAction -->'+selectedValueAction);
        ProductTriggerHandler.runProductAPITrigger=false;
        RecursiveTriggerHandler.isFirstTime=false;
        Data_Status_Mapping__c dsm=[select id,name from Data_Status_Mapping__c where Description__c=:selectedValueAction limit 1];
        product.Data_Status_Description__c=selectedValueAction;
        product.Product_Status__c =dsm.Name;
        update product;
        SUCCESS_MSG='Product Updated Successfully';
        system.debug('Product Updated');
        
    }
    
    public pageReference redirectToProduct(){
        PageReference pageRef = new PageReference('/'+productID);
        pageRef.setRedirect(true);
        return pageRef;
    }
    
}