force-app/main/default/objects/CTB_Staging__c/CTB_Staging__c.object-meta.xml
<CustomObject>
    <label>CTB Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CTB Stagings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CTB_Staging__c/fields/Accounts_Validation_Date__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Validation_Date__c</fullName>
    <description>Accounts Validation Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Accounts Validation Date</inlineHelpText>
    <label>Accounts Validation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Info</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Balance_Owed__c.field-meta.xml
<CustomField>
    <fullName>Balance_Owed__c</fullName>
    <description>The balance owed on this account.</description>
    <inlineHelpText>The balance owed on this account.</inlineHelpText>
    <label>Balance Owed</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Amount__c</fullName>
    <description>This value will be filed on the proof-of-claim documentation as the final amount owed on this account by the debtor(s).</description>
    <inlineHelpText>This value will be filed on the proof-of-claim documentation as the final amount owed on this account by the debtor(s).</inlineHelpText>
    <label>Claim Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>This field is created as a part of CTB Automation and this field will be used to store unique identifier of Insolvency Account which is used by CTB Business user to reference Insolvency account back to SF system.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DRN Debt Product ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/CTB_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>CTB_Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CTB Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/CTB_Reject_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>CTB_Reject_Reason_Code__c</fullName>
    <label>Reject Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BKPT</fullName>
            </value>
            <value>
                <fullName>CONS</fullName>
            </value>
            <value>
                <fullName>SOLD</fullName>
            </value>
            <value>
                <fullName>DDEC</fullName>
            </value>
            <value>
                <fullName>MLNS</fullName>
            </value>
            <value>
                <fullName>NMAT</fullName>
            </value>
            <value>
                <fullName>NINS</fullName>
            </value>
            <value>
                <fullName>NPRP</fullName>
            </value>
            <value>
                <fullName>NRTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Debtor_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_First_Name__c</fullName>
    <description>First name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First name of the primary debtor.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Debtor_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Last_Name__c</fullName>
    <description>Last name of the primary debtor.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the primary debtor.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The current interest rate charged on this account.</description>
    <inlineHelpText>The current interest rate charged on this account.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Payment_Amount_2__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount_2__c</fullName>
    <description>The last payment amount (2) for this account</description>
    <inlineHelpText>The last payment amount (2) for this account</inlineHelpText>
    <label>Last Payment Amount (2)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Payment_Amount_3__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount_3__c</fullName>
    <description>The last payment amount (3) for this account</description>
    <inlineHelpText>The last payment amount (3) for this account</inlineHelpText>
    <label>Last Payment Amount (3)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <description>The last payment amount for this account</description>
    <inlineHelpText>The last payment amount for this account</inlineHelpText>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <description>The last payment date (1) for this account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The last payment date (1) for this account.</inlineHelpText>
    <label>Last Payment Date (1)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Statement_Amount_2__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Amount_2__c</fullName>
    <description>The amount owning on the last statement sent (2) for this account.</description>
    <inlineHelpText>The amount owning on the last statement sent (2) for this account.</inlineHelpText>
    <label>Last Statement Amount (2)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Statement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Amount__c</fullName>
    <description>The amount owning on the last statement sent (1) for this account.</description>
    <inlineHelpText>The amount owning on the last statement sent (1) for this account.</inlineHelpText>
    <label>Last Statement Amount (1)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Statement_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Date_2__c</fullName>
    <description>The date the last statement was sent (2) for this account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the last statement was sent (2) for this account.</inlineHelpText>
    <label>Last Statement Date (2)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Last_Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Date__c</fullName>
    <description>The date the last statement was sent (1) for this account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the last statement was sent (1) for this account.</inlineHelpText>
    <label>Last Statement Date (1)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>Open Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Open Date</inlineHelpText>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CTBFileValidationUtility.cls
public with sharing class CTBFileValidationUtility {
    public static void validateInsolvencyAccountRecords(String fileName) {
        CTB_Staging__c[] listSuccessStagingRecords = [
            SELECT
                Debtor_1_First_Name__c,
                Debtor_1_Last_Name__c,
                CTB_Date_of_Birth__c,
                Correlation_ID__c,
                CTB_Reject_Reason_Code__c,
                Open_Date__c,
                Balance_Owed__c,
                Claim_Amount__c,
                Accounts_Validation_Date__c,
                Interest_Rate__c,
                Last_Payment_Date__c,
                Last_Payment_Amount__c,
                Last_Payment_Date_2__c,
                Last_Payment_Amount_2__c,
                Last_Payment_Date_3__c,
                Last_Payment_Amount_3__c,
                Last_Statement_Date__c,
                Last_Statement_Amount__c,
                Last_Statement_Date_2__c,
                Last_Statement_Amount_2__c,
                Last_Statement_Date_3__c,
                Last_Statement_Amount_3__c,
                Previous_Account_Reference__c,
                Additional_Info__c
            FROM CTB_Staging__c
        ];
    }
}