force-app/main/default/objects/CTB_Staging__c/CTB_Staging__c.object-meta.xml
<CustomObject>
    <label>CTB Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CTB Stagings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CTB_Staging__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>This field is created as a part of CTB Automation and this field will be used to store unique identifier of Insolvency Account which is used by CTB Business user to reference Insolvency account back to SF system.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DRN Debt Product ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/CTB_Update_Filename__c.field-meta.xml
<CustomField>
    <fullName>CTB_Update_Filename__c</fullName>
    <description>This field is created a part of CTB Automation Ticket and this field will store the file name from which this record was created.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CTB Update Filename</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTB_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Document_Extension__c.field-meta.xml
<CustomField>
    <fullName>Document_Extension__c</fullName>
    <description>Document Extension</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Document Extension</inlineHelpText>
    <label>Document Extension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Document_Storage__c.field-meta.xml
<CustomField>
    <fullName>Document_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent document storage</description>
    <inlineHelpText>Parent document storage</inlineHelpText>
    <label>Parent Document Storage</label>
    <referenceTo>Document_Storage__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/File_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>File_Processing_Status__c</fullName>
    <description>File Processing Status</description>
    <inlineHelpText>File Processing Status</inlineHelpText>
    <label>File Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Staging Table Created</fullName>
            </value>
            <value>
                <fullName>Staging Table Creation Failed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Storage__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is the lookup to Insolvency Account to which the statement is related to</description>
    <inlineHelpText>This field is the lookup to Insolvency Account to which the statement is related to</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/recordTypes/CTB.recordType-meta.xml
<RecordType>
    <fullName>CTB</fullName>
    <active>true</active>
    <description>Record Type for CTB file storage</description>
    <label>CTB</label>
</RecordType>

force-app/main/default/objects/Document_Storage__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Document_Storage__c/recordTypes/MM.recordType-meta.xml
<RecordType>
    <fullName>MM</fullName>
    <active>true</active>
    <description>Record Type for MM file storage</description>
    <label>MM</label>
</RecordType>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Co_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Co_Debtor__c</fullName>
    <description>Name of the co-debtor</description>
    <formula>Debtor_2_First_Name__c + &apos; &apos; + Debtor_2_Last_Name__c</formula>
    <inlineHelpText>Name of the co-debtor</inlineHelpText>
    <label>Co-Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <formula>Debtor_1_First_Name__c + &apos; &apos; + Debtor_1_Last_Name__c</formula>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <description>This field is created as a part of CTB Automation and this field will be used to store unique identifier of Insolvency Account which is used by CTB Business user to reference Insolvency account back to SF system.</description>
    <displayFormat>{0000000000}</displayFormat>
    <label>Correlation Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/CTB_Update_Filename__c.field-meta.xml
<CustomField>
    <fullName>CTB_Update_Filename__c</fullName>
    <description>This field is created a part of Automation Ticket and this field will store the file name of csv processed for insolvency accounts.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Field used to store the file name of csv processed for insolvency accounts</inlineHelpText>
    <label>Incoming Filename</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_1_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The debtor estate number as noted on the creditor’s package</inlineHelpText>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The debtor estate number as noted on the creditor’s package</inlineHelpText>
    <label>Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>Name of the primary debtor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the primary debtor</inlineHelpText>
    <label>Debtor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>This status represents the current point in the processing workflow for this account.</description>
    <inlineHelpText>This status represents the current point in the processing workflow for this account.</inlineHelpText>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Recall Requested</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>BOT Mismatch</fullName>
            </value>
            <value>
                <fullName>BOT Review</fullName>
            </value>
            <value>
                <fullName>BOT Review completed</fullName>
            </value>
            <value>
                <fullName>Claim Filed</fullName>
            </value>
            <value>
                <fullName>Claim Omitted</fullName>
            </value>
            <value>
                <fullName>Claim Withdrawn</fullName>
            </value>
            <value>
                <fullName>Debtor Paying Direct</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Extinguished</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No PoC Required</fullName>
            </value>
            <value>
                <fullName>Pending Assignment to Collection Agency</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Sent to Collections</fullName>
            </value>
            <value>
                <fullName>Trustee Followup</fullName>
            </value>
            <value>
                <fullName>Wait / Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdraw PoC</fullName>
            </value>
            <value>
                <fullName>No Match</fullName>
            </value>
            <value>
                <fullName>Sent on File</fullName>
            </value>
            <value>
                <fullName>Claim Established</fullName>
                <isActive>false</isActive>
                <label>Claim Established</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MMFileProcessingQueueable.cls
/**
 * @description       : Queueable class to parse csv, validate fields and create CTB Staging records for MM accounts
 * @author            : adeshi@a5econsulting.net
 * @last modified on  : 01-07-2025
 * @last modified by  : adesh.ikhar@canaccede.com
 **/
public class MMFileProcessingQueueable implements Queueable, Database.AllowsCallouts {
    // List of file names to process
    public List<String> fileNames = new List<String>();
    // Identifier to know type of file, Account or Payment
    public String fileIdentifier = '';

    public MMFileProcessingQueueable(List<String> fileNames, String fileIdentifier) {
        this.fileNames = fileNames;
        this.fileIdentifier = fileIdentifier;
    }

    /**
     * @description : Execute method to call correct method based on file type
     * @author adeshi@a5econsulting.net | 11-23-2023
     * @param context
     **/
    public void execute(QueueableContext context) {
        try {
            // Call SFTP API to get the file uploaded in SF as a content version record and get it's Id
            String documentId = CTBGetFileApiQueueable.getDocumentId(fileNames[0]);
            if (String.isBlank(documentId)) {
                return;
            }
            // Convert CSV to string
            Document fileToProccess = [SELECT Name, ContentType, Body FROM Document WHERE Id = :documentId];
            String csvContents = fileToProccess.Body.toString();
            // Create Doc storage record with received file details
            Document_Storage__c docStorage = createDocStorage(fileNames[0], fileToProccess.ContentType);
            if (fileIdentifier == System.Label.CTB_Insolvency_Account) {
                processMMStagingAccounts(csvContents, docStorage);
            }
            // Remove the file which was processed
            fileNames.remove(0);
            delete fileToProccess;
            // This will be the last queueable in case of multiple unprocessed files
            if (fileNames.isEmpty()) {
                // Query and delete successfull records
                List<CTB_Staging__c> stagingRecordsToDelete = [SELECT Id FROM CTB_Staging__c WHERE Status__c != 'Error'];
                if (!stagingRecordsToDelete.isEmpty() && !Test.isRunningTest()) {
                    System.enqueueJob(new BulkDmlQueueable(stagingRecordsToDelete, 0, 'Delete'));
                }
                return;
            }
            if (!Test.isRunningTest()) {
                System.enqueueJob(new MMFileProcessingQueueable(fileNames, System.Label.CTB_Insolvency_Account));
            }
        } catch (Exception e) {
            System.debug('Exception in MMFileProcessingQueueable ' + e.getMessage() + e.getStackTraceString());
            CTBFileProcessingQueueable.createInsolvencyError(e.getMessage(), e.getStackTraceString());
        }
    }

    /**
     * @description : Method to create document storage record for incoming file
     * @author adesh.ikhar@canaccede.com | 05-07-2024
     * @param fileName
     * @param extension
     * @return Document_Storage__c
     **/
    public static Document_Storage__c createDocStorage(String fileName, String extension) {
        // Create document storage status associated to the file
        Document_Storage__c docInfo = new Document_Storage__c();
        docInfo.Document_Type__c = 'Insolvency Daily Update';
        docInfo.Document_Extension__c = extension;
        docInfo.Document_Name__c = fileName;
        docInfo.File_Processing_Status__c = 'Pending';
        docInfo.RecordTypeId = Schema.SObjectType.Document_Storage__c.getRecordTypeInfosByName().get('CTB').getRecordTypeId();
        try {
            DocumentStorageTriggerHandler.runDocumentStorageTrigger = false;
            Database.insert(docInfo);
            DocumentStorageTriggerHandler.runDocumentStorageTrigger = true;
            return docInfo;
        } catch (DmlException ex) {
            System.debug('DMLException in createDocStorage ' + ex.getDmlMessage(0));
            CTBFileProcessingQueueable.createInsolvencyError(ex.getDmlMessage(0), ex.getStackTraceString());
            return null;
        }
    }

    /**
     * @description : Parse, validate and create Staging records for Insolvency Accounts
     * @author adeshi@a5econsulting.net | 11-23-2023
     * @param csvContents
     * @param docStorage
     **/
    public static void processMMStagingAccounts(String csvContents, Document_Storage__c docStorage) {
        List<CTB_Staging__c> stagingRecordsToCreate = new List<CTB_Staging__c>();
        Map<Id, Insolvency_Account__c> accountRecordsToUpdateMap = new Map<Id, Insolvency_Account__c>();
        Map<String, Insolvency__c> insolvencyRecordsToUpdateMap = new Map<String, Insolvency__c>();
        Set<String> correlationIdSet = new Set<String>();
        Map<String, Insolvency_Account__c> mapCorrelationIdAccount = new Map<String, Insolvency_Account__c>();
        List<String> validOldInsolvencyStatuses = System.Label.CTB_Valid_Insolvency_Statuses.split(',');
        Boolean invalidFile = false;
        List<String> csvRows = csvContents.split('\n');
        // Check for number of rows, should have atleast 3 rows
        if (csvRows.size() < 3) {
            docStorage = CTBFileValidationUtility.updateDocStorageDetails(
                docStorage,
                'Failed',
                'File should contain atleast 3 rows. Header, record detail and trailer.'
            );
            update docStorage;
            return;
        }
        // Validate header and trailer
        String headerTrailerValidationMsg = CTBFileValidationUtility.validateHeaderTrailer(csvRows[0], csvRows[csvRows.size() - 1], csvRows.size());
        if (String.isNotBlank(headerTrailerValidationMsg)) {
            docStorage = CTBFileValidationUtility.updateDocStorageDetails(docStorage, 'Failed', headerTrailerValidationMsg);
            update docStorage;
            return;
        }
        for (Integer i = 1; i < csvRows.size() - 1; i++) {
            // Split the current row into columns
            List<String> csvColumns = CTBFileValidationUtility.parseCsv(csvRows[i]);
            if (csvColumns.size() != 51) {
                docStorage = CTBFileValidationUtility.updateDocStorageDetails(
                    docStorage,
                    'Failed',
                    'Invalid number of columns for row number ' + (i + 1) + ', please check the file'
                );
                invalidFile = true;
                break;
            }
            // Get all correlation Ids
            correlationIdSet.add(csvColumns[CTBFileValidationUtility.CORRELATION_ID]);
            CTB_Staging__c recordToCreate = CTBFileValidationUtility.validateAccountCTBStagingRecord(csvColumns);
            recordToCreate.CTB_Update_Filename__c = docStorage.Document_Name__c;
            stagingRecordsToCreate.add(recordToCreate);
        }
        // Query existing account with the correlation Ids from the csv and create map with correlation id and account
        if (!correlationIdSet.isEmpty() && !stagingRecordsToCreate.isEmpty() && !invalidFile) {
            for (Insolvency_Account__c acc : [
                SELECT Id, Correlation_Id__c, Insolvency_Status__c, Debtor_1_Estate_Number__c, Debtor_2_Estate_Number__c, Debtor__c, Co_Debtor__c, Insolvency__c
                FROM Insolvency_Account__c
                WHERE Correlation_Id__c IN :correlationIdSet
            ]) {
                mapCorrelationIdAccount.put(acc.Correlation_Id__c, acc);
            }
        }
        if (!stagingRecordsToCreate.isEmpty() && !invalidFile) {
            for (CTB_Staging__c stagingAcc : stagingRecordsToCreate) {
                Insolvency_Account__c accountToUpdate = new Insolvency_Account__c();
                String accountId = '';
                // If no account exists with correlation Id provided in the csv
                if (!mapCorrelationIdAccount.containsKey(stagingAcc.Correlation_Id__c) && !stagingAcc.Error_Message__c.contains('No Correlation Id provided')) {
                    stagingAcc.Status__c = 'Error';
                    stagingAcc.Error_Message__c += '; No Account with given Correlation Id found in SF';
                } else {
                    accountId = mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c).Id;
                }
                // Check if status can be updated to PoC Details Provided
                if (
                    stagingAcc.Status__c != 'Error' &&
                    !validOldInsolvencyStatuses.contains(mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c).Insolvency_Status__c)
                ) {
                    accountToUpdate.Id = accountId;
                    accountToUpdate.CTB_Update_File_Timestamp__c = Datetime.now();
                    accountToUpdate.CTB_Update_Filename__c = docStorage.Document_Name__c;
                    accountRecordsToUpdateMap.put(accountToUpdate.Id, accountToUpdate);
                    continue;
                }
                // Remove ; from start of the string if it starts with ;
                if (String.isNotBlank(stagingAcc.Error_Message__c)) {
                    stagingAcc.Error_Message__c = stagingAcc.Error_Message__c.removeStart(';');
                }
                // If validation was successfull
                if (stagingAcc.Status__c != 'Error') {
                    // Check for duplicate accounts and ignore current row if existing account was not rejected as NMAT
                    // This is only for duplicate account scenario for multiple debtors
                    if (
                        accountRecordsToUpdateMap.containsKey(accountId) &&
                        String.isBlank(accountRecordsToUpdateMap.get(accountId).CTB_Reject_Reason_Code__c) &&
                        stagingAcc.CTB_Reject_Reason_Code__c == 'NMAT'
                    ) {
                        CTBFileProcessingQueueable.checkNoMatchDebtor(
                            accountRecordsToUpdateMap.get(accountId),
                            mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c),
                            stagingAcc
                        );
                        continue;
                    }
                    if (String.isBlank(stagingAcc.CTB_Reject_Reason_Code__c)) {
                        accountToUpdate = CTBFileValidationUtility.updateMmInsolvencyAccount(stagingAcc);
                    }
                    accountToUpdate.Id = accountId;
                    accountToUpdate.CTB_Update_File_Timestamp__c = Datetime.now();
                    accountToUpdate.CTB_Update_Filename__c = docStorage.Document_Name__c;
                    accountToUpdate.CTB_Reject_Reason_Code__c = stagingAcc.CTB_Reject_Reason_Code__c;
                    if (String.isBlank(accountToUpdate.CTB_Reject_Reason_Code__c)) {
                        accountToUpdate.Insolvency_Status__c = 'PoC Details Provided';
                    }
                    // Only update no match fields if account has co debtor
                    if (
                        accountToUpdate.CTB_Reject_Reason_Code__c == 'NMAT' &&
                        String.isNotBlank(mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c).Co_Debtor__c)
                    ) {
                        // Default fields to false
                        accountToUpdate.No_Match_Debtor__c = false;
                        accountToUpdate.No_Match_Co_Debtor__c = false;
                        CTBFileProcessingQueueable.checkNoMatchDebtor(accountToUpdate, mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c), stagingAcc);
                    }
                    // When duplicate account with NMAT reject code is already processed preserve it's no match fields
                    if (
                        accountRecordsToUpdateMap.containsKey(accountId) &&
                        String.isNotBlank(accountRecordsToUpdateMap.get(accountId).CTB_Reject_Reason_Code__c) &&
                        accountRecordsToUpdateMap.get(accountId).CTB_Reject_Reason_Code__c == 'NMAT'
                    ) {
                        // If current row is also NMAT then don't mark any debtor as no match
                        if (accountToUpdate.CTB_Reject_Reason_Code__c == 'NMAT') {
                            accountToUpdate.No_Match_Debtor__c = false;
                            accountToUpdate.No_Match_Co_Debtor__c = false;
                        } else {
                            accountToUpdate.No_Match_Debtor__c = accountRecordsToUpdateMap.get(accountId).No_Match_Debtor__c;
                            accountToUpdate.No_Match_Co_Debtor__c = accountRecordsToUpdateMap.get(accountId).No_Match_Co_Debtor__c;
                        }
                    }
                    accountRecordsToUpdateMap.put(accountToUpdate.Id, accountToUpdate);
                    if (stagingAcc.CTB_Date_of_Birth__c != null) {
                        String insolvencyId = mapCorrelationIdAccount.get(stagingAcc.Correlation_Id__c).Insolvency__c;
                        insolvencyRecordsToUpdateMap.put(
                            insolvencyId,
                            new Insolvency__c(Id = insolvencyId, Debtor_1_Date_of_Birth__c = stagingAcc.CTB_Date_of_Birth__c)
                        );
                    }
                }
            }
            try {
                Database.insert(stagingRecordsToCreate);
            } catch (DmlException dex) {
                System.debug('Error updating stging records ' + dex.getDmlMessage(0));
                docStorage.File_Processing_Status__c = 'Failed';
                docStorage.File_Processing_Error__c = dex.getDmlMessage(0).length() > 255 ? dex.getDmlMessage(0).substring(0, 255) : dex.getDmlMessage(0);
                update docStorage;
                CTBFileProcessingQueueable.createInsolvencyError(dex.getDmlMessage(0), dex.getStackTraceString());
            }
        }
        if (!accountRecordsToUpdateMap.values().isEmpty()) {
            try {
                update accountRecordsToUpdateMap.values();
            } catch (DmlException dex) {
                System.debug('Error updating account records ' + dex.getDmlMessage(0));
                docStorage.File_Processing_Status__c = 'Failed';
                docStorage.File_Processing_Error__c = dex.getDmlMessage(0).length() > 255 ? dex.getDmlMessage(0).substring(0, 255) : dex.getDmlMessage(0);
                update docStorage;
                CTBFileProcessingQueueable.createInsolvencyError(dex.getDmlMessage(0), dex.getStackTraceString());
                return;
            }
        }
        if (!insolvencyRecordsToUpdateMap.values().isEmpty()) {
            try {
                InsolvencyTriggerHandler.runInsolvencyTrigger = false;
                update insolvencyRecordsToUpdateMap.values();
                InsolvencyTriggerHandler.runInsolvencyTrigger = true;
            } catch (DmlException dex) {
                System.debug('Error updating Insolvency records ' + dex.getDmlMessage(0));
                docStorage.File_Processing_Status__c = 'Failed';
                docStorage.File_Processing_Error__c = dex.getDmlMessage(0).length() > 255 ? dex.getDmlMessage(0).substring(0, 255) : dex.getDmlMessage(0);
                update docStorage;
                CTBFileProcessingQueueable.createInsolvencyError(dex.getDmlMessage(0), dex.getStackTraceString());
                return;
            }
        }
        Integer successRecordCount = accountRecordsToUpdateMap.size();
        Integer failedRecordCount = stagingRecordsToCreate.size() - successRecordCount;
        if (!invalidFile) {
            docStorage.File_Processing_Status__c = 'Processed';
            CTBFileValidationUtility.sendEmail(
                'Account file successfully processed',
                'File ' + docStorage.Document_Name__c + ' was successfully processed',
                System.Label.CTB_File_Processing_Emails
            );
        }
        docStorage.Comment__c = 'Success Records : ' + String.valueOf(successRecordCount) + '\n' + 'Failed Records : ' + String.valueOf(failedRecordCount);
        // Update doc storage with processing status and error message if failed
        update docStorage;
    }
}