force-app/main/default/objects/PTP_Information__c/PTP_Information__c.object-meta.xml
<CustomObject>
    <label>PTP Information</label>
    <nameField>
        <displayFormat>PTP-{000}</displayFormat>
        <label>PTP Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTP Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PTP_Information__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <formula>( DATEVALUE( PTP_Date__c ) - 7)</formula>
    <label>PTP Expected Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Date__c.field-meta.xml
<CustomField>
    <fullName>PTP_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Promise Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PTPUpdateBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Batch Class that updates PTP those satisfy criteria for Process builder and workflow
*  @author : A5E Consulting
*  @date : 09/14/2017   

*************************************************************************************************/
public Class PTPUpdateBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select Id, Name, createdDate, Payment_Date__c, PTP_Method__c, PTP_Amount__c, PTP_Date__c, PTP_mate__c
                                         From PTP_Information__c]);
    }
    
    public void execute(Database.BatchableContext BC, List<PTP_Information__c> ptpList){
        
        List<PTP_Information__C> ptpListToUpdate = new List<PTP_Information__c>();
        
        For(PTP_Information__c ptp : ptpList){
            
            if(system.Today() == (ptp.Payment_Date__c + 5)){
                ptpListToUpdate.add(ptp);
            }
            if(system.Today() == (ptp.Payment_Date__c - 3)){
                ptpListToUpdate.add(ptp);
            }
            
        }
        
        PTPInformationTriggerHandler.runPTPTrigger = false;
        update ptpListToUpdate;
        PTPInformationTriggerHandler.runPTPTrigger = true;
    }
    
    public void finish(Database.BatchableContext BC){
    }
}