force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <description>The primary account holder&apos;s address line 1</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address line 1</inlineHelpText>
    <label>Address Line1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The primary account holder&apos;s address city</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address city</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>The primary account holder&apos;s date of birth</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>The primary account holder&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s email address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Home__c.field-meta.xml
<CustomField>
    <fullName>Phone_Home__c</fullName>
    <description>The primary account holder&apos;s home phone number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s home phone number</inlineHelpText>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Work__c.field-meta.xml
<CustomField>
    <fullName>Phone_Work__c</fullName>
    <description>Customer Phone Work</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer Phone Work</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Secret_Code__c.field-meta.xml
<CustomField>
    <fullName>Secret_Code__c</fullName>
    <description>Secret Code from customer record</description>
    <formula>Customer__r.Secret_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Secret Code from customer record</inlineHelpText>
    <label>Secret Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>OO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The primary account holder&apos;s address postal code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPortalCustomerProcessor.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : Test class for PortalCustomerProcessor
 *  @author : A5E Consulting
 *  @date : 07/099/2021
 
 *************************************************************************************************/
@isTest
public class TestPortalCustomerProcessor {
    public static testMethod void parseCustmerJSONTest(){
        Account customerInstance = PaymentProcessorTestUtility.getDistressedAccount();
        system.debug('ss'+customerInstance.SF_ID__c);
        Product__c productInstance = PaymentProcessorTestUtility.getDistressedProduct();
        productInstance.Customer__c = customerInstance.Id;
        update productInstance;
        
        RestRequest req = new RestRequest ();
        RestResponse res = new RestResponse();
        system.debug('req: '+req);
        String jsonTokenResponse = '{"Primary_FirstName":"Anna", "Primary_LastName": "Stark",'+
                                    '"Primary_PersonEmail": "anna@test.com","Primary_SIN": 11111,"Primary_PersonMailingStreet": "test",'+
                                    '"Primary_PersonMailingCity": "test","Primary_PersonMailingPostalCode": "123","Primary_PersonMailingState": "test","Primary_PersonHomePhone": 1245666,"Primary_Work_Phone": 1245666,"Primary_PersonOtherPhone": 1245666}';
        system.debug('JSONPaymentTransaction: '+jsonTokenResponse);
        req.requestBody  = Blob.valueof(jsonTokenResponse);
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        PortalCustomerProcessor.processCustomer();
    }
    
    public static testMethod void updateCustomerTest(){
        /*Account customerInstance = PaymentProcessorTestUtility.getDistressedAccount();
        system.debug('ss'+customerInstance.SF_ID__c);
        Product__c product = PaymentProcessorTestUtility.getDistressedProduct();
        product.Customer__c = customerInstance.Id;
        update product;

        system.debug('sss'+customerInstance.Products__r);*/

        ID CanaccedeCustomerRecordTypeID = Schema.SObjectType.account.getRecordTypeInfosByName().get('Canaccede Customer').getRecordTypeId();
        Account accInstance = new Account();
        accInstance.FirstName = 'Anna';
        accInstance.LastName = 'Stark';
        accInstance.PersonBirthdate = system.today().addYears(-30);
        accInstance.PersonMailingStreet = '3024 Port Road';
        accInstance.PersonMailingCity = 'Toronto';
        accInstance.PersonMailingState = 'Ontario';
        accInstance.PersonMailingPostalCode = '91761';
        accInstance.PersonHomePhone = '613-555-0178';
        accInstance.Work_Phone__pc = '613-555-0165';
        accInstance.PersonOtherPhone = '613-555-0126';
        accInstance.PersonEmail = 'annatest@email.com';
        accInstance.Secret_Code__c = 'A9OBVW1Q';
        accInstance.Secret_Code_Expiration_Date__c = system.today().addDays(5);
        accInstance.RecordTypeId = CanaccedeCustomerRecordTypeID;
        accInstance.Portal_Profile_Update_Date__c = system.today();
        insert accInstance; 
        
        
        ID DistressedProductRecordTypeID = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Distressed Account').getRecordTypeId();
        
        Product__c productInstance = new Product__c();
        //productInstance.Customer__c = accInstance.Id;
        productInstance.Name = 'Test Product';
        productInstance.First_Name__c = 'Anna1';
        productInstance.Last_Name__c = 'Stark1';
        productInstance.Email_Address__c = 'anna@email.com';
        productInstance.Date_of_Birth__c = system.today().addYears(-29);
        productInstance.Address_Line1__c = 'Street1';
        productInstance.City__c = 'T';
        productInstance.Zip_Code__c = '91762';
        //productInstance.State__c = 'ON';
        productInstance.Phone_Home__c = '613-555-0111';
        productInstance.Phone_Work__c = '613-555-0112';
        productInstance.Collection_Agency__c = 68;
        productInstance.RecordTypeId = DistressedProductRecordTypeID;
        productInstance.Collection_Agency__c = 68;
        productInstance.Customer__c = accInstance.Id;
        insert productInstance;
        
        
        
        
        
        map<String, String> paramMap = new map<String, String>();
        paramMap.put('Primary_FirstName', 'Annie');
        paramMap.put('Primary_LastName','james');
        paramMap.put('Primary_PersonEmail','test@testemail.com');
        //paramMap.put('Primary_SIN','123333');
        paramMap.put('Primary_PersonMailingStreet','testStreet');
        paramMap.put('Primary_PersonMailingCity','testCity');
        paramMap.put('Primary_PersonMailingPostalCode','55555');
        paramMap.put('Primary_PersonMailingState','testState');
        paramMap.put('Primary_PersonHomePhone','2222222');
        paramMap.put('Primary_Work_Phone','1111111');
        paramMap.put('Primary_PersonOtherPhone','111111');
        
        PortalCustomerProcessorUtil.updateCustomer(paramMap, accInstance);
    }
}