force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Collection_Sub_Status__c</fullName>
    <description>A status for this account indicating customer&apos;s relevant circumstances for collection (deceased, bankrupt, etc)</description>
    <inlineHelpText>A status for this account indicating customer&apos;s relevant circumstances for collection (deceased, bankrupt, etc)</inlineHelpText>
    <label>Collection Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankrupt Account</fullName>
            </value>
            <value>
                <fullName>Cease and Desist – In Writing</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Credit Counselling</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Exhausted</fullName>
            </value>
            <value>
                <fullName>Fraud Claimed</fullName>
            </value>
            <value>
                <fullName>Incarcerate</fullName>
            </value>
            <value>
                <fullName>Language Barrier</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Moved out of Province.</fullName>
            </value>
            <value>
                <fullName>Paid in Full Account</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement – Monthly</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement – Weekly</fullName>
            </value>
            <value>
                <fullName>Prepped for Legal</fullName>
            </value>
            <value>
                <fullName>Previously Paid with Agency</fullName>
            </value>
            <value>
                <fullName>Previously Paid with Vendor</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Refuse to Pay</fullName>
            </value>
            <value>
                <fullName>Settled In Full Account</fullName>
            </value>
            <value>
                <fullName>Skip Trace – Completed</fullName>
            </value>
            <value>
                <fullName>Skip Trace – Required</fullName>
            </value>
            <value>
                <fullName>Sourcing for Funds</fullName>
            </value>
            <value>
                <fullName>CET Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Record_Last_Updated_In_Staging__c.field-meta.xml
<CustomField>
    <fullName>Record_Last_Updated_In_Staging__c</fullName>
    <description>The date this record was last updated from the System of Record</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date this record was last updated from the System of Record</inlineHelpText>
    <label>ETL Last Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DistressedRecalled.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Batch Class that mark distressed products as RECALLED
*  @author : A5E Consulting
*  @date : 20 Feb 2019  

*************************************************************************************************/
public Class DistressedRecalled implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
    
        //Datetime recalledAccountdate = AddBusinessDays(system.TODAY(), -3);
        return Database.getQueryLocator([select id, name, recordType.Name, Record_Last_Updated_In_Staging__c,
                                         Collection_Sub_Status__c
                                         from product__c where recordType.name = 'Distressed Account'
                                         AND Collection_Sub_Status__c <> 'RECALLED'
                                         AND Collection_Agency__c = null]);
    }
    
    public void execute(Database.BatchableContext BC, List<Product__C> prodList){
        
        for(Product__C prod : prodList){
            prod.Collection_Sub_Status__c = 'RECALLED';
            
        }
        
        ProductTriggerHandler.runProductTrigger = false;
        update prodList;
        ProductTriggerHandler.runProductTrigger = true;
    }
    
    public void finish(Database.BatchableContext BC){
        Database.executeBatch(New DistressedToActive(), 100);
    }
    
    /*
    public static Boolean IsWeekendDay(Date dateParam)
   {
      boolean result     = false;
      system.debug('dateParam = '+dateParam); 
      //Recover the day of the week
      Date startOfWeek   = dateParam.toStartOfWeek();
      system.debug('startOfWeek = '+startOfWeek);
      Integer dayOfWeek  = dateParam.day() - startOfWeek.day();
      system.debug('dayOfWeek = '+dayOfWeek);   
      result = dayOfWeek == 0 || dayOfWeek == 6 ? true : false;
      system.debug('result = '+result); 
      return result;
   } 
   
   
   public static Date AddBusinessDays(Date StartDate, integer BusinessDaysToAdd )
   {
      //Add or decrease in BusinessDaysToAdd days 
      Date finalDate = StartDate;
      system.debug('finaldate = '+finalDate);
      integer direction = BusinessDaysToAdd < 0 ? -1 : 1;
      system.debug('direction = '+direction);
       while(BusinessDaysToAdd != 0)
       {
           finalDate = finalDate.AddDays(direction);
           system.debug('BusinessDaysToAdd = '+BusinessDaysToAdd);            
           system.debug('finaldate = '+finalDate);
           if (!isWeekendDay(finalDate))
           {
               BusinessDaysToAdd -= direction;
               
           }
       }

       return finalDate;
   }
   */
}