force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Run_Identifier_Check_On__c.field-meta.xml
<CustomField>
    <fullName>Run_Identifier_Check_On__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Run Identifier Check On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/CCS_Account.recordType-meta.xml
<RecordType>
    <fullName>CCS_Account</fullName>
    <active>true</active>
    <label>CCS Account</label>
</RecordType>

force-app/main/default/objects/Product__c/recordTypes/Distressed_Account.recordType-meta.xml
<RecordType>
    <fullName>Distressed_Account</fullName>
    <active>true</active>
    <label>Distressed Account</label>
</RecordType>

force-app/main/default/classes/CustomerIdentifierBatch.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : This is a Batch class for Customer object to calculate Collection Agency identifier 
 *                 and RecordTypeIdentifier based on related Products
 *  @author : A5E Consulting
 *  @date : 06/08/2020
 
 *************************************************************************************************/
public class CustomerIdentifierBatch implements Database.Batchable<sObject> {
    public static final string SEPARATOR = 'A';
    public static final string UNPLACED = 'unplaced';
    public static final string CCS_ACCOUNT = 'CCS_Account';
    public static final string DISTRESSED_ACCOUNT = 'Distressed_Account';

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            [
                SELECT ID, Collection_Agency_Identifier__c, Record_Type_Identifier__c
                FROM Account
                WHERE
                    ID IN (
                        SELECT Customer__c
                        FROM Product__c
                        WHERE
                            (Run_Identifier_Check_On__c = TODAY
                            AND RecordType.name IN ('CCS Account', 'Distressed Account'))
                            OR (customer__r.createdDAte = today
                            AND recordType.name = 'Canaccede Customer')
                    )
            ]
        );
    }

    public void execute(Database.BatchableContext bc, List<Account> listAccounts) {
        map<Id, list<Product__c>> mapCustomerProducts = new Map<Id, list<Product__c>>();
        list<Account> listCustomersToUpdate = new List<Account>();
        Account account;
        String AccountClientIdentifier;
        String ProductClientIdentifier;
        String AccountRecordTypeIdentifier;

        //Get Customers and all its related Products
        for (Account accountObj : [
            SELECT
                ID,
                Collection_Agency_Identifier__c,
                Record_Type_Identifier__c,
                (
                    SELECT ID, Name, RecordType.DeveloperName, Collection_Agency__c
                    FROM Products__r
                )
            FROM Account
            WHERE ID IN :listAccounts
        ]) {
            AccountClientIdentifier = '';
            AccountRecordTypeIdentifier = '';
            for (Product__c productObj : accountObj.Products__r) {
                //***Updating Collection Agency Identifier on Account***
                if (productObj.RecordType.DeveloperName == DISTRESSED_ACCOUNT) {
                    if (productObj.Collection_Agency__c == null || productObj.Collection_Agency__c == 9999) {
                        ProductClientIdentifier = SEPARATOR + UNPLACED + SEPARATOR;
                    } else {
                        ProductClientIdentifier = SEPARATOR + String.valueOf((integer) productObj.Collection_Agency__c) + SEPARATOR;
                    }
                    if (String.IsBlank(AccountClientIdentifier)) {
                        AccountClientIdentifier = ProductClientIdentifier;
                    } else {
                        //check if Product collection agency is already present in accpunt client identifier string else append
                        if (!AccountClientIdentifier.contains(ProductClientIdentifier)) {
                            AccountClientIdentifier += ',' + ProductClientIdentifier;
                        }
                    }
                }
                //***Updating Record Type Identifier on Account***
                if (productObj.RecordType.DeveloperName == CCS_ACCOUNT) {
                    if (String.isBlank(AccountRecordTypeIdentifier)) {
                        AccountRecordTypeIdentifier = productObj.RecordType.DeveloperName;
                    } else {
                        //check AccountRecordType identifier does not contain Product record type and append
                        if (!AccountRecordTypeIdentifier.contains(productObj.RecordType.DeveloperName)) {
                            AccountRecordTypeIdentifier += ',' + productObj.RecordType.DeveloperName;
                        }
                    }
                }
            }

            //Create Customer instance to update and add to list
            account = new Account();
            account.Id = accountObj.Id;
            account.Collection_Agency_Identifier__c = AccountClientIdentifier;
            //update External Collection Agency Identifier for Agency Group Sharing Rule
            account.External_Collection_Agency_Identifier__c = account.Collection_Agency_Identifier__c.replace('A68A', '')
                .replace('A6A', '')
                .replace(SEPARATOR + UNPLACED + SEPARATOR, '')
                .replace(',', '');
            account.Record_Type_Identifier__c = AccountRecordTypeIdentifier;
            listCustomersToUpdate.add(account);
        }

        if (!listCustomersToUpdate.isEmpty()) {
            //Do not run the customer trigger
            CustomerTriggerHandler.runCustomerTrigger = false;
            update listCustomersToUpdate;
            CustomerTriggerHandler.runCustomerTrigger = true;
        }
    }
    public void finish(Database.BatchableContext bc) {
        // execute any post-processing operations
        //Call Judgment Batch
        Database.executeBatch(new JudgmentIdentifierBatch(), 200);
    }
}