force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The date this account was closed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date this account was closed</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <description>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</inlineHelpText>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Hold_Payments__c.field-meta.xml
<CustomField>
    <fullName>Hold_Payments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</description>
    <inlineHelpText>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</inlineHelpText>
    <label>Hold Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Amount__c</fullName>
    <description>An override of the next payment amount for automatic processing</description>
    <inlineHelpText>An override of the next payment amount for automatic processing</inlineHelpText>
    <label>Override Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Date__c</fullName>
    <description>An override of the next payment date for automatic processing</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>An override of the next payment date for automatic processing</inlineHelpText>
    <label>Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Released_Date__c</fullName>
    <description>The date that account funds were delivered to the customer</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that account funds were delivered to the customer</inlineHelpText>
    <label>Payment Released Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>Sub Status</description>
    <inlineHelpText>Sub Status</inlineHelpText>
    <label>Placement Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Accepted by agency</fullName>
            </value>
            <value>
                <fullName>Initial Letter Sent</fullName>
            </value>
            <value>
                <fullName>Follow-Up Letter Sent</fullName>
            </value>
            <value>
                <fullName>Return To Sender</fullName>
            </value>
            <value>
                <fullName>Added To Dialer</fullName>
            </value>
            <value>
                <fullName>Message Left</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
            </value>
            <value>
                <fullName>Email Contact Established</fullName>
            </value>
            <value>
                <fullName>Possible Payer</fullName>
            </value>
            <value>
                <fullName>Settlement Pending</fullName>
            </value>
            <value>
                <fullName>Refusal</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Debtor Claims Paid - Awaiting Proof</fullName>
            </value>
            <value>
                <fullName>Proof of Payment Submitted to Client</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Client Request</fullName>
            </value>
            <value>
                <fullName>Checking for Assets - Possible Legal</fullName>
            </value>
            <value>
                <fullName>Claim Issued</fullName>
            </value>
            <value>
                <fullName>Claim Served</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement</fullName>
            </value>
            <value>
                <fullName>Defended Action</fullName>
            </value>
            <value>
                <fullName>Media Requested - Awaiting</fullName>
            </value>
            <value>
                <fullName>Counterclaim</fullName>
            </value>
            <value>
                <fullName>Abandonned Claim</fullName>
            </value>
            <value>
                <fullName>Recommended for Legal Action</fullName>
            </value>
            <value>
                <fullName>Approved for Legal Action</fullName>
            </value>
            <value>
                <fullName>Reviewing for Legal action</fullName>
            </value>
            <value>
                <fullName>Demand Letter Sent</fullName>
            </value>
            <value>
                <fullName>Legal Action Rejected</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBulkProductUpdates.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : TestBulkProductUpdates
*  @author : A5E Consulting
*  @date : 19/07/2022  

*************************************************************************************************/
@isTest (seeAllData = false)
public class TestBulkProductUpdates {
    
     static testMethod void insertTestData(){
         List<Product__c> Listprod = new List<Product__c>();
        Product__c prod =  new Product__c ();
        string recrdid= [SELECT id from RecordType where sobjecttype='product__c' 
                         AND RecordType.Name='Distressed Account'].id;
        prod.RecordTypeId=recrdid;
        prod.Override_Payment_Amount__c = 100;
        prod.Override_Payment_Date__c = System.today()+1;
        prod.Closed_Date__c = null;
        prod.Hold_Payments__c = false;
        prod.Funding_Status__c = 'Funded';
        prod.Source_System__c = 'Megasys';
        prod.Payment_Setup_Status__c = 'Automated' ;
        prod.External_Status_Current__c = 'Active';
        prod.Payment_Released_Date__c = System.Today()+2;
        prod.First_Payment_Date__c = System.today() + 2;
        prod.Payment_Amount__c  = 200;
        prod.Status__c = 'New Allocation - New Allocation';
        prod.Sub_Status__c = 'Ready';
        prod.Product_Status__c = 'Test';
        prod.Current_Principal_Balance__c = 100;
        prod.Interest_Rate__c = 10;
        prod.Interest_Amount_Last_Calculated_Date__c = Date.newInstance(2023, 12, 19);
        prod.Insolvency_Date__c = Null;
        prod.Deceased_Date__c = Null;
        Listprod.add(prod);
        Insert Listprod;
        
        Test.StartTest();
		BulkProductUpdates instancevar = new BulkProductUpdates(Listprod);
		ID batchprocessid = Database.executeBatch(instancevar);
		Test.StopTest();
         // Database.executeBatch(new BulkProductUpdates(), 1);
         
     }
}