force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Address_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Address_Last_Changed_Date__c</fullName>
    <description>The date the customer&apos;s address last changed in the system of record</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the customer&apos;s address last changed in the system of record</inlineHelpText>
    <label>Address Last Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <description>The primary account holder&apos;s address line 1</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address line 1</inlineHelpText>
    <label>Address Line1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <description>The primary account holder&apos;s address line 2</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address line 2</inlineHelpText>
    <label>Address Line2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The primary account holder&apos;s address city</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address city</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>The primary account holder&apos;s date of birth</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>The primary account holder&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s email address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Manual_Review_Reason__c.field-meta.xml
<CustomField>
    <fullName>Manual_Review_Reason__c</fullName>
    <description>Manual Review Reason</description>
    <inlineHelpText>Manual Review Reason</inlineHelpText>
    <label>Manual Review Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Matches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Home__c.field-meta.xml
<CustomField>
    <fullName>Phone_Home__c</fullName>
    <description>The primary account holder&apos;s home phone number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s home phone number</inlineHelpText>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Other__c.field-meta.xml
<CustomField>
    <fullName>Phone_Other__c</fullName>
    <description>Customer Phone Other</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer Phone Other</inlineHelpText>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Work__c.field-meta.xml
<CustomField>
    <fullName>Phone_Work__c</fullName>
    <description>Customer Phone Work</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer Phone Work</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <description>The primary account holder&apos;s Social Insurance Number</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s Social Insurance Number</inlineHelpText>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>OO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The primary account holder&apos;s address postal code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductPotentialMatchController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a controller class to process product potential matches 
 *  @author : A5E Consulting
 *  @date : 02/15/2018
 *
 *************************************************************************************************/
public class ProductPotentialMatchController {
    
    public String prdctId;
    public Boolean manualReview{get;set;}
    public String validationErrMsg{get;set;}  
    
    //decides whether to refresh main detail page or not
    public Boolean refreshPage {get; set;}  
    
    //Wrapped Potential matches
    public List<PotentialMatchProductAccountWrapper> existingWrappedAccounts {get;set;}
        
    //Constructor
    public ProductPotentialMatchController(ApexPages.StandardController controller) {
        
        prdctId = ApexPages.currentPage().getParameters().get('id');
        existingWrappedAccounts = new List<PotentialMatchProductAccountWrapper>();
        refreshPage = false;
                
        Product__c prdct = getProductByID(prdctId);
        /*[Select Id, customer__c, 
                                        First_Name__c, Last_Name__c, Email_Address__c, 
                                        SIN__c, Date_of_Birth__c, 
                                        Needs_Manual_Review__c, Manual_Review_Reason__c 
                                        from  Product__c 
                                        where id=:prdctId];*/
                                        
        manualReview = prdct.Needs_Manual_Review__c == true ? true : false;
        
        if(manualReview){
        
            List<Account> potentialMatchList;
            
            /*
            if(String.isNotBlank(prdct.Last_Name__c)){
        
                String firstNameLetter;
                if(prdct.First_Name__c != null){
                    firstNameLetter = prdct.First_Name__c.subString(0,1)+'%';
                }
                
                potentialMatchList = [SELECT Id FROM Account WHERE (
                                    (LastName!=null and SIN__pc!=null and  LastName =: prdct.Last_Name__c AND SIN__pc =: prdct.SIN__c) 
                                     OR 
                                    (LastName!=null and FirstName!=null and PersonBirthdate!=null and FirstName =: prdct.First_Name__c AND LastName =: prdct.Last_Name__c AND PersonBirthdate =: prdct.Date_of_Birth__c) 
                                     OR 
                                    (LastName!=null and PersonEmail!=null and FirstName!=null and FirstName LIKE : firstNameLetter AND LastName =: prdct.Last_Name__c AND PersonEmail =: prdct.Email_Address__c )
                                    ) 
                                    AND (RecordType.Name= 'Customer Salesforce' OR RecordType.Name='Updated From SOR') 
                                    ORDER BY CreatedDate DESC];
            }
            */
            
            potentialMatchList = ProductUtil.queryCustomer(prdct, 'Canaccede Customer');
            if(!potentialMatchList.isEmpty()){
                                
                for(Account existingAcc : potentialMatchList){
                    if(existingAcc.Id != prdct.customer__c){
                        existingWrappedAccounts.add(new PotentialMatchProductAccountWrapper(existingAcc));
                    }                    
                }            
            }             
        }                                                                 
    }
    
    //Assign Application to selected Account  
    public PageReference assignSelected(){
        
        prdctId = ApexPages.currentPage().getParameters().get('id');         
        String matchAccntId;                
        Integer matchCnt = 0;
        refreshPage = false;
        
        for (PotentialMatchProductAccountWrapper matchAccntWrppr : existingWrappedAccounts){
            
            if(matchAccntWrppr.selected){
                matchAccntId = matchAccntWrppr.accnt.Id;
                matchCnt++;  
            }           
        }
        
        //Single selection
        if(matchCnt == 1){
            if(matchAccntId != null){
                //PotentialMatchUtil.assignSelectedAccountToApplication(Id.valueOf(matchAccntId), Id.valueOf(applnId));
                Product__C prdct = getProductByID(prdctId);
                prdct.Customer__c = matchAccntId;
                prdct.Manual_Review_Reason__c = null;
                prdct.Needs_Manual_Review__c = false;
        
                ProductTriggerHandler.runProductTrigger = false;
                update prdct;
                ProductTriggerHandler.runProductTrigger = true;
                refreshPage = true;
            }           
        }
        
        //No selection
        if(matchCnt == 0){
            validationErrMsg = 'You must first Select a Customer.';
            refreshPage = false;                        
        }
        
        //Multiple selection
        if(matchCnt > 1){
            validationErrMsg = 'Select only one Customer.';
            refreshPage = false;                    
        }   
               
        return null;     
    }
    
    //Create new Account and assign Application to it
    public PageReference createNewNAssign(){
        
        prdctId = ApexPages.currentPage().getParameters().get('id');
        //PotentialMatchUtil.createNewAccountAndAssignToApplication(Id.valueOf(applnId));
        Product__C prdct = getProductByID(prdctId);
        prdct.Customer__c = (ProductUtil.createCustomer(prdct, 'Canaccede Customer')).id;
        prdct.Manual_Review_Reason__c = null;
        prdct.Needs_Manual_Review__c = false;

        ProductTriggerHandler.runProductTrigger = false;
        update prdct;
        ProductTriggerHandler.runProductTrigger = true;
        
        refreshPage = true;
        
        return null;
    }
    
    //Keep Assignmnet as it is, reset review flags
    public PageReference keepSameCustomer(){
      
        prdctId = ApexPages.currentPage().getParameters().get('id');
        //PotentialMatchUtil.keepSameCustomer(Id.valueOf(applnId));
        Product__C prdct = getProductByID(prdctId);
        prdct.Manual_Review_Reason__c = null;
        prdct.Needs_Manual_Review__c = false;

        ProductTriggerHandler.runProductTrigger = false;
        update prdct;
        ProductTriggerHandler.runProductTrigger = true;
        refreshPage = true;
                       
        return null;
    }
    
    //WRapper Class
    public class PotentialMatchProductAccountWrapper {
        
        public Account accnt {get; set;}
        public Boolean selected {get;set;}
        public String accountLink {get;set;}
        public String birthdateStr {get;set;}
        
        public PotentialMatchProductAccountWrapper(Account accnt){
            
            this.accnt = accnt;
            this.selected = false; 
            this.accountLink = URL.getSalesforceBaseUrl().toExternalForm() + '/' + accnt.Id;    
            
            if(accnt.PersonBirthdate != null){
                birthdateStr = PotentialMatchUtil.formatDate(accnt.PersonBirthdate);        
            }
            else{
                birthdateStr = '';
            }
        }
    }
    
    public static String formatDate(Date d) {
        if (d == null) {
            return null;
        }
        return Datetime.newInstance(d.year(), d.month(), d.day()).format('MM-dd-yyyy');
    }
    
    public static Product__c getProductByID(Id prodID){
        Product__c prdct = [Select Id, customer__c, First_Name__c, Last_Name__c, Email_Address__c, SIN__c, Date_of_Birth__c, 
                            Needs_Manual_Review__c, Manual_Review_Reason__c, Address_Line1__c, Address_Line2__c, City__c,
                            Zip_Code__c, State__c, Phone_Home__c, Phone_Work__c, Phone_Other__c, Address_Last_Changed_Date__c
                            from  Product__c 
                            where id=:prodId];
        return prdct;
    }
}