force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Collection_Sub_Status__c</fullName>
    <description>A status for this account indicating customer&apos;s relevant circumstances for collection (deceased, bankrupt, etc)</description>
    <inlineHelpText>A status for this account indicating customer&apos;s relevant circumstances for collection (deceased, bankrupt, etc)</inlineHelpText>
    <label>Collection Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankrupt Account</fullName>
            </value>
            <value>
                <fullName>Cease and Desist – In Writing</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Credit Counselling</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Exhausted</fullName>
            </value>
            <value>
                <fullName>Fraud Claimed</fullName>
            </value>
            <value>
                <fullName>Incarcerate</fullName>
            </value>
            <value>
                <fullName>Language Barrier</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Moved out of Province.</fullName>
            </value>
            <value>
                <fullName>Paid in Full Account</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement – Monthly</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement – Weekly</fullName>
            </value>
            <value>
                <fullName>Prepped for Legal</fullName>
            </value>
            <value>
                <fullName>Previously Paid with Agency</fullName>
            </value>
            <value>
                <fullName>Previously Paid with Vendor</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Refuse to Pay</fullName>
            </value>
            <value>
                <fullName>Settled In Full Account</fullName>
            </value>
            <value>
                <fullName>Skip Trace – Completed</fullName>
            </value>
            <value>
                <fullName>Skip Trace – Required</fullName>
            </value>
            <value>
                <fullName>Sourcing for Funds</fullName>
            </value>
            <value>
                <fullName>CET Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Principal_Balance__c</fullName>
    <description>The total current principal amount on this account to date</description>
    <inlineHelpText>The total current principal amount on this account to date</inlineHelpText>
    <label>Current Principal Balance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Deceased_Date__c.field-meta.xml
<CustomField>
    <fullName>Deceased_Date__c</fullName>
    <description>Deceased Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Deceased Date</inlineHelpText>
    <label>Deceased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Insolvency_Date__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Date__c</fullName>
    <description>DebtNext-specific</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DebtNext-specific</inlineHelpText>
    <label>Insolvency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Amount_Last_Calculated_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_Last_Calculated_Date__c</fullName>
    <description>Interest Amount Last Calculated Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Interest Amount Last Calculated Date</inlineHelpText>
    <label>Interest Amount Last Calculated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Stopped__c.field-meta.xml
<CustomField>
    <fullName>Interest_Stopped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Stopped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Waived_Of_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Waived_Of_End_Date__c</fullName>
    <description>Interest Waived Off End Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Interest Waived Off End Date</inlineHelpText>
    <label>Interest Waived Off End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Waived_Off__c.field-meta.xml
<CustomField>
    <fullName>Interest_Waived_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check the field if product needs to be excluded from Interest Calculation for any reasons</description>
    <inlineHelpText>Exclude from Interest Calculation</inlineHelpText>
    <label>Interest Waived Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Waived_Off_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Waived_Off_Start_Date__c</fullName>
    <description>Start Date to Waive off Interest Amount</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Start Date to Waive off Interest Amount</inlineHelpText>
    <label>Interest Waived Off Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Distressed_Account.recordType-meta.xml
<RecordType>
    <fullName>Distressed_Account</fullName>
    <active>true</active>
    <label>Distressed Account</label>
</RecordType>

force-app/main/default/classes/InterestWaiverBatchFalseFlag.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : This is a Batch class to calculate Product is eligible to Interest Waiver or not
 *  @author : A5E Consulting
 *  @date : 12/10/2023
 
 *************************************************************************************************/
public class InterestWaiverBatchFalseFlag implements Database.Batchable<sObject> { 
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        return Database.getQueryLocator(
            [Select id,name,Interest_Stopped__c,Interest_Amount_Last_Calculated_Date__c,Interest_Waived_Off_Start_Date__c,Interest_Waived_Of_End_Date__c from product__c  WHERE RecordType.DeveloperName='Distressed_Account'  
             AND (Current_Principal_Balance__c != null 
             OR Current_Principal_Balance__c > 0 
             OR Interest_Rate__c != NULL 
             OR Interest_Rate__c != 0
             OR Interest_Amount_Last_Calculated_Date__c != NULL
             OR Collection_Sub_Status__c != 'Paid in Full Account'
             OR Collection_Sub_Status__c != 'Settled in Full Account'
             OR Collection_Sub_Status__c != 'Deceased'
             OR Collection_Sub_Status__c != 'Bankrupt Account'
             OR Collection_Sub_Status__c != 'Credit Counselling'
             OR Insolvency_Date__c = NULL
             OR Deceased_Date__c = NULL
             )     
            ]
        );
        
    }     
    
    public void execute(Database.BatchableContext bc, List<Product__c> listProducts){ 
		Map<id,product__c> mapProduct = new Map<id,product__c>();
        for(Product__c prodData : listProducts){
            if(prodData.Interest_Waived_Off__c = False || (prodData.Interest_Waived_Off__c = true 
                  && (prodData.Interest_Amount_Last_Calculated_Date__c < prodData.Interest_Waived_Off_Start_Date__c
                  || prodData.Interest_Amount_Last_Calculated_Date__c > prodData.Interest_Waived_Of_End_Date__c))){
                  		prodData.Interest_Stopped__c = False;
                        mapProduct.put(prodData.id,prodData);
             } 
        }
        ProductTriggerHandler.runProductTrigger = false;
        update mapProduct.values();
        ProductTriggerHandler.runProductTrigger = true;
    }

    //Finish method
    public void finish(Database.BatchableContext bc){  
       
    }
    
}