force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Is_Future_PTP__c.field-meta.xml
<CustomField>
    <fullName>Is_Future_PTP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Future PTP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTP_Information__c/PTP_Information__c.object-meta.xml
<CustomObject>
    <label>PTP Information</label>
    <nameField>
        <displayFormat>PTP-{000}</displayFormat>
        <label>PTP Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTP Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PTP_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PTP Information</relationshipLabel>
    <relationshipName>PTP_Informations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Date__c.field-meta.xml
<CustomField>
    <fullName>PTP_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Promise Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/IsFuturePTPPresent.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class will populate the value if there are any future PTP records present
*  @author : A5E Consulting
*  @date : 01/15/2018   
*
*************************************************************************************************/
public Class IsFuturePTPPresent{
        
    @InvocableMethod(label='Future PTP' description='Checks the flag if Future PTP is present for the Product')
    public static void isFuturePTPAvailable(List<Product__c> prod){
        
        Product__c productData = [select id, name, Is_Future_PTP__c from Product__c where id =: prod[0].id];
        
        List<PTP_Information__c> listPTP = [select id, name, PTP_Date__c from PTP_Information__c where Product__c =: productData.ID and PTP_Date__C > Today];
        
        if(listPTP.size() > 0){
            productData.Is_Future_PTP__c = true;
        }else{
            productData.Is_Future_PTP__c = false;
        }
        
        ProductTriggerHandler.runProductTrigger = false;
        update productData;
        ProductTriggerHandler.runProductTrigger = true;

    }
}