force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Is_Future_PTP__c.field-meta.xml
<CustomField>
    <fullName>Is_Future_PTP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Future PTP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTP_Information__c/PTP_Information__c.object-meta.xml
<CustomObject>
    <label>PTP Information</label>
    <nameField>
        <displayFormat>PTP-{000}</displayFormat>
        <label>PTP Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTP Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PTP_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PTP Information</relationshipLabel>
    <relationshipName>PTP_Informations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Date__c.field-meta.xml
<CustomField>
    <fullName>PTP_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Promise Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestIsFuturePTPPresent.cls
/**************************************************************************************************
 *
 *  Class:  TestIsFuturePTPPresent 
 *
 *  @description : This is a testclass for IsFuturePTPPresent.
 *  @author : A5E Consulting
 *  @date : 02/22/2018
 *  
 
 *************************************************************************************************/

@isTest
public class TestIsFuturePTPPresent {

  //Positive Testing
  static testMethod void testMethodPositive(){
      
        // insert product record
        Product__c productdata = new Product__c(Name = 'Test-123', Is_Future_PTP__c= false);
        insert productdata;
        list<Product__c> productlist = new list<Product__c>();
        productlist.add(productdata);
      
        // insert ptp information record
        PTP_Information__c ptp_infodata = new PTP_Information__c();
        ptp_infodata.PTP_Date__c = system.today()+1;
        ptp_infodata.Product__c = productdata.id;
        insert ptp_infodata;
        
        list<PTP_Information__c> ptp_infolist = new list<PTP_Information__c>();
        ptp_infolist.add(ptp_infodata);
        
        if(ptp_infolist.size()>0)
        {
            productdata.Is_Future_PTP__c = true;
        }
        update productdata;
        IsFuturePTPPresent.isFuturePTPAvailable(productlist);
    }
    
    //Negative Testing
    static testMethod void testMethodNegative(){
    
        Product__c productdata = new Product__c(Name = 'Test-123');
        insert productdata;
        list<Product__c> productlist = new list<Product__c>();
        productlist.add(productdata);
        
        PTP_Information__c ptp_infodata = new PTP_Information__c();
        ptp_infodata.PTP_Date__c = system.today();
        ptp_infodata.Product__c = productdata.id;
        insert ptp_infodata;
        
        list<PTP_Information__c> ptp_infolist = new list<PTP_Information__c>();
        ptp_infolist.add(ptp_infodata);
        
        if(ptp_infoList.size()==null){
                    productdata.Is_Future_PTP__c = false;
        }
        update productdata;
        IsFuturePTPPresent.isFuturePTPAvailable(productlist);
    }
}