force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Total Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>The primary account holder&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s email address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Date__c</fullName>
    <description>The date the most recent statement was issued on this account</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the most recent statement was issued on this account</inlineHelpText>
    <label>Last Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Paperless_Statement__c.field-meta.xml
<CustomField>
    <fullName>Paperless_Statement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Checkbox determines whether the user wants paperless statements or not.</description>
    <inlineHelpText>This Checkbox determines whether the user wants paperless statements or not.</inlineHelpText>
    <label>Paperless Statement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stmt_Hold_Flag__c.field-meta.xml
<CustomField>
    <fullName>Stmt_Hold_Flag__c</fullName>
    <description>To capture Stmt flag in Salesforce from FDR ETL</description>
    <inlineHelpText>To capture Stmt flag in Salesforce from FDR ETL</inlineHelpText>
    <label>Stmt Hold Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FidemCustomerNotificationBatch.cls
/**************************************************************************************************
 *
 *  Class:    FidemCustomerNotificationBatch
 *
 *  @description : To send Monthly Email Statement to Fidem Customers
 *  @author : A5E Consulting
 *  @date : 05/21/2021
 *
 *************************************************************************************************/

public class FidemCustomerNotificationBatch implements Database.Batchable<sobject>{
    static Final String TEMPLATE_NAME = 'Fidem Customer Notification Template';
    static Final String orgWideEmail = 'accountmanagement@fidemfinance.ca';
    static Final String externalStatus = 'Normal Status';
    static Final String recordType = 'Credit Card Account';
        
    //Start Method
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        //Fetch all eligible product records 
        return Database.getQueryLocator([select Id, Name, Last_Statement_Date__c, PRIN_Number__c, 
                                         External_Status_Description__c, Current_Balance__c, Email_Address__c,
                                         Customer__r.PersonHasOptedOutOfEmail, Customer__r.PersonEmail, Customer__r.PersonContactID
                                         from Product__c where RecordType.name = :recordType and
                                         Last_Statement_Date__c = YESTERDAY and
                                         PRIN_Number__c = 200 and
                                         External_Status_Description__c = :externalStatus and 
                                         Current_Balance__c > 0 and 
                                         Customer__r.PersonHasOptedOutOfEmail = false and 
                                         Customer__r.PersonEmail != null and                                          
                                         ((Stmt_Hold_Flag__c != null AND (Stmt_Hold_Flag__c = 'R' OR Stmt_Hold_Flag__c = 'W')) OR 
                                         (Stmt_Hold_Flag__c = null AND Paperless_Statement__c = true))]);
    }
    
    //Execute method
    public void execute(Database.BatchableContext bc, List<Product__c> listEligibleProducts){
        System.debug('In Execute method');
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail;
        
        //Fetch Template
        EmailTemplate template = [SELECT ID, Body, HtmlValue, Subject FROM EmailTemplate WHERE Name = :TEMPLATE_NAME LIMIT 1];
        
        //Fetch 'From' Address
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = :orgWideEmail];
        
        //Looping eligible records and sending mail
        for(Product__c prod:listEligibleProducts){
            
            mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(prod.Customer__r.PersonContactID); //To send Email to the Contact Email
            mail.setHtmlBody(template.HtmlValue);
            mail.setSubject(template.Subject);
            mail.setOrgWideEmailAddressId(owea.get(0).Id);
            
            emailMessages.add(mail);   
        }
        
        //Send Email
        if(!emailMessages.isEmpty() && !Test.isRunningTest()){
            Messaging.SendEmailResult[] emailResult = Messaging.sendEmail(emailMessages);
        }
    }
    
    //Finish method
    public void finish(Database.BatchableContext bc){
        //Do nothing
    }
}