force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Address_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Address_Last_Changed_Date__c</fullName>
    <description>The date the customer&apos;s address last changed in the system of record</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the customer&apos;s address last changed in the system of record</inlineHelpText>
    <label>Address Last Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <description>The primary account holder&apos;s address line 1</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address line 1</inlineHelpText>
    <label>Address Line1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <description>The primary account holder&apos;s address line 2</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address line 2</inlineHelpText>
    <label>Address Line2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The primary account holder&apos;s address city</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address city</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>The primary account holder&apos;s date of birth</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>The primary account holder&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s email address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Home__c.field-meta.xml
<CustomField>
    <fullName>Phone_Home__c</fullName>
    <description>The primary account holder&apos;s home phone number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s home phone number</inlineHelpText>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Other__c.field-meta.xml
<CustomField>
    <fullName>Phone_Other__c</fullName>
    <description>Customer Phone Other</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer Phone Other</inlineHelpText>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Work__c.field-meta.xml
<CustomField>
    <fullName>Phone_Work__c</fullName>
    <description>Customer Phone Work</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer Phone Work</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <description>The primary account holder&apos;s Social Insurance Number</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s Social Insurance Number</inlineHelpText>
    <label>SIN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>QC</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>OO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The primary account holder&apos;s address postal code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s address postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductUtil.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a utility class for Product Object 
 *  @author : A5E Consulting
 *  @date : 02/19/2018
 *
 *************************************************************************************************/
public class ProductUtil{
    
    public static Id customerAccountRecordTypeId;
    public static Map <Id, String> prodRecorTypeMap;
    public static Map<String, Id> prodRTypeIdMap = new Map<String, Id>();
    public static Map<Id, String> prodRTypeIdNameMap = new Map<Id, String>();
    
    static{
        prodRecorTypeMap = Utilities.getProdRecorTypeMap();
        customerAccountRecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Customer Salesforce' LIMIT 1].Id;
      
        for(RecordType rType : [SELECT Id, DeveloperName, Name FROM RecordType WHERE sobjectType = 'Product__c' ]){
            prodRTypeIdMap.put(rType.DeveloperName, rType.Id);
            prodRTypeIdNameMap.put(rType.Id, rType.Name);
        }
    }
    
    // Create Account for Product
    public static Account createCustomer(Product__c prod, String RecordType){
        
        ID recordTypeIDValue = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = :recordType LIMIT 1].Id;
        
        if(String.isNotBlank(prod.Last_Name__c)){
            
            Account acc = new Account(RecordTypeId = recordTypeIDValue);
        
            // Map Product fields with Customer Account to create
            if(String.isNotBlank(prod.First_Name__c)){
                if((prod.First_Name__c).length() > 39){
                    acc.FirstName = (prod.First_Name__c).subString(0,39);
                    acc.LastName = (prod.First_Name__c).subString(40,((prod.First_Name__c).length()-1));
                }else{
                    acc.FirstName = prod.First_Name__c;
                }
            }
            if(String.isNotBlank(prod.Last_Name__c)){
                if(String.isNotBlank(acc.LastName)){
                    acc.LastName += ' ' + prod.Last_Name__c;
                }else{
                    acc.LastName = prod.Last_Name__c;
                }
            }
            if(String.isNotBlank(prod.Email_Address__c)){
                acc.PersonEmail = prod.Email_Address__c;
            }
            if(prod.Date_of_Birth__c != null){
                acc.PersonBirthdate = prod.Date_of_Birth__c;
            }
            if(String.isNotBlank(prod.SIN__c)){
                acc.SIN__pc = prod.SIN__c;
            }
            String address = '';
            if(String.isBlank(prod.Address_Line2__c)){
                address = prod.Address_Line1__c;
            }
            else{
                address = (prod.Address_Line1__c != null ? prod.Address_Line1__c : '')+''+prod.Address_Line2__c;
            }
            acc.PersonMailingStreet = address;
            if(String.isNotBlank(prod.City__c)){
                acc.PersonMailingCity = prod.City__c;
            }
            if(String.isNotBlank(prod.Zip_Code__c)){
                acc.PersonMailingPostalCode = prod.Zip_Code__c;
            }
            if(String.isNotBlank(prod.State__c)){
                acc.PersonMailingState = prod.State__c;
            }
            if(String.isNotBlank(prod.Phone_Home__c)){
                acc.PersonHomePhone = prod.Phone_Home__c;
            }
            if(String.isNotBlank(prod.Phone_Work__c)){
                acc.Work_Phone__pc = prod.Phone_Work__c;
            }
            if(String.isNotBlank(prod.Phone_Other__c)){
                acc.PersonOtherPhone = prod.Phone_Other__c;
            }
            if(prod.Address_Last_Changed_Date__c != null){
                acc.Address_Last_Changed_Date__c = prod.Address_Last_Changed_Date__c;
            }
            
            insert acc;
            return acc; 
            
        }
        else {
            return null;
        }           
    }
    
    // Fetch customer using product information
    public static List<Account> queryCustomer(Product__c prod, String recordType){
        
        List<Account> accList = new List<account>();
        
        ID recordTypeIDValue = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = :recordType LIMIT 1].Id;
        
        //If Last Name is null, don't run the query
        if(String.isNotBlank(prod.Last_Name__c)){
        
            String firstNameLetter;
            if(prod.First_Name__c != null){
                firstNameLetter = prod.First_Name__c.subString(0,1)+'%';
            }
            accList = [SELECT Id, FirstName, LastName, SIN__pc, PersonBirthdate, PersonEmail, Address_Last_Changed_Date__c,
                       PersonOtherPhone, Work_Phone__pc, PersonHomePhone, PersonMailingState, PersonMailingPostalCode,
                       PersonMailingCity, PersonMailingStreet
                        FROM Account WHERE (
                                (LastName!=null and SIN__pc!=null and  LastName =: prod.Last_Name__c AND SIN__pc =: prod.SIN__c) 
                                 OR 
                                (LastName!=null and FirstName!=null and PersonBirthdate!=null and FirstName =: prod.First_Name__c AND LastName =: prod.Last_Name__c AND PersonBirthdate =: prod.Date_of_Birth__c) 
                                 OR 
                                (LastName!=null and PersonEmail!=null and FirstName!=null and FirstName LIKE : firstNameLetter AND LastName =: prod.Last_Name__c AND PersonEmail =: prod.Email_Address__c )
                                ) 
                                AND RecordTypeId =: recordTypeIDValue 
                                //AND (RecordType.Name= 'Customer Salesforce' OR RecordType.Name='Updated From SOR') 
                                ORDER BY CreatedDate DESC];
        }
            
        return accList;
    }
}