force-app/main/default/objects/Judgment__c/Judgment__c.object-meta.xml
<CustomObject>
    <description>To store the data for Judgement data</description>
    <label>Judgment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Judgment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment__c/fields/Current_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Principal_Balance__c</fullName>
    <inlineHelpText>Current Principal Balance</inlineHelpText>
    <label>Current Principal Balance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Co_Borrower_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Co_Borrower_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Borrower First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Co_Borrower_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Co_Borrower_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Borrower Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency__c</fullName>
    <label>Agency ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Collection_Agency_Formula__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency_Formula__c</fullName>
    <formula>Collection_Agency_Placement__r.Agency_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Display Agency Name
This field is used for Distressed Accounts Only</inlineHelpText>
    <label>Agency Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Total Balance</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Amount__c</fullName>
    <description>The total amount of interest accrued on this insolvency account to date</description>
    <inlineHelpText>The total amount of interest accrued on this insolvency account to date</inlineHelpText>
    <label>Current Interest Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Rate__c</fullName>
    <inlineHelpText>Current Interest Rate</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Principal_Balance__c</fullName>
    <description>The total current principal amount on this account to date</description>
    <inlineHelpText>The total current principal amount on this account to date</inlineHelpText>
    <label>Current Principal Balance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Canaccede Customer, Fidem Customer, Easyfinancial CCS Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The specific product this record represents</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The specific product this record represents</inlineHelpText>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Refer_to_Legal__c.field-meta.xml
<CustomField>
    <fullName>Refer_to_Legal__c</fullName>
    <description>Legal process status</description>
    <inlineHelpText>Legal process status</inlineHelpText>
    <label>Refer to Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Object to store the data for Judgement</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Settlement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Work_Assignment__c/Work_Assignment__c.object-meta.xml
<CustomObject>
    <description>For task management</description>
    <label>Work Assignment</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Work Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer</description>
    <inlineHelpText>Customer</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Canaccede Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <formula>Product__r.First_Name__c</formula>
    <inlineHelpText>First Name</inlineHelpText>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <formula>Product__r.Last_Name__c</formula>
    <inlineHelpText>Last Name</inlineHelpText>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Assignment__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Settlement</description>
    <inlineHelpText>Settlement</inlineHelpText>
    <label>Settlement ID</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Work Assignments</relationshipLabel>
    <relationshipName>Work_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplaintWorkAssignmentWidgetController.cls
public class ComplaintWorkAssignmentWidgetController {
//@AuraEnabled Public static List<Settlement__C> settljudglist{set;get;}
  Public Static Set<Id> SetId = new Set<Id>();
  Public Static Set<Id> setProdId = new Set<Id>();
	@AuraEnabled 
    public static List<Product__C> getproduct(String parentId){
    	List<Work_Assignment__c> complaintprolist= [SELECT Product__c, Customer__c from Work_Assignment__c where id=: parentId ];
        system.debug('product record is' + complaintprolist);
        List<Id> lisid= new List<Id>();
        list<product__C> prodList = new List<Product__C>();
        for(Work_Assignment__c proid:complaintprolist){
            system.debug('Block'+proid);
            //if(proid.product__c <> NULL){
            	prodList = [SELECT Name, First_Name__c,Co_Borrower_First_Name__c,Last_Name__c,Co_Borrower_Last_Name__c,Current_Principal_Balance__c,
                            Current_Interest_Rate__c,Current_Interest_Amount__c,Current_Balance__c,Product_Type__c,Collection_Agency__c,
                            Collection_Agency_Formula__c,Refer_to_Legal__c,Collection_Sub_Status__c,Interest_Rate__c,Account_Portfolio_ID__c,Originating_Creditor__c
                            from Product__C where Id =: proid.product__c];
            //}
            
            /*else if(proid.Customer__c <> NULL){
                //prodList = JudgmentWidgetController.getaccountnumbers(proid.Judgment__c);
            }*/
        }
        system.debug('prodList' + prodList);
        return prodList;
    }

    @AuraEnabled 
	public static List<Account> getcustomer(String parentId){
    	List<Work_Assignment__c> complaintcustlist= [SELECT Product__c, Customer__c from Work_Assignment__c where id=: parentId ];
        For (Work_Assignment__c workAssig :complaintcustlist ){
            setProdId.add(workAssig.Product__c);
        }
        List<Product__c> prodList= [SELECT Id, Customer__c/*,(Select Name From Work_Assignments__r where id=: parentId)*/ from Product__c  where id=: setProdId ];
        For(Product__c prod :prodList ){
            SetId.add(prod.Customer__c);
        }
        system.debug('product record is' + complaintcustlist);
        List<Id> lisid= new List<Id>();
        list<Account> custList = new List<Account>();
        for(Work_Assignment__c custid:complaintcustlist){
            if(custid.Customer__c <> NULL){
            	/*custList = [SELECT Name, Customer_ID__c, Mobile_Phone__c, Office_Phone__c, BillingAddress,
                          AccountNumber, PersonEmail,Phone,ShippingAddress
                          from Account where Id =: custid.Customer__c];*/
                custList = [SELECT Name,Previous_First_Name__c,Previous_Last_Name__c,Previous_Email_Address__c,Previous_MailingCity__c,
                  			  Previous_HomePhone__c,Previous_Mobile_Phone__c,Previous_MailingStreet__c,Previous_MailingState__c,
                  			  Address_Type__pc,PersonMailingAddress,PersonHomePhone,PersonEmail,PersonMobilePhone,PersonMailingCity,PersonMailingState ,PersonMailingCountry
                  			  from Account where Id =: custid.Customer__c];
            }
            Else if (custid.Customer__c == NULL){
                custList = [SELECT Name,Previous_First_Name__c,Previous_Last_Name__c,Previous_Email_Address__c,Previous_MailingCity__c,
                  			  Previous_HomePhone__c,Previous_Mobile_Phone__c,Previous_MailingStreet__c,Previous_MailingState__c,
                  			  Address_Type__pc,PersonMailingAddress,PersonHomePhone,PersonEmail,PersonMobilePhone,PersonMailingCity,PersonMailingState,PersonMailingCountry
                  			  from Account where Id =:SetId ];
                
            }
      }
    	return custList;
    }
}