force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Prefix__c</fullName>
    <description>Scope Prefix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Prefix</inlineHelpText>
    <label>Scope Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Suffix__c</fullName>
    <description>Scope Suffix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Suffix</inlineHelpText>
    <label>Scope Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Storage__c/Document_Storage__c.object-meta.xml
<CustomObject>
    <label>Document Storage</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Storages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Storage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom Product Lookup</description>
    <label>Account ID</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Document Storages</relationshipLabel>
    <relationshipName>Document_Storages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>Sub Status</description>
    <inlineHelpText>Sub Status</inlineHelpText>
    <label>Placement Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Accepted by agency</fullName>
            </value>
            <value>
                <fullName>Initial Letter Sent</fullName>
            </value>
            <value>
                <fullName>Follow-Up Letter Sent</fullName>
            </value>
            <value>
                <fullName>Return To Sender</fullName>
            </value>
            <value>
                <fullName>Added To Dialer</fullName>
            </value>
            <value>
                <fullName>Message Left</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
            </value>
            <value>
                <fullName>Email Contact Established</fullName>
            </value>
            <value>
                <fullName>Possible Payer</fullName>
            </value>
            <value>
                <fullName>Settlement Pending</fullName>
            </value>
            <value>
                <fullName>Refusal</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Debtor Claims Paid - Awaiting Proof</fullName>
            </value>
            <value>
                <fullName>Proof of Payment Submitted to Client</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Client Request</fullName>
            </value>
            <value>
                <fullName>Checking for Assets - Possible Legal</fullName>
            </value>
            <value>
                <fullName>Claim Issued</fullName>
            </value>
            <value>
                <fullName>Claim Served</fullName>
            </value>
            <value>
                <fullName>Payment Arrangement</fullName>
            </value>
            <value>
                <fullName>Defended Action</fullName>
            </value>
            <value>
                <fullName>Media Requested - Awaiting</fullName>
            </value>
            <value>
                <fullName>Counterclaim</fullName>
            </value>
            <value>
                <fullName>Abandonned Claim</fullName>
            </value>
            <value>
                <fullName>Recommended for Legal Action</fullName>
            </value>
            <value>
                <fullName>Approved for Legal Action</fullName>
            </value>
            <value>
                <fullName>Reviewing for Legal action</fullName>
            </value>
            <value>
                <fullName>Demand Letter Sent</fullName>
            </value>
            <value>
                <fullName>Legal Action Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPortalDocumentStorageProcessingAPI.cls
/**************************************************************************************************
 *
 *  Class:   
 *  @description : Test class for Document Storage API (TestPortalDocumentStorageProcessingAPI)
 *  @author : A5E Consulting
 *  @date : 28/01/2022
 
 *************************************************************************************************/
@isTest
public class TestPortalDocumentStorageProcessingAPI {
    public static testMethod void testDocumentStorageAPI(){
        Test.setMock(HttpCalloutMock.class, new PortalAPIMockResponse());

        API_Call_Details__c  settings = new API_Call_Details__c ();
        settings.Name = 'Agency Portal API';
        settings.AuthorizationtUrl__c = 'https://test.com/portalapi';
        settings.Tenand_ID__c = '123';
        settings.Proxy_Client_ID__c = '123';
        settings.Client_ID__c = '1234';
        settings.Client_Secret__c = '1234';
        settings.PDF_API_URL__c = 'https://test.com/endpointurl';
        settings.Scope_Prefix__c = 'scopep.com';
        settings.Scope_Suffix__c = '/.default';
        insert settings;
        
        //Product Record Creation
        Product__c prod=new Product__C();
        prod.Name ='123456789';
        prod.Status__c = 'New Allocation - New Allocation';
        prod.Sub_Status__c = 'Ready';
        prod.Product_Status__c = 'Test';
        INSERT prod;
        
        //Judgment Record Creation
        Judgment__c judg= new Judgment__c();
        judg.Judgment_Number__c='JC-001';
        judg.Legal_Agency__c = 'Test Agency';
        insert judg;
        
        //Document Storage Record Creation
        Document_Storage__c docStor=new Document_Storage__c();
        docStor.Product__c=prod.id;
        docStor.Judgment__c=judg.id;
        INSERT docStor;
        
        PortalDocumentStorageProcessingAPI.processDocumentStorage(docStor.Id); 
    }
}