force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Prefix__c</fullName>
    <description>Scope Prefix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Prefix</inlineHelpText>
    <label>Scope Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Suffix__c</fullName>
    <description>Scope Suffix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Suffix</inlineHelpText>
    <label>Scope Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <description>Agency Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency Name</inlineHelpText>
    <label>Agency Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Serviceable_Province__c.field-meta.xml
<CustomField>
    <fullName>Serviceable_Province__c</fullName>
    <label>Serviceable Province</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
                <label>AB</label>
            </value>
            <value>
                <fullName>British Columbia</fullName>
                <label>BC</label>
            </value>
            <value>
                <fullName>Manitoba</fullName>
                <label>MB</label>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
                <label>NB</label>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
                <label>NL</label>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
                <label>NT</label>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
                <label>NS</label>
            </value>
            <value>
                <fullName>Nunavut</fullName>
                <label>NU</label>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
                <label>PE</label>
            </value>
            <value>
                <fullName>Ontario</fullName>
                <label>ON</label>
            </value>
            <value>
                <fullName>Quebec</fullName>
                <label>QC</label>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
                <label>SK</label>
            </value>
            <value>
                <fullName>Yukon</fullName>
                <label>YT</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>OO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pool__c/Pool__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Pool ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pool__c/fields/Placement_Agency__c.field-meta.xml
<CustomField>
    <fullName>Placement_Agency__c</fullName>
    <description>Placement Agency</description>
    <inlineHelpText>Placement Agency</inlineHelpText>
    <label>Agency ID</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pool__c/fields/Placement_agency_lookup__c.field-meta.xml
<CustomField>
    <fullName>Placement_agency_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>placement agency lookup field</description>
    <label>Agency ID</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Pools</relationshipLabel>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Collection_Agency_Placement__c.field-meta.xml
<CustomField>
    <fullName>Collection_Agency_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup against Placement</description>
    <inlineHelpText>Lookup against Placement</inlineHelpText>
    <label>Agency ID - NOT AUTHORITATIVE</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Interest_Amount__c</fullName>
    <description>The total amount of interest accrued on this insolvency account to date</description>
    <inlineHelpText>The total amount of interest accrued on this insolvency account to date</inlineHelpText>
    <label>Current Interest Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Principal_Balance__c</fullName>
    <description>The total current principal amount on this account to date</description>
    <inlineHelpText>The total current principal amount on this account to date</inlineHelpText>
    <label>Current Principal Balance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pool_Name__c.field-meta.xml
<CustomField>
    <fullName>Pool_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated by Bulk Pool Excel Processing</description>
    <inlineHelpText>Pool Name</inlineHelpText>
    <label>Pool Name</label>
    <referenceTo>Pool__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Previously_Reviewed_for_Legal_Action__c.field-meta.xml
<CustomField>
    <fullName>Previously_Reviewed_for_Legal_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Previously Reviewed for Legal Action</inlineHelpText>
    <label>Previously Reviewed for Legal Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAgencyPoolRecallController.cls
@isTest
public class TestAgencyPoolRecallController {
    
    public static testMethod void testConstructor1(){

        Test.setMock(HttpCalloutMock.class, new PortalAPIMockResponse());

        API_Call_Details__c  settings = new API_Call_Details__c ();
        settings.Name = 'Agency Portal API';
        settings.AuthorizationtUrl__c = 'https://test.com/portalapi';
        settings.Tenand_ID__c = '123';
        settings.Proxy_Client_ID__c = '123';
        settings.Client_ID__c = '1234';
        settings.Client_Secret__c = '1234';
        settings.PDF_API_URL__c = 'https://test.com/endpointurl';
        settings.Scope_Prefix__c = 'scopep.com';
        settings.Scope_Suffix__c = '/.default';
        insert settings;

        
        //list<Pool__c> poolList = new list<Pool__c>();
        Placement__c plcmnt= new Placement__c();      
        plcmnt.Name= '89'; 
        plcmnt.Serviceable_Province__c = 'Nova Scotia';
        plcmnt.Agency_Name__c = 'CCS Agency';
        insert plcmnt;    
        
        Placement__c placement= new Placement__c();      
        placement.Name= '9999'; 
        placement.Serviceable_Province__c = 'AB';
        placement.Agency_Name__c = 'Warehouse';
        insert placement; 
        
        Pool__c pool = new Pool__c();
       // pool.Placement_Agency__c = 89;
        pool.Placement_agency_lookup__c = plcmnt.id;
        pool.Id = ApexPages.currentPage().getParameters().get('id');   
        insert pool;
        
        //Product Record Creation
        Product__c prod = new Product__C();
        prod.Pool_Name__c = pool.id;
        prod.Collection_Agency_Placement__c =plcmnt.id;
        prod.Previously_Reviewed_for_Legal_Action__c=True;
        prod.Current_Principal_Balance__c = 101;
        prod.Current_Interest_Amount__c = 1000;
        prod.Name ='123456789';
        prod.State__c = 'Nova Scotia';
        prod.Status__c = 'Client Request - Others';
        prod.Sub_Status__c = 'Recall'; 
        prod.Product_Status__c = 'Test';
        prod.DebtNext_Data_ID__C = pool.Id; 
        prod.Current_Balance__c=34567;
        prod.Legal_Status__c='Legal';
        
       
        
        
        Agency_Portal_Settings__c ab = Agency_Portal_Settings__c.getOrgDefaults();
        ab.Pool_Recall_Reasons__c = 'Test,Client'; // -Request Contractual';
        insert ab;
        Placement_Status_Code_Mapping__c place= new Placement_Status_Code_Mapping__c();
        place.Complete_Status__c = 'Test';
        place.Name= 'NameTest';
        place.Placement_Status_Code__c='112987';
        place.Parent_Status__C ='test2';
        place.Data_Status_Code__c ='DataStatus Code';
        place.Data_Status_Description__c='dataStatusDescription';
        place.Status__c='status';
        place.Sub_Status__c='subStatus1';
        insert place;
        
        Data_Status_Mapping__c dataStatusMapping = new Data_Status_Mapping__c();
        dataStatusMapping.Name ='123233';
        dataStatusMapping.Description__c ='Warehouse';
        dataStatusMapping.Description1__c ='Description1 Allocation';
        dataStatusMapping.Description2__c ='Description2 Allocation';
        insert dataStatusMapping;
        
        insert prod;
        // insert place;

        PageReference testPage = Page.AgencyPoolRecall;
        Test.setCurrentPage(testPage);
        
        ApexPages.currentPage().getParameters().put('id', pool.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(pool);
        AgencyPoolRecallController controller = new AgencyPoolRecallController(sc);
        list<Product__c> pclist = new list<Product__c>();
        pclist.add(prod);
        controller.listProd = pclist;
        controller.selectedValueAction = 'Pending Recall';
        controller.getItems();
        controller.getactionItems();
        controller.selectedValue = '112987';// For code coverage
       //  controller.oldPlacementID = a1x7g0000004C5uAAE;
        controller.listProd = pclist;
        controller.recallProduct();
        controller.selectedValueAction = 'Send to Warehouse';
        controller.recallProduct();
        controller.selectedValueAction = 'Pending Allocation';
        controller.recallProduct();       
        controller.selectedValueAction = 'Pending Recall';
        controller.recallProduct();        
        controller.recallWithWarning();
        controller.selectedValueAction = 'Send to Warehouse';
        controller.recallWithWarning();
        controller.selectedValueAction = 'Pending Allocation';
        controller.recallWithWarning();       
        controller.selectedValueAction = 'Pending Recall';
        controller.recallWithWarning();        
        ProductTriggerHandler.runProductTrigger = true;
        controller.redirectToPool();
    }
    
    static testMethod void testWrapperclass(){
        
        Product__c prod = new Product__c(Name='Test');
        String comments ='Test';
        List<AgencyPoolRecallController.productWrapper> w;
        
        AgencyPoolRecallController.productWrapper testWrap=new AgencyPoolRecallController.productWrapper(prod,comments); 
        
    } 
    
    public static testMethod void testConstructor(){
        Test.setMock(HttpCalloutMock.class, new PortalAPIMockResponse());

        API_Call_Details__c  settings = new API_Call_Details__c ();
        settings.Name = 'Agency Portal API';
        settings.AuthorizationtUrl__c = 'https://test.com/portalapi';
        settings.Tenand_ID__c = '123';
        settings.Proxy_Client_ID__c = '123';
        settings.Client_ID__c = '1234';
        settings.Client_Secret__c = '1234';
        settings.PDF_API_URL__c = 'https://test.com/endpointurl';
        settings.Scope_Prefix__c = 'scopep.com';
        settings.Scope_Suffix__c = '/.default';
        insert settings;
        
       //list<Pool__c> poolList = new list<Pool__c>();
        Placement__c plcmnt= new Placement__c();      
        plcmnt.Name= '89'; 
        plcmnt.Serviceable_Province__c = 'Nova Scotia';
        plcmnt.Agency_Name__c = 'CCS Agency';
        insert plcmnt;  
        
        Pool__c pool = new Pool__c();
        //pool.Name = 'P0001';
        //pool.Placement_Agency__c = 89;
        pool.Placement_Agency__c = null;
        pool.Placement_agency_lookup__c = plcmnt.id;
        pool.Id = ApexPages.currentPage().getParameters().get('id');   
        insert pool;
        
        //Product Record Creation
        Product__c prod=new Product__C();
        prod.Name ='123456789';
        prod.Previously_Reviewed_for_Legal_Action__c=True;
        prod.Current_Principal_Balance__c = 101;
        prod.Current_Interest_Amount__c = 1000;
        prod.Pool_Name__c = pool.Id;
        prod.Collection_Agency__c = 89;
        prod.Status__c = 'Client Request - Others';
        prod.Sub_Status__c = 'Recall'; 
        prod.Product_Status__c = 'Test';
        prod.Legal_Status__c='Legal';
        insert prod;


        PageReference testPage = Page.AgencyPoolRecall;
        Test.setCurrentPage(testPage);
        Test.StartTest();
        ApexPages.currentPage().getParameters().put('id', pool.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(pool);
        AgencyPoolRecallController controller = new AgencyPoolRecallController(sc);
        controller.redirectToPool();
        //controller.recallWithWarning();
        Test.StopTest(); 
    }
    

    public static testMethod void testvalidationOnRecordUpdate()
    {
        Placement__c plcmnt= new Placement__c();      
        plcmnt.Name= '89'; 
        plcmnt.Serviceable_Province__c = 'Nova Scotia';
        plcmnt.Agency_Name__c = 'CCS Agency';
        insert plcmnt;  
        
        Pool__c pool = new Pool__c();
        //pool.Name = 'P0001';
        pool.Placement_Agency__c = 89;
        pool.Placement_agency_lookup__c = plcmnt.id;
        pool.Id = ApexPages.currentPage().getParameters().get('id');   
        insert pool;
        
        //Product Record Creation
        Product__c prod=new Product__C();
        prod.Name ='123456789';
        prod.Previously_Reviewed_for_Legal_Action__c=True;
        prod.Current_Principal_Balance__c = 101;
        prod.Current_Interest_Amount__c = 1000;
        prod.Pool_Name__c = pool.Id;
        prod.Collection_Agency__c = 89;
        prod.Status__c = 'Client Request - Others';
        prod.Sub_Status__c = 'Recall'; 
        prod.Product_Status__c = 'Test';
        ProductTriggerHandler.runProductTrigger = false;
        insert prod;
        ProductTriggerHandler.runProductTrigger = true;

        
        PageReference testPage = Page.AgencyPoolRecall;
        Test.setCurrentPage(testPage);
        Test.StartTest();
        ApexPages.currentPage().getParameters().put('id', pool.Id);
        ApexPages.StandardController sc = new ApexPages.standardController(pool);
        AgencyPoolRecallController controller = new AgencyPoolRecallController(sc);
        //controller.recallProduct();
        Test.StopTest(); 

    }

    public static API_Call_Details__c testDocumentAPI(){
        //Test.setMock(HttpCalloutMock.class, new PortalAPIMockResponse());
        
        API_Call_Details__c  settings = new API_Call_Details__c ();
        settings.Name = 'Agency Portal API';
        settings.AuthorizationtUrl__c = 'https://test.com/portalapi';
        settings.Tenand_ID__c = '123';
        settings.Proxy_Client_ID__c = '123';
        settings.Client_ID__c = '1234';
        settings.Client_Secret__c = '1234';
        settings.PDF_API_URL__c = 'https://test.com/endpointurl';
        settings.Scope_Prefix__c = 'scopep.com';
        settings.Scope_Suffix__c = '/.default';
        settings.API_Request_Timeout__c = 90000; 
        insert settings;
        return settings;
        
    }    
}