force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Prefix__c</fullName>
    <description>Scope Prefix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Prefix</inlineHelpText>
    <label>Scope Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Scope_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Scope_Suffix__c</fullName>
    <description>Scope Suffix</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Scope Suffix</inlineHelpText>
    <label>Scope Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCTBInsolvencyAccountGeneratorSchdler.cls
@isTest
public class TestCTBInsolvencyAccountGeneratorSchdler {
    @TestSetup
    static void makeData(){
        API_Call_Details__c  settings = new API_Call_Details__c ();
        settings.Name = 'Agency Portal API';
        settings.AuthorizationtUrl__c = 'https://login.microsoftonline.com/{{tenandId}}/oauth2/v2.0/token';
        settings.Tenand_ID__c = '0f455e83-d015-4300-80c3-3b73c4ce1d10';
        settings.Proxy_Client_ID__c = '8c862ddf-0df2-4322-8490-e858d46f18ce';
        settings.Client_ID__c = '3b3cd051-5cc0-469f-98e0-601d5d9577f4';
        settings.Client_Secret__c = 'lxW8Q~YfJqn5yr8bRlTlH.hI6BAfAb_x-VIzDcNd';
        settings.PDF_API_URL__c = 'https://test.com/endpointurl';
        settings.Scope_Prefix__c = 'https://canaccedeb2cdevelopment.onmicrosoft.com/';
        settings.Scope_Suffix__c = '/.default';
        insert settings;
    }
    
    @isTest
    static void testMethod1(){
        Test.setMock(HttpCalloutMock.class, new CTBApiCalloutsQueueableMock());
        test.startTest();
        CTBInsolvencyAccountGeneratorScheduler ctb=new CTBInsolvencyAccountGeneratorScheduler();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test CTB Check', sch, ctb); 
        Test.stopTest(); 
    }
}