force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/Application_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global config settings such as on/off switch (checkbox) that will decide whether to run the trigger code or not</description>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Config_Settings__c/fields/Bank_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Bank_Eligible_for_Duplicate_Check__c</fullName>
    <description>Bank Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Bank Eligible for Duplicate Check</inlineHelpText>
    <label>Bank Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Display_Duplicate_Accounts_List_View__c.field-meta.xml
<CustomField>
    <fullName>Display_Duplicate_Accounts_List_View__c</fullName>
    <label>Display Duplicate Accounts List View</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Claim_Type_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Claim_Type_Calculation__c</fullName>
    <description>Eligible for Claim Type Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Claim Type Calculation</inlineHelpText>
    <label>Eligible for Claim Type Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Eligible_for_Validn_Needed_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Validn_Needed_Calculation__c</fullName>
    <description>Eligible for Validation Needed Calculation</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Eligible for Validation Needed Calculation</inlineHelpText>
    <label>Eligible for Validn Needed Calculation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Ignore_Account_Number_for_DuplicateCheck__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Account_Number_for_DuplicateCheck__c</fullName>
    <description>Ignore Account Number for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Ignore Account Number for Duplicate Check</inlineHelpText>
    <label>Ignore Account Number for DuplicateCheck</label>
    <length>224</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Profile_Eligible_for_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Profile_Eligible_for_Duplicate_Check__c</fullName>
    <description>Profile Eligible for Duplicate Check</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Profile Eligible for Duplicate Check</inlineHelpText>
    <label>Profile Eligible for Duplicate Check</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Duplicate_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Run Insolvency Account Duplicate Check</description>
    <inlineHelpText>Run Insolvency Account Duplicate Check</inlineHelpText>
    <label>Run Insolvency Account Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Account_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Account Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Account Trigger or not</inlineHelpText>
    <label>Run Insolvency Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Status_Validations__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Status_Validations__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Status Validation Rules or not</description>
    <inlineHelpText>Checks whether to run Insolvency Status Validation Rules or not</inlineHelpText>
    <label>Run Insolvency Status Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Config_Settings__c/fields/Run_Insolvency_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Insolvency_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checks whether to run Insolvency Trigger or not</description>
    <inlineHelpText>Checks whether to run Insolvency Trigger or not</inlineHelpText>
    <label>Run Insolvency Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Client_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifiers__c</fullName>
    <description>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Populated when a new Insolvency Account record is created for the Insolvency record. 
Clients can only see records in this Object if their client identifier value is present in this field.</inlineHelpText>
    <label>Client Identifiers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Parsed_Response_Holder__c/Parsed_Response_Holder__c.object-meta.xml
<CustomObject>
    <label>Parsed Response Holder</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Parsed Response Holder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parsed Response Holder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parsed_Response_Holder__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Parsed Response Holder</relationshipLabel>
    <relationshipName>Parsed_Response_Holder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDocumentParser.cls
@isTest(seeAllData = false)
public class TestDocumentParser {
    
    @TestSetup
    static void makeData(){

         //Custom setting record creation
         Application_Config_Settings__c config = Application_Config_Settings__c.getOrgDefaults();
         config.Run_Insolvency_Account_Trigger__c = true;
         config.Run_Insolvency_Status_Validations__c = true;
         config.Eligible_for_Validn_Needed_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
         config.Eligible_for_Claim_Type_Calculation__c = 'Scotia Bank, SPL, Cannacede, SDA, Affirm';
         config.Profile_Eligible_for_Duplicate_Check__c = 'CFG,System Administrator,SPL,SDA,Scotia,Affirm';
         config.Display_Duplicate_Accounts_List_View__c=10;
         config.Bank_Eligible_for_Duplicate_Check__c = 'SPL';
         config.Ignore_Account_Number_for_DuplicateCheck__c = 'UNKNOWN';
         config.Run_Insolvency_Trigger__c = false;
         config.Run_Insolvency_Account_Duplicate_Check__c = true;
         insert config;

        API_Call_Details__c docParseApi = new API_Call_Details__c(
                                                Name = 'Document Parser API',
                                                authorizationtUrl__c = 'https://autherizationUrl.com/{{dptenandId}}/oauth2/v2.0/token',
                                                Client_ID__c = 'Client_ID',
                                                Client_Secret__c = 'Client_Secret',
                                                Proxy_Client_ID__c = 'Proxy_Client_ID',
                                                Tenand_ID__c = 'Tenand_ID',
                                                PDF_API_URL__c = 'https://apiurl/canaccede/v1/datapipeline/pdf');
        insert docParseApi;                


        //Insolvency record creation
        Insolvency__c insolvencyRec = new Insolvency__c();
        insolvencyRec.Name = 'INSOL-90809';
       // insolvencyRec.Insolvency_Type__c = 'Consumer Proposal';
        insolvencyRec.Client_Identifiers__c = 'Scotia Bank';
        INSERT insolvencyRec;

        //Case record creation
        Case caseObj = new Case();
        caseObj.SuppliedEmail = 'abc@a5econsulting.net';
        caseObj.Assigned_To__c = UserInfo.getUserId();
        caseObj.Status = 'InProgress';
        caseObj.Insolvency__c = insolvencyRec.Id;
        INSERT caseObj;

        //EmailMessage record creation
        EmailMessage emailMsg =  new EmailMessage();
        emailMsg.relatedToid = caseObj.Id;
        emailMsg.TextBody = 'Test Email';
        emailMsg.FromAddress = 'abc@gmail.com';
        emailMsg.ToAddress = 'xyz@gmail.com';
        INSERT emailMsg;

        //Attachment record creation
        Attachment att = new Attachment();
        att.parentId = emailMsg.Id;
        att.Body = Blob.valueOf('Test Attach');
        att.Name= 'Test';
        INSERT att;

    }

    static @IsTest
    public void testsuccessResponse(){
        Case cs = [SELECT Id FROM Case LIMIT 1];
        Attachment att = [select id from Attachment LIMIT 1];
        Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, TestDocumentParseMock.getDocumentParserResponse());
        DocumentParser.sendDoc(new Map<Id, Id>{cs.Id=> att.id});
        Test.stopTest();
    }

    static @IsTest
    public void testUpdateParseResponse(){
        DocumentParser.updateParsedResponse(new Parsed_Response_Holder__c(), new HttpResponse(), 'errorDetails');
        DocumentParser.replaceSpecialString('Test String Bankrupt Failli(e)');
    }
}