force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Allowances_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Allowances_Expenses__c</fullName>
    <description>Allowances Expenses</description>
    <inlineHelpText>Allowances Expenses</inlineHelpText>
    <label>Allowances Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_State_Province__c</fullName>
    <description>The primary debtor&apos;s address province.</description>
    <inlineHelpText>The primary debtor&apos;s address province.</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Eligible_For_Voting_Decision__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_Voting_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Eligible For Voting Decision</description>
    <inlineHelpText>Eligible For Voting Decision</inlineHelpText>
    <label>Eligible For Voting Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Entertainment_Sports_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Entertainment_Sports_Expenses__c</fullName>
    <description>Entertainment Sports Expenses</description>
    <inlineHelpText>Entertainment Sports Expenses</inlineHelpText>
    <label>Entertainment Sports Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Food_Grocery_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Food_Grocery_Expenses__c</fullName>
    <description>Food Grocery Expenses</description>
    <inlineHelpText>Food Grocery Expenses</inlineHelpText>
    <label>Food Grocery Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Gifts_Charitable_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Gifts_Charitable_Expenses__c</fullName>
    <description>Gifts Charitable Expenses</description>
    <inlineHelpText>Gifts Charitable Expenses</inlineHelpText>
    <label>Gifts Charitable Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Number_Of_Persons_In_Household__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Persons_In_Household__c</fullName>
    <description>Number Of Persons In Household</description>
    <inlineHelpText>Number Of Persons In Household</inlineHelpText>
    <label>Number Of Persons In Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Number_Of_Persons_In_Household_Below_17__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Persons_In_Household_Below_17__c</fullName>
    <description>Number Of Persons In Household Below 17</description>
    <inlineHelpText>Number Of Persons In Household Below 17</inlineHelpText>
    <label>Number Of Persons In Household Below 17</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Revival_Date__c.field-meta.xml
<CustomField>
    <fullName>Revival_Date__c</fullName>
    <description>Revival Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Revival Date</inlineHelpText>
    <label>Revival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Secured_Debts_Unsecured_Portion__c.field-meta.xml
<CustomField>
    <fullName>Secured_Debts_Unsecured_Portion__c</fullName>
    <description>Secured Debts Unsecured Portion</description>
    <inlineHelpText>Secured Debts Unsecured Portion</inlineHelpText>
    <label>Secured Debts Unsecured Portion</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Trustee_Fees__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Fees__c</fullName>
    <description>The calculated trustee fees for this insolvency</description>
    <formula>IF(TEXT(Insolvency_Type__c) == &apos;Consumer Proposal&apos; || TEXT(Insolvency_Type__c) == &apos;Division 1 Proposal&apos;,

$Setup.Trustee_Fees__c.Trustee_Administration_Fee__c + $Setup.Trustee_Fees__c.Counselling_Fee__c + $Setup.Trustee_Fees__c.Receiver_Fee__c + Trustee_Variable_Fees__c +
(
(
Trustee_Variable_Fees__c + $Setup.Trustee_Fees__c.Trustee_Administration_Fee__c + $Setup.Trustee_Fees__c.Counselling_Fee__c
)
* $Setup.Trustee_Fees__c.HST_Tax_Rate__c
),

null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The calculated trustee fees for this insolvency</inlineHelpText>
    <label>Trustee Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trustee_Fees__c/Trustee_Fees__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trustee Fees</description>
    <label>Trustee Fees</label>
</CustomObject>

force-app/main/default/objects/Trustee_Fees__c/fields/Counselling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Counselling_Fee__c</fullName>
    <defaultValue>170</defaultValue>
    <description>Counselling Fee</description>
    <inlineHelpText>Counselling Fee</inlineHelpText>
    <label>Counselling Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trustee_Fees__c/fields/Receiver_Fee__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Fee__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Receiver Fee</description>
    <inlineHelpText>Receiver Fee</inlineHelpText>
    <label>Receiver Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trustee_Fees__c/fields/Trustee_Administration_Fee__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Administration_Fee__c</fullName>
    <defaultValue>1500</defaultValue>
    <description>Trustee Administration Fee</description>
    <inlineHelpText>Trustee Administration Fee</inlineHelpText>
    <label>Trustee Administration Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trustee_Fees__c/fields/Trustee_Variable_Fee_Rate__c.field-meta.xml
<CustomField>
    <fullName>Trustee_Variable_Fee_Rate__c</fullName>
    <defaultValue>20</defaultValue>
    <description>Trustee Variable Fee Rate</description>
    <inlineHelpText>Trustee Variable Fee Rate</inlineHelpText>
    <label>Trustee Variable Fee Rate</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TestVotingEngineFutureCall.cls
@isTest
public class TestVotingEngineFutureCall {
    public static testMethod void testVotingAutomationCall() {
        //set Mockresponse class
        Test.setMock(HttpCalloutMock.class, new VotingEngineClientMockResponse());

        Voting_Automation_Reason_Mapping__c votingReasonMapping = new Voting_Automation_Reason_Mapping__c();
        votingReasonMapping.Name = 'ENTERTAINMENT_EXCEEDED';
        votingReasonMapping.Value__c = 'Entertainment limit exceeded';
        insert votingReasonMapping;

        API_Call_Details__c APICallDetailsInst = new API_Call_Details__c();
        APICallDetailsInst.Name = 'Voting Automation API';
        APICallDetailsInst.AuthorizationtUrl__c = 'https://login.automotion.com/{{dptenandId}}/oauth2/v2.0/token';
        APICallDetailsInst.Client_ID__c = 'xyxyxyxyxyxyxyxxyxyx';
        APICallDetailsInst.Client_Secret__c = 'yxyxyxyxyx';
        APICallDetailsInst.PDF_API_URL__c = 'https://paschidev.azure-api.net/canaccede/v1/bdm/cpva/5a008cd1-adc4-41c0-8c6e-cd22683f7cba?decisions=leExtendedResults';
        APICallDetailsInst.Proxy_Client_ID__c = 'xyxyxyxyxyx';
        APICallDetailsInst.Tenand_ID__c = 'yyxyxyxyxyxxyxy';
        insert APICallDetailsInst;

        Trustee_Fees__c trusteeFees = Trustee_Fees__c.getOrgDefaults();
        trusteeFees.Trustee_Administration_Fee__c = 10;
        trusteeFees.Counselling_Fee__c = 10;
        trusteeFees.Receiver_Fee__c = 10;
        trusteeFees.Trustee_Variable_Fee_Rate__c = 10;
        insert trusteeFees;

        Insolvency__c insolvencyInstance = new Insolvency__c(
            Name = '12456789',
            eligible_for_voting_decision__c = true,
            Debtor_2_Estate_Number__c = '985236987',
            Insolvency_Status__c = 'Active',
            Insolvency_Type__c = 'Consumer Proposal',
            Sent_For_Owner_Review_Date__c = null,
            //Revival_Date__c = System.today(),
            Number_Of_Persons_In_Household__c = 3,
            Number_Of_Persons_In_Household_Below_17__c = 1,
            Food_Grocery_Expenses__c = 100,
            Entertainment_Sports_Expenses__c = 50,
            Gifts_Charitable_Expenses__c = 30,
            Allowances_Expenses__c = 20,
            Debtor_1_Mailing_State_Province__c = 'Alberta',
            Secured_Debts_Unsecured_Portion__c = 100,
            Bulk_Payment_Amount__c = 10,
            Payment_Amount__c = 20,
            Total_Estimated_Realizable_Value__c = 15,
            Available_Monthly_Income_Of_Family__c = 30,
            Debtor_Portion_Of_Monthly_Income__c = 58,
            Ever_been_Bankrupt_Before__c = 'Yes',
            //Budgetary_Surplus_Deficit__c = 50,
            Trustee_Comments_Notes__c = 'The payments proposed under the terms of the proposal are within the debtors family means and will result in more funds being available for distribution to creditors then would otherwise be available through a bankruptcy.',
            Other_Housing_Expenses__c = 10,
            Other_Personal_Expenses__c = 20,
            Other_Medical_Expenses__c = 30,
            Other_Living_Expenses__c = 40,
            Other_TransportationExpenses__c = 50,
            Other_Insurance_Expenses__c = 60,
            Other_Payments__c = 70,
            Insolvency_date__c = Date.newInstance(2022, 3, 1),
            Allow_Insolvency_Date_In_Past__c = true
        );

        insert insolvencyInstance;

        List<Id> listInsolvency = new List<Id>();
        listInsolvency.add(insolvencyInstance.Id);

        Test.startTest();
        VotingEngineFutureCall.votingAutomationCall(listInsolvency);
        Database.executeBatch(new VotingEngineBatch(listInsolvency), 90);
        Test.stopTest();
    }
}