force-app/main/default/objects/API_Call_Details__c/API_Call_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores all API, client key, secret key for API calls</description>
    <label>API Call Details</label>
</CustomObject>

force-app/main/default/objects/API_Call_Details__c/fields/AuthorizationtUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationtUrl__c</fullName>
    <description>AuthorizationtUrl</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AuthorizationtUrl</inlineHelpText>
    <label>AuthorizationtUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client ID</inlineHelpText>
    <label>Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>Client Secret</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Client Secret</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/PDF_API_URL__c.field-meta.xml
<CustomField>
    <fullName>PDF_API_URL__c</fullName>
    <description>API URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API URL</inlineHelpText>
    <label>API URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Proxy_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Proxy_Client_ID__c</fullName>
    <description>Proxy Client ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Proxy Client ID</inlineHelpText>
    <label>Proxy Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Call_Details__c/fields/Tenand_ID__c.field-meta.xml
<CustomField>
    <fullName>Tenand_ID__c</fullName>
    <description>Tenand ID</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tenand ID</inlineHelpText>
    <label>Tenand ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Allowances_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Allowances_Expenses__c</fullName>
    <description>Allowances Expenses</description>
    <inlineHelpText>Allowances Expenses</inlineHelpText>
    <label>Allowances Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Available_Monthly_Income_Of_Family__c.field-meta.xml
<CustomField>
    <fullName>Available_Monthly_Income_Of_Family__c</fullName>
    <description>Available Monthly Income Of Family</description>
    <inlineHelpText>Available Monthly Income Of Family</inlineHelpText>
    <label>Available Monthly Income Of Family</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Bulk_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Payment_Amount__c</fullName>
    <description>The amount of a debtor&apos;s bulk payment to the Trustee, if any</description>
    <inlineHelpText>The amount of a debtor&apos;s bulk payment to the Trustee, if any</inlineHelpText>
    <label>Bulk Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_1_Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Debtor_1_Mailing_State_Province__c</fullName>
    <description>The primary debtor&apos;s address province.</description>
    <inlineHelpText>The primary debtor&apos;s address province.</inlineHelpText>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_2_Estate_Number__c.field-meta.xml
<CustomField>
    <fullName>Debtor_2_Estate_Number__c</fullName>
    <description>The debtor estate number as noted on the creditor’s package.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Co-Debtor Estate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_Age__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Age__c</fullName>
    <formula>YEAR(Insolvency_Date__c) -  Date_Of_Birth_Year__c</formula>
    <label>Debtor Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Debtor_Portion_Of_Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Portion_Of_Monthly_Income__c</fullName>
    <description>Debtor Portion Of Monthly Income</description>
    <inlineHelpText>Debtor Portion Of Monthly Income</inlineHelpText>
    <label>Debtor Portion Of Monthly Income</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Eligible_For_Voting_Decision__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_Voting_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Eligible For Voting Decision</description>
    <inlineHelpText>Eligible For Voting Decision</inlineHelpText>
    <label>Eligible For Voting Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Entertainment_Sports_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Entertainment_Sports_Expenses__c</fullName>
    <description>Entertainment Sports Expenses</description>
    <inlineHelpText>Entertainment Sports Expenses</inlineHelpText>
    <label>Entertainment Sports Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Food_Grocery_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Food_Grocery_Expenses__c</fullName>
    <description>Food Grocery Expenses</description>
    <inlineHelpText>Food Grocery Expenses</inlineHelpText>
    <label>Food Grocery Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Gifts_Charitable_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Gifts_Charitable_Expenses__c</fullName>
    <description>Gifts Charitable Expenses</description>
    <inlineHelpText>Gifts Charitable Expenses</inlineHelpText>
    <label>Gifts Charitable Expenses</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Status__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Status__c</fullName>
    <description>The status of this debtor’s current / most recent insolvency filing.</description>
    <inlineHelpText>The status of this debtor’s current / most recent insolvency filing.</inlineHelpText>
    <label>Insolvency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
                <default>true</default>
                <label>Staging</label>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Annulled - Filed New</fullName>
            </value>
            <value>
                <fullName>Refused – Filed New</fullName>
            </value>
            <value>
                <fullName>Withdrawn – Filed New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Insolvency_Type__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Type__c</fullName>
    <description>The type of insolvency filing the debtor(s) have made.</description>
    <inlineHelpText>The type of insolvency filing the debtor(s) have made.</inlineHelpText>
    <label>Insolvency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Consumer Proposal</fullName>
            </value>
            <value>
                <fullName>Division 1 Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Is_Spouse_Disclosing_Income__c.field-meta.xml
<CustomField>
    <fullName>Is_Spouse_Disclosing_Income__c</fullName>
    <formula>IF((Number_Of_Persons_In_Household__c - Number_Of_Persons_In_Household_Below_17__c) &gt; 1  &amp;&amp; Debtor_Portion_Of_Monthly_Income__c &lt; 1.0 &amp;&amp; NOT(ISBLANK(Total_Monthly_Income_Spouse__c)) || ( Number_Of_Persons_In_Household__c - Number_Of_Persons_In_Household_Below_17__c ) = 1,true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is Spouse Disclosing Income</inlineHelpText>
    <label>Is Spouse Disclosing Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Number_Of_Persons_In_Household__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Persons_In_Household__c</fullName>
    <description>Number Of Persons In Household</description>
    <inlineHelpText>Number Of Persons In Household</inlineHelpText>
    <label>Number Of Persons In Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Number_Of_Persons_In_Household_Below_17__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Persons_In_Household_Below_17__c</fullName>
    <description>Number Of Persons In Household Below 17</description>
    <inlineHelpText>Number Of Persons In Household Below 17</inlineHelpText>
    <label>Number Of Persons In Household Below 17</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount of the regular monthly payment to the Trustee, as applicable</description>
    <inlineHelpText>The amount of the regular monthly payment to the Trustee, as applicable</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Revival_Date__c.field-meta.xml
<CustomField>
    <fullName>Revival_Date__c</fullName>
    <description>Revival Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Revival Date</inlineHelpText>
    <label>Revival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Secured_Debts_Unsecured_Portion__c.field-meta.xml
<CustomField>
    <fullName>Secured_Debts_Unsecured_Portion__c</fullName>
    <description>Secured Debts Unsecured Portion</description>
    <inlineHelpText>Secured Debts Unsecured Portion</inlineHelpText>
    <label>Secured Debts Unsecured Portion</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Sent_For_Owner_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_For_Owner_Review_Date__c</fullName>
    <description>Sent For Owner Review Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sent For Owner Review Date</inlineHelpText>
    <label>Sent For Owner Review Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/fields/Total_Estimated_Realizable_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Realizable_Value__c</fullName>
    <description>Total Estimated Realizable Value</description>
    <inlineHelpText>Total Estimated Realizable Value</inlineHelpText>
    <label>Total Estimated Realizable Value</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/classes/TestSendToVotingEngineController.cls
@isTest
public class TestSendToVotingEngineController {

    static testMethod void SendToVotingEngine(){
                    
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new VotingEngineClientMockResponse());
        
        Voting_Automation_Reason_Mapping__c votingReasonMapping = new Voting_Automation_Reason_Mapping__c();
        votingReasonMapping.Name = 'ENTERTAINMENT_EXCEEDED';
        votingReasonMapping.Value__c = 'Entertainment limit exceeded';
        insert votingReasonMapping;
        
        API_Call_Details__c APICallDetailsInst = new API_Call_Details__c();
        APICallDetailsInst.Name = 'Voting Automation API';
        APICallDetailsInst.AuthorizationtUrl__c = 'https://login.automationurl.com/{{dptenandId}}/oauth2/v2.0/token';
        APICallDetailsInst.Client_ID__c = 'xyxyxyxyxyxyxyxxyxyx'; 
        APICallDetailsInst.Client_Secret__c = 'yxyxyxyxyx';
        APICallDetailsInst.PDF_API_URL__c = 'https://paschidev.azure-api.net/canaccede/v1/bdm/cpva/5a008cd1-adc4-41c0-8c6e-cd22683f7cba?decisions=leExtendedResults';
        APICallDetailsInst.Proxy_Client_ID__c = 'xyxyxyxyxyx';
        APICallDetailsInst.Tenand_ID__c = 'yyxyxyxyxyxxyxy';
        insert APICallDetailsInst;

        //create insolvency record
        Insolvency__c insolvencyInstance = new Insolvency__c();
            insolvencyInstance.Name = '12456789';
            insolvencyInstance.eligible_for_voting_decision__c = true;
            insolvencyInstance.Debtor_2_Estate_Number__c = '985236987';
            insolvencyInstance.Insolvency_Status__c = 'Active';
            //insolvencyInstance.Insolvency_Type__c = 'Consumer Proposal';
            insolvencyInstance.Sent_For_Owner_Review_Date__c = null;
            //insolvencyInstance.Revival_Date__c = System.today();
            insolvencyInstance.Number_Of_Persons_In_Household__c = 3;
            insolvencyInstance.Number_Of_Persons_In_Household_Below_17__c = 1;
            insolvencyInstance.Food_Grocery_Expenses__c = 100;
            insolvencyInstance.Entertainment_Sports_Expenses__c = 50;
            insolvencyInstance.Gifts_Charitable_Expenses__c = 30;
            insolvencyInstance.Allowances_Expenses__c = 20;
            
            insolvencyInstance.Debtor_1_Mailing_State_Province__c = 'Alberta';
            //Debtor_Age__c = null,
            insolvencyInstance.Secured_Debts_Unsecured_Portion__c = 100;
            insolvencyInstance.Bulk_Payment_Amount__c = 10;
            insolvencyInstance.Payment_Amount__c = 20;
            insolvencyInstance.Total_Estimated_Realizable_Value__c = 15;
            //Is_Spouse_Disclosing_Income__c = true,
            insolvencyInstance.Available_Monthly_Income_Of_Family__c = 30;
            insolvencyInstance.Debtor_Portion_Of_Monthly_Income__c = 58;
            insolvencyInstance.Ever_been_Bankrupt_Before__c = 'Yes';
            //Other_Expenses__c = null;
            //insolvencyInstance.Budgetary_Surplus_Deficit__c = 50;
         
            insert insolvencyInstance;
            
            ApexPages.currentPage().getParameters().put('id', insolvencyInstance.Id);
            ApexPages.StandardController sc = new ApexPages.StandardController(insolvencyInstance);
            
            SendToVotingEngineController send = new SendToVotingEngineController(sc);
            send.mypageloadingmethod();


        
        Test.stopTest();
    }
    
}