force-app/main/default/objects/Creditor_Account__c/Creditor_Account__c.object-meta.xml
<CustomObject>
    <description>Creditor Account records captured from Credit pack</description>
    <label>Creditor Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditor Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Creditor_Account__c/fields/Address_of_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Address_of_Creditor__c</fullName>
    <description>Address of Creditor</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Address of Creditor</inlineHelpText>
    <label>Address of Creditor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Claim Type</description>
    <inlineHelpText>Claim Type</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Creditor_Id__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Id__c</fullName>
    <description>Creditor Package from Creditor Id</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Creditor Package from Creditor Id</inlineHelpText>
    <label>Creditor Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <description>Creditor Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Creditor Name</inlineHelpText>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insolvency</description>
    <inlineHelpText>Insolvency</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Creditor Accounts</relationshipLabel>
    <relationshipName>Creditor_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Liabilities_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Liabilities_Type_Code__c</fullName>
    <description>Liabilities Type Code</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Liabilities Type Code</inlineHelpText>
    <label>Liabilities Type Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Liability_Id__c.field-meta.xml
<CustomField>
    <fullName>Liability_Id__c</fullName>
    <description>Creditor Package From LiabilityId</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Creditor Package From LiabilityId</inlineHelpText>
    <label>Liability Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Preferred_Amount__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Amount__c</fullName>
    <description>Preferred Amount</description>
    <inlineHelpText>Preferred Amount</inlineHelpText>
    <label>Preferred Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Secured_Asset_Amount__c.field-meta.xml
<CustomField>
    <fullName>Secured_Asset_Amount__c</fullName>
    <description>Secured Asset Amount</description>
    <inlineHelpText>Secured Asset Amount</inlineHelpText>
    <label>Secured Asset Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Creditor_Account__c/fields/Unsecured_Asset_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unsecured_Asset_Amount__c</fullName>
    <description>Unsecured Asset Amount</description>
    <inlineHelpText>Unsecured Asset Amount</inlineHelpText>
    <label>Unsecured Asset Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/Insolvency__c.object-meta.xml
<CustomObject>
    <description>This custom object represents the Insolvency information.</description>
    <label>Insolvency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estate Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency__c/fields/Created_By_Doc_Parser__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Doc_Parser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks whether the record is created by Document parser or not</description>
    <inlineHelpText>Checks whether the record is created by Document parser or not</inlineHelpText>
    <label>Created By Doc Parser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insolvency__c/recordTypes/Insolvency.recordType-meta.xml
<RecordType>
    <fullName>Insolvency</fullName>
    <active>true</active>
    <description>Default Insolvency Record Type</description>
    <label>Insolvency</label>
</RecordType>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Claim_Type__c</fullName>
    <description>Indicate whether this is a secured or unsecured account.</description>
    <inlineHelpText>Indicate whether this is a secured or unsecured account.</inlineHelpText>
    <label>Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Unsecured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Creditor_Id__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Id__c</fullName>
    <description>Creditor Id from Creditor package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Creditor Id from Creditor package</inlineHelpText>
    <label>Creditor Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency__c.field-meta.xml
<CustomField>
    <fullName>Insolvency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the insolvency record this insolvency account is attached to.</description>
    <inlineHelpText>A reference to the insolvency record this insolvency account is attached to.</inlineHelpText>
    <label>Insolvency</label>
    <referenceTo>Insolvency__c</referenceTo>
    <relationshipLabel>Insolvency Accounts</relationshipLabel>
    <relationshipName>Insolvency_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Liability_Id__c.field-meta.xml
<CustomField>
    <fullName>Liability_Id__c</fullName>
    <description>Liability id from Creditor package</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Liability id from Creditor package</inlineHelpText>
    <label>Liability Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/fields/Secured_Asset_Amount__c.field-meta.xml
<CustomField>
    <fullName>Secured_Asset_Amount__c</fullName>
    <description>The secured asset amount on this account.</description>
    <inlineHelpText>The secured asset amount on this account.</inlineHelpText>
    <label>Secured Asset Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreditorAccountToInsolvencyAccountCntrl.cls
/**************************************************************************************************
 *
 *  Class:    CreditorAccountToInsolvencyAccountCntrl
 *
 *  @description : Copies specified fields from Creditor Account to creates Insolvency Account
 *  @author : A5E Consulting
 *  @date : 05/05/2020
 
 *************************************************************************************************/
public class CreditorAccountToInsolvencyAccountCntrl {
    
    // Variable captures selected record type on VF page
    public String selectedRecordType{set;get;}
    
    // variable stores current Creditor Account, and is visible in test class
    @TestVisible
    Creditor_Account__c creditorAccount;
    
    // Controller
    public CreditorAccountToInsolvencyAccountCntrl(ApexPages.StandardController controller) {
        creditorAccount = (Creditor_Account__c) controller.getRecord();
        creditorAccount = [SELECT   Id, 
                                Name, 
                                Creditor_Name__c, 
                                Address_of_Creditor__c, 
                                Unsecured_Asset_Amount__c,
                                Secured_Asset_Amount__c,
                                Preferred_Amount__c,
                                Claim_Type__c,
                                Liabilities_Type_Code__c,
                                Liability_Id__c, 
                                Creditor_Id__c,
                                Insolvency__c, 
                                Created_By_Doc_Parser__c 
                        FROM Creditor_Account__c
                        WHERE Id =: creditorAccount.Id];
    }
    
    //Fetch Insolvency Record Types
    public List < SelectOption > getRecordTypes() {
        List < SelectOption > types = new List < SelectOption > ();        
        for(RecordType rType: [SELECT Id, Name FROM RecordType WHERE SObjectType='Insolvency_Account__c' and (NOT name like 'Canadian%')]){
                types.add(new SelectOption(rType.Id, rType.Name));    
        }      
        return types;
    }

    // Method creates Insolvency account from Creditor account, and delete creditor account
    public Pagereference createInsolvencyAccount(){
        Insolvency_Account__c insolvAccount = new Insolvency_Account__c();
        insolvAccount.Name = creditorAccount.Name;
        insolvAccount.RecordTypeId = selectedRecordType;
        insolvAccount.Created_By_Doc_Parser__c = creditorAccount.Created_By_Doc_Parser__c;
        if(creditorAccount.Creditor_Name__c != NULL){
            insolvAccount.Creditor_Name__c = creditorAccount.Creditor_Name__c;
        }
        if(creditorAccount.Address_of_Creditor__c != NULL){
            insolvAccount.Address_of_Creditor__c = creditorAccount.Address_of_Creditor__c;
        }       
        if(creditorAccount.Unsecured_Asset_Amount__c != NULL){
            insolvAccount.Unsecured_Asset_Amount__c = creditorAccount.Unsecured_Asset_Amount__c;
        }
        if(creditorAccount.Secured_Asset_Amount__c != NULL){
            insolvAccount.Secured_Asset_Amount__c = creditorAccount.Secured_Asset_Amount__c;
        }
        if(creditorAccount.Preferred_Amount__c != NULL){
            insolvAccount.Preferred_Amount__c = creditorAccount.Preferred_Amount__c;
        }
        if(creditorAccount.Claim_Type__c != NULL){
            insolvAccount.Claim_Type__c = creditorAccount.Claim_Type__c;
        }
        if(creditorAccount.Liabilities_Type_Code__c != NULL){
            insolvAccount.Liabilities_Type_Code__c = creditorAccount.Liabilities_Type_Code__c;
        }
       
        // creditor Account Related creditorId  & liabilityId 
        if(creditorAccount.Liability_Id__c != NULL){
            insolvAccount.Liability_Id__c = creditorAccount.Liability_Id__c;
        }
        if(creditorAccount.Creditor_Id__c != NULL){
            insolvAccount.Creditor_Id__c = creditorAccount.Creditor_Id__c;
        }
        
        if(creditorAccount.Insolvency__c != NULL){
            insolvAccount.Insolvency__c = creditorAccount.Insolvency__c;
        }
        try{
            insert insolvAccount;
            delete creditorAccount;
            PageReference creditorAccountPage = new PageReference('/' + insolvAccount.id);
        return creditorAccountPage;
        }catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getMessage()));
        }
        return null;        
    }
}