force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment Transaction</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount</description>
    <inlineHelpText>Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Completion_Date__c</fullName>
    <description>Payment Completion Date for one time payment</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Completion Date</inlineHelpText>
    <label>Payment Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type</description>
    <inlineHelpText>Payment Type</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment in Full</fullName>
            </value>
            <value>
                <fullName>One-Time Payment</fullName>
            </value>
            <value>
                <fullName>Recurring Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Record_Type_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/One_time_Payment.recordType-meta.xml
<RecordType>
    <fullName>One_time_Payment</fullName>
    <active>true</active>
    <description>One time Payment</description>
    <label>One time Payment</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Recurring_Payment_Child.recordType-meta.xml
<RecordType>
    <fullName>Recurring_Payment_Child</fullName>
    <active>true</active>
    <description>Recurring Payment Child</description>
    <label>Recurring Payment Child</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Payments__c/Product_Payments__c.object-meta.xml
<CustomObject>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Payments__c/fields/CCS_Account__c.field-meta.xml
<CustomField>
    <fullName>CCS_Account__c</fullName>
    <description>CCS Account</description>
    <label>Account ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CCS_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distressed_Account</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GoEasy_CCS_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Payments</relationshipLabel>
    <relationshipName>Product_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Agency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Agency__c</fullName>
    <description>Payment Provided Agency Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Provided Agency Number</inlineHelpText>
    <label>Payment Agency</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Product Account.</description>
    <inlineHelpText>The amount to be applied to the Product Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date that the payment is posted to the Product Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the payment is posted to the Product Account.</inlineHelpText>
    <label>Payment Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Source__c</fullName>
    <description>Payment Source</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1 OR 2 OR 3
1 - Placement,
2 - CFG,
3 - Seller,</inlineHelpText>
    <label>Payment Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Payments__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type</description>
    <inlineHelpText>Payment Type</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1001</fullName>
            </value>
            <value>
                <fullName>1002</fullName>
            </value>
            <value>
                <fullName>1003</fullName>
            </value>
            <value>
                <fullName>3000</fullName>
            </value>
            <value>
                <fullName>4000</fullName>
            </value>
            <value>
                <fullName>5000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTransactionTriggerHandler.cls
/**************************************************************************************************
*
*  Trigger:   
*
*  @description : This is a Trigger Handler Class for Product_Payments__C object 
*  @author : A5E Consulting
*  @date : 05/07/2022
* 
***********************************************	**************************************************/

public class PaymentTransactionTriggerHandler {
    static String COMPLETED = 'Completed';
    static ID DistressedProductPayID;
    static  boolean stopRecurrsion = false;
    public static void handleAFterUpdate(list<Payment_Transaction__c> listPaymentTransaction, 
                                          map<ID, Payment_Transaction__c> mapOldPaymentTransactions){
		
        list<Payment_Transaction__c> listPaymentTransactionToProcess = new list<Payment_Transaction__c>();
		map<ID, Payment_Transaction__c> mapPaymentTransactions = new Map<ID, Payment_Transaction__c>();
        set<ID> setProductID = new set<ID>();
        //stopRecurrsion = false;                                      
		for(Payment_Transaction__c payTransaction : listPaymentTransaction){    
            if((payTransaction.Record_Type_Name__c == 'One_time_payment' 
            || payTransaction.Record_Type_Name__c == 'Recurring_Payment_Child')
            && String.isNotBlank(payTransaction.Status__c)
            && stopRecurrsion == false
            && (payTransaction.Status__c == COMPLETED && mapOldPaymentTransactions.get(payTransaction.ID).Status__c != COMPLETED)){
                system.debug('payTransaction here'+payTransaction);
				listPaymentTransactionToProcess.add(payTransaction);
                mapPaymentTransactions.put(payTransaction.ID, payTransaction);
                setProductID.add(payTransaction.Product__c);
                stopRecurrsion = true;
            }
        }
        //Call createProductPayments
        system.debug('listPaymentTransactionToProcess::'+listPaymentTransactionToProcess);
        createProductPayments(mapPaymentTransactions.values(), setProductID);
		
    }
    
    //handleBefore insert functionality
    public static void handleBeforeInsert(list<Payment_Transaction__c> listPaymentTransaction){
        list<Payment_Transaction__c> listPaymentTransactionToProcess = new list<Payment_Transaction__c>();
        set<ID> setProductID = new set<ID>();
        
        //map<ID, Product__c> mapProductAGency = 
		for(Payment_Transaction__c payTransaction : listPaymentTransaction){  
            system.debug('payTransaction.Record_Type_Name__c:'+payTransaction.Record_Type_Name__c);
            system.debug('payTransaction.Status__c :0'+payTransaction.Status__c );
            
            if((payTransaction.Record_Type_Name__c == 'One_time_payment' 
            || payTransaction.Record_Type_Name__c == 'Recurring_Payment_Child')
            && String.isNotBlank(payTransaction.Status__c)
            && (payTransaction.Status__c == COMPLETED)){
				system.debug('payTransaction::'+payTransaction);
                listPaymentTransactionToProcess.add(payTransaction);
                setProductID.add(payTransaction.Product__c);
            }
        }
        
        createProductPayments(listPaymentTransactionToProcess, setProductID);
    }
    
    //Create Prodct Payment records
    public static void createProductPayments(list<Payment_Transaction__c> listPaymentTransaction, set<ID> setProductID){
        list<Product_Payments__c> listProductPaymentsToInsert = new list<Product_Payments__c>();
		DistressedProductPayID =  Schema.SObjectType.Product_Payments__c.getRecordTypeInfosByName().get('Distressed Product Payment').getRecordTypeId();
            
        system.debug('DistressedProductPayID::'+DistressedProductPayID);
        
		for(Payment_Transaction__c payTransaction : listPaymentTransaction){
            system.debug('payTransaction::'+payTransaction);
            Product_Payments__c productPayment = new Product_Payments__c();
            productPayment.CCS_Account__c = payTransaction.Product__c;
            productPayment.Payment_Amount__c = payTransaction.Amount__c;
            productPayment.Payment_Posting_Date__c = Date.valueOf(payTransaction.Payment_Completion_Date__c);
            productPayment.Payment_Source__c = '2';
            productPayment.Payment_Type__c = '1000';
            productPayment.Payment_Agency__c = String.valueOf(payTransaction.Collection_Agency__c);
            productPayment.Ignore_Warning__c = true;
            productPayment.RecordTypeId = DistressedProductPayID;
            system.debug('productPayment::'+productPayment);
            listProductPaymentsToInsert.add(productPayment);
        }
                                              
		//ProductPaymentsTriggerHandler.runTrigger = false;
		system.debug('listProductPaymentsToInsert::'+listProductPaymentsToInsert);
        if(!Test.isRunningTest()){
        	insert listProductPaymentsToInsert;		    
        }
		//ProductPaymentsTriggerHandler.runTrigger = true;
    }
}