force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment Transaction</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount</description>
    <inlineHelpText>Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/CSV_Export_Completed__c.field-meta.xml
<CustomField>
    <fullName>CSV_Export_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CSV Export Completed</description>
    <inlineHelpText>CSV Export Completed</inlineHelpText>
    <label>CSV Export Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Processor_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor_Id__c</fullName>
    <description>Payment Processor Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Payment Processor Id</inlineHelpText>
    <label>Payment Processor Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type</description>
    <inlineHelpText>Payment Type</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment in Full</fullName>
            </value>
            <value>
                <fullName>One-Time Payment</fullName>
            </value>
            <value>
                <fullName>Recurring Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Portal_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_ID__c</fullName>
    <description>Portal ID (record identifier in  Portal)</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Portal ID</inlineHelpText>
    <label>Portal ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Record_Type_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/One_time_Payment.recordType-meta.xml
<RecordType>
    <fullName>One_time_Payment</fullName>
    <active>true</active>
    <description>One time Payment</description>
    <label>One time Payment</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Recurring_Payment_Child.recordType-meta.xml
<RecordType>
    <fullName>Recurring_Payment_Child</fullName>
    <active>true</active>
    <description>Recurring Payment Child</description>
    <label>Recurring Payment Child</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction_CSV__c/Payment_Transaction_CSV__c.object-meta.xml
<CustomObject>
    <description>Payment Transaction CSV</description>
    <label>Payment Transaction CSV</label>
    <nameField>
        <displayFormat>PTCSV-{000000}</displayFormat>
        <label>Payment Transaction CSV Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transaction CSV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/DebtNext_Data_ID__c.field-meta.xml
<CustomField>
    <fullName>DebtNext_Data_ID__c</fullName>
    <description>External Id for Debtnext Accounts</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>DebtNext Data ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Previous_Primary_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Primary_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Previous Primary Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTransactionCSVUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Utility class for creating payment CSV file.   
*  @author : A5E Consulting
*  @date : 17/06/2021   

*************************************************************************************************/
public Class PaymentTransactionCSVUtil{
    
    private static final String TRANSACTION_STATUS = 'Completed';
    private static final String ONE_TIME_PAYMENT =  'One_time_Payment';
    private static final String RECURRENT_PAYMENT_CHILD =  'Recurring_Payment_Child';
    static List<Payment_Transaction__c> listPaymentTransaction;
    
    //fetch All Eligible Payment Transaction Records
    public static List<Payment_Transaction__c> fecthPaymentTransaction(){        
        //Check if Product is present on transaction to exclude Withdra Transactions
        listPaymentTransaction = [SELECT Id, Name, Amount__c, Payment_Processor_Id__c, CreatedDate, Portal_ID__c, 
                                         Payment_Type__c,
                                         Product__r.DebtNext_Data_ID__c, Product__r.Previous_Primary_Account_Number__c
                                  FROM Payment_Transaction__c 
                                  WHERE CSV_Export_Completed__c = false
                                  AND Status__c = :TRANSACTION_STATUS
                                  AND (Record_Type_Name__c = :ONE_TIME_PAYMENT
                                       OR Record_Type_Name__c = :RECURRENT_PAYMENT_CHILD)
                                  AND Product__c != NULL];
        System.debug('listPaymentTransaction=='+listPaymentTransaction);
        return listPaymentTransaction;                                                                   
    }
    
    //fetch All Eligible Payment Transaction Records
    public static boolean createPaymentCSV(){
        String finalPaymentCSV = 'data_id' + ','
                                + 'pay_type'+',' 
                                + 'pay_date' +','                
                                + 'pri_acctno' +','
                                + 'pay_amount' +',' 
                                + '' +''
                                + '\n'; 
        String codeValue = '';
        
        List<Payment_Transaction__c> listPaymentTransaction = fecthPaymentTransaction();
        for(Payment_Transaction__c payTransactionObj : listPaymentTransaction){         
            String paymentDate='';
            //if (payTransactionObj.Portal_ID__c != null){
                paymentDate = convertDateToString(payTransactionObj.CreatedDate);
            //}
            String payCSV = '';
            payCSV = checkComma((payTransactionObj.Product__r.DebtNext_Data_ID__c != null) ? payTransactionObj.Product__r.DebtNext_Data_ID__c : '')+',' 
                                + checkComma((payTransactionObj.Payment_Type__c == 'Payment in Full') ? '1001' : '1000')+',' 
                                + checkComma(paymentDate) +','
                                + checkComma(payTransactionObj.Product__r.Previous_Primary_Account_Number__c) +',' 
                                + checkComma(String.valueOf(payTransactionObj.Amount__c)) +','
                                + '' +''
                                + '\n'; 
            
            if(String.isNotBlank(payCSV)){
                finalPaymentCSV += payCSV;
            }              
        }
        Boolean CSVCreated = createPaymentTransactionCSVRecord(finalPaymentCSV);
        return CSVCreated;
        //return finalPaymentCSV;
    }
    
    //Create Payment Transaction CSV Record
    public static boolean createPaymentTransactionCSVRecord(String versaPayCSV){
        //Payment Trassanction CSV record
        Payment_Transaction_CSV__c payTransactionCSV = new Payment_Transaction_CSV__c();
        insert payTransactionCSV;
        
        //Payment CSV Attachment
        Attachment attachment = new Attachment();
        attachment.Body = Blob.valueOf(versaPayCSV);
        attachment.Name = 'Payment Transaction-CSV-' + convertDateToString(system.Now()) + '.csv';
        attachment.ParentId = payTransactionCSV.Id; 
        
        try{
			insert attachment;   
            updatePayTransactionRecords();
            return true;
        }
        catch(Exception ex){
            system.debug('Exception ex : '+ex);
            return false;
        }
    }
    
    //update Payment Transaction records and return result
    public static Boolean updatePayTransactionRecords(){
        system.debug('listPaymentTransaction in update'+listPaymentTransaction);
        List<Payment_Transaction__c> listPayTransactionUpdate = New List<Payment_Transaction__c>();
        for(Payment_Transaction__c prodPay : listPaymentTransaction){
            prodPay.CSV_Export_Completed__c = true;    
            listPayTransactionUpdate.add(prodPay);
        }
        
        update listPayTransactionUpdate;
        return true;
    }
    
    //Convert Date to String
    @testvisible
    private static String convertDateToString(DateTime dt){
        if(dt != null){
            //Date dte = dt.Date();
            //return String.valueof(dte.month()+'/'+dte.day()+'/'+dte.year());
            return (dt.formatGMT('MM/dd/yyyy'));
        }
        else{
            return '';
        }
    }
    
    //if value contains comma',' , append quote in trailing and heading
    @testvisible
    private static String checkComma(String str){

        if(String.isNotBlank(str) && str.contains(',')){
                return +' \"'+str+'\" ';
        }
        else{
            return str;
        }
    }
}