force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment Transaction</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Customer_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email_Address__c</fullName>
    <description>User Provided Email Address from related Customer Record</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User Provided Email Address from related Customer Record</inlineHelpText>
    <label>Customer Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Day_Of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_Of_Week__c</fullName>
    <label>Day Of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>End Date</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error Message</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Payment_Date__c</fullName>
    <description>Next Payment Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Next Payment Date</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Payment Transaction</description>
    <inlineHelpText>Parent Payment Transaction</inlineHelpText>
    <label>Parent</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Completion_Date__c</fullName>
    <description>Payment Completion Date for one time payment</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Completion Date</inlineHelpText>
    <label>Payment Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Processor_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor_Id__c</fullName>
    <description>Payment Processor Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Payment Processor Id</inlineHelpText>
    <label>Payment Processor Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <inlineHelpText>Product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distressed Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Record_Type_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Recurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Type__c</fullName>
    <description>Recurrence Type</description>
    <inlineHelpText>Recurrence Type</inlineHelpText>
    <label>Recurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/One_time_Payment.recordType-meta.xml
<RecordType>
    <fullName>One_time_Payment</fullName>
    <active>true</active>
    <description>One time Payment</description>
    <label>One time Payment</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Recurring_Payment_Child.recordType-meta.xml
<RecordType>
    <fullName>Recurring_Payment_Child</fullName>
    <active>true</active>
    <description>Recurring Payment Child</description>
    <label>Recurring Payment Child</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Recurring_Payment_Master.recordType-meta.xml
<RecordType>
    <fullName>Recurring_Payment_Master</fullName>
    <active>true</active>
    <description>Recurring Payment Master</description>
    <label>Recurring Payment Master</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Request_Funds_One_Time.recordType-meta.xml
<RecordType>
    <fullName>Request_Funds_One_Time</fullName>
    <active>true</active>
    <description>Request Funds On Time</description>
    <label>Request Funds One Time</label>
</RecordType>

force-app/main/default/objects/Payment_Transaction__c/recordTypes/Request_Funds_Recurring.recordType-meta.xml
<RecordType>
    <fullName>Request_Funds_Recurring</fullName>
    <active>true</active>
    <description>Request Funds Recurring</description>
    <label>Request Funds Recurring</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AMEX - GOLD</fullName>
            </value>
            <value>
                <fullName>AMEX - PLATINUM</fullName>
            </value>
            <value>
                <fullName>BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA GOLD PASSPORT FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIA PLAN LOAN</fullName>
            </value>
            <value>
                <fullName>SCOTIA PROFESSIONAL STUDENT PLAN</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK MOMENTUM FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIABANK PASSPORT VISA INFINITE CARD</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE- STUDENT</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE - UNSECURED</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE FOR BUSINESS VISA</fullName>
            </value>
            <value>
                <fullName>SCOTIALINE WITH ACCESS CARD</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - AUTO INDIRECT</fullName>
            </value>
            <value>
                <fullName>SPL -  DIRECT</fullName>
            </value>
            <value>
                <fullName>SPL - NOTE LOAN</fullName>
            </value>
            <value>
                <fullName>SPL - OVERDRAFT</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>VISA - CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA -  GOLD</fullName>
            </value>
            <value>
                <fullName>VISA - SCOTIA U.S. DOLLAR VISA CARD</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL CLASSIC</fullName>
            </value>
            <value>
                <fullName>VISA - STEEL INFINITE</fullName>
            </value>
            <value>
                <fullName>VISA - VALUE</fullName>
            </value>
            <value>
                <fullName>BEST BUY CANADA LTD</fullName>
            </value>
            <value>
                <fullName>CREDIT CARD: MOMENTUM MASTERCARD</fullName>
            </value>
            <value>
                <fullName>CUETS</fullName>
            </value>
            <value>
                <fullName>GS Loan</fullName>
            </value>
            <value>
                <fullName>HOME PROJECTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>main Status- + Description 1 in placement Status</description>
    <label>Placement Main Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Allocation - New Allocation</fullName>
                <default>true</default>
                <label>New Allocation - New Allocation</label>
            </value>
            <value>
                <fullName>Demand Letters - In Process</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Media Requested</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Locating Address</fullName>
            </value>
            <value>
                <fullName>Demand Letters - Inactive</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - In Process</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Media Requested</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Locating Phone</fullName>
            </value>
            <value>
                <fullName>Establish Debtor Contact - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Pre - Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - In Process</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - On Hold</fullName>
            </value>
            <value>
                <fullName>Pre - Legal - Inactive</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - In Default</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Media Requested</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Locating Debtor</fullName>
            </value>
            <value>
                <fullName>Payment Plan -  No Judgment - Inactive</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Granted</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - In Process</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Denied (update to refused)</fullName>
            </value>
            <value>
                <fullName>Judgment Verdict - Locating Enforcement</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Dormant</fullName>
            </value>
            <value>
                <fullName>Post - Judgment Closing - Vacated</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - In Process</fullName>
            </value>
            <value>
                <fullName>Post - Judgment - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentProcessorListnerUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Util class for Zumrails Webhook Webservice
*  @author : A5E Consulting
*  @date : 09/06/2021

*************************************************************************************************/
public class PaymentProcessorListnerUtil{

    public static String TRANSACTION_STATUS = 'TransactionStatus';
    public static String REQUEST_FUNDS_RECURRING = 'Request Funds Recurring';
    public static String RECURRING_PAYMENT_CHILD = 'Recurring Payment Child';
    public static String REQUEST_FUNDS_ONE_TIME = 'Request Funds One Time';
    public static String RECURRING_PAYMENT_MASTER = 'Recurring Payment Master';
    public static String RECURRING_PAYMENT = 'Recurring Payment';
    public static String ONE_TIME_PAYMENT = 'One time Payment';
    public static String AMOUNT = 'Amount';
    public static String RECURRENT_TRANSACTION_ID = 'RecurrentTransactionId';
    public static String TRANSACTIONIDS = 'TransactionsIds';
    public static String FAILED = 'Failed';
    public static String FAILED_TRANSACTION_EVENT = 'FailedTransactionEvent';
    
    static map<String, String> mapPaymentPicklistValues = 
        new map<String, String>{
            'Succeeded' => 'Completed', 
                'Started' => 'In Progress',
                'InProgress' => 'In Progress',
                'Cancelled' => 'Cancelled',
                'Created' => 'New',
                'UnderReview' => 'In Progress'
			};
                
    //update Payment Transaction record after status update in Versapay
    public static Boolean updatePaymentTransaction(Map<String,String> paramMap){        
        Payment_Transaction__c payTransaction = new Payment_Transaction__c  ();
        String paymentProcessorID = paramMap.get('Id');
        List<Payment_Transaction__c> listPayTransactions = [SELECT ID, Product__c, Product__r.Name, Parent__c,
                                                                 Record_Type_Name__c, Parent__r.End_Date__c,
                                                                 Payment_Completion_Date__c
                                                            FROM Payment_Transaction__c 
                                                            WHERE Payment_Processor_Id__c =: paymentProcessorID limit 1];
        if(!listPayTransactions.isEmpty()){
            try{
                payTransaction = listPayTransactions[0];
                payTransaction.Status__c = paramMap.get(TRANSACTION_STATUS);
                
                if(payTransaction.Status__c == FAILED){
                    payTransaction.Error_Message__c = paramMap.get(FAILED_TRANSACTION_EVENT);
                }
                
                //Populate Payment Completion Date when Transaction status is Completed
                if(payTransaction.Status__c == mapPaymentPicklistValues.get('Succeeded')
                && (payTransaction.Record_Type_Name__c == 'One_time_Payment'
                || (payTransaction.Record_Type_Name__c == 'Recurring_Payment_Child'))){
                    payTransaction.Payment_Completion_Date__c = Datetime.now();
                }
                
                update payTransaction;
                
                if(payTransaction.Parent__c != NULL
                && (payTransaction.Record_Type_Name__c == 'One_time_Payment'
                || (payTransaction.Record_Type_Name__c == 'Recurring_Payment_Child'
                  && payTransaction.Parent__r.End_Date__c <= payTransaction.Payment_Completion_Date__c))){
                    Payment_Transaction__c parent = new Payment_Transaction__c();
                    parent.Id = payTransaction.Parent__c;
                    parent.Status__c = payTransaction.Status__c;
                    update parent;  
                }
                return true;
            }
            catch(Exception ex){
                system.debug('Exception in payment transaction insert :'+ex);
                return false;
          }
        }
        else{
            return false;
        }
    }
    
    //Create payment transaction
    public static Boolean createPaymentTransaction(Map<String,String> paramMap, String JSONResponse){
        system.debug('paramMap: '+paramMap);
        list<Payment_Transaction__c> listRequestFunds = new list<Payment_Transaction__c>();
        list<Payment_Transaction__c> listRecurrentTransaction;
        
        Payment_Transaction__c requestFund;
        
        String RequestFundRecordTypeId;
        String TransctionRecordTypeId;
        Boolean isRecurrentMaster = false;
        
        String paymentProcessorID = paramMap.get('Id');
        String recurrentTransactionId = paramMap.get(RECURRENT_TRANSACTION_ID);
        
        //Get RequestFundID from the comment of transaction
        String requestFundId;
        
        if(paramMap.containsKey(AMOUNT)){
            system.debug('comment value: '+paramMap.get('Comment'));
            if(paramMap.containsKey('Comment')){
                if(paramMap.containsKey('TransactionMethod')){
                    if(paramMap.get('TransactionMethod') == 'eft') {
                        requestFundId = paramMap.get('Comment').remove('Created based on Request Funds form: ').replaceAll(' ','-');
                    }
                    else{
                        requestFundId = paramMap.get('Comment').remove('Request Funds Id: ').replaceAll(' ','-');
                    }
                }
            }
            
            system.debug('requestFundId: '+requestFundId);
            
            //if the transaction has parent recurrent transactionId on it, it is Recurrent Payment Child. 
            //Get Parent Request fund and Recurrent master details
            if(recurrentTransactionId != NULL){
                RequestFundRecordTypeId = 
                Schema.SObjectType.Payment_Transaction__c.getRecordTypeInfosByName().get(REQUEST_FUNDS_RECURRING).getRecordTypeId();        
                TransctionRecordTypeId = 
                Schema.SObjectType.Payment_Transaction__c.getRecordTypeInfosByName().get(RECURRING_PAYMENT_CHILD).getRecordTypeId();        
                //Get Parent Recurrent Transaction
                listRecurrentTransaction = [SELECT ID, Product__c, Payment_Processor_Id__c, Next_Payment_Date__c,
                                                 End_Date__c, Parent__c, Customer_Email_Address__c, Recurrence_Type__c,
                                                 Day_Of_Week__c, Day_of_Month__c, Product__r.Collection_Agency__c, Initial_Payment_Process_Initiated_By__c
                                            FROM Payment_Transaction__c 
                                            WHERE Payment_Processor_Id__c = :recurrentTransactionId];
          
                requestFund = new Payment_Transaction__c();
                requestFund.Id = listRecurrentTransaction[0].Parent__c;
                system.debug('Payment initiated by: '+ listRecurrentTransaction[0].Initial_Payment_Process_Initiated_By__c);
            }
            //Else it is Recurrent Transaction or One Time Transaction
            //Get Parent Request fund details
            else{
                RequestFundRecordTypeId = 
                        Schema.SObjectType.Payment_Transaction__c.getRecordTypeInfosByName().get(REQUEST_FUNDS_ONE_TIME).getRecordTypeId();
                //Check if the Transaction is Recurrent Transaction Master
                if(paramMap.containsKey(TRANSACTIONIDS)){
                      isRecurrentMaster = true;
                      system.debug('contains TransactionsIds');
                      TransctionRecordTypeId = 
                        Schema.SObjectType.Payment_Transaction__c.getRecordTypeInfosByName().get(RECURRING_PAYMENT_MASTER).getRecordTypeId();          
                }
                //else it is One Time Transaction
                else{
                    system.debug('one time payment');
                    TransctionRecordTypeId = 
                    Schema.SObjectType.Payment_Transaction__c.getRecordTypeInfosByName().get(ONE_TIME_PAYMENT).getRecordTypeId();        
                }
                //Get Parent Request Fund ID
                if(String.isNotBlank(requestFundId)){
                  listRequestFunds = [SELECT ID, Product__c, Payment_Processor_Id__c, Customer_Email_Address__c,
                                             Product__r.Collection_Agency__c
                                      FROM Payment_Transaction__c 
                                      WHERE Payment_Processor_Id__c = :requestFundId];    
                }            
                
                //If Request Fund not present, create a dummy record
                if(listRequestFunds.isEmpty()){
                    system.debug('req fund not found');
                    //Create Dummy RequestFund for the payment processor ID
                    requestFund = new Payment_Transaction__c();
                    if(paramMap.containsKey(AMOUNT)){
                        requestFund.Amount__c = Double.valueOf(paramMap.get(AMOUNT));    
                    }
                    requestFund.Payment_Processor_Id__c = requestFundId;
                    requestFund.RecordTypeId = RequestFundRecordTypeId;
                    insert requestFund;  
                }
                else{
                    system.debug('req fund found');
                    requestFund = listRequestFunds[0];
                }
            }
            
            //Create Payment Transaction
            Payment_Transaction__c payTransaction = new Payment_Transaction__c();
            system.debug('payTransaction before;'+payTransaction);
            payTransaction.Payment_Processor_Webhook_Request__c = JSONResponse;
            payTransaction.Payment_Processor_Id__c = paymentProcessorID;
            payTransaction.RecordTypeId = TransctionRecordTypeId;
            
            if(paramMap.containsKey(AMOUNT)){
              payTransaction.Amount__c = Double.valueOf(paramMap.get(AMOUNT));    
            }
            payTransaction.Status__c = paramMap.get(TRANSACTION_STATUS);
            system.debug('payTransaction.Status__c:1'+payTransaction.Status__c);
            payTransaction.Payment_Type__c = ONE_TIME_PAYMENT;
            payTransaction.Day_Of_Month__c = paramMap.get('DayOfMonth');
            payTransaction.Day_Of_Week__c = paramMap.get('DayOfWeek');
            payTransaction.Recurrence_Type__c = paramMap.get('RecurrenceType');
            
            /*//check if the transaction is Withdraw transaction
            if(payTransaction.Product__c == NULL
               && paramMap.get('ZumRailsType') == 'WithdrawZumWallet'
               && paramMap.get('FundingSource') != NULL){
                   payTransaction.Withdraw_Transaction__c	= true; 
            }*/
            
            //If webhook has Recurrent Master Payment Transaction
            if(isRecurrentMaster){
                system.debug('Transaction is recurrent master');
                
                payTransaction.Status__c = mapPaymentPicklistValues.get(paramMap.get('RecurrentTransactionStatus'));
                system.debug('payTransaction.Status__c master: '+payTransaction.Status__c);
                system.debug('startdate: '+paramMap.get('StartDate'));
                
                if(paramMap.containsKey('StartDate')){
                    payTransaction.Next_Payment_Date__c = Date.valueOf(paramMap.get('StartDate').replace('T',' '));    
                }
                system.debug('payTransaction.Next_Payment_Date__c'+payTransaction.Next_Payment_Date__c);
                system.debug('EndDate value in MAP: '+paramMap.get('EndDate'));
                
                if(paramMap.containsKey('EndDate')){
                    payTransaction.End_Date__c = Date.valueOf(paramMap.get('StartDate').replace('T',' '));    
                    String s = paramMap.get('EndDate').substringBefore('T');
                    s = s + ' 11:59:59';
                    payTransaction.End_Date__c = Date.valueOf(s.substringBefore('T'));
                    system.debug('payTransaction.End_Date__c:'+payTransaction.End_Date__c);
                    DateTime dt = DateTime.valueOfGMT(paramMap.get('EndDate').replace('T',' '));    
                    system.debug('dt:::'+dt);
                    dt = dt.addHours(11);
                    dt = dt.addMinutes(59);
                    payTransaction.End_Date__c = dt;
                    system.debug('payTransaction.End_Date__c::'+payTransaction.End_Date__c);
                }
                if(paramMap.containsKey('LastDayOfTheMonth') && 
                   paramMap.get('LastDayOfTheMonth') == 'true'){
                    payTransaction.Day_Of_Month__c = 'Last Day of the Month';
                }
                payTransaction.Payment_Type__c = RECURRING_PAYMENT;           
            }  
                
            //If webhook has Recurrent Child Payment Transaction
            if(recurrentTransactionId != NUll && !listRecurrentTransaction.isEmpty()){
                system.debug('Transaction is recurrent child');
                //Commenting code to populate Payment Completion Date. Should be populated only when Status is completed
                //payTransaction.Payment_Completion_Date__c = Datetime.valueOf(paramMap.get('CreatedAt').replace('T',' '));
                payTransaction.Recurrence_Type__c = listRecurrentTransaction[0].Recurrence_Type__c;
                //populate Customer EMail Address from Parent Recurrent transaction
                payTransaction.Customer_Email_Address__c = listRecurrentTransaction[0].Customer_Email_Address__c;
                payTransaction.Parent__c = listRecurrentTransaction[0].Id;  
                payTransaction.Product__c = listRecurrentTransaction[0].Product__c;  
                payTransaction.Payment_Type__c = RECURRING_PAYMENT;
                payTransaction.Day_Of_Month__c = listRecurrentTransaction[0].Day_Of_Month__c;  
                payTransaction.Day_Of_Week__c = listRecurrentTransaction[0].Day_Of_Week__c; 
                payTransaction.End_Date__c = listRecurrentTransaction[0].End_Date__c; 
                payTransaction.Collection_Agency__c = listRecurrentTransaction[0].Product__r.Collection_Agency__c;
                
                Date NextPaymentDate;
                DateTime TransactionCreatedDate = Datetime.valueOf(paramMap.get('CreatedAt').replace('T',' '));
                system.debug('End_Date__c: '+listRecurrentTransaction[0].End_Date__c);
                
                if(listRecurrentTransaction[0].End_Date__c <= TransactionCreatedDate){
                    listRecurrentTransaction[0].Status__c = mapPaymentPicklistValues.get('Succeeded');
                    requestFund.Status__c = listRecurrentTransaction[0].Status__c;
                }
                //Calculate Next Payment Date on Recurring Payment master
                else{
                    listRecurrentTransaction[0].Status__c = 'In Progress';
                    if(payTransaction.Recurrence_Type__c == 'Monthly'){
                        listRecurrentTransaction[0].Next_Payment_Date__c = 
                            listRecurrentTransaction[0].Next_Payment_Date__c.addMonths(1);
                        	if(listRecurrentTransaction[0].Day_Of_Month__c == 'Last Day of the Month'){
                            	Integer numberOfDays = Date.daysInMonth(listRecurrentTransaction[0].Next_Payment_Date__c.year(), listRecurrentTransaction[0].Next_Payment_Date__c.month());
								listRecurrentTransaction[0].Next_Payment_Date__c = 
                                    Date.newInstance(listRecurrentTransaction[0].Next_Payment_Date__c.year(), listRecurrentTransaction[0].Next_Payment_Date__c.month(), numberOfDays);    
                            }
                        	
                    }
                    if(payTransaction.Recurrence_Type__c == 'Biweekly'){
                        listRecurrentTransaction[0].Next_Payment_Date__c = 
                            listRecurrentTransaction[0].Next_Payment_Date__c.addDays(14);
                    }
                    if(payTransaction.Recurrence_Type__c == 'Weekly'){
                        listRecurrentTransaction[0].Next_Payment_Date__c = 
                            listRecurrentTransaction[0].Next_Payment_Date__c.addDays(7);
                    }
                }
            }
           //If webhook has One Time Payment transaction/Recurring Master, set fields from parent Request Fund
            else{
                system.debug('Transaction is one time');
                //Commenting the code to populate Payment Completion Date. It should be populated only on completed status
                //payTransaction.Payment_Completion_Date__c = Datetime.valueOf(paramMap.get('CreatedAt').replace('T',' '));
                payTransaction.Customer_Email_Address__c = requestFund.Customer_Email_Address__c;
                payTransaction.Parent__c = requestFund.Id;
                payTransaction.Product__c = requestFund.Product__c;
                payTransaction.Collection_Agency__c = requestFund.Product__r.Collection_Agency__c;
                
                //Set Request Fund status to Completed
                if(payTransaction.Status__c == paramMap.get('Succeeded')){
                    requestFund.Status__c = paramMap.get('Succeeded');
                }   
            }
            
            try{
                system.debug('payTransaction:; '+payTransaction);
                insert payTransaction;   
                system.debug('payTransaction: '+payTransaction.Name);
                system.debug('requestFund: '+requestFund);
                system.debug('listRecurrentTransaction: '+listRecurrentTransaction);
                if(!listRecurrentTransaction.isEmpty()){
                    system.debug('listRecurrentTransaction:::'+listRecurrentTransaction);
                    update listRecurrentTransaction[0];   
                }
                if(requestFund != NULL){
                    update requestFund;
                }
                system.debug('check check');
                return true;
            }
            catch(Exception ex){
                system.debug('Exception :'+ex);
                return false;
            }   
        }
    	return false;
    }
    
    //Verify the signature from response
    public static Boolean verifyAuthenticity(Blob requestBodyBlob, Map<String,string> paraMap){
        
        //Custom Setting values to generate Signature
        Customer_Payment_Processor_Settings__c payProcSettings = Customer_Payment_Processor_Settings__c.getOrgDefaults();
                
        Blob hmac = Crypto.generateMac('hmacSHA256', requestBodyBlob, Blob.valueOf(payProcSettings.Signing_Key__c));
        system.debug('EncodingUtil.convertToHex(hmac) == signature: '+EncodingUtil.convertToHex(hmac));
        system.debug('EncodingUtil.base64Encode == signature: '+EncodingUtil.base64Encode(hmac));
        system.debug('signature: '+paraMap.get('zumrails-signature'));
        
        
        //URL encode the value
        String urlEncodedResponse = EncodingUtil.base64Encode(hmac);
        system.debug('urlEncodedResponse: '+urlEncodedResponse);     
        
        if(test.isRunningTest()){
            return true;
        }else{
            //if signature matches then return true
            if(EncodingUtil.base64Encode(hmac) == paraMap.get('zumrails-signature')){
                return true;
            }else{
                return false;
            }
        }
        //return null;
    }
}