force-app/main/default/objects/Delinquency_Tracker__c/Delinquency_Tracker__c.object-meta.xml
<CustomObject>
    <label>Daily Delinquency Tracker</label>
    <nameField>
        <displayFormat>DT-{0000}</displayFormat>
        <label>Delinquency Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Delinquency Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delinquency_Tracker__c/fields/Iteration_Number__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Number__c</fullName>
    <description>Iteration Number  (for back-end processing)</description>
    <inlineHelpText>Iteration Number  (for back-end processing)</inlineHelpText>
    <label>Iteration Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delinquency_Tracker_Settings__c/Delinquency_Tracker_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Delinquency Tracker Settings</description>
    <label>Delinquency Tracker Settings</label>
</CustomObject>

force-app/main/default/objects/Delinquency_Tracker_Settings__c/fields/Iteration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Limit__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Iteration Limit</description>
    <inlineHelpText>Iteration Limit</inlineHelpText>
    <label>Iteration Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delinquency_Tracker_Settings__c/fields/Next_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Next_Iteration__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Next Iteration</description>
    <inlineHelpText>Next Iteration</inlineHelpText>
    <label>Next Iteration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDeleteDelinquencyTrackerBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Test Class for DeleteDelinquencyTrackerBatch
*  @author : A5E Consulting
*  @date : 07/13/2017   

*************************************************************************************************/
@isTest
public class TestDeleteDelinquencyTrackerBatch{

    public Static testMethod void delDTBatch(){
    
        //create Product Snapshot Custom Setting Record    
        createDTCS();
                
        //create Delinquency_Tracker__c records
        createDTRecords();
        
        //execute DeleteDelinquencyTrackerBatch
        Database.executeBatch(New DeleteDelinquencyTrackerBatch());
    }
    
    //create Delinquency Tracker records
    public static void createDTRecords(){
        
        Delinquency_Tracker__c dtRec = New Delinquency_Tracker__c();
        dtRec.Iteration_Number__c = 2;
        insert dtRec;
        
        dtRec = New Delinquency_Tracker__c();
        dtRec.Iteration_Number__c = 2;
        insert dtRec;
    }
    
    //Create Custom Setting Record
    public static void createDTCS(){
        
        Delinquency_Tracker_Settings__c dtCS = New Delinquency_Tracker_Settings__c();
        dtCS.Iteration_Limit__c = 1;
        dtCS.Next_Iteration__c = 2;        
        insert dtCS; 
    }    
}