force-app/main/default/objects/Deleted_Records__c/Deleted_Records__c.object-meta.xml
<CustomObject>
    <label>Deleted Records</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Deleted Records Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deleted_Records__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This field keeps the name of the Object for ADF to know on which table it needs to perform deletion.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deleted_Records__c/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <description>This field keeps the Salesforce Record ID for ADF Job to pick to perform deletion in Analytics DB.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Salesforce Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Account__c/Insolvency_Account__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual accounts owned by the Insolvent Debtor included as part of the insolvency filing.</description>
    <label>Insolvency Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insolvency Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Account__c/fields/Insolvency_Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Last_Payment_Amount__c</fullName>
    <description>The last payment amount for this Insolvency</description>
    <inlineHelpText>The last payment amount for this Insolvency</inlineHelpText>
    <label>Insolvency Last Payment Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/Insolvency_Payment__c.object-meta.xml
<CustomObject>
    <description>This custom object represents individual payments made on individual accounts in the insolvency filing.</description>
    <label>Insolvency Payment</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>Insolvency Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insolvency Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insolvency_Payment__c/fields/External_Correlation_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Correlation_ID__c</fullName>
    <description>This field is an immutable Id which allows record synchronization with external systems.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>External Correlation ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Account__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Account__c</fullName>
    <description>A reference to the Insolvency Account this payment belongs to.</description>
    <inlineHelpText>A reference to the Insolvency Account this payment belongs to.</inlineHelpText>
    <label>Insolvency Account</label>
    <referenceTo>Insolvency_Account__c</referenceTo>
    <relationshipLabel>Insolvency Payments</relationshipLabel>
    <relationshipName>Insolvency_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Insolvency_Payment_Name_Original__c.field-meta.xml
<CustomField>
    <fullName>Insolvency_Payment_Name_Original__c</fullName>
    <description>This field gets the value from Insolvency Payment Name (Auto Number) field only on record insert. This is used to retain the first generated Auto Number value even after Unarchival.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Insolvency Payment Name Original</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The amount to be applied to the Insolvency Account.</description>
    <inlineHelpText>The amount to be applied to the Insolvency Account.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Created__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Payment Created</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Created</inlineHelpText>
    <label>Payment Created</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Reversal_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reversal_Date__c</fullName>
    <description>Payment Reversal Date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Payment Reversal Date</inlineHelpText>
    <label>Payment Reversal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insolvency_Payment__c/fields/Payment_Reversed__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reversed__c</fullName>
    <label>Payment Reversed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Unauthorised</fullName>
            </value>
            <value>
                <fullName>Stale Dated</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Payment posted to Incorrect account</fullName>
            </value>
            <value>
                <fullName>Payment Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsolvencyPaymentsTriggerHandler.cls
/**************************************************************************************************
 *
 *  Class:    
 *
 *  @description : This is a trigger handler class for Insolvency Payment object 
 *  @author : A5E Consulting
 *  @date : 05/21/2024
 
 *************************************************************************************************/
public class InsolvencyPaymentsTriggerHandler {
    public static boolean runInsolvencyPaymentsTrigger = true;
    public static void handleBeforeInsert(List<Insolvency_Payment__c> insolvPaymentsNew) {
        Map<String, Insolvency_Account__c> acctsToUpdateMap = new Map<String, Insolvency_Account__c>();
        // Migrate 2 workflows to trigger
        for (Insolvency_Payment__c payment : insolvPaymentsNew) {
            // Update Insolvency last Payment Date
            if (payment.Payment_Created__c != null) {
                acctsToUpdateMap.put(
                    payment.Insolvency_Account__c,
                    new Insolvency_Account__c(Id = payment.Insolvency_Account__c, Insolvency_Last_Payment_Date__c = payment.Payment_Created__c)
                );
            }
            // Update Insolvency Last Payment Amount on Insolvency Account
            if (
                payment.Payment_Amount__c != null
            ) {
                if (acctsToUpdateMap.containsKey(payment.Insolvency_Account__c)) {
                    acctsToUpdateMap.get(payment.Insolvency_Account__c).Insolvency_Last_Payment_Amount__c = payment.Payment_Amount__c;
                } else {
                    acctsToUpdateMap.put(
                        payment.Insolvency_Account__c,
                        new Insolvency_Account__c(Id = payment.Insolvency_Account__c, Insolvency_Last_Payment_Amount__c = payment.Payment_Amount__c)
                    );
                }
            }
            updatePaymentReversalDate(payment, null);
        }
        if (!acctsToUpdateMap.values().isEmpty()) {
            update acctsToUpdateMap.values();
        }
    }

    public static void handleBeforeUpdate(List<Insolvency_Payment__c> insolvPaymentsNew, Map<Id, Insolvency_Payment__c> oldMap) {
        for (Insolvency_Payment__c payment : insolvPaymentsNew) {
            updatePaymentReversalDate(payment, oldMap.get(payment.Id));
        }
    }

    public static void updatePaymentReversalDate(Insolvency_Payment__c newPayment, Insolvency_Payment__c oldPayment) {
        // Migrate 1 workflow to trigger
        // Update Insolvency last Payment Date
        if (
            newPayment.Payment_Reversal_Date__c == null &&
            String.isNotBlank(newPayment.Payment_Reversed__c) &&
            (oldPayment == null || (oldPayment != null && newPayment.Payment_Reversed__c != oldPayment.Payment_Reversed__c))
        ) {
            newPayment.Payment_Reversal_Date__c = System.today();
        }
    }

    public static void handleBeforeDelete(List<Insolvency_Payment__c> insolvPaymentRecords) {
        list<Deleted_Records__c> deletedRecords = new List<Deleted_Records__c>();
        for (Insolvency_Payment__c insolvPayment : insolvPaymentRecords) {
            ID recordID = insolvPayment.ID;
            Deleted_Records__c deletedRec = new Deleted_Records__c();
            deletedRec.Object_Name__c = recordId.getSObjectType().getDescribe().getName();
            deletedRec.Salesforce_Record_Id__c = insolvPayment.External_Correlation_ID__c;
            deletedRecords.add(deletedRec);
        }
        if (!deletedRecords.isEmpty()) {
            insert deletedRecords;
        }
    }

    //After Insert
    public static void handleAfterInsert(List<Insolvency_Payment__c> insolvPaymentsNew) {
        map<id, Insolvency_Payment__c> insolvPaymentMap = new Map<id, Insolvency_Payment__c>();
        for (Insolvency_Payment__c insolvPayment : [
            SELECT ID, Name, External_Correlation_ID__c, Insolvency_Payment_Name_Original__c
            FROM Insolvency_Payment__c
            WHERE ID IN :insolvPaymentsNew
        ]) {
            insolvPayment.External_Correlation_ID__c = insolvPayment.ID;
            insolvPayment.Insolvency_Payment_Name_Original__c = insolvPayment.Name;
            insolvPaymentMap.put(insolvPayment.ID, insolvPayment);
        }
        if (!insolvPaymentMap.isEmpty()) {
            InsolvencyPaymentsTriggerHandler.runInsolvencyPaymentsTrigger = false;
            update insolvPaymentMap.values();
        }
    }
}