force-app/main/default/objects/Deleted_Records__c/Deleted_Records__c.object-meta.xml
<CustomObject>
    <label>Deleted Records</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Deleted Records Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deleted_Records__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This field keeps the name of the Object for ADF to know on which table it needs to perform deletion.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestProcessRecordsDeletionBatch.cls
@IsTest
public class TestProcessRecordsDeletionBatch {
    @testSetup
    private static void setup() {
        List<Deleted_Records__c> deletedRecordsList = new List<Deleted_Records__c>();
        for (Integer i = 0;i<100 ;i++) {
            deletedRecordsList.add(new Deleted_Records__c(Object_Name__c ='Error for testing '+i,
                                     CreatedDate = Date.Today() - 10));
        }
        insert deletedRecordsList;
    }
    
    @isTest
    private static void deleteRecordProcess_PositiveTest() {
        Test.startTest();
        Id batchId = Database.executeBatch(new ProcessRecordsDeletionBatch(), 200);
        Test.stopTest();
        System.assertEquals(99, [select count() from Deleted_Records__c]);
    }
}